### ISSUE TITLE
Error: ResponseError: Unauthorized

### ISSUE THREAD

**Issue by DeeIdowu** [sendgrid/sendgrid-nodejs#1002]
In attempts to get contact form interacting with with sendgrid api, an error was received as displayed in the terminal:
![Screen Shot 2019-11-19 at 6 35 17 PM](https://user-images.githubusercontent.com/38046425/69196150-a6d0eb00-0afb-11ea-9df6-42d2b3f3f516.png)
![Screen Shot 2019-11-19 at 6 35 29 PM](https://user-images.githubusercontent.com/38046425/69196152-a9334500-0afb-11ea-9a64-1ac48f4c75eb.png)
![Screen Shot 2019-11-19 at 6 35 38 PM](https://user-images.githubusercontent.com/38046425/69196155-aafd0880-0afb-11ea-9510-8e22c6525a9c.png)

Seeking to find the solution to this expeditiously for a client

Here is the client code:
![Screen Shot 2019-11-19 at 6 38 53 PM](https://user-images.githubusercontent.com/38046425/69196245-e7c8ff80-0afb-11ea-9adb-e9fde1effeb8.png)
![Screen Shot 2019-11-19 at 6 39 07 PM](https://user-images.githubusercontent.com/38046425/69196248-eb5c8680-0afb-11ea-9a96-69c616183df0.png)

Here is the server code:
![Screen Shot 2019-11-19 at 6 40 19 PM](https://user-images.githubusercontent.com/38046425/69196295-19da6180-0afc-11ea-9393-b3c129e17af4.png)
![Screen Shot 2019-11-19 at 6 40 28 PM](https://user-images.githubusercontent.com/38046425/69196300-1cd55200-0afc-11ea-80cc-ff549b3b314c.png)

The process.env is in a function due the fact the nodemon returns process.env is not a function, looking for assistance with that also. Please and thank you.

Kind regards

**Comment by JoseNoriegaa** [comment]
It looks like you are not setting up the API KEY correctly.
Check what "process.env(SENDGRID_API_KEY)" is returning by printing to the console.
```js
console.log({ key: process.env(SENDGRID_API_KEY) }); // key => ?
```

**Comment by DeeIdowu** [comment]
How do I set up the API KEY correctly please @JoseNoriegaa
