### ISSUE TITLE
email activity : authorization required with valid API key

### ISSUE THREAD

**Issue by kirtiperficient** [sendgrid/sendgrid-nodejs#1003]
#### Issue Summary

I am issuing the following request to the email activities endpoint:
and also use 'API KEY' as a bearer token

#### API: 

https://api.sendgrid.com/v3/messages?limit=10

#### and I receive the following response:
{
    "errors": [
        {
            "message": "authorization required"
        }
    ]
}

**Comment by kirtiperficient** [comment]
FYI I am using a free account.

**Comment by childish-sambino** [comment]
https://sendgrid.api-docs.io/v3.0/email-activity/filter-all-messages

> In order to gain access to the Email Activity Feed API, you must purchase [additional email activity history](https://app.sendgrid.com/settings/billing/addons/email_activity).
