### ISSUE TITLE
Contacts added via v3 API are never processed

### ISSUE THREAD

**Issue by alfredoreduarte** [sendgrid/sendgrid-nodejs#1004]
#### Issue Summary

Tried adding contacts through the `/v3/marketing/contacts` endpoint mentioned [here at the docs](https://sendgrid.api-docs.io/v3.0/contacts/add-or-update-a-contact). Both the "try it out" tool and the nodejs sdk gave me no problems, a `job_id` is returned as expected, but the contacts never actually show up on the list, seems like they're never processed. It's been more than six hours since I added the first one, so this seems like an issue.

#### Steps to Reproduce

1. Use the [Try it out](https://sendgrid.api-docs.io/v3.0/contacts/add-or-update-a-contact) tool with your own list and API key
2. Get a successful response
3. Check the list at least half an hour later to see if the new contact has been processed

Here's my code. Again, the API returns an OK response with a `job_id`, but the new contact never shows up on the list.

```
const client = require("@sendgrid/client")
client.setApiKey("TOKEN")

const request = {
	method: "PUT",
	url: "/v3/marketing/contacts",
	body: {
		list_ids: ["list-id"],
		contacts: [
			{
				id: "custom_id",
				email: "my@email.com",
				first_name: "Alfredo",
				last_name: "Re",
			},
		],
	},
}
client
	.request(request)
	.then(([response, body]) => {
		console.log("response.statusCode")
		console.log(response.statusCode)
		console.log(JSON.stringify(body))
	})
	.catch(err => {
		console.log("error")
		console.log(err)
	})
```

#### Technical details:

* sendgrid-nodejs Version: 6.4.0 master (latest commit: 8b20079ec82d9bd83254de173ecd3c3c989e5f64)
* Node.js Version: 8.11.4

**Comment by alfredoreduarte** [comment]
Closed by https://github.com/sendgrid/sendgrid-nodejs/issues/957#issuecomment-559244701

**Comment by Buffalonian** [comment]
I'm having issues with this on the GET list API endpoint that has conflicting documentation and results differ.

**Comment by Buffalonian** [comment]
https://github.com/sendgrid/sendgrid-csharp/issues/1013 <-- posted this.

https://api.sendgrid.com/v3/marketing/lists/{list ID}?contact_sample=true <-- works with my authentication and gives me a sample of 50 years. I need all of them, so I looked further down at documentation and found the CONTACT LIST API section.

When I try this ... it does not return what I expect, based on the sample and both in POSTMAN to test the endpoint and also the TRY IT OUT tool on the website.

https://api.sendgrid.com/v3/contactdb/lists/{list ID} <--- I expect this to work
https://api.sendgrid.com/v3/contactdb/lists/{list ID}?list_id=1 <-- why dual list IDs?!?!?! Documentation and sample both give me issues.

I get an access forbidden and know EXPLICITLY my API_KEY has full access and I can indeed get access to that list in SendGrid. 

Anyone from SendGrid able to reproduce this issue?

**Comment by childish-sambino** [comment]
@Buffalonian Someone will follow-up on the new ticket you opened. Let's just keep the conversation there for easier tracking.
