### ISSUE TITLE
Canceling email send if specified time has not passed yet

### ISSUE THREAD

**Issue by cryptoman04** [sendgrid/sendgrid-nodejs#1005]
#### Issue Summary

I'm wondering if it's possible to schedule an email to be sent at some point in the future, and then cancel the sending of the email, if you determine you do not need to send it anymore.

Use case:
- User gets halfway through onboarding.
- Backend creates an email to be sent 46 min in the future, letting user know that they need to complete the onboarding flow (this is done to make the email seem less robotic and more humane) 
- User comes back in 20 minutes and completes the onboarding flow. How can I stop the email from being sent to the user?

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by childish-sambino** [comment]
Does this help? https://sendgrid.com/docs/for-developers/sending-email/stopping-a-scheduled-send/
