### ISSUE TITLE
problem with wpml language

### ISSUE THREAD

**Issue by manarbb** [sendgrid/sendgrid-nodejs#1007]
I translate my website with wpml language, the site is a booking website, all the pages translated good and each took its place i have a problem in reading the language, the two languages appears in one page in different places, but mainly its not a pages its like a plugin named room you can add to it the rooms that you want to show to people the problem with its content, please see the link  www.insight.ps/evilla  the arabic and english in one page but if you visit the other pages arabic and english you find that everything ok. also in arabic language the thumb picture doesn't appears why?

is there any code i can add so it reads the language correct
please help me and thank you

**Comment by childish-sambino** [comment]
This doesn't look related to using SendGrid.
