### ISSUE TITLE
PRs not being merged

### ISSUE THREAD

**Issue by bs85** [sendgrid/sendgrid-nodejs#1009]
Is the package still maintained? Obviously SendGrid is alive, shouldn't there be some resources allocated to at least merge small fixes in the official SDK?

Last commit is from 6 months ago, and there are many no-brainer PRs that haven't been merged for a long time, including typo fixes in documentation (e.g. #984), and the one I'm looking at, a fix to the TS definitions for @sendgrid/mail (#921 and #846).

Maybe there is a good reason for the freeze? Would really like some official word on this topic.

**Comment by childish-sambino** [comment]
PRs merged. Next release scheduled for 2020-02-19.

**Comment by bs85** [comment]
Cheers, glad to see activity :)
