### ISSUE TITLE
Can't send even using API's simple example 

### ISSUE THREAD

**Issue by sherif2011** [sendgrid/sendgrid-nodejs#1020]
Hello,

SendGrid looks like a good tool. I was able to create a dynamic template and test sending it with no issues. When I try using API, the email is never sent.
I installed latest version of Sendgrid: @sendgrid/mail@6.4.0
I am following your directions to run even the simple send API example. Here is my code:
.env file contains the API_Key:
`SENDGRID_API_KEY='SG.........RF2eQ'`

index.js contains the following:
```
require('dotenv').config();
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'smankarious@sunrisedataservices.com',
  from: 'smankarious@sunrisedataservices.com',
  subject: 'Sending with Twilio SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};
sgMail.send(msg);
```

Please help, as it's getting on my nerves, how simple it seems to be, yet not working.
Again, I am able to create dynamic templates, send them using Test (and even substituting tags)... no issues whatsoever. 

I deleted and created API_Key 3 times to ensure, I actually have the correct key.

Thanks for advising.

Sherif

**Comment by sherif2011** [comment]
For the above, it looks like all those emails are quarantined, any idea why? the above email is an office 365 account.
Now when I try sending out my actual email (with substitution and image - simply a birthday greeting message) it also gets quarantined when going to office 365 account, and never delivers when sending to a yahoo account. Please advise. Thanks!

**Comment by Juanperezc** [comment]
same issue

**Comment by AmrAlmagic** [comment]
I faced the same issue solvled by :
1- `npm i --save nodemailer nodemailer-sendgrid-transport`
2-  to send email
```
const nodemailer = require('nodemailer');
const sendgridTransport = require('nodemailer-sendgrid-transport');

const transporter = nodemailer.createTransport(
    sendgridTransport({
        auth: {
            api_key:
            process.env.SENDGRID_API_KEY        }
    })
);

function sendEmail(mailOptions) {
    transporter.sendMail({
        to: mailOptions.to,
        from: mailOptions.from,
        subject: mailOptions.subject,
        html: mailOptions.html
    })
        .catch(err => {
            const error = new Error(err);
            error.httpStatusCode = 500;
            return next(error);
        });
}
```

**Comment by thinkingserious** [comment]
Hello @sherif2011,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
