### ISSUE TITLE
href attribute not taking dynamic template data

### ISSUE THREAD

**Issue by Pmurs** [sendgrid/sendgrid-nodejs#1021]
#### Issue Summary

I have a dynamic email template for sending a user a unique token link to reset their password. I assign the link to a field named 'link' in the dynamic_template_data section of my personalizations in my request object. When I receive the email, my anchor tag has no href attribute.

Here is my request object:
```
{
        method: "POST",
        url: "/v3/mail/send",
        headers: {
          "content-type": "application/json"
        },
        body: {
          personalizations: [
            {
              to: [{ email: email, name: name }],
              dynamic_template_data: {
                link: link
              }
            }
          ],
          // some other content
          // ...
          template_id: Constants.EMAIL.RESET_PASSWORD
        },
        json: true
      }
```
And the html in my sendgrid dynamic template:

```
<div>Use the following link to reset your password: <a href="{{link}}">{{link}}</a></div>
```

When I receive the email, the _text_ of the link is correctly filled in with my dynamic content but the <a> element has no href attribute so it renders as plain text and isn't clickable:

![image](https://user-images.githubusercontent.com/16808643/71750261-e3576c80-2e45-11ea-9e02-2004b16eb384.png)

**Comment by bs85** [comment]
I think you need ta pass the full placeholder, e.g. `{ dynamic_template_data: { '{{link}}': link } }`. Not 100% sure though, give it a try.

**Comment by Pmurs** [comment]
No, if that were the case then the text of the link wouldn't be correctly filled in with my dynamic content with the code I had already written.

**Comment by Pmurs** [comment]
The issue was ultimately due to setting an href that didn't being with "http://". Adding this in resolved the issue, this seems to just be a quirk of the anchor tag element itself
