### ISSUE TITLE
Setting Content-Transfer-Encoding in v3

### ISSUE THREAD

**Issue by nkumarcc** [sendgrid/sendgrid-nodejs#1036]
### Issue Summary

A large number of our clients use Microsoft Outlook. Arbitrary line breaks have popped up across our emails. SendGrid's resources document this type of error:
https://sendgrid.com/docs/for-developers/sending-email/send-mime-messages-with-sendgrid/

We want to be able to set the `Content-Transfer-Encoding` as documented there. I think that this should be possible through SendGrid's SMTP API, which I believe was folded into v3 of this API, but I can't figure out how to set it. When I tried setting via the headers option, I get a "Can't set reserved headers error."

### Steps to Reproduce
1. Pass "Lorem ipsum" paragraph into Dyanmic Template
2. Send to Outlook email
3. Get this response:
<img width="560" alt="Screen Shot 2020-01-27 at 12 01 42 PM" src="https://user-images.githubusercontent.com/19844471/73195987-d0f6e880-40fc-11ea-8daa-167ea23d4ad5.png">

Should look like this (renders in Gmail):
<img width="554" alt="Screen Shot 2020-01-27 at 12 01 09 PM" src="https://user-images.githubusercontent.com/19844471/73196000-d81df680-40fc-11ea-9571-f361ed2c1bac.png">

### Code Snippet
```node
await sgMail.send(
       {
            to: xxxx,
            from: xxxx,
            templateId: templateId,
            dynamicTemplateData: dynamicTemplateData,
        }
);
```

### Exception/Log
Error from using `.send`: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Headers-Errors, error message `Header can not be one of the reserved keys.`

### Technical details:
* sendgrid-nodejs version: 6.3.1
* node version: 11.15.0

**Comment by thinkingserious** [comment]
Hello @nkumarcc,

The v3 API does not currently support overriding the `Content-Transfer-Encoding` setting.

The SMTP API library for node is located [here](https://github.com/sendgrid/smtpapi-nodejs).

I suggest you reach out to https://support.sendgrid.com to request support for overriding the `Content-Transfer-Encoding` setting.

Thank you!

With best regards,

Elmer
