### ISSUE TITLE
warning > request@2.88.2 deprecated

### ISSUE THREAD

**Issue by ArtashMardoyan** [sendgrid/sendgrid-nodejs#1042]
warning @sendgrid/mail > @sendgrid/client > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by ArtashMardoyan** [comment]
Please change "request" to "axios"
[https://www.npmjs.com/package/axios](URL)

**Comment by childish-sambino** [comment]
Work is in progress. I'd like to get some feedback from the community if this warrants a major version roll or not. The request/response interfaces will change along with the TS types which _may_ break consumers depending on their usage.

**Comment by ArtashMardoyan** [comment]
Do not change the main version.
We will have no problems.
You can insert v6.6.0.
The beautiful version will be.

**Comment by childish-sambino** [comment]
@ArtashMardoyan _You_ may not have any problems, but others might. It just depends on your usage.

**Comment by ArtashMardoyan** [comment]
@childish-sambino [https://docs.npmjs.com/about-semantic-versioning](url)

**Comment by childish-sambino** [comment]
@ArtashMardoyan I don't follow. Previously you indicated to roll the minor version but now you're recommending the major version?

**Comment by ArtashMardoyan** [comment]
Well, yes, if you think that some users may have problems, you should change the main version.

**Comment by childish-sambino** [comment]
@ArtashMardoyan Gotcha. Just making sure.

**Comment by ArtashMardoyan** [comment]
Well then, we will wait for the new version.Good luck

**Comment by jimmywarting** [comment]
I vote for node-fetch
