### ISSUE TITLE
JSON to: going empty even though is provided.

### ISSUE THREAD

**Issue by molBR** [sendgrid/sendgrid-nodejs#1043]
### Issue Summary
I'm trying to send a simple dynamic email but sendgrid is saying is coming without the "to:" key as it shows in the picture below:
![image](https://user-images.githubusercontent.com/7649915/74853925-5a28c600-531d-11ea-8615-571b192da903.png)

I've used sendgrid api before and this never happened to me, it is very strange.

Here's the code
```
 Sendgrid.setApiKey(
    'apikeystring'
  );
  const msg = {
    to: 'email@email.com' //this is shown as not being sent eventhought I'm sending,
    from: 'email2@email.com',
    subject: 'RELATORIO METAS10',
    templateId: 'templatekeystring',
    text: 'Hello plain world!',
    html: '<p>Hello HTML world!</p>',
    dynamic_template_data: {
      test: "ok"
    }
  }
  console.log('info:', msg);
  const send = await Sendgrid.send(msg);
  console.log(JSON.parse(JSON.stringify(send)))
  return true
}
```

### Technical details:
* sendgrid-nodejs version: "^6.5.2"
* node version: 10.16

**Comment by molBR** [comment]
The email design is described below (it's in portuguese sorry)
```
Olá! Seu relatório está completo.
Abaixo estão os links!

{{{ test }}}

```

**Comment by molBR** [comment]
It is a simple Google Cloud Function that recieves a push notification from Pubsub and sends it's email

**Comment by childish-sambino** [comment]
Can you try logging the mail object to make sure it has the to address as part of the personalizations?
```
const { Mail } = require("@sendgrid/helpers").classes;
...
console.log(JSON.stringify(Mail.create(msg), null, 2));
```

**Comment by molBR** [comment]
Sorry for the delay
Here's the output:
```
{
    "from": {
        "email": "contato@clubpetro.com.br"
    },
    "personalizations": [
        {
            "to": [
                {
                    "email": "pedromollica@gmail.com"
                }
            ],
            "dynamic_template_data": {
                "subject": "RELATORIO METAS100",
                "test": "ok"
            }
        }
    ],
    "content": [
        {
            "value": "Hello plain world!",
            "type": "text/plain"
        },
        {
            "value": "<p>Hello HTML world!</p>",
            "type": "text/html"
        }
    ],
    "template_id": "**the id of the template**"
}
```

**Comment by childish-sambino** [comment]
The message payload looks proper to me so I don't think this is an issue with the repo. Best to open a support ticket so they can look into it.

**Comment by thinkingserious** [comment]
Hello @molBR,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by molBR** [comment]
already did.. no answer as well...

**Comment by molBR** [comment]
actually, they sent me to here...

**Comment by molBR** [comment]
can you guys unclose this?

**Comment by molBR** [comment]
@thinkingserious can you please respond? 
This is a real issue, support sent me here.

**Comment by Gervwyk** [comment]
Hi, we are experiencing the same issue. Was this resolved?

**Comment by childish-sambino** [comment]
@molBR @Gervwyk New tickets have been sent out for your accounts. Please login to your account and view support tickets through [support.sendgrid.com](https://support.sendgrid.com).
