### ISSUE TITLE
Are there any plans to implement the Marketing Emails API?

### ISSUE THREAD

**Issue by eldilibra** [sendgrid/sendgrid-nodejs#105]
For example, adding an email (with whatever other columns) to a list via this module could be something like:

``` javascript
var list_name = 'Paying Customers';
var data = [
  { email: 'derp@herp.com',
    first_name: 'Great',
    last_name: 'Gatsby'
  },
  { email: 'guy@site.com',
    first_name: 'Justan',
    last_name: 'Human'
  }
];
sendgrid.addToList(list_name, data);
```

**Comment by agustinhaller** [comment]
Does anyone came up with something?

**Comment by eldilibra** [comment]
Sadly, I totally forgot about this half-hearted commitment of mine :~(. Shame on me. I haven't heard of any other solutions by others. @agustinhaller: I think I ended up just crafting the request meticulously according to the sendgrid docs using the [request module](https://github.com/request/request). I hope that helps you.

**Comment by agustinhaller** [comment]
Yup i think i will end up doing the same, thanks man
