### ISSUE TITLE
setTimeout needs to be defined in mail.d.ts

### ISSUE THREAD

**Issue by huricool** [sendgrid/sendgrid-nodejs#1051]
### Issue Summary
The class MailService in mail.d.ts needs to define `setTimeout` in order to provide a proper type to the typescript compiler. 

### Steps to Reproduce
1. N/A

### Code Snippet
```node
  /**
   * Set timeout for request
   */
  setTimeout(timeout: number): void;

```

### Exception/Log
```
```

### Technical details:
* sendgrid-nodejs version: 6.5.4
* node version: NODE 12 LTS

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
