### ISSUE TITLE
Transactional Template send Email Answer 202 but not sent email

### ISSUE THREAD

**Issue by aneggi** [sendgrid/sendgrid-nodejs#1052]
### Issue Summary
I am using TRANSACTIONAL TEMPLATE (Dynamics Template) 
Template ID: d-344aae640470433bb9bb949f6cb2b81b
And try to send email from NODEjs local server.

### Steps to Reproduce
1. Create template
2. Insert code
3. Try to send request

### Code Snippet
```node
const msg = {
      to: _user.email  ,
      from: 'xx@xx.eu',
      templateId: _template,
      dynamic_template_data: {
        dest_Name: _user.fullName,
        dest_Subject: "test1",
        dest_Content: _content
      },
    };
    debug(JSON.stringify(msg));
    sgMail.send(msg, (error,result) => {
      if(error) {
        debug('Error:' + error);
      }
      else {
        debug('Email sent:' + JSON.stringify(result));
      }
    });
```
The msg contents is: 
{"to":"xx@xx.it","from":"xx@xx.eu","templateId":"d-344aae640470433bb9bb949f6cb2b81b","dynamic_template_data":{"dest_Name":"Alessandro Aneggi","dest_Subject":"test1","dest_Content":"un saluto di prova"}}

There is no error, the answe from the server is:
### Exception/Log
```
sent:[{"statusCode":202,"headers":{"server":"nginx","date":"Thu, 05 Mar 2020 15:23:27 GMT","content-length":"0","connection":"close","x-message-id":"M7XkPaSPTZK5QS8wHYJf2g","access-control-allow-origin":"https://sendgrid.api-docs.io","access-control-allow-methods":"POST","access-control-allow-headers":"Authorization, Content-Type, On-behalf-of, x-sg-elas-acl","access-control-max-age":"600","x-no-cors-reason":"https://sendgrid.com/docs/Classroom/Basics/API/cors.html"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"api.sendgrid.com","port":443,"hostname":"api.sendgrid.com","hash":null,"search":null,"query":null,"pathname":"/v3/mail/send","path":"/v3/mail/send","href":"https://api.sendgrid.com/v3/mail/send"},"method":"POST","headers":{"Accept":"application/json","User-agent":"sendgrid/6.5.3;nodejs","Authorization":"******","content-type":"application/json","content-length":268}}},null]
```

### Technical details:
* sendgrid-nodejs version: 6.5.4
* node version: 12.16.1

Why nothing happened? No mail, no errors?

**Comment by thinkingserious** [comment]
Hello @aneggi,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
