### ISSUE TITLE
Unable to add image to the email body using inline

### ISSUE THREAD

**Issue by ssankabathula** [sendgrid/sendgrid-nodejs#1055]
Trying to add a image as part of Sendgrid/mail body, email doesnt show image. 
                    

                  function base64_encode(file) {
                        var bitmap = fs.readFileSync(file);
                        return new Buffer(bitmap).toString('base64');
                    }

                    let data_base64 = base64_encode(imageFile);

                    const msg = {
                        to: emailList,
                        from: '',
                        subject: '',
                        html:'<strong>Some Text</strong><img src="cid:Logo" alt="image" />',
                        files: [
                            {
                                filename: image,
                                type: 'image/png',
                                cid:'Logo',
                                content: data_base64,
                                disposition: 'inline'
                            },
                        ],
                    };

                    sgMail.send(msg, function (err, json) {
                        if (err) {
                            return console.error(err);
                        } else
                            process.exit;
                    });

Expected output : Image in the body
Current output: No image

**Comment by childish-sambino** [comment]
Duplicates #701
