### ISSUE TITLE
Please settle on one style to name your API variables

### ISSUE THREAD

**Issue by 0x80** [sendgrid/sendgrid-nodejs#1059]
Because of recent updates to the mail client I was forced to rename some variables in the api payload. For example asm.group_id became asm.groupId and asm.groups_to_display became asm.groupsToDisplay. 

Fine, so I'm assuming you're moving from snake-case to camel-case. 

But there are still loads of other variables that are still snake-cased. This is confusing and annoying. It's not like the v3 api is new. Can you please decide on one style of naming your variables and make it consistent? A public facing API should have names that are chosen carefully.

**Comment by childish-sambino** [comment]
Best I can tell is that this library supports either in some cases (possibly for backwards-compatibility reasons) but not in call cases. And the TS definitions use camelCase for input and snake_case for output (since that's what the API expects).

For the renaming you've had to do, was this because of changes to the TS definitions? Or changes to the JS implementation? Also, what version were you migrating from and to? Just trying to track down where the breakdown happened.

**Comment by 0x80** [comment]
@childish-sambino I am surprised that the input is supposed to be camelCased. Mine seems to be all snake-cased, apart from replyTo. Maybe my config it messed up or some things were carried over from older versions. Below you will find the function that formats the data for sendgrid. As you can see most fields are not camel-cased. The fact that this works maybe means that it's internally converted anyway?

Also, this is for a project that I barely ever need to touch anymore, so I prefer to leave it at that. Your type definitions cause me a lot of trouble in the past so I hope things are improving. As you can see there is still even a ts-ignore in here :) I will give it another try a few months from now.

```ts
function buildSendgridEmail(emailId: string, message: EmailMessage): MailData {
  const {
    template,
    subject,
    to,
    from,
    replyTo,
    categories,
    unsubGroup,
    utmCampaign,
    utmContent,
    substitutions,
    personalizations,
    trackingSettings
  } = message;

  const result = {
    asm: {
      group_id: unsubGroup,
      groups_to_display: [unsubGroup]
    },
    categories,
    from,
    replyTo,
    to: to ? useMailtrapForDevelopment(to) : undefined,
    subject,
    template_id: template,
    substitutions,
    personalizations,
    custom_args: {
      /**
       * We pass the email id to sendgrid so we have a reference once they call
       * our webhook with email status updates.
       */
      emailId
    },
    ip_pool_name: "transactional",

    /**
     * @TODO refactor this so the mappings are cleaner and trackingSettings is
     * typed.
     */
    tracking_settings: merge(
      {
        open_tracking: { enable: true },
        click_tracking: {
          enable: false,
          enable_text: false
        },
        ganalytics: {
          enable: utmCampaign ? true : false,
          utm_source: "Email",
          utm_medium: "email",
          utm_campaign: utmCampaign,
          utm_content: utmContent
        }
      },
      trackingSettings
    ),
    mail_settings: {
      sandbox_mode: {
        enable: SENDGRID_USE_SANDBOX ? true : false
      }
    },
    timestamp: Date.now()
  };

  // @ts-ignore
  return result;
}
```

**Comment by childish-sambino** [comment]
Yes, either camelCase or snake_case are supported in some cases. I'm open to improving this repo and reviewing PRs to that end; just need to know what specifically is broken/incorrect. Let me know if/when you're able to circle back to this.
