### ISSUE TITLE
Error in sending email from Firebase Cloud Functions when new record is added to Realtime Database

### ISSUE THREAD

**Issue by yifeili924** [sendgrid/sendgrid-nodejs#1060]
If running the following code, that works well.
But it doesn't work in Firebase Cloud Functions.
```
const sgMail = require('@sendgrid/mail');
var API_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx";
var text = "This is test email";
sgMail.setApiKey(API_KEY);
const msg = {
	to: 'toaddress',
	from: 'fromaddress@',
	subject: 'Hi,',
	text: text,
	html: text,
};
sgMail.send(msg)
```

**Comment by childish-sambino** [comment]
Not seeing any error handling here. You'll need to catch any exceptions to properly debug the issue: https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/success-failure-errors.md

**Comment by yifeili924** [comment]
This is my whole Firebase cloud function. 

const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();
// Listener for new message sent to Admin
exports.addNewMessage = functions.database.ref('/messages/{chatid}/{messageid}')
    .onCreate((snapshot, context) => {
        var chatid = context.params.chatid;
        // read all contacts of Admin
        admin.database().ref('/users/2670b7e5-5c57-42b3-80db-fc89ed08ffc5/contacts/').once('value', contactsnapshot => {
            contactsnapshot.forEach(childSnapshot => {
                if (chatid === childSnapshot.val()) {
                    admin.database().ref('/users/' + childSnapshot.key).once('value', snapshot => {
                        var messageSentUser = snapshot.val();
                        var username = messageSentUser.username;
                        var useremail = messageSentUser.email;
                        
                        var SENDGRID_API_KEY = '';
                        var text = username + " (" + useremail + ") " + " sent message.";

                        // using SendGrid's v3 Node.js Library
                        const sgMail = require('@sendgrid/mail');
                        sgMail.setApiKey(SENDGRID_API_KEY);
                        const msg = {
                            to: 'to address',
                            from: 'from address',
                            subject: 'Hi,',
                            text: text,
                            html: text,
                        };
                        console.log(msg);
                        sgMail.send(msg).then(() => console.log("email sent!"))
                            .catch(err => console.log(err));
                        return true;
                    })
                }
            })
        });
        return false;
    });

**Comment by yifeili924** [comment]
when running this code, I found out the following in logs of Firebase functions.
- Billing account not configured. External network is not accessible and quotas are severely limited. Configure billing account to remove these restrictions
- { Error: getaddrinfo EAI_AGAIN api.sendgrid.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.sendgrid.com',
  host: 'api.sendgrid.com',
  port: 443 }

**Comment by childish-sambino** [comment]
_Cloud Functions_ limits _Outbound networking_ to _Google services only_ for free accounts.
https://firebase.google.com/pricing/

**Comment by yifeili924** [comment]
oh, I see. thank you for your help. I will set up the account billed.
