### ISSUE TITLE
Intermittent "Permission denied" errors using sendgrid node client 1.9.2

### ISSUE THREAD

**Issue by kk3399** [sendgrid/sendgrid-nodejs#1062]
### Issue Summary
Intermittent "Permission denied" errors using sendgrid node 1.9.2
About 50% of requests are failing with this error since Mar 7th.
is there is any API redirection from older version to newer version?
Creating an issue here to see if the client needs to be updated to avoid any anticipated change in behavior.

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
error - Permission denied
```

### Technical details:
* sendgrid-nodejs version: 1.9.2
* node version: 10.15.0

**Comment by childish-sambino** [comment]
Version `1.9.2` is almost 5 years old. Recommend upgrading to a later version to see if problem still exists. That said, I don't know of any recent changes that would cause this sort of behavior. Would need some sample code and more details about the error/exception to be able to debug.
