### ISSUE TITLE
Client network socket disconnected

### ISSUE THREAD

**Issue by arashsoftco** [sendgrid/sendgrid-nodejs#1066]
hi i have this problem i also use vpn but still has error

`
PS C:\Users\Arashsoft\Desktop\ionic\start_angular> ionic start

Every great app needs a name!

Please enter the full name of your app. You can change this at any time. To bypassthis prompt next time, supply name, the first argument to ionic start.

? Project name: test

Pick a framework!

Please select the JavaScript framework to use for your new app. To bypass this    
prompt next time, supply a value for the --type option.

? Framework: Angular

Let's pick the perfect starter template!

Starter templates are ready-to-go Ionic apps that come packed with everything you 
need to build your app. To bypass this prompt next time, supply template, the     
second argument to ionic start.

? Starter template: blank
√ Preparing directory .\test - done!
- Downloading and extracting blank starter

  ────────────────────────────────────────────────────────────

           Ionic CLI update available: 5.4.16 → 6.2.1
     The package name has changed from ionic to @ionic/cli!

             To update, run: npm uninstall -g ionic
                 Then run: npm i -g @ionic/cli

  ────────────────────────────────────────────────────────────

Error: Client network socket disconnected before secure TLS connection was        
established

at connResetException (internal/errors.js:570:14)
at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
at Object.onceWrapper (events.js:299:28)
at TLSSocket.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1183:12)

`

**Comment by childish-sambino** [comment]
I don't see the relation to `sendgrid-nodejs`.
