### ISSUE TITLE
Error handling in setApiKey

### ISSUE THREAD

**Issue by rockert42** [sendgrid/sendgrid-nodejs#1068]
### Issue Summary
I'm retrieving the api key from an environment variable. Somehow in one of our environments the api key was `undefined`. It would be helpful if an error is logged or an error is thrown when setupApiKey is called with `undefined`, or with other wrong inputs, so that we are immediately informed when this is the case.

### Steps to Reproduce
1. Setup the api key as undefined `sgMail.setupApiKey(undefined)`
2. No error, so it seems like the ApiKey is set correctly
3. Only when trying to send a mail an error is thrown

### Code Snippet
```node
const msg = {
  to: 'test@example.com',
  from: 'test@example.com',
  subject: 'Sending with SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};
sgMail.setApiKey(undefined);
sgMail.send(msg);
```

### Exception/Log

None after `setupApiKey(undefined)`

Error after sending the mail;
```
Unauthorized (401)
  Permission denied, wrong credentials
```

### Technical details:
* sendgrid-nodejs version: 6.5.4
* node version: 8.16.2

**Comment by childish-sambino** [comment]
Makes sense to me. I'll look into a fix.

**Comment by childish-sambino** [comment]
Reviewing the code, I think it's best to add logic when a `401` is returned rather than block setting the API key to be undefined. The underlying client can be used to call APIs that don't require an API key so removing auth from the client should be allowed.

**Comment by rockert42** [comment]
So if I am interpreting correctly, there's two ways to use `sgMail`:
1) With authorization (using `setApiKey`, for example)
2) Without authorization (either by `not using setApiKey` or using `setApiKey(undefined / null / '')`

If my understanding is correct, my question is: why would someone ever try and intentionally set `setApiKey(undefined)`?

**Comment by childish-sambino** [comment]
You _could_ have a workflow that switches between APIs that require auth and others that don't and you want to make sure creds aren't sent when not needed. Or it's a config-driven process that supports both and doesn't want additional logic to test the given credentials.

**Comment by rockert42** [comment]
Calling the `setApiKey` function _implies_ the user's need to set an api key. Setting an api key with undefined/null/'' will never result in an actual api key to be set, so most logical resulting in an error in my opinion.

In workflows where (sometimes) no auth is required, someone can just simply not call the `setupApiKey` function before accessing an API that does not require it. Alternatively a simple condition can be built in to not call `setupApiKey` when no api key is specified.

**Comment by childish-sambino** [comment]
Simplified example:

```
const client = require('@sendgrid/client');

client.setApiKey(process.env.SENDGRID_API_KEY);
const request = {
  method: 'POST',
  url: '/auth-api'
};
await client.request(request);

... do things

client.setApiKey(undefined);
const request = {
  method: 'GET',
  url: '/non-auth-api'
};
const response = await client.request(request);

.. do things
```

**Comment by rockert42** [comment]
In case of your example, it is also possible to just omit the  `client,setApiKey(undefined)`, correct? Resulting in: 
```
const client = require('@sendgrid/client');

client.setApiKey(process.env.SENDGRID_API_KEY);
const request = {
  method: 'POST',
  url: '/auth-api'
};
await client.request(request);

... do things

// client.setApiKey(undefined); --> Why even set this if the input is undefined?
const request = {
  method: 'GET',
  url: '/non-auth-api'
};
const response = await client.request(request);

.. do things
```

The point I am trying to make: if no auth is required, someone can just choose to **not** use the `setApiKey` function. Whereas if someone needs to access an api with auth, he can simply add `setApiKey(process.env.SENDGRID_API_KEY)`

Resulting that any use of `setApiKey(undefined)` is not desired

**Comment by childish-sambino** [comment]
From previous comment:
> and you want to make sure creds aren't sent when not needed

I don't know if anyone is doing this, but it's possible and completely valid and the change you're proposing would break them.

**Comment by rockert42** [comment]
| the change you're proposing would break them
Agreed

**Comment by childish-sambino** [comment]
Looked over the code and found another instance where a warning is logged in certain cases, but the caller can hide the warning with an option. I think just adding the warning is fine and if others later are intentionally calling `setApikey` with an empty value we can look into hiding the warning in a similar way.

**Comment by rockert42** [comment]
I think that is reasonable
