### ISSUE TITLE
Can not send email design via sendgrid

### ISSUE THREAD

**Issue by Mert1980** [sendgrid/sendgrid-nodejs#1071]
### Issue Summary
I made an email design in sendgrid homepage and I copied the code to node.js in order to send it via my app. But I am not able to send it

### Steps to Reproduce
1. This is the first step

### Code Snippet
```node
const sgMail = require('@sendgrid/mail')
const path = require('path');
require('dotenv').config({path: path.resolve(process.cwd(), 'config', '.env'), debug: true});

sgMail.setApiKey(process.env.SENDGRID_API_KEY)

const sendWelcomeEmail = (email, name) => {
    sgMail.send({
        to: email,
        from: 'softwaredeveloperjava80@gmail.com',
        subject:'Welcome to DanceWithMe!',
        html: `<td style="font-size:6px; line-height:10px; padding:0px 0px 0px 0px;" valign="top" align="center">
        <img class="max-width" border="0" style="display:block; color:#000000; text-decoration:none; font-family:Helvetica, arial, sans-serif; font-size:16px; max-width:100% !important; width:100%; height:auto !important;" width="600" alt="" data-proportionally-constrained="true" data-responsive="true" src="http://cdn.mcauto-images-production.sendgrid.net/ecfbf4aace3a49e1/b128e5f9-57e9-4c9f-9e4f-590648d8c153/1600x900.png">
      </td>`,
        text:`Welcome ${name}. Be ready to join wonderful dance events with the best partners which our matching engine will offer to you!`
    })
}

module.exports = sendWelcomeEmail

# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* sendgrid-nodejs version: @sendgrid/mail": "^6.5.4"
* node version: v12.14.1

**Comment by thinkingserious** [comment]
Hello @Mert1980,

Could you please provide us with the error you have received? 

It looks like the quotes around the content for `html` or `text` are not correct. They should be the same as what you have for `subject`. That is, ' instead of `. 

With best regards,

Elmer

**Comment by Mert1980** [comment]
Hello @thinkingserious I moved text into html and it is working fine now, except the style. The response email shows picture, text and button side by side, but not up to bottom. I couldn't figure out how to solve it. Would you please give an advise?
`const sendWelcomeEmail = (email, name) => {
  sgMail.send({
    to: email,
    from: "softwaredeveloperjava80@gmail.com",
    subject: "Welcome to DanceWithMe!",
    html: `<div>
                <td style="font-size:6px; line-height:10px; padding:0px 0px 0px 0px;" valign="top" align="center">
                <img class="max-width" border="0" style="display:block; color:#000000; text-decoration:none; font-family:Helvetica, arial, sans-serif; font-size:16px; max-width:100% !important; width:70%; height:auto !important;" width="290" alt="" data-proportionally-constrained="true" data-responsive="true" src="http://cdn.mcauto-images-production.sendgrid.net/ecfbf4aace3a49e1/b128e5f9-57e9-4c9f-9e4f-590648d8c153/1600x900.png">
                </td>
             <div style="font-family: inherit; text-align: justify inherit">Thanks for joining to our community. Please click the <strong>DanceWithMe</strong> button to explore the latest dance events and find your best partner!&nbsp;</div>
                 <td align="center" bgcolor="#333333" class="inner-td" style="border-radius:6px; font-size:16px; text-align:center; background-color:inherit;">
                        <a href="http://localhost:3000/DanceWithMe" style="background-color:#333333; border:1px solid #333333; border-color:#333333; border-radius:6px; border-width:1px; color:#ffffff; display:inline-block; font-size:14px; font-weight:normal; letter-spacing:0px; line-height:normal; padding:12px 18px 12px 18px; text-align:center; text-decoration:none; border-style:solid;" target="_blank">DanceWithMe</a>
                    </td>
             </div>
            </div>`
  });
};` 
![Screenshot from 2020-03-26 08-08-05](https://user-images.githubusercontent.com/55088530/77619754-30287c00-6f39-11ea-9c13-b006b492c729.png)

**Comment by Mert1980** [comment]
`const sendWelcomeEmail = (email, name) => {
  sgMail.send({
    to: email,
    from: "softwaredeveloperjava80@gmail.com",
    subject: "Welcome to DanceWithMe!",
    html: `<div>
                <td style="font-size:6px; line-height:10px; padding:0px 0px 0px 0px;" valign="top" align="center">
                <img class="max-width" border="0" style="display:block; color:#000000; text-decoration:none; font-family:Helvetica, arial, sans-serif; font-size:16px; max-width:100% !important; width:70%; height:auto !important;" width="290" alt="" data-proportionally-constrained="true" data-responsive="true" src="http://cdn.mcauto-images-production.sendgrid.net/ecfbf4aace3a49e1/b128e5f9-57e9-4c9f-9e4f-590648d8c153/1600x900.png">
                </td>
             <div style="font-family: inherit; text-align: justify inherit">Thanks for joining to our community. Please click the <strong>DanceWithMe</strong> button to explore the latest dance events and find your best partner!&nbsp;</div>
                 <td align="center" bgcolor="#333333" class="inner-td" style="border-radius:6px; font-size:16px; text-align:center; background-color:inherit;">
                        <a href="http://localhost:3000/DanceWithMe" style="background-color:#333333; border:1px solid #333333; border-color:#333333; border-radius:6px; border-width:1px; color:#ffffff; display:inline-block; font-size:14px; font-weight:normal; letter-spacing:0px; line-height:normal; padding:12px 18px 12px 18px; text-align:center; text-decoration:none; border-style:solid;" target="_blank">DanceWithMe</a>
                    </td>
             </div>
            </div>`
  });
};`

**Comment by Mert1980** [comment]
![Screenshot from 2020-03-26 08-08-05](https://user-images.githubusercontent.com/55088530/77620035-c9579280-6f39-11ea-8a31-2dad86e8dafd.png)

**Comment by thinkingserious** [comment]
Hello @Mert1980,

I suggest you use [Litmus](https://litmus.com/email-testing) (or similar tooling) for testing out email styles.

You may also want to look into our [transactional templates](https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/). Documentation on how to use those templates in this helper library can be found [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/transactional-templates.md).

Thanks!

With best regards,

Elmer
