### ISSUE TITLE
Examples for @sendgrid/contact-importer please

### ISSUE THREAD

**Issue by heymartinadams** [sendgrid/sendgrid-nodejs#1074]
### Issue Summary
Cannot find any examples for the **@sendgrid/contact-importer** node package. Can someone post a quick example on how to use it?

Thanks!

**Comment by heymartinadams** [comment]
Found one here!

**Comment by chadlittle** [comment]
Seconded

**Comment by ccerrato147** [comment]
There should be at least a basic example on how to use the package.

**Comment by vicentel89** [comment]
> Found one [here](https://github.com/sendgrid/sendgrid-nodejs/issues/988#issuecomment-595440691)!

That is not for nodejs

**Comment by heymartinadams** [comment]
> > Found one [here](https://github.com/sendgrid/sendgrid-nodejs/issues/988#issuecomment-595440691)!
> 
> That is not for nodejs

It is, @vicentel89

**Comment by jamesjjk** [comment]
> > > Found one [here](https://github.com/sendgrid/sendgrid-nodejs/issues/988#issuecomment-595440691)!
> > 
> > 
> > That is not for nodejs
> 
> It is, @vicentel89

Its note related to the helper contact-importer lib
