### ISSUE TITLE
The from address does not match

### ISSUE THREAD

**Issue by musti-91** [sendgrid/sendgrid-nodejs#1088]
### Issue Summary
I'm trying to integrate nodejs app with SendGrid, by submitting contact form in the front-end
so `from` mail could be any one
and `to` will be me
And I got this message

### Code Snippet
```node
sendGrid.setApiKey(process.env.MY_SENDGRID_API_KEY);

    const msg = {
      to: 'myemai@gmail.com,
      from: "sendemail@anyone.com",
      subject: 'Sending with SendGrid is Fun',
      text: message,
      html: `<strong>${name} is trying to get in touch with you!</strong>`,
    };
    return sendGrid.send(msg);
```

### Exception/Log
```
"message": "The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements",

```

### Technical details:
* sendgrid-nodejs version: latest
* node version: 10.16.0

**Comment by childish-sambino** [comment]
This use case is not supported. The sender needs to be a verified sender identity: https://sendgrid.com/docs/for-developers/sending-email/sender-identity/

**Comment by LEscobar-Driver** [comment]
@childish-sambino booooo

**Comment by a5okol** [comment]
You need to verify the mail that is the sender. I solved this problem in this way:

Go here:
**Setting** -> **Sender Authentication** -> **Single Sender Verification** -> **Verify an Address**

[Example](https://i.stack.imgur.com/BIMoP.png)

After that, fill out the form on the right and complete the verification of the sender's mail.

[You can read with more detail here.](https://sendgrid.com/docs/ui/sending-email/sender-verification/)

**Comment by nicovoni** [comment]
@a5okol 
![sendgrid](https://user-images.githubusercontent.com/49231283/107157374-15f66180-6984-11eb-8c39-a5a5ce036574.png)
I still get this error even though I have successfully completed the single sender verification!

**Comment by Reivilo85k** [comment]
I have the same problem. I have verified my sender address and still get this message

**Comment by Kazzz** [comment]
I have the same problem.
I had already completed "Domain Authentication" so until 2/17 "Single Sender Verification" wasn't an issue.

**Comment by somesayinice** [comment]
I have the same problem. I have verified the domain and I still get this 403.

**Comment by Abhijeet-Ashapure** [comment]
Kindly set verified sender email address in "setFrom" method of smtp

**Comment by thinkingserious** [comment]
Thank you for helping out @Abhijeet-Ashapure!

**Comment by Prabhjit2401** [comment]
I am using Send grid with Django, my sender address is verified but I am too getting same error" The from address does not match a verified Sender Identity ". Will appreciate any form of help.

**Comment by Rahulm2310** [comment]
@Abhijeet-Ashapure I am getting the same error on my django app. 
![image](https://user-images.githubusercontent.com/54268438/111040493-286b2b80-8459-11eb-825c-1b707fb2f201.png)

Can anyone help me fix this ?

**Comment by JenniferMah** [comment]
Hi @Rahulm2310 we don't track comments on closed issues. Please open a new issue [here](https://github.com/sendgrid/sendgrid-nodejs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

**Comment by BenGratitudeIndia** [comment]
> Kindly set verified sender email address in "setFrom" method of smtp

please i'm using postman but it's not working

**Comment by Wurthma** [comment]
I have the same problem. I have verified the domain and I still get this 403.

**Comment by mjcadz** [comment]
For anyone wondering, If you're using the default email templates you need to set your shipper email to your sendgrid verified email as it overrides the default.

http://localhost:1337/admin/settings/users-permissions/email-templates

**Comment by pkmankar** [comment]
use phpmailer or laravel mail

**Comment by agamadev** [comment]
Same problem here! In our case, we are using Strapi. Both domain and email are verified, still getting the 403.

**Comment by mguyco** [comment]
make sure you use the correct port. sendgrid does not use the default smtp port

**Comment by agamadev** [comment]
> make sure you use the correct port. sendgrid does not use the default smtp port
> 
> `SENDGRID_PORT=465`

Definitely not related to the port. Thanks, though.

**Comment by BinHussein-SA** [comment]
I had same problem, first i set-up the sender verification :
https://docs.sendgrid.com/ui/sending-email/sender-verification
then in Node source code,  i just changed the email in  "to:" , so the receiver "to :" is not the same email as the sender "from:".. and thats fixed the issue ..  
i found the email in the junk mail. hope this work with you.

**Comment by sergiocelis-aite** [comment]
> ¡El mismo problema aqui! En nuestro caso, estamos usando Strapi. Tanto el dominio como el correo electrónico están verificados, aún obteniendo el 403.

Hi @zoix . I have the same error with Strapi. Do you found any solution?

**Comment by zoix** [comment]
Hey @sergiocelis-aite / unfortunately not; we didn’t spend too much time on it and ended up going with a different provider.
Not sure if this helps, but if this still an issue and both domain and email are verified, I would start by checking the api key.
