### ISSUE TITLE
Firebase Cloud Function crashed and no email trigger

### ISSUE THREAD

**Issue by weilies** [sendgrid/sendgrid-nodejs#1092]
### Issue Summary
i am creating a mail flow in Firebase Cloud Function (using TypeScript). It was successfully deployed but i hit error "Error: could not handle the request". Furthermore, there isn't any email trigger to my mailbox

### Code Snippet
```node
export const sendGridTestMailxPOST = functions.https.onRequest((request, response) => {
    cors(request, response, async () => {
        const msg = {
            to: 'weilies@astudion.com',
            from: 'weilies@astudion.com',
            subject: "Test Email",
            text: "This is a test text email",
            html: "<p>This is a test html email</p>"
        };
        // Send it
        await sgMail.send(msg);
    })
});
```

### Exception/Log
```
API key does not start with "SG.".
Unhandled rejection
Error: Unauthorized
    at axios.then.catch.error (node_modules/@sendgrid/client/src/classes/client.js:105:29)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

```

**Comment by weilies** [comment]
i updated my API key, now it reflect different error

> Error: Unauthorized
>     at axios.then.catch.error (node_modules/@sendgrid/client/src/classes/client.js:105:29)
>     at <anonymous>
>     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
> Function execution took 335 ms, finished with status: 'crash'

**Comment by weilies** [comment]
i noticed it was due to error 401 (not authorized). end up i given myself full access and now the mail sent! After that i lower down the accesses one by one to make sure i give out least send email right

**Comment by eshanholtz** [comment]
This appears to be an issue with your SendGrid API token. Please make sure you have properly set your environment variable properly:
```bash
export SENDGRID_API_KEY = '<your_api_key>'
```
Then,
```node
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
```

**Comment by cesarcastmore** [comment]
Hello @weilies 

Can you help me to solve this error?, I have the same error, but my code is developed for firestore.

`import * as functions from 'firebase-functions';
const sgMail = require('@sendgrid/mail');
import { sendGrid } from './sendgrid';

// // Start writing Firebase Functions
// // https://firebase.google.com/docs/functions/typescript
//  export GOOGLE_APPLICATION_CREDENTIALS="/home/ccastillo/Documents/covid19/functions/covid19-273816-0a4922a6f109.json"


exports.createContact = functions.firestore
    .document('/contacts/{id}')
    .onCreate((snap, context) => {


        let contact: any = snap.data();

        return new Promise((resolve, reject) => {


            let text: string = contact.email + '\n';
            text += contact.first_name + ' ' + contact.last_name + '\n';
            text += contact.body;

            sgMail.setApiKey(sendGrid.api);
            const msg = {
                from: 'ccastillo@tegik.com',
                to: 'cesar.cast.more@gmail.com',
                subject: contact.subject,
                html: text
            };

            sgMail.send(msg).then(
                () => {
                    resolve(true);
                },
                (error: any) => {
                    console.log(error)
                });
        })

    });
`
