### ISSUE TITLE
Cancel email scheduled via sendAt

### ISSUE THREAD

**Issue by dandv** [sendgrid/sendgrid-nodejs#1095]
New to Sendgrid, coming from Sparkpost, in particular for the [sendAt feature](https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/time-to-send.md).

I don't see any docs there though about how to cancel scheduled emails.

Is that possible?

`sgMail.send(msg)` returns HTTP 202, with an empty body. It would be far more useful if it returned an id of the scheduled transmission ([as SparkPost does](https://developers.sparkpost.com/api/transmissions/#transmissions-post-schedule-a-transmission)), so it could be cancelled later.

Also, would help to manage expectations by documenting the limitations of this feature, including:
* [scheduling more than 72 hours in advance is forbidden](https://github.com/sendgrid/sendgrid-nodejs/issues/166#issuecomment-255521853). Sparkpost has the same limitation and they're [upfront about it](https://developers.sparkpost.com/api/transmissions/#transmissions-post-schedule-a-transmission).
* cancelling or updating the transmission is not possible

I've sent a PR with these changes (#1097), but unfortunately, these limitations make the scheduled email feature unusable for us.

**Comment by eshanholtz** [comment]
Hi @dandv 

Here is official documentation on how to [stop in-progress emails](https://sendgrid.com/docs/for-developers/sending-email/stopping-an-in-progress-send/). I also found that according to the request body definition in the [api documentation](https://sendgrid.com/docs/api-reference/), the `send_at` parameter cannot be used to schedule emails more than 72 hours in advance.

**Comment by thinkingserious** [comment]
Documentation updated here: https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/scheduled-send.md

Thanks again for bringing this issue to our attention @dandv!
