### ISSUE TITLE
Duplicate email 

### ISSUE THREAD

**Issue by olaven** [sendgrid/sendgrid-nodejs#1101]
### Issue Summary
Sending an email with `@sendgrid/mail` I am receiving the email two times, even though Sendgrid only receives the request once. The image below is from the "activity"-menu on the Sendgrid dashboard. The API call is triggered with a scheduled Google Cloud function, however, the function only runs once. 

<img width="1193" alt="Screenshot 2020-04-22 at 20 15 14" src="https://user-images.githubusercontent.com/18209665/80018586-80621200-84d6-11ea-9e6a-b05ac1437880.png">

### Steps to Reproduce
1. `import {send} from "@sendgrid/mail";`
2. Run `send(await payload)` in scheduled Google Cloud Function

### Technical details:
* sendgrid-nodejs version: `^6.4.0`
* node version: 8

Is this a known issue? 
Thanks for any help! 😄

**Comment by campgurus** [comment]
Having the same issue, sporadically. I send to a list of nine people and 2 of them will receive the same message 2 or three times though the request was only sent once.

**Comment by thinkingserious** [comment]
Hello @lensherrggg,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at https://support.sendgrid.com.

Thank you!

SendGrid DX Team

**Comment by campgurus** [comment]
I have tried that. NO matter what computer or browser  I use I get an error
"too many redirects"

**Comment by childish-sambino** [comment]
That's odd. What if you login first? https://app.sendgrid.com/login

**Comment by campgurus** [comment]
When I get to support, I click the button "Login & Contact Support" and I
get the browser error. I have cleared cookies and tried multiple browsers:

This page isn’t working

*sendgrid.com <http://sendgrid.com>* redirected you too many times.


   - Try clearing your cookies
   <https://support.google.com/chrome?p=rl_error&hl=en-US>.

ERR_TOO_MANY_REDIRECTS

**Comment by childish-sambino** [comment]
@campgurus Not sure why it's not working. What about using an incognito window?

**Comment by piotrjurga** [comment]
I am experiencing exactly the same issue, I've tried three browsers on a computer and a phone, cleared cookies, used incognito, I've trien making another account, no matter what I get infinite redirects after trying to log in on the support page. There seems to be no way to contact the support and I've no idea where to even send the bug report about broken support page as there seems to be no email or phone alternative whatsoever.
