### ISSUE TITLE
SMTP relay with MS Azure

### ISSUE THREAD

**Issue by 4DallasC** [sendgrid/sendgrid-nodejs#1105]
Howdy SendGrid,

I created a SendGrid account via Microsoft Azure, which automatically connected the two account. But now I don't have a normal SendGrid username and password.

When I read the documentation, is says to send via SMTP you simply use your SendGrid username and password. I'm not able to change my username away from the Azure one to my normal email, nor am I able to reset my password, as I might disrupt the Azure/SendGrid connection.

When I tried creating an API key, and using the host "smtp.sendgrid.net" on port 587 with username "apikey" and password "SG.FC.....DI",  it's responding with the following error message:-
"Authentication failed: The provided authorization grant is invalid, expired, or revoked".

I tried editing the api key and granting full permissions, but it had no effect on the authentication failure.

What am I don't wrong? And what is the easiest way to remedy the situation?

Cheers,
Dallas.

**Comment by childish-sambino** [comment]
Not sure if it will work, but have you tried base64-encoding the username and password?

**Comment by 4DallasC** [comment]
Howdy @childish-sambino 

When I don't base64 encode the username or password, I  get "Syntax error in parameters", or incorrect username / password error.

**Comment by childish-sambino** [comment]
Ah, I see. Recommend following-up with support as this is not something that can be resolved in the client lib.

**Comment by thinkingserious** [comment]
Hello @4DallasC,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
