### ISSUE TITLE
Error: Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by factorypolaris** [sendgrid/sendgrid-nodejs#1106]
### Issue Summary
sendgridMail.send(msg).... Returns the following error when attempting to send an email where data/body is greater than 10mb including attachments. 
```
error: {
    message : "Request body larger than maxBodyLength limit",
    ...
}
```
The error is generated by the "follow-redirects" module required by the "axios" module. 

### Steps to Reproduce
Send an email containing an attachment(s) larger than 10mb after base64 encoding. 

### Steps to Fix
The issue can be fixed by increasing the "maxBodyLength" in **follow-redirects** by setting the maxBodyLength in the following way.

```
const sendgridMail = require('@sendgrid/mail');
const followRedirects = require('follow-redirects');
followRedirects.maxBodyLength = 25 * 1024 * 1024;  // set to 25mb to match sendGrid limits.
```
While this can be manually done as shown above, this caused me issues and took quite a bit of time to track down the source of the error.  This should get set within @sendgrid/mail

### Technical details:
* sendgrid-nodejs version: 7.0.1
* node version: 8.17

**Comment by childish-sambino** [comment]
I'm seeing this too. Looking into the fix.

**Comment by childish-sambino** [comment]
Another workaround for now: `sendgridMail.client.setDefaultRequest('maxContentLength', 30 * 1014 * 1024)`
