### ISSUE TITLE
More useful success response

### ISSUE THREAD

**Issue by dandv** [sendgrid/sendgrid-nodejs#1109]
Over time, a number of API users have been confused by the empty response on success ([1](https://github.com/sendgrid/sendgrid-nodejs/issues/652#issuecomment-358714615), [2](https://github.com/sendgrid/sendgrid-nodejs/issues/652), [3](https://github.com/sendgrid/sendgrid-nodejs/issues/397)).

What if the success response included an automatically created Batch ID?

That would allow for [easy canceling of scheduled emails](https://github.com/sendgrid/sendgrid-nodejs/issues/1095), or keeping track of bounced, or whatnot. [Mandrill](https://mandrillapp.com/api/docs/messages.JSON.html#method=send), [Sparkpost](https://developers.sparkpost.com/api/transmissions/#transmissions-post-send-a-template), [mailgun](https://documentation.mailgun.com/en/latest/api-sending.html#examples) etc., all return a useful ID.

**Comment by childish-sambino** [comment]
Since this is not something that can be implemented in the client library, best to contact [support](https://support.sendgrid.com) to see if this is on the horizon.
