### ISSUE TITLE
How can I set the name of the recipient?

### ISSUE THREAD

**Issue by dandv** [sendgrid/sendgrid-nodejs#1111]
https://sendgrid.com/docs/api-reference/ says `to.name` is "The name of the person or company that is sending the email." The same description shows for `cc.name` and `reply_to.name`.

Is that a copy/paste typo from `from.name`?

**Comment by childish-sambino** [comment]
Yeah, looks like copy-paste error. Looking into how to get this corrected ...

**Comment by childish-sambino** [comment]
I was able to track down the process for getting this updated and have put in the request but don't have a timeline yet. Closing this issue since it's not something that can be resolved in the library itself. I'll circle back here when this issue's been corrected.

**Comment by childish-sambino** [comment]
Docs have been updated.
