### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Forbidden

### ISSUE THREAD

**Issue by tazzzzzzz** [sendgrid/sendgrid-nodejs#1115]
### Issue Summary
I'm relatively new to using sendgrid with node.js, and wanted to check it out. I followed all the instructions provided on https://app.sendgrid.com/guide/integrate/langs/nodejs. I even tried to replacing the "to" and "from" properties of "msg" with my own email id, and got the same error as the result.
### Steps Followed
1. Created a new account and generated API Key over at https://app.sendgrid.com/guide/integrate/langs/nodejs
2. Followed steps 2,3,4
3. Tried to implement step 5, and the below mentioned error was encountered
4. In order to get the log of the error, I set up a try-catch statement to work as a promise handler which would output the error log, if there was an error.

### Code Snippet
```node
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'test@example.com',
  from: 'test@example.com',
  subject: 'Sending with Twilio SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};
sgMail.send(msg);
```

### Exception/Log

```
(node:2831) UnhandledPromiseRejectionWarning: Error: Forbidden
    at Request._callback (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:2831) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2831) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Technical details:
* sendgrid-nodejs version: 6.5.5
* node version: v12.16.2
* OS: Ubuntu 18.04 LTS

**Comment by tazzzzzzz** [comment]
It was least expected, but upon more close checking I realised that I had made the mistake of not including a '.' in the sender's email address I had registered as a single sender. Apologies.

**Comment by mbrookes** [comment]
@thazhemadam Please could you reopen this? 

It's a documentation issue, since the page doesn't mention that you need to use a valid sender and a recipient. Since there is a validation step that interrogates logs, it would seem reasonable to use the example.com email addresses provided.

Incidentally, for anyone coming across this - you might find that that once the test mail does send, that it lands in spam.
