### ISSUE TITLE
Allow for timeout option for sendgrid/client request

### ISSUE THREAD

**Issue by caitlinjshort** [sendgrid/sendgrid-nodejs#1116]
### Issue Summary

With the upgrade to axios the option to pass a timeout value is not accepted. https://github.com/axios/axios#request-config

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* sendgrid-nodejs version: 7.1.0
* node version: 10.19

**Comment by childish-sambino** [comment]
Was this something you were able to do previously with the `request` client or is this just a new ask? If it's the former, could you provide a code example of how you were doing this? If it's the latter, could you provide an example of how you'd expect to pass the timeout?
