### ISSUE TITLE
The provided authorization grant is invalid, expired or revoked

### ISSUE THREAD

**Issue by alhime1225** [sendgrid/sendgrid-nodejs#1118]
### Issue Summary
Okay, so I have integrated sendgrid into my site which is deployed in heroku. I've set up domain sender validation and had it validated (added CNAME in my domain provider etc.) Now, I kept having issues such as:

1. **"API does not start with SG"**
2. **"The provided authorization grant is invalid, expired or revoked"** is my other issue.

I have edited the API key to have full access but didn't change a thing. I can't get in contact with the support team either, I'm at my wits end. 

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```node
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

app.post("/", function(req, res) {
  const emailFrom = req.body.emailFrom;
  const emailSubject = req.body.emailSubject;
  const emailMessage = req.body.emailMessage;

  const msg = {
    to: [{
        email: 'test@test.com'
      },
      {
        email: 'test@test.com'
      }, {
        email: 'test@test.com'
      }
    ],
    from: emailFrom,
    subject: emailSubject,
    text: emailMessage
  };

  sgMail.send(msg).then(() => {
    console.log('Message sent')
  }).catch((error) => {
    console.log(error.response.body)
  })

  process.on('unhandledRejection', (reason, p) => {
    console.log('Unhandled Rejection at: Promise', p, 'reason:', reason);
  });
});

```

### Exception/Log
```
2020-05-06T16:46:46.569386+00:00 app[web.1]: API key does not start with "SG.".
2020-05-06T16:46:46.570017+00:00 app[web.1]: undefined
2020-05-06T16:46:46.683253+00:00 app[web.1]: {
2020-05-06T16:46:46.683255+00:00 app[web.1]: errors: [
2020-05-06T16:46:46.683256+00:00 app[web.1]: {
2020-05-06T16:46:46.683257+00:00 app[web.1]: message: 'The provided authorization grant is invalid, expired, or revoked',
2020-05-06T16:46:46.683257+00:00 app[web.1]: field: null,
2020-05-06T16:46:46.683258+00:00 app[web.1]: help: null
2020-05-06T16:46:46.683258+00:00 app[web.1]: }
2020-05-06T16:46:46.683260+00:00 app[web.1]: ]
2020-05-06T16:46:46.683260+00:00 app[web.1]: }
```

### Technical details:
* sendgrid-nodejs version: 7.1.0
* node version: V12.16.2

**Comment by childish-sambino** [comment]
It's likely the API key is not being set properly in the env var. Recommend logging the `process.env.SENDGRID_API_KEY` value to make sure it's being populated.

**Comment by 1curtislee** [comment]
If you use this command line input (found in the README) to set up your .env file:
```
echo "export SENDGRID_API_KEY='YOUR_API_KEY'" > sendgrid.env
echo "sendgrid.env" >> .gitignore
source ./sendgrid.env
```
it will generate your .env with the wrong syntax. Remove ` ' ' ` surrounding your api key, and your app will use the correct api key, formatted properly.

Alternatively, here is the fixed command:
```
echo "export SENDGRID_API_KEY=YOUR_API_KEY" > sendgrid.env
echo "sendgrid.env" >> .gitignore
source ./sendgrid.env
``` 
Be sure to replace `YOUR_API_KEY` with the actual, full key.

**Comment by childish-sambino** [comment]
I don't believe that is the solution. See my comment here: https://github.com/sendgrid/sendgrid-nodejs/pull/1126#issuecomment-632267232

Recommend path forward is to try logging/printing the env var to verify it's the proper format.

**Comment by halouzkovap** [comment]
i work with spring boot and i have same problem :401
{"errors":[{"message":"The provided authorization grant is invalid, expired, or revoked","field":null,"help":null}]}   i use you integraion guid and nothing work, can you help ?

**Comment by childish-sambino** [comment]
> It's likely the API key is not being set properly in the env var. Recommend logging the `process.env.SENDGRID_API_KEY` value to make sure it's being populated.

> Recommend path forward is to try logging/printing the env var to verify it's the proper format.
