### ISSUE TITLE
Reply-To is not processed correctly

### ISSUE THREAD

**Issue by jonathan-short** [sendgrid/sendgrid-nodejs#1121]
### Issue Summary
When sending an email through this SDK, if the 'name' portion of 'from' contains commas and ampersands, it is shown properly in gmail.  When the 'name' portion of 'replyTo' is set to the same exact name, gmail finds it malformed.

Portion from "Show original" in gmail to see raw headers (with some values redacted):
```
...
From: "\"Jonathan Short, jonathan.short+051220@example.com & Jonathan Short\"" <test@redacted>
Mime-Version: 1.0
Message-ID: <redacted>
Subject: Sending with Twilio SendGrid is Fun
Reply-To: jonathan.short+051220@example.com, "& Jonathan Short" <test2@redacted>
To: <redacted>
...
```

### Steps to Reproduce
1. In the code snippet, replace the <redacted> email domain on the 'to' field to your gmail email address
2. In the code snippet, replace the <redacted> email domain in 'from' and 'replyTo' fields to a domain properly configured for Sender Authentication in your SendGrid account
3. Export SENDGRID_API_KEY with a key which has permission to send email
4. Run the code snippet and observe the email received in gmail

### Code Snippet
```node
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
# this complex name is handled correctly for From address but incorrectly for Reply-To
const name = "Jonathan Short, jonathan.short+051220@example.com & Jonathan Short";
const msg = {
  to: 'jonathan.short@<redacted>',
  from: {
    email: 'test@<redacted>',
    name: name,
  },
  replyTo: {
    email: 'test2@<redacted>',
    name: name,
  },
  subject: 'Sending with Twilio SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};

sgMail
  .send(msg)
  .then(() => {}, error => {
    console.error(error);

    if (error.response) {
      console.error(error.response.body)
    }
  });
```

### Exception/Log
```
none
```

### Technical details:
* sendgrid-nodejs version: 7.1.0
* node version: 14.2.0

**Comment by jonathan-short** [comment]
I logged the body sent to SendGrid here (https://github.com/sendgrid/sendgrid-nodejs/blob/fa11e35bee18ac480ca9b331c09447907e1a8799/packages/mail/src/classes/mail-service.js#L193), looks like the from name and reply-to name are identical so perhaps a server side issue?

```
{
  from: EmailAddress {
    email: 'test@<redacted>',
    name: '"Jonathan Short, jonathan.short+051220@example.com & Jonathan Short"'
  },
  subject: 'Sending with Twilio SendGrid is Fun',
  personalizations: [ { to: [Array] } ],
  content: [
    {
      value: 'and easy to do anywhere, even with Node.js',
      type: 'text/plain'
    },
    {
      value: '<strong>and easy to do anywhere, even with Node.js</strong>',
      type: 'text/html'
    }
  ],
  reply_to: EmailAddress {
    email: 'test2@<redacted>',
    name: '"Jonathan Short, jonathan.short+051220@example.com & Jonathan Short"'
  }
}
```

**Comment by thinkingserious** [comment]
Hello @jonathan-short,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
