### ISSUE TITLE
README.md includes wrong command line syntax for setting up api key environment variable

### ISSUE THREAD

**Issue by 1curtislee** [sendgrid/sendgrid-nodejs#1125]
### Issue Summary
README.md provides this command line input for setting up .env variables:
```
echo "export SENDGRID_API_KEY='YOUR_API_KEY'" > sendgrid.env
echo "sendgrid.env" >> .gitignore
source ./sendgrid.env
```
There should not be `'  '` around `YOUR_API_KEY`. Using `process.env.SENDGRID_API_KEY` will throw the `API key does not start with "SG."` error.

### Technical details:
* sendgrid-nodejs version: v3 
* node version: v10.16.3

**Comment by childish-sambino** [comment]
Following up on #1126
