### ISSUE TITLE
Documentation regarding sgMail.sendMultiple()

### ISSUE THREAD

**Issue by phao5814** [sendgrid/sendgrid-nodejs#1127]
In the [docs](https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/multiple-emails-multiple-recipients.md), it mentions that using sgMail.send() for multiple emails will send those emails in parallel, which potentially may exhaust API restrictions.

Is this the case when using sgMail.sendMultiple()? If not, might be worthwhile to document it for people wondering the same thing.

**Comment by eshanholtz** [comment]
Yes, `sgMail.sendMultiple(data, callback)` is just a shortcut for `sgMail.send(data, true, callback)`, which sends multiple emails in parallel.
