### ISSUE TITLE
Unable to retain the content of the file when zipped file is sent over by sendgrid

### ISSUE THREAD

**Issue by kushal4** [sendgrid/sendgrid-nodejs#1130]
Issue Summary
Unable to send mail with zip as attachment.

Steps to Reproduce
Create a zip file with a single csv file in it.
generate base64 encode of the zip file and provide as content value, type: application/zip
I see that the generated base64 content of the zip file isn't correct and attaches an empty zip file attachment .

return new MailMessage("sphurti XXX","Testing attachment","TestMail",[{
        content: await fs.readFileSync(test.zip).toString('base64'),
        filename: "test.zip",
        type: 'application/zip',
        disposition: 'attachment',
    }])

**Comment by kushal4** [comment]
When am sending invidual file then the file content and payload is conserved but when i zip it and send it as attachement then the file is getting corrupted

**Comment by thinkingserious** [comment]
Hello @kushal4,

Could you please let me know how you constructed the zip file? I was not able to reproduce using the following steps and I'm thinking your zip file may be corrupt:

`zip test.zip test.csv` (`test.csv` just has one line: `1, 2, 3, 4`)

```javascript
const sgMail = require('@sendgrid/mail');
const fs = require('fs');

let pathToAttachment = `${__dirname}/test.zip`;
let zippedContent = fs.readFileSync(pathToAttachment).toString("base64");
const msg = {
  to: 'to@example.com',
  from: 'from@example.com',
  subject: 'Hello attachment',
  html: '<p>Here’s an attachment for you!</p>',
  attachments: [
    {
      content: zippedContent,
      filename: 'test.zip',
      type: 'application/zip',
      disposition: 'attachment'
    },
  ],
};

sgMail.setApiKey(process.env.SENDGRID_API_KEY);
sgMail
  .send(msg)
  .then(() => {
    console.log("Email sent.");
  })
  .catch(error => {
    // Log friendly error
    console.error(error);

    if (error.response) {
      // Extract error msg
      const {message, code, response} = error;

      // Extract response msg
      const {headers, body} = response;

      console.error(body);
    }
  });
```

**Comment by kushal4** [comment]
Hi ,
I went on creating the zip file with 'archiver' library by creating zip from xlsx file, and tried to send it by the format you mentioned but still am getting corrupted  xlsx file within the zipped file

**Comment by thinkingserious** [comment]
Hello @kushal4,

Is the file still corrupted if you use this command: `zip test.zip test.xlsx`?
