### ISSUE TITLE
Create a convenience method to enable sandbox mode

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#1134]
### Issue Summary

Related to issue https://github.com/sendgrid/sendgrid-nodejs/issues/1128

Currently, here is some sample code to enable sandbox mode:

```javascript
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'recipient@example.org',
  from: 'sender@example.org',
  subject: 'Hello world',
  text: 'Hello plain world!',
  html: '<p>Hello HTML world!</p>',
  mailSettings: {
    sandboxMode: {
      enable: true,
    },
  },
};
```

Implementing a convenience method `sgMail.enableSandboxMode()` is the ask.

**Comment by childish-sambino** [comment]
Recommend we close this and just use #1128 to track the work. Issues created by members are not tracked.
