### ISSUE TITLE
Marketing - Senders List returns forbidden

### ISSUE THREAD

**Issue by rokern002** [sendgrid/sendgrid-nodejs#1135]
We are trying to use senders api, but always get 403 - fobidden as result. The Api Key is unrestricted and work in correct:
![image](https://user-images.githubusercontent.com/45965470/83641214-8525e580-a5ad-11ea-865c-15dcadf65716.png)

Now the senders api from marketing:

![image](https://user-images.githubusercontent.com/45965470/83641361-b7cfde00-a5ad-11ea-994c-96305959ce2a.png)

We currently using free account, but will switch to paid one, if the software go live.

Do anyone have same issue or experienced similar problem? Do we need paid subscription?

**Comment by childish-sambino** [comment]
I don't think the legacy marketing APIs are available for new accounts. Try using the new ones. Example docs here: https://sendgrid.api-docs.io/v3.0/senders
