### ISSUE TITLE
SendGrid Broken After Unsubscribing

### ISSUE THREAD

**Issue by JimLynchCodes** [sendgrid/sendgrid-nodejs#1137]
I am using the nodejs client to send an email:

```
const sgClient = require('@sendgrid/client');
sgClient.setApiKey(process.env.SENDGRID_KEY);
const msg = {
 to: sgTgRecipients,
 from: 'jim.lynch@evaluates2.com',
 subject: `Triple Gainers for ${currentDay}!`,
 text: fullTextEmail,
 html: fullTextEmail,
 tracking_settings: {
 subscription_tracking: {
 enable: true,
 substitution_tag: '<% Unsubscribe Here %>'
        }
      }
    };
const mailResponse = await sgMail.send(msg)
```

When I received this email as the recipient user I did see an unsubscribe link in the email:
https://u16916466.ct.sendgrid.net/wf/unsubscribe?upn=uL79VpfnkgEnZ9EeQXYj11wQRB-2BII-2FgvYj1opoqL6UlrpZvU-2BPtXNuGhEXSW6PkO8axKr5uHXgoIeMRMBexhXzDSCJXgYSkx4lDQDNSsmPuinCorLQ33NHMuvYAXyh1XhhgLcDlXtG8BWi8lU6cRNBM5gwjW2r-2FmstPR-2FDobkZnpoQeWjTMcvqVJxAxlcnMxKceIjvEDdRoIKkr0mbz6rb0tpPuAngaImZnVgDcpBWI-3D

When clicking on it the link took me to a page with one h1 and one p tag saying "you have unsubscribed. You will no longer receive mails from this list".
However, I do not see this email adderess in any of my unsubscriber groups (also, I don't see how this is associating the unsubscribed email address with any specific unsubscribed group). 
Since this my my own test email, i would like to receive emails again. However, when I set "subscription_tracking" "enable' to false I don't get any email. When I completely delete the ubsubscriber group I still don't see any emails. 
So my question is- what is it that i actually subscribed to here? Why do I not see the unsubscribed email in any of my unsubscriber lists? How to I "undo the ubsubscribe"? Thanks!

**Comment by thinkingserious** [comment]
Hello @JimLynchCodes,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
