### ISSUE TITLE
event webhook - please provide example for usage in express 

### ISSUE THREAD

**Issue by steinroe** [sendgrid/sendgrid-nodejs#1142]
### Issue Summary
I am struggling with the EventWebhook signing procedure a while now and can't get it to work. Tried multiple options, including using the raw req body for the timestamp. The verification always fails..

Edit: I am using the verifySignature function from the eventwebhook package here.
Edit 2: Added sample data that was gathered by logging the respective constants.
### Steps to Reproduce
1. Setup an express server, deploy it somewhere and trigger the Webhook.

### Code Snippet
```node
import express from "express";
import cors from "cors";
import asyncHandler from "express-async-handler";
import createError from "http-errors";
// @ts-ignore
import { Ecdsa, Signature, PublicKey } from '@starkbank/ecdsa';
const app = express();
app.use(cors({ origin: true }));
app.use(
    express.json({
        verify: (req, res, buf) => {
            // @ts-ignore
            req.rawBody = buf;
        },
    })
);

const verifySignature = (publicKey: PublicKey, payload: any, signature: string, timestamp: string) => {
    let timestampPayload = typeof payload === 'object' ? JSON.stringify(payload) : payload;
    timestampPayload = timestamp + timestampPayload;
    const decodedSignature = Signature.fromBase64(signature);

    return Ecdsa.verify(timestampPayload, decodedSignature, publicKey);
}

app.post(
    "/event",
    asyncHandler(async (req, res) => {
        const signature = req.get('X-Twilio-Email-Event-Webhook-Signature');
        const timestamp = req.get('X-Twilio-Email-Event-Webhook-Timestamp');
        const payload = req.body;  // req.rawBody also does not work

        if (!signature || !timestamp || !payload) {
            throw createError(403, "Unauthorized Request");
        }

        console.log('verifying')
        console.log(signature)
        console.log(timestamp)
        console.log(JSON.stringify(payload))
        const publicKey = PublicKey.fromPem(functions.config().env.sendgrid.publicKey);
        if(!verifySignature(publicKey, payload, signature, timestamp)) {
            throw createError(403, "Unauthorized Request");
        }
        console.log('verified')

   
    })
);

// @ts-ignore
app.use((error, req, res, _) => {
    res.status(error.status || 500);
    res.json({
        status: error.status,
        message: error.message,
    });
    console.error(error.message)
});
```
```node
// sample data from logs above
const TIMESTAMP = "1591866114"
const PAYLOAD = [{"email":"heyanna-test@hotmail.com","event":"bounce","ip":"167.89.17.173","mc_stats":"singlesend","phase_id":"send","reason":"550 5.5.0 Requested action not taken: mailbox unavailable (S2017062302). [VE1EUR03FT058.eop-EUR03.prod.protection.outlook.com]","send_at":"1591866054","sg_event_id":"Ym91bmNlLTAtMTU2MTI0NDktQTVjTHQweTBTWXlBLXN2N3RWNUQydy0x","sg_message_id":"A5cLt0y0SYyA-sv7tV5D2w.filterdrecv-p3iad2-784dbb6bd8-cmnvf-19-5EE1F2DB-11B.1","sg_template_id":"d-bb3d0c9fd0e1494f990a9d386437c6b0","sg_template_name":"Clone: Clone: Clone: Clone: Clone: Clone: Clone: Clone: Clone: Clone: Clone 2020-06-11T08:58:41.387Z","singlesend_id":"bfba94a4-abc1-11ea-b5ff-fac9c7677002","singlesend_name":"DEV-Test 11","smtp-id":"<A5cLt0y0SYyA-sv7tV5D2w@ismtpd0087p1mdw1.sendgrid.net>","status":"5.5.0","template_hash":"030c05c8aa7b8112e5e2d6a99def801d95ccb03f0cf0388874129b4dfb1f41e9","template_id":"d-bb3d0c9fd0e1494f990a9d386437c6b0","template_version_id":"a55a3135-fdf9-41af-8c29-7b93962baab7","timestamp":1591866077,"tls":1,"type":"bounce"}]
const PUBLIC_KEY = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAETg3hldXJ3S/JlTbsYXdYCDuSpQHISB5C9xPgDkqjjPAyVIVhwSTR7UhIWC7mpvXa4vmCNyAucNmHAosg3p0/eA=="
const SIGNATURE = "MEYCIQCKLxRqhAbX/XlPl35AoiOII6l5D64R21TaiX4TB8sejQIhAJc/PM1SDCkfdyx6gu9Up1GjbJyHz2m6jicfyjaKJupj"
```

### Exception/Log
Unauthorized Request

**Comment by childish-sambino** [comment]
Payload in the sample is an array? Maybe try just passing in the contained object itself.

**Comment by steinroe** [comment]
Thanks for the hint, but it does not work. Your docs also state that the entire payload has to be used.

**Comment by eshanholtz** [comment]
Thanks for reaching out, I've been able to reproduce this issue using my own account. I've reached out to the owning team for further help and will circle back with an update when I hear more.

**Comment by eshanholtz** [comment]
Hi @steinroe 
I was able to talk to the owning team and determine that the issue here is that a `\r\n` carriage return is being stripped from the end of the JSON. Here's a snippet of the express server I wrote to process incoming webhooks:

```js
var express = require('express');
var bodyParser = require('body-parser');
var app = express();

var EventWebhook = require('@sendgrid/eventwebhook');

app.use(bodyParser.text({ type: 'application/json' }));

var isValidSignature = function(req, res, next) {
  let eventWebhook = new EventWebhook();
  const signature = req.get('X-Twilio-Email-Event-Webhook-Signature');
  const timestamp = req.get('X-Twilio-Email-Event-Webhook-Timestamp');
  const ecPublicKey = eventWebhook.convertPublicKeyToECDSA('<your_public_key>');
  if (eventWebhook.verifySignature(ecPublicKey, req.body, signature, timestamp)) {
    next();
  } else {
    res.status(400).end();
  }
};

app.use(isValidSignature);

app.post('/', function (req, res) {
  // do something with the request
  res.status(200).end();
});

app.listen(3000);

```

The key here was using `app.use(bodyParser.text({ type: 'application/json' }));` as middleware to parse the request.

Hope this helps!

**Comment by Neilpoulin** [comment]
First of all, I was able to follow this thread and get my signature validating to work. So, thank you for that! 

However, I spent the last 2 days trying to get this event signing to work, and tried a number of libraries for validating these signatures, and none of them worked. I am on node 10, so the example linked in the [documentation](https://sendgrid.com/docs/for-developers/tracking-events/getting-started-event-webhook-security-features/#the-signed-event-webhook)  that references the Node Crypto library wouldn't work for me (as it was only available on node 14). 

I tried all of the popular elliptic crypto libraries on NPM, and none of them worked for lots of reasons- unable to parse the signature, unable to parse the public key, etc. I tried all of the different curve options provided by the `elliptic` library on npm. All failed for different reasons. 

None of my googling surfaced the Starkbank library. Even if i found it, i likely wouldn't have trusted it as only been downloaded ~100 times. 

I wrote to support, and they attempted to escalate the request - still haven't heard back. 

It wasn't until a friend dug out the pull request from @eshanholtz for the `eventwebhook` package that I was able to find a solution. _THANK YOU_ for that package. 

The good news is that using the package, is as able to verify signatures on the first try. 

Please, please, please update your documentation/readme to at least _mention_ all of the various SDKs that are available in this monorepo. That small hint would have saved me 2 days of frustration.

**Comment by steinroe** [comment]
First of all, sorry for my late response and thanks for the help @eshanholtz!

Unfortunately, I can agree with @Neilpoulin. Whatever I tried, including your source code, did not work and I always get false back. However, thanks to the code from @Neilpoulin, it finally worked. I guess what was missing in your code @eshanholtz was the toString().

**Comment by Piccirello** [comment]
I just ran into this signature verification issue when implementing a new webhook. `JSON.stringify(req.body)` would always fail validation, but switching to `req.rawBody` fixed it. +1 on the suggestion to mention`req.rawBody` in the example. And thanks @eshanholtz for building `@sendgrid/eventwebhook`.

> None of my googling surfaced the Starkbank library. Even if i found it, i likely wouldn't have trusted it as only been downloaded ~100 times.

I have to agree with this. After reading the webhook docs online, I resorted to using `test/typescript/eventwebhook.ts` as a reference implementation because it was contained in the initial PR. After reviewing the eventwebhook source, I initially looked into alternative ecdsa libraries, and then at copying over just the necessary code from starkbank (which was more extensive than I anticipated). The starkbank repo is missing a `package-lock.json` and relies on 2 packages that can be replaced with native node libraries: `js-sha256` and `big-integer`. It also lists `mocha` as a non-dev dependency. None of these are earth shattering, but they do make me question how much peer review the repo has received.

**Comment by eshanholtz** [comment]
Thank you all for your feedback! I have opened PR #1153 to update the interface for the signature verification function to accept both `string` and `Buffer` types. The PR also includes documentation for the `bodyParser` middleware and Firebase Cloud Functions example usages (thanks @Neilpoulin !).

**Comment by eshanholtz** [comment]
Changes will be included in the next release scheduled for tomorrow, 2020-06-24
