### ISSUE TITLE
Repeated error: Service Unavailable (axios.then.catch.error)

### ISSUE THREAD

**Issue by Tsabary** [sendgrid/sendgrid-nodejs#1143]
I am new to SendGrid and trying to send an email from my React.js app using Firebase Cloud functions for my back-end.
When someone wants to send a message, I write a document to Firestore. I then listen to that collection and when a document is created I send an email from a cloud function.

I'm trying to make it work, but keep getting an error logged in my cloud functions and this error message:

```
    Error: Service Unavailable
        at axios.then.catch.error (node_modules/@sendgrid/client/src/classes/client.js:133:29)
        at <anonymous>
        at process._tickDomainCallback (internal/process/next_tick.js:229:7)
``` 

I can't figure out if I'm doing anything wrong, or am I just unlucky and have been trying to implement it for the first time while SendGrid is experiencing some issues (`Service Unavailable`).

This is how I define sgMail:

```
    import * as sgMail from "@sendgrid/mail";
    const SENDGRID_API_KEY = functions.config().sendgridfull.key;
    sgMail.setApiKey(SENDGRID_API_KEY);
```

This is my cloud function, and I've checked all the variables and they all exist.

```
    exports.firestoreEmail = functions.firestore
      .document("email_messages/{messageID}")
      .onCreate((snap, context) => {
        const msgData = snap.data();
        if (!msgData) return;
    
        return db
          .collection("users")
          .doc(msgData.recipient_ID)
          .get()
          .then((doc) => {
            const recipientData = doc.data();
            if (!recipientData) return;
    
            const promises: any = [];
    
            const msg = {
              to: recipientData.email,
              from: msgData.sender_email,
              templateId: "d-myRandomTemplateId",
              dynamic_template_data: {
                sender_name: "Some One",
              },
            };
    
            const msg2 = {
              to: msgData.sender_email,
              from: recipientData.email,
              templateId: "d-myRandomTemplateId",
              dynamic_template_data: {
                sender_name: "Some One",
              },
            };
    
    
    
            promises.push(sgMail.send(msg));
            promises.push(sgMail.send(msg2));
    
            return Promise.all(promises);
          });
      });
```

**Comment by Tsabary** [comment]
I've caught the error in a catch statement, and got more details about it. This is the full log:

    { Error: Forbidden
        at axios.then.catch.error (node_modules/@sendgrid/client/src/classes/client.js:133:29)
        at <anonymous>
        at process._tickDomainCallback (internal/process/next_tick.js:229:7)
      code: 403,
      message: 'Forbidden',
      response: 
       { headers: 
          { server: 'nginx',
            date: 'Thu, 11 Jun 2020 17:03:27 GMT',
            'content-type': 'application/json',
            'content-length': '281',
            connection: 'close',
            'access-control-allow-origin': 'https://sendgrid.api-docs.io',
            'access-control-allow-methods': 'POST',
            'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
            'access-control-max-age': '600',
            'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' },
         body: { errors: [Array] } } }

**Comment by Tsabary** [comment]
EDIT 2:
So I've follow the link in the error `https://sendgrid.com/docs/for-developers/sending-email/cors/` and if I get that right, it suggests that it blocks me because I am trying to make a browser-based call to their API? But that's not the case. I'm making the call from a cloud function.

**Comment by childish-sambino** [comment]
Try logging the error body. It's only showing as `body: { errors: [Array] } ` in your log. It will contain a more detailed reason. Example here: https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/success-failure-errors.md

**Comment by Tsabary** [comment]
Thank you, that helped me figure out my issue. For my 'from' field I've set an email that wasn't set as an authorized sender

**Comment by slk333** [comment]
Faced the same issue. Sendgrid told me to send a test mail from "...@example.com" but of course it cannot work.
