### ISSUE TITLE
uploading emails from .csv file

### ISSUE THREAD

**Issue by tanishq-soni** [sendgrid/sendgrid-nodejs#1148]
I have an issue that i want to send mails to the emails in the csv file,
so can anyone show me the nodejs program of that in which we can add csv file as a email in the program.

**Comment by thinkingserious** [comment]
Hello @tanishq-soni,

You will likely use one of the following use cases as you iterate through the csv of emails:
- https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/multiple-emails-multiple-recipients.md
- https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/single-email-multiple-recipients.md

However, if you are using marketing campaigns, please check here: https://sendgrid.com/docs/ui/managing-contacts/create-and-manage-contacts

Thank you!

With best regards,

Elmer
