### ISSUE TITLE
Substitutions in dynamic data

### ISSUE THREAD

**Issue by adamreisnz** [sendgrid/sendgrid-nodejs#1154]
Is it at all possible to use substitutions _and_ dynamic template data _together_ with the new dynamic templates?

We let our customers send out generic emails, and allow them to format these using markdown. Since Sendgrid does not support markdown, we pre-render the markdown on our end, which generates HTML, which we pass as dynamic template data to be used in the dynamic email template.

However – we also let our customers use some basic substitutions in their email messages, like first/last name of the recipient.

I know I can generate the HTML message _per recipient_ and send this in the dynamic data per personalisation, however that seems like a brute force approach and will result in a lot of overhead of duplicate HTML being sent with the request.

However, if we could use substitutions in our dynamic template data, this would work great.

For example:

### Template
```hbs
<div>
  {{{message}}}
</div>
```

### JS
```
const message = `<p>Some generated HTML for [FIRST_NAME]</p>`;
const mail = {
  templateId: 'd-xxxxxx',
  dynamicTemplateData: {
    message
  },
  personalizations: [
    {to: 'foo@example.org', substitutions: {FIRST_NAME: 'Foo'}},
    {to: 'bar@example.org', substitutions: {FIRST_NAME: 'Bar'}},
  ],
};
```

### Result
```html
<div>
  <p>Some generated HTML for Foo</p>
</div>

<div>
  <p>Some generated HTML for Bar</p>
</div>
```

Does this already work? If not, is it doable? Alternative suggestions?

**Comment by childish-sambino** [comment]
No, that's currently not possible without doing (as you mentioned) sending duplicate HTML in each request/personalization.

Only thing I can think of is to actually create a dynamic template (by calling a different API) given the customer's input and then use dynamic template data as usual.

**Comment by adamreisnz** [comment]
Yeah I was worried that wouldn't work. Would it be possible to implement something like that on your end though?
Since both mechanisms are already there, there may be a relatively easy way to sort of use them both.

Creating templates first seems like overkill, so we'll probably stick with duplicate HTML for the time being.

**Comment by childish-sambino** [comment]
This is not a change that can be made in the library. An internal ticket has been filed against the relevant product team (reference ID: _CL-3070_).

**Comment by adamreisnz** [comment]
Yep, that's what I was referring to. Thanks.
