### ISSUE TITLE
Mail from nodejs not working

### ISSUE THREAD

**Issue by sriramgroot** [sendgrid/sendgrid-nodejs#1159]
### Issue Summary
I'm trying to trigger an email from nodejs application with a specific set of informations, but even after triggering the from the nodejs as a receiver i could not to receive the email from sendgrid.

### Steps to Reproduce
1. Based on the instruction provided in below mentioned link i tried to trigger mail
https://sendgrid.com/docs/for-developers/sending-email/quickstart-nodejs/
2. Mail action is performed from nodejs side but i couldn't receive the email

### Code Snippet
```
let msg = {
		to: userInfo.username,
		from: 'githubuser@gmail.com',
		subject: 'Sendgrid Sample Mail',
		html: 
		`<p>Hello ` + userInfo.username + `,<br/><br/>
		Thanks for registering with Sendgrid. You can able to download the files from the link mentioned below<br/><br/>
		<strong>Download Link: </strong>` + userInfo.downloadFile + `<br/><br/>
		Thanks & Regards,<br/>
		Sendgrid Team</p>`
};
sgMail.send(msg);
```

### Exception/Log
```
No Exception received to mention here
```

### Technical details:
* sendgrid-nodejs version: "@sendgrid/mail": "^6.5.5"
* node version: v8.10.0

**Comment by thinkingserious** [comment]
Hello @sriramgroot,

Please use [this example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/success-failure-errors.md) to help determine what the error is and let us know what you find.

Thanks!

With best regards,

Elmer

**Comment by sriramgroot** [comment]
Hi @thinkingserious 
I had checked the instruction you had provided for logging error, But iam not getting any type of logs to show here. Added code for your reference

```
let msg = {
		to: userInfo.username,
		from: 'githubuser@gmail.com',
		subject: 'Sendgrid Sample Mail',
		html: 
		`<p>Hello ` + userInfo.username + `,<br/><br/>
		Thanks for registering with Sendgrid. You can able to download the files from the link mentioned below<br/><br/>
		<strong>Download Link: </strong>` + userInfo.downloadFile + `<br/><br/>
		Thanks & Regards,<br/>
		Sendgrid Team</p>`
};
sgMail.send(msg)
	.then(() => {
		// Celebrate
	  })
	  .catch(error => {
		// Log friendly error
		console.error(error);
	
		if (error.response) {
		  // Extract error msg
		  const {message, code, response} = error;
	
		  // Extract response msg
		  const {headers, body} = response;
	
		  console.error(body);
		}
	  });
```

**Comment by thinkingserious** [comment]
Could you please capture the [request body](https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md#viewing-the-request-body)? Thanks!

**Comment by sriramgroot** [comment]
> Could you please capture the [request body](https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md#viewing-the-request-body)? Thanks!

Could you please tell me how to capture those information from node

**Comment by thinkingserious** [comment]
Right before `sgMail.send(msg)`, please do the following:

```javascript
const {
  classes: {
    Mail,
  },
} = require('@sendgrid/helpers');
const mail = Mail.create(data);
const body = mail.toJSON();
console.log(body);
```

**Comment by sriramgroot** [comment]
> Right before `sgMail.send(msg)`, please do the following:
> 
> ```js
> const {
>   classes: {
>     Mail,
>   },
> } = require('@sendgrid/helpers');
> const mail = Mail.create(data);
> const body = mail.toJSON();
> console.log(body);
> ```

Thanks @thinkingserious 
Will this approach and get back to you soon

**Comment by thinkingserious** [comment]
Hello @sriramgroot,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
