### ISSUE TITLE
How do I use the HTTPS

### ISSUE THREAD

**Issue by raygao** [sendgrid/sendgrid-nodejs#1161]
I got an email from sendgrid, stating from 1st of September, HTTP will be turned off. And, only HTTPS is supported.
Currently, we are using the: following libraries.
// https://github.com/sendgrid/sendgrid-nodejs
// sudo npm install --save zip-local
// sudo npm install --save @sendgrid/mail

How do I implement the logic to send the email using HTTPS?

Thanks,

**Comment by perfect-pixel** [comment]
I received the same alert. I think you have nothing to worry about. Here is a screenshot from the source code.
![111](https://user-images.githubusercontent.com/10826813/87408612-6400dd80-c5cc-11ea-82f2-1550123819e5.jpg)

**Comment by thinkingserious** [comment]
Thanks for helping out @perfect-pixel!

Hello @raygao,

Unless you were manually overriding the `baseUrl`, you should be fine.

Thanks!

With best regards,

Elmer
