### ISSUE TITLE
Email send , but recipient didn't receive. No errors

### ISSUE THREAD

**Issue by Kihoshi** [sendgrid/sendgrid-nodejs#1163]
Hi ,
Just occur this last month, previously was ok.  
Email send , but recipient didn't receive. 
Using valid api key, and email
No errors.

              const sgMail = require('@sendgrid/mail');
              sgMail.setApiKey('xxxxx');
              const msg = {
                to: ['b@email.com','c@email.com'],
                from: 'a@email.com',
                subject: 'Test',
                html: '<b>Body</b>',
                attachments
              };

            sgMail.send(msg);

**Comment by mishatron** [comment]
Have the same issue with  next data:
`
let msg = {
            "personalizations": [
                {
                    "to": [
                        { "email": "z@gmail.com" }
                    ]
                }
            ],
            "subject": "qwe2",
            "from": { "email": "q@gmail.com" },
            "template_id": "d-af55a5aeab424dd290ab8c2cd9e69d20"
        };
`

**Comment by childish-sambino** [comment]
Recommend first waiting for the response and handling any errors. Examples here: https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/success-failure-errors.md

**Comment by mishatron** [comment]
> Recommend first waiting for the response and handling any errors. Examples here: https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/success-failure-errors.md

I got success and in the response i have 202 status and id of the created message. but in the console I have status "not delivered". What is weird - in the field "TO" data is empty. so I suppose something with library while detecting recepient

**Comment by childish-sambino** [comment]
@mishatron It's unlikely this is a library issue given that you're getting back a 202. Recommend inspecting the request body to ensure the `to` field _is_ getting set properly: https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md#viewing-the-request-body

If it looks proper, best to reach out to [support](https://support.sendgrid.com/hc/en-us) for investigation.

**Comment by mishatron** [comment]
I saw documentation and it doesn't work for me. I use the next code to send message
```
let msg = {
            "personalizations": [
                {
                    "to": [
                        { "email": "mmm@gmail.com" }
                    ]
                }
            ],
            "subject": "111",
            "from": { "email": "qqq@gmail.com" },
            "template_id": "d-af55a5aeab424dd290ab8c2cd9e69d20"
        };
        let mail = Mail.create(msg);
        let body = mail.toJSON();
        console.log(body);
        await sgMail.send(body, (error, result) => {
            console.log(error);
            console.log(result);
            if (error) {
                res.send(error);
            } else {
                return res.status(200).send('Success')
            }
        });
```
And my console logs are:
{
>    from: EmailAddress { email: 'questapp.ukraine@gmail.com' },
>    subject: '111',
>    personalizations: [ { to: [Array] } ],
>    template_id: 'd-af55a5aeab424dd290ab8c2cd9e69d20'
>  }
>  null
>  [
>    Response {
>      statusCode: 202,
>      body: '',
>      headers: {
>        server: 'nginx',
>        date: 'Sat, 01 Aug 2020 18:51:30 GMT',
>        'content-length': '0',
>        connection: 'close',
>        'x-message-id': 'KrrV4QzeTtez9NVi6191_A',
>        'access-control-allow-origin': 'https://sendgrid.api-docs.io',
>        'access-control-allow-methods': 'POST',
>        'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
>        'access-control-max-age': '600',
>        'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html'
>      }
>    },
>    ''
>  ]

**Comment by childish-sambino** [comment]
Best to reach out to [support](https://support.sendgrid.com/hc/en-us) for investigation then.

**Comment by thinkingserious** [comment]
Hello @Kihoshi,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
