### ISSUE TITLE
Send email with file attachment of an unknown format

### ISSUE THREAD

**Issue by ArshZilpe** [sendgrid/sendgrid-nodejs#1167]
Hello. I want to send an email with the file a user has uploaded on a HTML form. I have read the docs and examples but they all specify what format the file is (eg. 'type: 'plain/text''). Is there a way so that any type of file can be attached?

**Comment by richardbarrell-calvium** [comment]
Might `type: 'application/octet-stream'` (which is the MIME type for "here's some bytes, I have no opinion about what they are") be appropriate?

**Comment by ArshZilpe** [comment]
I will give that a go. Thanks!

**Comment by eshanholtz** [comment]
Let us know if you need further help, or close this issue if it works!

**Comment by jiska78** [comment]
I have the same issue.
