### ISSUE TITLE
attachments throw error for optional fields

### ISSUE THREAD

**Issue by viphak** [sendgrid/sendgrid-nodejs#1175]
### Issue Summary
When adding an attachment with just filename and content (both required), the library throws an error "Expected the attachment's type field to be a string". Type is not required per the spec here https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

### Steps to Reproduce
1. create new message packet
2. set one attachment to the message packet with only { content, filename }
3. call SG.send(messagePacket)

### Code Snippet
```node

const data = {
  personalizations: [{ to: [{ email: 'to@example.com' }] }'],
  from: {
    email: 'from@example.com',
  },
  subject: 'subject',
  template_id: 'd-111111111111',
  atttachments: [{
    content: 'blah blah',
    filename: 'test.txt',
  }]
}
await sgMail.send(data);
```

### Exception/Log
```
"    at Mail.setAttachments (/app/node_modules/@sendgrid/helpers/classes/mail.js:445:13)",
    "    at Mail.fromData (/app/node_modules/@sendgrid/helpers/classes/mail.js:82:10)",
    "    at new Mail (/app/node_modules/@sendgrid/helpers/classes/mail.js:46:12)",
    "    at Function.create (/app/node_modules/@sendgrid/helpers/classes/mail.js:670:12)",
    "    at MailService.send (/app/node_modules/@sendgrid/mail/src/classes/mail-service.js:188:25)",```

### Technical details:
* sendgrid-nodejs version: 7.2.3
* node version: v12.18.1

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by dlq84** [comment]
Same issue with disposition: https://github.com/sendgrid/sendgrid-nodejs/issues/1179

**Comment by TheOptimisticFactory** [comment]
This issue should have been resolved by https://github.com/sendgrid/sendgrid-nodejs/issues/1179, which hasn't been released yet released

**Comment by childish-sambino** [comment]
@TheOptimisticFactory Thanks! Forget to check linked issues. Closing as the work is done and this will be released later today.
