### ISSUE TITLE
You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by ErxrilOwl** [sendgrid/sendgrid-nodejs#1176]
Writing issue here as the support has no response for almost 2 weeks.

**Comment by thinkingserious** [comment]
Hello @ErxrilOwl,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by childish-sambino** [comment]
It sounds like your account status might be under review. You should have received [a notice](https://sendgrid.com/docs/ui/account-and-settings/account-under-review/) in your e-mail with more details.

If you would like to discuss it, please respond to the email you received regarding the notice. 

If you cannot find this e-mail, we ask our customers do the following:

> 
> 1. Go to [support.sendgrid.com](https://support.sendgrid.com/hc/en-us)
> 2. Click on Trouble Logging In
> 3. Click "I am having a different log in issue"
> 
> To reactivate your account, you may be prompted to outline your sending practices for support to vet and either reactivate or keep closed. Unfortunately, there is not a way around this since this vetting process is put in place by Compliance to prevent bad actors from misusing our product.

Support cannot assist in reactivation of banned accounts.

Hope this helps!
Twilio SendGrid Team

**Comment by Prakash07-er** [comment]
**You are not authorized to access SendGrid, please contact Support...
This is terrible...i was depressed with this.....
I'm need of this in short time.. but facing signup issues.....it is too silly...
Could the team please resolve this quickly.....**

like this image, i'm getting error.
<img width="542" alt="sendgrid" src="https://user-images.githubusercontent.com/71871887/120634741-3db88a80-c489-11eb-8011-5bcfff278689.png">

**Comment by JenniferMah** [comment]
Hi @Prakash07-er please follow the steps outlined in the comment above. If you are locked out from your account please open a new [support request](https://support.sendgrid.com/hc/en-us/requests/new/submit).
