### ISSUE TITLE
Firefox preflighted request

### ISSUE THREAD

**Issue by phisch-zz** [sendgrid/sendgrid-nodejs#1177]
Hello, i post new recipients to our Sendgrid global contacts with this:
```

                const client = require('@sendgrid/client');
                client.setApiKey(process.env.SENDGRID_APIKEY);
                const recipient = [
                    {
                        "email": 'test@test.de',
                        "first_name": 'testFirstname',
                        "last_name": 'testLastname'
                    }
                ];
                let request = { method: 'POST', url: '/v3/contactdb/recipients', body: recipient };

```
All is fine except in Firefox. The preflighted request from Firefox seems to enforce the User-Agent header on Access-Control-Allow-Headers. All other browsers ignore it. 

The response from the https://api.sendgrid.com/v3/contactdb/recipients is this:
Access-Control-Allow-Headers | AUTHORIZATION, Content-Type, On-behalf-of, x-sg-elas-acl, X-Recaptcha, X-Request-Source

There is no user-agent allowed and so Firefox blocks my POST-Request.

Could you perhaps return also the user-agent in your Access-Control-Allow-Headers list or is there perhaps another solution for Firefox to allow my request?

Thx

**Comment by eshanholtz** [comment]
Are you using this package in a Client-side application? These libraries are intended to be used server-side.
