### ISSUE TITLE
from field wrap in quotes if there is a comma in

### ISSUE THREAD

**Issue by moriatuch** [sendgrid/sendgrid-nodejs#1183]
### Issue Summary
Hey 
we used to use smtp in ruby on rails 
we start to use your node js sdk instead of gem in ruby and recently we switched to using api in node js (using yours sdk).
we found that if there is a comma in the from field its wraps the name in quotes

for example 

"Pitty, Desk" 
![Screen Shot 2020-08-19 at 12 01 43](https://user-images.githubusercontent.com/20752631/90615128-57e3ed80-e214-11ea-8d6b-86b08aa8e649.png)

### Steps to Reproduce
just fill your email in the To field in the code i attached and run it 

### Code Snippet
```node

const sendgridClient = require('@sendgrid/mail')

const email = {
	"from": {
		"email": "<some email>",
		"name": "Pitty, Desk"
	},
	"personalizations": [{
		"to": [{
			"email": "<some email>",
			"name": "some email"
		}],
		"subject": "TEST",
		"custom_args": {
			"account_id": "1",
		}
	}],
	"reply_to": {
		"email": "replyto@email.com",
		"name": "Reply To TEST"
	},
	"content": [{
		"type": "text/html",
		"value": "content of email"
	}]
}

sendgridClient.setApiKey('****************')
sendgridClient.send(email, function(err) {
  if (err) {
    console.log(err)
  } else {
    console.log('success')
  }
})

```

### Technical details:
* sendgrid-nodejs version: @sendgrid/mail: "6.4.0"

* node version: 12.18.2

**Comment by thinkingserious** [comment]
Hello @moriatuch,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by eshanholtz** [comment]
I've been able to recreate this issue and find the source of the bug. Working on a fix.

**Comment by eshanholtz** [comment]
Relates to https://github.com/sendgrid/sendgrid-csharp/issues/268
