### ISSUE TITLE
How to send a single send with sengrid-nodejs?

### ISSUE THREAD

**Issue by jacintofleta** [sendgrid/sendgrid-nodejs#1194]
Hello,

This is more a question than an issue... Can I use sengrid-nodejs to send single sends to a list?

In v3 api there is the endpoint /marketing/singlesend but I don't find it here.

Thank you so much

**Comment by childish-sambino** [comment]
There isn't any code/example specific to that API. But you can call the API using the client similar to this example: https://github.com/sendgrid/sendgrid-nodejs/tree/main/packages/client#general-v3-web-api-usage-example
