### ISSUE TITLE
Example for validating email addresses

### ISSUE THREAD

**Issue by theweiweiway** [sendgrid/sendgrid-nodejs#1195]
Hi, I can't seem to find an example for validating email addresses with SendGrid's new validation feature (https://sendgrid.com/solutions/email-api/email-address-validation-api/). 

Thanks

### Technical details:
version 7.2.5

**Comment by childish-sambino** [comment]
API docs are here: https://sendgrid.api-docs.io/v3.0/email-address-validation/validate-an-email

Here's an example that can be tweaked to work with that API: https://github.com/sendgrid/sendgrid-nodejs/tree/main/packages/client#general-v3-web-api-usage-example

**Comment by mansoor292** [comment]
It may have actually taken less words to actually help...


const request = {
  url: "/v3/validations/email",
  body: {
    email: "email@example.com",
    source: "Newsletter Signup",
  },
};
client.request(request).then(([response, body]) => {
  console.log(response.statusCode);
  console.log(body);
});

**Comment by jivinivan** [comment]
For anyone still having trouble `method: post` is now required. 

Example: 

```
const request = {
  url: '/v3/validations/email',
  method: 'post',
  body: {
    email: 'email@example.com',
    source: 'Newsletter Signup'
  }
};
client.request(request).then(([response, body]) => {
  console.log(response.statusCode);
  console.log(body);
});
```
