### ISSUE TITLE
How To Style Group Unsubscribe Links?

### ISSUE THREAD

**Issue by JimLynchCodes** [sendgrid/sendgrid-nodejs#1199]
Hi!

I am using this library to send sendgrid emails. thanks!

I've added
```
asm: {
    groupId: 12345
},
```
into the msg object, but I'm getting the same behavior as OP- it adds un-stylable links to the bottom of my email when really I would like them to be centered and have a different background color.

It seems that I have no control over this. 😢

**Comment by JimLynchCodes** [comment]
I see this sort of similar issue with no working solution (although it is for the python library and templated emails... I'm using the barebones "sg.send" with an "html" property.

**Comment by eshanholtz** [comment]
It looks to me like you've answered your own question! Thank you so much for the detailed guide on how you solved your use case. I'm going to go ahead and close this issue as there does not appear to be further assistance needed on our part.

**Comment by nicholaschiang** [comment]
Where is the documentation for this? Clearly this should be more well documented and easily accessible.

**Comment by davidtom** [comment]
@JimLynchCodes thank you for posing this!!! You saved me such much time trying to wrestle with these preferences/settings/template strings.

@eshanholtz as @nicholaschiang mentioned, this really should be better documented. The only place to find help even close to this is on random blogs - at least as far as I could find - and even those seem to be outdated.
