### ISSUE TITLE
Cannot send error logs to my mail using shell script and curl call

### ISSUE THREAD

**Issue by shridhar-hegde** [sendgrid/sendgrid-nodejs#1200]
I am having a cron job in my Linux machine that runs a shell script every hour, checks if there are new entries in the error log. 

I wanted to receive these error logs as a mail and thus started using SendGrid V3 API. 
But I am getting an error after running the shell script if I send the error logs in the message. I thought there might be restrictions about the message length but not able to figure out. 

Here is the error message:

`{"errors":[{"message":"Bad Request","field":null,"help":null}]}`

If I send a simple text like **You have new errors. Please check.**, it works.

Here is how I send the mail:

`maildata='{"personalizations": [{"to": [{"email": "'${EMAIL_TO}'"}]}],"from": {"email": "'${FROM_EMAIL}'",
		"name": "'${FROM_NAME}'"},"subject": "'${SUBJECT}-${SUBJECT_MEM}'","content": [{"type": "text/html", "value": "'${MSG}'"}]}'

	curl --request POST \
		--url https://api.sendgrid.com/v3/mail/send \
		--header 'Authorization: Bearer '$SENDGRID_API_KEY \
		--header 'Content-Type: application/json' \
		--data "'$maildata'"`

Sample of my Java error log which I want to send in the mail:

`2020-09-28 03:13:41,288 ERROR [.] [main]: java.lang.NullPointerException
java.lang.NullPointerException
2020-09-28 03:13:41,298 ERROR [.] [main]: java.lang.NullPointerException
java.lang.NullPointerException
	at com.myPackage.anotherPackage.DoSomething.processSomeData(MagicallyPullData.java:98)
	at com.myPackage.anotherPackage.DoSomething.processSomeData(MagicallyPullData.java:56)
	at com.myPackage.anotherPackage.DoSomething.processSomeData(MagicallyPullData.java:112)`

**Comment by thinkingserious** [comment]
Hello @shridhar-hegde,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
