### ISSUE TITLE
Please consider adding the `hacktoberfest` topic to this repo

### ISSUE THREAD

**Issue by nck** [sendgrid/sendgrid-nodejs#1204]
### Issue Summary
As explained [here](https://hacktoberfest.digitalocean.com/hacktoberfest-update), Hacktoberfest is now opt-in only for projects, which requires maintainers to add the `hacktoberfest` topic to a repository.

**Comment by childish-sambino** [comment]
While we have participated in Hacktoberfest in the past, this year we do not have the bandwidth to handle the spike in volume given existing commitments and a backlog (in the hundreds) of prior year Hacktoberfest PRs that we're still working through.
