### ISSUE TITLE
Error: Error occurred while sending email Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by carlzacher-placester** [sendgrid/sendgrid-nodejs#1211]
Hi. I'm getting this error: **INFO	Error While getting the lead assignment Data: Error: Error occurred while sending email Error: connect ETIMEDOUT** everytime I try to send an email from my Node.js Lambda function. I'm trying to change something in my codebase so that I'll be able to use the dynamic template data handlebars notation. Could this problem be caused by the current version of SendGrid used in the app? It currently has "@sendgrid/mail": "^6.4.0" in its dependencies.

**Comment by eshanholtz** [comment]
This issue looks related to #894. As of version [`6.5.0`](#898) the `MailService` class includes a `setTimeout` function (if using TypeScript, support was added in [`7.0.0`](#1076)). Try updating your `@sendgrid/mail` package and [increasing the timeout](https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/timeout.md).

**Comment by carlzacher-placester** [comment]
Okay thank you. I will definitely try this out. But just to add some more details to this, the error mostly happens when I have more than 1 field inside my dynamic_template_data object. For example here. When the personalizations look like this:
        ```
personalizations:[
          {
             to: [
                {
                   email: email
                }
             ],
             dynamic_template_data: {
                subject: emailSubject
              }
          }
       ]
```
the Lambda works but when I update it into this one:
        ```
personalizations:[
          {
             to: [
                {
                   email: email
                }
             ],
             dynamic_template_data: {
                subject: emailSubject,
                exportType: exportType
              }
          }
       ]
```
that's when the timeout error pops up in the CloudWatch logs.

**Comment by carlzacher-placester** [comment]
It's a bit strange that the mail send request times out when I add another field in the dynamic_template_data object. Could that also be because of the version not being latest?

**Comment by thinkingserious** [comment]
Hi @carlzacher-placester,

What does your template look like? Maybe `exportType` is not defined correctly in the template.

I suggest that you log the personalization object on each failure to see if there are any other patterns of note.

With best regards,

Elmer

**Comment by carlzacher-placester** [comment]
Do all handlebars variables need to be supported in my payload to SendGrid? Because currently our template has 4 handlebars but when I send a request to SendGrid I only send in two, subject and exportType. What's strange is sometimes it works but most cases it fails because of the timeout. I've used the **sgMail.setTimeout(10000)** line and it still times out. Like last night after I added that line to the function code I tested like 6 consecutive email sending requests and all were sent successfully but this morning all of my tests have failed.

**Comment by thinkingserious** [comment]
Given your test results, I do not believe you need all handlbar variables present for a successful email send.

If you are using the same code with the same parameters and in one case it sends fine and in the other it times out (you can double check this by comparing the payloads), then I believe this would be a network error that likely needs investigating by your server's service provider. I do not think you should need a 10 second timeout.
