### ISSUE TITLE
Image is not showing in the html email instead it shows as an attachment?

### ISSUE THREAD

**Issue by ra4zi** [sendgrid/sendgrid-nodejs#1213]
The problem I am having now is that, my Logo in the html email template is not showing up, instead my image appears as an attachments.

`
  
           const msg = {
                to: user.email,
                from: process.env.EMAIL_FROM,
                subject: 'Welcome',
                html: '<strong>Some Text</strong><img src="content_id:logo" alt="image" />',

                attachments: [{
                    filename: 'logo2',
                    type: 'image/png',
                    content_id: 'logo',
                    content: fs.readFileSync('./src/img/logo2.png', { encoding: 'base64' }),
                    disposition: 'inline',
                }],

            };
            send_email(msg);

`
How to solve this issue?

**Comment by childish-sambino** [comment]
Small change needed: https://github.com/sendgrid/sendgrid-nodejs/issues/701#issuecomment-715387841

> Change the `img src` to `cid`: `<img src="cid:logo" alt="image" />`
