### ISSUE TITLE
Sample using @sendgrid/client - PUT /marketing/contacts to add customers to marketing List

### ISSUE THREAD

**Issue by brettgpalmer** [sendgrid/sendgrid-nodejs#1215]
### Issue Summary
We are trying to use the sendgrid/client to make a PUT /marketing/contacts call to add new contact to an existing marketing list.  When we try to use the client for the PUT request we get an "Error: Not Found" exception.  It's probably a problem with transposing the PUT request correctly with the client request.  If we run the "General v3 Web API Usage Example" to get the existing api_keys the client call works as expected.

#### Using the Native api_v3 PUT call is working but we would like to standardize on the sendgrid/client if possible

1. Code not working using the sendgrid/client:
```
const request = {
        method: 'PUT',
        url: '/vs/marketing/contacts',
        body: {
            list_ids: [ <LIST_ID> ],
            contacts: [
                {
                    first_name: member.firstName,
                    last_name: member.lastName,
                    email: member.email
                }
            ]
        }
    };

    sgClient.request(request)
        .then(([response, body]) => {
            console.log(response.statusCode);
            console.log(body);
        }
    ) 
```
#### Here is the nodeJS error we are seeing:
```
-- Error: Not Found
      at node_modules/@sendgrid/client/src/classes/client.js:145:29
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
2. Working Code using the native sendGrid API PUT /marketing/contacts from the API docs

```
var options = {
      "method": "PUT",
      "hostname": "api.sendgrid.com",
      "port": null,
      "path": "/v3/marketing/contacts",
      "headers": {
        "authorization": `Bearer <API_KEY>`,
        "content-type": "application/json"
      }
    };
    
    var req = http.request(options, function (res) {
      var chunks = [];
    
      res.on("data", function (chunk) {
        chunks.push(chunk);
      });
    
      res.on("end", function () {
        var body = Buffer.concat(chunks);
        console.log(body.toString());
      });
    });
    
    req.write(JSON.stringify({ list_ids: [ <LIST_ID> ],
      contacts: 
       [ { 
           email: member.email,
           first_name: member.firstName,
           last_name: member.lastName
         } ] }));
    req.end();
```

### Technical details:
* sendgrid-nodejs version: @sendgrid/client": "^7.3.0
* node version: v12.12.0

**Comment by eshanholtz** [comment]
The url in the first example has `vs/marketing/contacts` when it should be `v3/marketing/contacts`. Are you still seeing this issue with the proper url?

**Comment by brettgpalmer** [comment]
I missed that typo in the example code.  Yes, when I use v3/marketing/contacts the sendgrid/client works as expected.   Thanks so much for your help.

**Comment by samarth-math** [comment]
Is it necessary to pass authorization headers separately as opposed to simply setting client.setApiKey()?
