### ISSUE TITLE
SSRF vulnerability in Axios

### ISSUE THREAD

**Issue by huydoan2** [sendgrid/sendgrid-nodejs#1217]
### Issue Summary
The latest version of sendgrid-nodejs, `7.4.0` is using axios `0.19.2` which contains a Server Side Request Forgery (SSRF) vulnerability. Currently there's no patch available from axios. Please update sendgrid-nodejs whenever the fixes are available.

Axios tracking issue:
https://github.com/axios/axios/issues/3369

Vulnerability report from Snyk:
https://snyk.io/vuln/SNYK-JS-AXIOS-1038255

### Technical details:
* sendgrid-nodejs version: 7.4.0
* node version: v14.12.0

### Note
@sendgrid/mail will also need to be updated when fixes are available.

**Comment by thinkingserious** [comment]
Thank you for reporting this @huydoan2!

**Comment by shackbarth** [comment]
This vulnerability has since been fixed on axios@0.21.1. Can you bump this dependency when you get a chance?

**Comment by matt-catellier** [comment]
Thanks @shackbarth.  I create a pull request with changes to review here @thinkingserious https://github.com/sendgrid/sendgrid-nodejs/pull/1236

**Comment by matt-catellier** [comment]
Any update on this? Will be resolved by this merge request https://github.com/sendgrid/sendgrid-nodejs/pull/1239

**Comment by jgravois** [comment]
fix has been published to npm as [v7.4.1](https://github.com/sendgrid/sendgrid-nodejs/releases/tag/7.4.1)

**Comment by ananay** [comment]
Hey! I think we can close this issue :)
Thanks!
