### ISSUE TITLE
Problems with CORs

### ISSUE THREAD

**Issue by david-fernando** [sendgrid/sendgrid-nodejs#1219]
### Issue Summary
I tried to register on the platform recently, and the following message appeared on the screen: "We were unable to create your account. Sorry about that! Please try again later." More details on this are in the section "Exception/Log"
### Steps to Reproduce
1. Access https://signup.sendgrid.com/
2. try to register

### Exception/Log
```
Access to manifest at 'https://sendgrid.com/brand/favicons/manifest.json' from origin 'https://signup.sendgrid.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Failed to load resource: net::ERR_FAILED

POST https://api.sendgrid.com/v3/public/s2s/signup/recaptcha_verify 400 (BAD REQUEST)
````

**Comment by seenickcode** [comment]
what was the fix?
