### ISSUE TITLE
Typings are poorly structured. Please fix it

### ISSUE THREAD

**Issue by tbhaxor** [sendgrid/sendgrid-nodejs#1224]
### Issue Summary
I want to instantiate sendgrid mail on the fly using MailService in typescript, wo when i import it using this
```ts
import { MailService } from '@sendgrid/mail'
```

I am getting
```
Module '"../node_modules/@sendgrid/mail"' has no exported member 'MailService'.
```

### Steps to Reproduce
1. `npm install @sendgrid/mail ts-node`
2. Create app.ts with the following content
    ```ts
    import { MailService } from '@sendgrid/mail'
    
    export default function (api: string): MailService { 
    const client = new MailService()
    client.setApiKey(api);
    return client
    }
    ```
3. Run the script `ts-node app.ts`

### Source of this problem

I have found that this file is the main source of problem.

https://github.com/sendgrid/sendgrid-nodejs/blob/main/packages/mail/index.d.ts#L3

For the fix you can visit this link &rArr; https://www.reddit.com/r/typescript/comments/ckxezi/module_has_no_exported_member/

### Technical details:
* sendgrid-nodejs version: 7.4.0
* node version: v15.0.1

**Comment by thinkingserious** [comment]
Hello @tbhaxor,

Does [this solution](https://github.com/sendgrid/sendgrid-nodejs/issues/674#issuecomment-379997468) work for you?

With best regards,

Elmer

**Comment by tbhaxor** [comment]
It worked @thinkingserious . Thanks
