### ISSUE TITLE
Update docs - substitutions and dynamic_template_data

### ISSUE THREAD

**Issue by johannesmutter** [sendgrid/sendgrid-nodejs#1225]
Hey everyone,

I was trying to figure out why I always received an error "bad request (data)" when using the "personalizations" (via retool sendgrid integration) with a substitutions object.

I then came across this issue from last year:
[Confused between `substitutions` and `dynamicTemplateData` #874](https://github.com/sendgrid/sendgrid-nodejs/issues/874)

It seems most docs (except this [howto article](https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/)) still use the "substitutions" key instead of "dynamic_template_data".

Also the tooltip labels in retool display "substitutions" instead of the correct key "dynamic_template_data"

It would be great if these docs could be updated:

- [ ] https://sendgrid.com/docs/for-developers/sending-email/personalizations/
- [ ] https://sendgrid.com/docs/ui/sending-email/substitution-and-section-tags/
- [ ] https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.substitutions

type: docs update

**Comment by JenniferMah** [comment]
@johannesmutter 
Thanks for bringing this to our attention. Can you file an issue [here](https://github.com/sendgrid/docs/issues) so the appropriate team can make these changes?
