### ISSUE TITLE
Receiving "Unauthorized" message in terminal

### ISSUE THREAD

**Issue by jmorales113** [sendgrid/sendgrid-nodejs#1229]
Hello, I am trying to wire up the SendGrid API to my front-end code through a submit form with HTML. For my backend, I am using Node.js. The node version is v12.16.1. The @sendgrid/mail version is 7.4.0. My form is: 

<form method="POST" action="/sendemail" data-aos="fade-up" data-aos-delay="300">
          <label for="name">Name</label>
          <input type="text" id="name" name="name" placeholder="Enter your name..." required/>
          <label for="email">Email</label>
          <input type="email" id="email" name="email" placeholder="Enter your email..." required/>
          <label for="subject">Subject:</label>
          <textarea name="subject" id="subject" cols="10" rows="10"></textarea>
          <input type="submit" value="submit" />
        </form>

My backend code is divided into two files. In my email.js file, my code: 
```
require("dotenv").config
const sgMail = require("@sendgrid/mail")
sgMail.setApiKey(process.env.SENDGRID_API_KEY)

    const receiveMail = (to, from, subject, text) => {
        const msg = {
        to,
        from,
        subject, 
        text
    }

    sgMail.send(msg, (error, result) => {
    if (error) {
        console.log(error)
    } else {
        console.log("Email sent!")
    }
 })
}

module.exports = receiveMail
```
and in my server.js file: 
```
const path = require("path")
const http = require("http")
const express = require("express")
const app = express()
const server = http.createServer(app)
const receiveMail = require("./utils/email.js")
const port = process.env.PORT || 3000
const publicDirectoryPath = path.join(__dirname, "../public")

app.use(express.static(publicDirectoryPath))
app.use(express.urlencoded({ extended: false }))

app.get("/", (req, res) => {
    res.render("public")
})

app.post("/sendemail", (req, res) => {
    const {name, email, subject} = req.body
    console.log(name, email, subject)
    const from = "jmorales113@gmail.com"
    const to = name

    const message = "New Contact Request"

    const output = `
    <p> You have a new Email</p>
    <h3>Contact Details</h3>
    <ul>
        <li>Name: ${name}</li>
        <li>Email: ${email}</li>
        <li>Subject: ${subject}</li>
    </ul>
    `
    receiveMail(to, from, message, output)
})

server.listen(port, () => {
    console.log(`Server is up on port ${port}!`)
})
```

There error I am receiving in the terminal when I click the submit button is:
```
ResponseError: Unauthorized
    at C:\Bootcamp\Portfolio\node_modules\@sendgrid\client\src\classes\client.js:145:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 401,
  message: 'Unauthorized',
  response: {
    headers: {
      server: 'nginx',
      date: 'Wed, 09 Dec 2020 01:09:12 GMT',
      'content-type': 'application/json',
      'content-length': '116',
      connection: 'close',
      'access-control-allow-origin': 'https://sendgrid.api-docs.io',
      'access-control-allow-methods': 'POST',
      'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
      'access-control-max-age': '600',
      'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html'
    },
    body: { errors: [Array] }
  }
}
```
Any help would be much appreciated. Thank you in advance!

**Comment by JenniferMah** [comment]
Hi @jmorales113 
This looks like an issue with your credentials. I would suggest you start by [testing your api key](https://sendgrid.com/docs/ui/account-and-settings/api-keys/#testing-an-api-key) to verify it is working properly. You should also verify that you are storing the key in an environment variable named `SENDGRID_API_KEY`.

**Comment by jmorales113** [comment]
Hello Jennifer,

Thank you for your timely response. I do have the API key stored in an environment variable named SENDGRID_API_KEY in a file called .env. Also, I tested the API key in another application and it's working properly. Any other suggestions would be greatly appreciated.

**Comment by thinkingserious** [comment]
Hello @jmorales113,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by seenickcode** [comment]
what was the fix to this? seems like a CORS issue
