### ISSUE TITLE
Problem with Gmail clipping, Sendgrid auto-setting encoding

### ISSUE THREAD

**Issue by Honason** [sendgrid/sendgrid-nodejs#1231]
### Issue Summary
I'm using the `html` field to send custom email notifications with Sendgrid. When viewing these emails, Gmail sometimes displaying the warning "[Message clipped]". This happens for emails much smaller than the 102KB limit, and when expanded, no more content is shown. Google apparently behaves in this way when the encoding of the email does not match the content. I have also noticed that any time the email was encoded as UTF-8, clipping did not happen.

How can I control the encoding (like always set it to UTF-8), or prevent Sendgrid from setting wrong one?

[This](https://stackoverflow.com/questions/56533164/gmail-is-clipping-html-email-for-no-reason) seems to be the same issue.

**Comment by thinkingserious** [comment]
Hello @Honason,

Our system will automatically encode the body with whatever encoding is being passed to us. This means, that if there are characters in that email that are ISO-8859 characters, then the body is going to be using that encoding. We do not currently have an option to force UTF-8 encode the body of emails that are being passed through us. Going forward, you would need to convert the content of your emails prior to sending them to our servers. My guess is that you have a rogue character in the offending emails. 

If you require further assistance, could you please share some sample code so that I may try to reproduce.

With best regards,

Elmer

**Comment by Honason** [comment]
Hi! Sorry for the late response. I tried to replicate the issue now and it's still a problem, however it might be a Gmail bug rather than Sendgrid bug specifically. When I send characters that are covered by ISO/IEC 8859-1, Sendgrids encodes the message as such. When the message includes characters that need to be covered by UTF-8, Sendgrid switches to UTF-8.

However when I send a simple message with this html content: `<p>ö</p>`, Sendgrid correctly sets encoding to ISO/IEC 8859-1, but Gmail shows clipping message.

![Screenshot 2021-02-02 at 15 54 02](https://user-images.githubusercontent.com/2352554/106617945-55314680-656f-11eb-90a7-f5c9d6e44201.png)

So until Gmail fixes this issue, the only fix I can think of is to always include hidden character that will force Sendgrid to always choose UTF-8, like "ř".

**Comment by JenniferMah** [comment]
Hi @Honason
That sounds like a good work around for now. Since we don't have any way to force a specific type of encoding and don't have control over what Gmail will clip.

**Comment by AviranAbady** [comment]
Facing the same bug, the workaround suggested by @Honason of adding a unicode character works fine, im adding the invisible charater \u200B instead of ř for batter visuals.

**Comment by MatthewSelfDecode** [comment]
> Facing the same bug, the workaround suggested by @Honason of adding a unicode character works fine, im adding the invisible charater \u200B instead of ř for batter visuals.

could you share how exactly you implemented  this? I have been trying with no luck. Using the ř does work.

**Comment by AviranAbady** [comment]
@MatthewSelfDecode Sure, working with python and using a template file for the html content

A template has the following structure:
```html
<html>
  <head>
    <meta charset="UTF-8">
    <title>title</title>
    FORCED_UNICODE_CONTENT
  </head>
  <body>
    <div style='width: 640px'>
      <div>
        <img alt='Banner' src='cid:banner' width='640'/>
      </div>
      <h1>Hello</h1>
      Text Text Text Text<br/>
      Text Text Text Text<br/>
      Text Text Text Text<br/>
     
    </div>
  </body>
</html>
```
The place holder FORCED_UNICODE_CONTENT is where the '\u200B' character is injected

```python
email_content = email_content.replace('FORCED_UNICODE_CONTENT', '\u200B').replace('\uFEFF', '')
```

Also removing `byte order mark` \uFEFF which may creep into the template files and break

**Comment by MatthewSelfDecode** [comment]
I see, thank you. I was hoping to add the character somewhere in the template text.

**Comment by AviranAbady** [comment]
@MatthewSelfDecode - that also works, just add that character (As a unicode character) into the text.
