### ISSUE TITLE
Calendar invite / Meeting request

### ISSUE THREAD

**Issue by TrierHealth** [sendgrid/sendgrid-nodejs#1232]
Hi,
We would like to send calendar invites/meeting request. So, we came up with a code to send calendar invite which is working, but the receiver has to manually click on "Add to calendar'. Ideally what we want is: as the receiver receives the calendar invite/meeting request, the invite should also sit in his calendar without explicitly adding it. He can however optionally click Yes or No just like how we do in a manual meeting request in Gmail/Outlook/etc. Please let us know nodejs solution for the same. The below is the current code. It would be great if we an get solution for right case of meeting request we are looking at.

```
var SENDGRID_API_KEY = 'KEY HERE'
sgMail.setApiKey(SENDGRID_API_KEY);

var encodedEvent = fs.readFileSync('/tmp/event.ics', function (err, data) {

  if (err) throw err;

}).toString('base64');

const msg = {
  to: [receiver1_email_id, receiver2_email_id],
  from: sender_email_id,
  subject: "Subject of Meeting",
  text: 'Meeting text',
  attachments: [{
	  content: encodedEvent,
	  filename: 'event.ics',
	  type: 'text/calendar',
	  disposition: 'attachment',
	  contentId: 'mytext'
  }],
};

await sgMail.send(msg);
```
Thanks,
Ravi Vinnakota.

**Comment by TrierHealth** [comment]
Closing this as I figured out that the METHOD should be REQUEST in ics file.

**Comment by TrierHealth** [comment]
Actually, this is working only when the receiver is gmail. But not when the receiver is using outlook ! Hence re-opening.

**Comment by PatrikTes** [comment]
Hello, I have the same problem, even I got further. In the google calendar I get it showed correctly, but not in outlook:

What is crucial is to have this type in the body of the message:

```
Content-Type: text/calendar; charset="UTF-8"; method=REQUEST
Content-Transfer-Encoding: 7bit

```

But the sendgrid allows only this :
```

        {
          filename: 'invite.ics',
          type: 'application/ics', // 'text/calendar',
          content: Buffer.from(cal.toString()).toString('base64'),
          disposition: 'inline',
          content_id: 'calendar'
        }

```

When I try it like this: (how it should be)

```

        {
          type: 'text/calendar',
          content: cal.toString(),
          disposition: 'inline',
          content_id: 'calendar'
        }

```
I got the error that the attachment needs to be base64!!! What is nonsense as the sample from above is the email what sends outlook or google itself. Could someone from sendgrid help?

**Comment by thinkingserious** [comment]
Please vote and comment on this issue in order to help increase its priority: https://github.com/sendgrid/sendgrid-nodejs/issues/697. Thank you!
