### ISSUE TITLE
Working SendGrid.mail() code fails without error in AWS Lambda environment

### ISSUE THREAD

**Issue by Ulthran** [sendgrid/sendgrid-nodejs#1233]
### Issue Summary
Running the basic test code for sending mail through the SendGrid node API works locally but fails without errors in a Lambda function.

### Steps to Reproduce
Take the code from https://app.sendgrid.com/guide/integrate/langs/nodejs and get it working locally. Then upload to an AWS Lambda function (follow the steps [here](https://stackoverflow.com/questions/34437900/how-to-load-npm-modules-in-aws-lambda) to upload to Lambda). Configure an arbitrary test event and run the function with any logging you want.

### Code Snippet
```node
exports.handler = async (event) => {

    const sgMail = require('@sendgrid/mail');
    //sgMail.setApiKey(process.env.SENDGRID_API_KEY);
    sgMail.setApiKey('my_api_key'); //Tested with environment variable and hardcoded, same result for both
    const msg = {
      to: 'my.email@gmail.com',
      from: 'team@example.com',
      subject: 'Sending with SendGrid is fun',
      text: 'and easy to do anywhere, even with Node.js',
      html: '<strong>and easy to do anywhere, even with Node.js</strong>',
    };

    sgMail
        .send(msg)
        .then(() => {
            console.log('Email sent');
            const response = {
                statusCode: 200,
            };
            return response;
        })
        .catch((error) => {
            console.error(error);
            const response = {
                statusCode: 400,
            };
            return response;
        });
   
    console.error("You shouldn't be here");
    const response = {
        statusCode: 300,
    };
    return response;
};
```

### Exception/Log
I haven't been able to get anything of interest appearing with console.log's, all that shows up is the 
I also tried adding a try/catch around the whole send/then/catch and it still shows the "You shouldn't be here" error
```
START RequestId: 7391f0e6-a3cf-4434-87d5-b2f89d53f628 Version: $LATEST
2020-12-14T14:48:15.399Z	d4e01174-9186-46e9-b757-c92c4dc0a5fb	ERROR	You shouldn't be here
END RequestId: 7391f0e6-a3cf-4434-87d5-b2f89d53f628
REPORT RequestId: 7391f0e6-a3cf-4434-87d5-b2f89d53f628	Duration: 823.19 ms	Billed Duration: 824 ms	Memory Size: 128 MB	Max Memory Used: 99 MB	Init Duration: 636.84 ms	
```

### Technical details:
* sendgrid-nodejs version: 6.3.1
* node version: 10.x (same as running locally, also tested with 12.x)

Any help would be greatly appreciated :) This problem has been persisting exactly the same for a few days now despite minor changes to the code, but running locally still works

EDIT: Very weird update to add to this, I just changed the Lambda's trigger which caused it to have a brief (~10 min) latency period before outputting CloudWatch logs again. During this period I added something to the S3 bucket it triggers on and received the email! But that run didn't produce any logs to CloudWatch. And now that logging seems to be up and running again I haven't gotten another email through.

**Comment by thinkingserious** [comment]
Hello @Ulthran,

The code looks good to me. Since you have changed configuration outside of the above source code and it worked (albeit just one time) without changing the source, it appears the issue is not with the helper library code. That said, it's been a while since you posted this, are you still experiencing the same issue?

With best regards,

Elmer

**Comment by Ulthran** [comment]
Hi Elmer,

Thanks for the response! I'm still stuck on the same issue but haven't looked into it much more since posting this.

**Comment by iAmWillShepherd** [comment]
I'm experiencing this same issue on my dev machine (macOS) using `"@sendgrid/mail": "^7.4.0"`. 

Things have been working fine for about a month, and now, without any changes to the code to send emails, it's failing inconsistently; sometimes, an error is caught, but I often get to the line of code to send an email, and nothing happens. Literally.


### Code snippet
```ts
 try {
      const message = {
        from: postApplyEmail,
        subject: subject,
        to: template.to,
        html: renderedEmail,
      };
      logger.info(`Sending email to ${message.to}...`);
      const [response] = await sgMail.send(message);
      logger.info("Email sent.");
    } catch (error) {
      logger.err(error, true);
    }
```

Note that "Email Sent" is never written, and neither is the error from the catch block.


### The one somewhat useful error I've received
```sh
[2021-01-11T20:36:21.574Z] ERROR: ResponseError: Unauthorized
    at node_modules/@sendgrid/client/src/classes/client.js:146:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 401,
  response: {
    headers: {
      server: 'nginx',
      date: 'Mon, 11 Jan 2021 20:36:21 GMT',
      'content-type': 'application/json',
      'content-length': '88',
      connection: 'close',
      'access-control-allow-origin': 'https://sendgrid.api-docs.io',
      'access-control-allow-methods': 'POST',
      'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
      'access-control-max-age': '600',
      'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html'
    },
    body: { errors: [Array] }
  }
}
```

I've tried going back and forth between the async/await and promise APIs, and nothing works. I could only get this message once (no success in getting this logged to the CLI because it seems the client ignores any callback passed to it and didn't respect the try/catch block).


I've tested my token to ensure it's correct using Curl. My server is also using cors, so no idea why the `x-no-cors-reason` header is set. I've been banging my head against the wall for about a day now without much progress. 

Any updates on this issue would be ideal.

**Comment by thinkingserious** [comment]
I'm still working on reproducing this @Ulthran, in the meantime, have you checked out [this blog post](https://www.twilio.com/blog/serverless-email-sms-gateway-lambda)? 

@iAmWillShepherd Since that's an authentication error, I would double check the environment variable in AWS.

**Comment by Ulthran** [comment]
Thanks @thinkingserious, I read through that blog post and it's suggesting all the steps as I've done them (except that my lambda is triggered off an S3 event rather than the API). Let me know if I can be any help in reproducing the issue.

**Comment by cloutiertyler** [comment]
I appear to be getting the same CORS error using the sendgrid api from my Nodejs server running on DigitalOcean. Please let me know if perhaps I can be helpful in reproducing the issue.

**Comment by eshanholtz** [comment]
@jp-bitcube 

Can you please use our [error handling guide](https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/success-failure-errors.md#handling-successfailureerrors) to capture the full error output and post it in a follow-up comment?

**Comment by jp-bitcube** [comment]
@eshanholtz I will set this up today and re-create the scenario. I know using purely the admin user email in the SendGrid account resolves the issues. Using a user allowed to access the account sometimes fails to send the mail.

**Comment by dejanvasic85** [comment]
I'm also experiencing this issue: 

in package.json:
```
"@sendgrid/mail": "7.4.2",
"serverless": "2.23.0",
```

Using serverless framework to deploy the lambda. When invoking from local environment it seems to work just fine, but from a deployed lambda in AWS, no mail is sent and no error is caught:

Code to send:
```
const mailer = {
  send: async (mail: Mail) => {
    try {
      logger.info('Sending email', { to: mail.to });
      const resp = await sgMail.send(mail);

      for (const clientResponse of resp) {
        logger.info(clientResponse);
      }
    } catch (err) {
      logger.error(err);
      throw err;
    }
  },
};

```

The client responses are not being logged ☝️  either and the lambda finishes execution successfully 😱 
Also note: the same code is being used by an application deployed to Heroku and it works just fine.

Apologies if this was just repeating the previous posts, let me know if you any more info would be helpful.

**Comment by dejanvasic85** [comment]
Ok. After some debugging, I found that it had to do with a badly written `Promise.all` method surrounding the `send` above.

The lambda was continuing execution and finishing instead of waiting on this promise all:

```
 await Promise.all(	
        users.map((u) => {	
         const mail = {...} // creates mail object
          mailer.send(mail);	
        }),	
      );
```

The working solution was to add the async and await inside :facepalm:
```
await Promise.all(
      users.map(async (u) => {
        const mail = {...} // creates mail object
        await mailer.send(mail);
      }),
    );
```

Disregard my comment :point_up:

**Comment by jp-bitcube** [comment]
I have not had the issue again if so will report it as soon as it occurs again.

**Comment by thinkingserious** [comment]
Hello @Ulthran,

Are you still experiencing this issue?

**Comment by jp-bitcube** [comment]
> Hello @Ulthran,
> 
> Are you still experiencing this issue?

I have sorted out the issue. It was based on a single sender set-up now it works well, verifying sender email

**Comment by thinkingserious** [comment]
Awesome, thanks for following up!

**Comment by leoosa** [comment]
in my case it was free plan limits, same error

> [2021-01-11T20:36:21.574Z] ERROR: ResponseError: Unauthorized
>     at node_modules/@sendgrid/client/src/classes/client.js:146:29
>     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
>   code: 401,

**Comment by Noeza** [comment]
@jp-bitcube how did you solve this issue, i am experiencing this same issue as well.
