### ISSUE TITLE
Need to update your module ASAP

### ISSUE THREAD

**Issue by krishnaTORQUE** [sendgrid/sendgrid-nodejs#1237]
This module is using `axios ^0.19.2` which is marked as high security issue (Server-Side Request Forgery).
Please update this module as soon as possible

Sendgrid used by thousand of website & all those sites are effected.

Axios has been released `^0.21.1` with the patch 10 days ago.

**Comment by thinkjrs** [comment]
@krishnaTORQUE Looks like there's already a PR #1236 and tracking in https://github.com/sendgrid/sendgrid-nodejs/issues/1217. 

This is so awesome of the community and thanks for taking initiative @matt-catellier :+1:

**Comment by Mikescops** [comment]
@eshanholtz please, do you mind updating this ticket as soon as the fix is released? We're following this topic and are highly waiting for it as it's a high security issue. Thanks.

**Comment by thinkjrs** [comment]
> @eshanholtz please, do you mind updating this ticket as soon as the fix is released? We're following this topic and are highly waiting for it as it's a high security issue. Thanks.

@Mikescops Just saw a release come through so figured I'd notify everyone here. I installed 7.4.1 and the npm warning is gone.

**Comment by thinkingserious** [comment]
Fixed with this release: https://github.com/sendgrid/sendgrid-nodejs/releases/tag/7.4.1

**Comment by Mikescops** [comment]
Thanks for the ping @thinkjrs :)
