### ISSUE TITLE
Axios upate

### ISSUE THREAD

**Issue by Henryxavierb** [sendgrid/sendgrid-nodejs#1241]
Currently, Github has been sending me alerts about the version of Axios used in Sendgrid

![2021-01-13_14-54](https://user-images.githubusercontent.com/48387142/104490508-b2109100-55af-11eb-9f5f-e411f39e94c6.png)

### Technical details:
- @sendgrid/mail: ^7.4.0: 
- node version: v12.20.1

**Comment by thinkingserious** [comment]
Hello @Henryxavierb,

Thanks for taking the time to report this to us!

[This fix](https://github.com/sendgrid/sendgrid-nodejs/pull/1239) has been implemented and be released later today.

With best regards,

Elmer
