### ISSUE TITLE
bug after sending e-mail from cloud functions

### ISSUE THREAD

**Issue by eeerrrttty** [sendgrid/sendgrid-nodejs#1242]
> 
> Process exited with code 16 at process.on.code (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:275:22) at process.emit (events.js:198:13) at process.EventEmitter.emit (domain.js:448:20) at process.exit (internal/process/per_thread.js:168:15) at Object.sendCrashResponse (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/logger.js:37:9) at process.on.err (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:271:22) at process.emit (events.js:198:13) at process.EventEmitter.emit (domain.js:448:20) at emitPromiseRejectionWarnings (internal/process/promises.js:140:18) at process._tickCallback (internal/process/next_tick.js:69:34) | more_vert
> -- | --
> 

![Screenshot from 2021-01-19 23-43-47](https://user-images.githubusercontent.com/19417947/105124360-629afb00-5ab0-11eb-8437-cb55fdbbf4da.png)

Here is my cloud function code:

```
exports.sendCustomEmailVerification = functions.https.onCall((userData) => {
  let emailsList = userData.emails
  let promises = []
  emailsList.forEach((email) => {
    let msg = {
      personalizations: [{
        to: email,
        subject: 'Eventos esportivos IMPRESSIONANTES'
      }],
      from: {
        email: 'eventos@kmaisclube.com.br',
        name: 'Kmais clube de vantagens'
      },
      reply_to: {
        email: 'eventos@kmaisclube.com.br',
        name: 'Kmais clube de vantagens'
      },
      template_id: 'd-50e2370999f742709686efce8fb742a9'
    }
    sgMail.setApiKey('MY_API_KEY)
    promises.push(sgMail.send(msg))
  })
  return Promise.all(promises).then(() => {
    return 'deu certo'
  })
```

emailsList is in the following format: [ [ { email: 'email@email.com' }, { email: 'email@email.com' } ] ], so "to: email" is an array with 1000 emails. in the [ {} ] format.

should work. If i change 'email' to a fixed array, it works.

**Comment by shwetha-manvinkurke** [comment]
Hi @eeerrrttty,

Thanks for reporting the issue. However, I could not reproduce locally. Which version of the library are you on? Is this issue new for this version? Have you tried reproducing this on an older version of the library? 

Thanks,
Shwetha

**Comment by silviokucz** [comment]
Try:
emailsList.forEach((**item**) => {
 let msg = {
      personalizations: [{
        to: **item.**email,

**Comment by thinkingserious** [comment]
Hello @silviokucz,

It looks like your message was truncated, could you please update or resend? Thank you!

With best regards,

Elmer

**Comment by silviokucz** [comment]
Hi @thinkingserious ,

I updated the comment, it seems to me that it has a small JavaScript mistake in the emailsList.forEach loop

**Comment by thinkingserious** [comment]
Thank you @silviokucz!! We appreciate your help!
