### ISSUE TITLE
Readme links to docs broken

### ISSUE THREAD

**Issue by TylerAHolden** [sendgrid/sendgrid-nodejs#1250]
### Issue Summary
all readme links to docs seem to be broken

### Steps to Reproduce
1. Click on any of the links that take you to api docs (https://sendgrid.com/docs/API_Reference/api_v3.html)
2. See broken link 404 page

I think the correct link would be https://sendgrid.com/docs/api-reference/ but I'm not actually sure if that's the documentation that was intended to be linked.

**Comment by JenniferMah** [comment]
Hi @TylerAHolden
Thanks for bringing this to our attention. These links in the readme should link to [sendgrid.com/docs/api-reference](sendgrid.com/docs/api-reference). If you would like to you can open a PR to change these links in the read.me or I can open a ticket internally to get this change prioritized in our backlog.
