### ISSUE TITLE
tanta in class js

### ISSUE THREAD

**Issue by igorko86** [sendgrid/sendgrid-nodejs#1253]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* sendgrid-nodejs version: 
* node version:

**Comment by JenniferMah** [comment]
Hi @igorko86 
I'm going to go ahead and close this issue for now since it looks like a blank issue template was submitted. Please feel free to open another issue if you run into problems while using the sendgrid-node library.
