### ISSUE TITLE
not able to send images in mail

### ISSUE THREAD

**Issue by HoaX7** [sendgrid/sendgrid-nodejs#1255]
I keep hitting the 400 error, and i cant even expand the error.response.body

Im also encoding the images as base64, still doesnt work..

            pathToAttachment = `${__dirname}/dir/name.jpg`;
            const attachment = fs.readFileSync(pathToAttachment).toString("base64");

                attachments: [
                    {
                        filename: "somename.jpg",
                        type: "image/jpg",
                        content: attachment,
                        disposition: "inline"
                    }
                ],

**Comment by HoaX7** [comment]
i even tried disposition "attachment"

**Comment by HoaX7** [comment]
nvm i solved it, bruh

**Comment by thinkingserious** [comment]
Hello @HoaX7,

Do you mind sharing the fix? Thank you!

With best regards,

Elmer

**Comment by HoaX7** [comment]
Well it's kinda stupid actually, I had put template variable in the environment files and had a typo while using the variable name "SENDGRID_TEMPLATE" I had written "SNEDGRID_TEMPLATE" lol smh

**Comment by efah** [comment]
@HoaX7 Which mail server or app you use? I've tried base64 and Gmail can't convert base64 to image.
