### ISSUE TITLE
Attachments: implementation and docs not corresponding with api specification for attachments

### ISSUE THREAD

**Issue by jaun-rg** [sendgrid/sendgrid-nodejs#1259]
### Issue Summary
implementation and docs not corresponding with api specification for attachments

Your documentation [Email Use Cases: Attachments](https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/attachments.md) and types in this project consider using `contentId` for attachments;

[The api's reference](https://sendgrid.com/docs/api-reference/) specifies `content_id`; please update implementation and docs

### Steps to Reproduce
use example in [Email Use Cases: Attachments](https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/attachments.md) 

### Code Snippet

using example

```node
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'recipient@example.org',
  from: 'sender@example.org',
  subject: 'Hello attachment',
  html: '<p>Here’s an attachment for you!</p>',
  attachments: [
    {
      content: 'Some base 64 encoded attachment content',
      filename: 'some-attachment.txt',
      type: 'plain/text',
      disposition: 'attachment',
      contentId: 'mytext'
    },
  ],
};
```

using correct property

```node
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'recipient@example.org',
  from: 'sender@example.org',
  subject: 'Hello attachment',
  html: '<p>Here’s an attachment for you!</p>',
  attachments: [
    {
      content: 'Some base 64 encoded attachment content',
      filename: 'some-attachment.txt',
      type: 'plain/text',
      disposition: 'attachment',
      content_id: 'mytext'
    },
  ],
};
```

### Exception/Log

using example

```log
Uncaught (in promise) ResponseError: Bad Request
at Request.http [as _callback] 
...
```

using correct property

```log
Argument of type '(MailData & { text: string; }) | (MailData & { html: string; }) | (MailData & { templateId: string; }) | (MailData & { content: MailContent[] & { ...; }; })' is not assignable to parameter of type 'MailDataRequired'.
```

### Technical details:
* sendgrid-nodejs version: latest
* node version: v10.22.0

**Comment by thinkingserious** [comment]
Hello @jaun-rg,

Thank you for bringing this to our attention! I've updated the docs with PR #1261. 

With best regards,

Elmer
