### ISSUE TITLE
How to pass variables in static text / html content?

### ISSUE THREAD

**Issue by turivishal** [sendgrid/sendgrid-nodejs#1260]
### Issue Summary
List of `to` email details,
```
let to = [
  {
    name: "A",
    email: "a@email.com"
  },
  {
    name: "B",
    email: "b@email.com"
  }
];
```

Text or Html content:
```
let text = "Hello Username";
```

I want to pass `name` from `to` array field in html/text, like,
```
let text = "Hello {{name}}";
```

My full code is,
```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(sendgridConfig.api_key);
sgMail
    .send({
      to: [
          { name: "A", email: "a@email.com" },
          { name: "B", email: "b@email.com" }
      ],
      from: { name: "admin", email: "admin@email.com" },
      subject: "Testing Bulk Email",
      text: "Hello {{name}}",
      html: "<h3>Hello {{name}}</h3>"
    })
    .then(() => { console.log("Success!"); })
    .catch((error) => { console.error(error.message); });
```

It should email to both emails with user's `name`,

### Technical details:
* sendgrid-nodejs version: "@sendgrid/mail": "^7.3.0",
* node version: 14.15.5

I know it is possible in dynamic template but i want to do this in static text and html content.

**Comment by thinkingserious** [comment]
Hello @turivishal,

I believe that [substitution tags](https://sendgrid.com/docs/ui/sending-email/substitution-and-section-tags) might be what you are looking for this use case. Please let us know.

With best regards,

Elmer

**Comment by turivishal** [comment]
Thank you for your quick response, 

I have tried as per that example,

```
.send({
      to: ["a@email.com", "b@email.com"],
      from: { name: "admin", email: "admin@email.com" },
      subject: "Testing Bulk Email",
      text: "Hello {{name}}",
      html: "<h3>Hello {{name}}</h3>",
      substitutions: {
        name: ["A", "B"]
      }
    })
```

but i receive this with all name,

Outcome for **A**:
a@email.com
> Text
```
Hello A, B
```

Outcome for **B**:
b@email.com
> Text
```
Hello A, B
```

**Comment by thinkingserious** [comment]
Hello @turivishal,

Ah, thank you for the clarification. I believe in that case, you would need to do something [like this](https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/customization.md), but instead of `customArgs`, for example, you would use `substitutions`.

With best regards,

Elmer

**Comment by turivishal** [comment]
Okay thank you, i got the solution,

```
.send({
      from: { name: "admin", email: "admin@email.com" },
      subject: "Testing Bulk Email",
      text: "Hello {{name}}",
      html: "<h3>Hello {{name}}</h3>",
      personalizations: [
        {
            to: "a@email.com",
            substitutions: {
                name: "A"
            }
        },
        {
            to: "b@email.com",
            substitutions: {
                name: "B"
            }
        }
      ]
    })
```
