### ISSUE TITLE
Invalid json

### ISSUE THREAD

**Issue by xavianaxw** [sendgrid/sendgrid-nodejs#1263]
### Issue Summary
When using @sendgrid/client and calling `/v3/marketing/contacts`, I was hit with a `400` error and a message of **Invalid json**

### Steps to Reproduce
1. Set up a nodejs application
2. Add the code snippet (as below) to a route of your choice. Mine is `subscribe` in this case.
3. Deploy and run the nodejs application and pass the following data

```
{
  "email": "name@gmail.com"
}
```

### Code Snippet
```node
app.post("/subscribe", function (req, res) {
  // Add your code here
  // res.json({success: 'post call succeed!', url: req.url, body: req.body})
  // don't need to json.parse req.body
  const { email } = req.body;
  const request = {
    method: "PUT",
    url: "/v3/marketing/contacts",
    data: {
      list_ids: [process.env.SENDGRID_LISTID],
      contacts: [
        {
          email: email,
        },
      ],
    },
  };

  sgClient
    .request(request)
    .then(([response, body]) => {
      console.log(`statusCode: ${response.statusCode}`);
      console.log(body);
      res.json({ statusCode: response.statusCode, body: body });
    })
    .catch(([response, body]) => {
      console.log(error);
      res.statusCode = response.statusCode;
      res.json({ statusCode: response.statusCode, body: body });
    });
});
```

### Exception/Log
```
{
  "statusCode": 400,
  "error": {
    "field_id": "",
    "message": "invalid json"
  }
}
```

### Technical details:
* sendgrid-nodejs version: 6.0.0
* node version: 10.23.0

### The Fix
As discovered in `packages/client/src/classes/client.js`, it is expecting a property `body` instead of `data` for the FormData you are passing to sendgrid.

```
createRequest(data) {
    let options = {
    url: data.uri || data.url,
    baseUrl: data.baseUrl,
    method: data.method,
    data: data.body,
    params: data.qs,
    headers: data.headers,
};
```

If you go back to the code snippet above, just swap `data` to `body` and it should fix this issue for you.

**Comment by xavianaxw** [comment]
I've no idea how to submit a PR to add this to the document but leaving this here for future reference lol

**Comment by shamoons** [comment]
I am having the same issue even when using `body`
