### ISSUE TITLE
Error: connect ETIMEDOUT 52.74.245.57:443

### ISSUE THREAD

**Issue by IQ1998** [sendgrid/sendgrid-nodejs#1264]
### Issue Summary
I use @sendgrid/mail and it worked without problems but now have been producing this error: `Error: connect ETIMEDOUT 52.74.245.57:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)`. This only happens at our deployment server, the code runs fine in our development server.

### Code Snippet
```node
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(config.sendGridApiKey);
...
const msg = {
    to, // list of receivers
    from: config.sendGridSender, // Change to your verified sender
    subject: templateEmail.subject, // Subject line,
    html: content,
  };

  sgMail
    .send(msg)
    .then(() => {
      console.log(error);
    })
    .catch((error) => {
      console.error(error);
    });
```
### Exception/Log

I have not found any logs that appear to be useful. If anyone need any other information, please let me know

### Technical details:
* sendgrid-nodejs version: 7.3.0
* node version: 10.24.0 (10-alpine)

I have read similar post about the timeout error and it seems the error may stem from network configuration issue. However, I also try testing manually using curl
```
curl -i --request POST \
--url https://api.sendgrid.com/v3/mail/send \
--header 'Authorization: Bearer MY_API_KEY_HERE' \
--header 'Content-Type: application/json' \
--data '{"personalizations": [{"to": [{"email": "mytestemail@gmail.com"}]}],"from": {"email": "myregisteredemail@gmail.com"},"subject": "Hello, World!","content": [{"type": "text/plain", "value": "Howdy!"}]}'
```
and it works instantly. Any help would be greatly appreciated. This problem has been persisting for a week now. I am just a maintainer without any network experience so excuse me if I missed any crucial debug information

**Comment by JenniferMah** [comment]
Hi @IQ1998 Are you making the request behind a proxy? and is there any errors that are caught when you try to send the email?

**Comment by IQ1998** [comment]
Thank you @JenniferMah for the reply. I am talking with the network & security department. But could it be the proxy though as I can directly make the request using curl ? Sorry if my question seemed obvious

**Comment by IQ1998** [comment]
It seems the request made by sendgrid mail does not go through proxy, but straight to the Internet. I was told that because the request tries to connect to an IP rather than an explicit domain, it does not go through the proxy, hence blocked by the security system. Can anyone confirm this ?

**Comment by IQ1998** [comment]
Just confirm that the error stems from the underlying implementation not having support for connecting through proxy. Guess I will have to implement my own function. Thank you @JenniferMah for the proxy idea
