### ISSUE TITLE
Fail to send mail with API key

### ISSUE THREAD

**Issue by gavenwang85** [sendgrid/sendgrid-nodejs#1275]
### Issue Summary
Since the early of this month, our health check program cannot trigger the alert mail when devices are failed. Then we try to send the alert mail manunally by changing the program code. The program show error when connect to the sendgrip smtp.  

Error Message from the err.log
{ Error: queryA EREFUSED smtp.sendgrid.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:196:19)
  errno: 'EREFUSED',
  code: 'EDNS',
  syscall: 'queryA',
  hostname: 'smtp.sendgrid.net',
  command: 'CONN' }```
 

### Steps to Reproduce
1. Add code on the "Health_check.js" code to manually send a test mail
2. Run "forever start -o out.log -e err.log health_check.js" on the Centos command console
3. Cat err.log the error message shown

### Code Snippet
```node
Part of code of the file "config.js"
=========================
const config = {}
config.port = 4433;
config.database = {
    "id": "lamppost"
};
config.mailList = 'gavenwang85@gmail.com';
config.mail = {
    host: 'smtp.sendgrid.net',
    username: 'apikey',
    password: 'SG.KEY'
    };

Part of code of the file "health_check.js"
=============================

const sendEmail = async (topic, body) => {
    let transporter = nodemailer.createTransport({
       host: config.mail.host,
       secure: true, // true for 465, false for other ports
       tls: {rejectUnauthorized: false},
       auth: {
         user: config.mail.username,
         pass: config.mail.password
       }
     });
     let ts = Date.now();
     let date_ob = new Date(ts);
     let date = ("0" + date_ob.getDate()).slice(-2);
     let month = ("0" + (date_ob.getMonth() + 1)).slice(-2);
     let year = date_ob.getFullYear();
     let hours = ("0" + date_ob.getHours()).slice(-2);
     let minutes = ("0" + date_ob.getMinutes()).slice(-2);
     let seconds = ("0" + date_ob.getSeconds()).slice(-2);
     const timestamp = "Mail Sent: "+ year + "-" + month + "-" + date + " " +  hours + ":" + minutes + ":" + seconds
     let info = await transporter.sendMail({
      from: '"xxx" <xxx@xxx.com>',
       to: '', // list of receivers
       bcc: config.mailList,
       subject: topic, // Subject line
       html: body + '<br>' + timestamp +  '<br>' + addbody
```    });
     console.log("Message sent: %s", info.messageId);
};
sendEmail('test','test').catch(console.error);


### Exception/Log
{ Error: queryA EREFUSED smtp.sendgrid.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:196:19)
  errno: 'EREFUSED',
  code: 'EDNS',
  syscall: 'queryA',
  hostname: 'smtp.sendgrid.net',
  command: 'CONN' }```

# paste exception/log here
```

### Technical details:'
* sendgrid-nodejs version: 
* v10.22.1
* node version:
* v10.22.1

**Comment by JenniferMah** [comment]
Hi @gavenwang85 I've gone ahead and removed your password SG.key and would recommend you regenerate a new key to use. What version of sendgrid-nodejs are you using? Was this working earlier this month? Based on your error log it looks like this could be an [issue with node mailer](https://stackoverflow.com/questions/54385031/nodemailer-fails-with-connection-refused-using-known-good-smtp-server).

**Comment by asam139** [comment]
Same problem
