### ISSUE TITLE
Sending a reply with original email content quoted below

### ISSUE THREAD

**Issue by SKempin** [sendgrid/sendgrid-nodejs#1277]
### Issue Summary
I'm trying to send a reply as a thread, where the original email content is quoted below the reply content (as a standard email reply has). 

Following https://github.com/sendgrid/sendgrid-nodejs/issues/482#issuecomment-641747083 and https://github.com/sendgrid/sendgrid-nodejs/issues/690#issuecomment-393336215 I have been able to create reply (which is successfully grouped as a thread) but the reply email itself doesn't include the previous email content as quoted content. 

As there is a lack of documentation for replying in general I am unsure how to achieve this?

### Steps to Reproduce
1. Use Inbound Parse to post RAW message content to API endpoint
2. Use simpleParser to parse email content
3. Send reply as snippet below
4. Reply is received but doesn't include the original email content as quoted content.

### Code Snippet
```node
  const parsedEmail = await simpleParser(req.body.email);
  const msg = {
    to: parsedEmail.from?.text,
    headers: {
      References: `${parsedEmail.references} ${parsedEmail.messageId}`,
      'In-Reply-To': parsedEmail.messageId,
    },
    from: 'myemail@mydomain.co.uk', // actual email removed for the purposes of this snippet
    subject: `Re: ${parsedEmail.subject}`, // where subject is the sender's subject.
    text: 'This is the reply from SendGrid',
  };
```

### Technical details:
* sendgrid-nodejs version: 7.4.2
* node version: 14.16.0

**Comment by thinkingserious** [comment]
Hello @SKempin,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by SKempin** [comment]
@thinkingserious I submitted this as an issue but the team was unable to support. Is this not possible to achieve?

**Comment by SKempin** [comment]
For anyone looking for this behaviour I was able to emulate the formatting by wrapping the content in block quotes:

 ```
<blockquote type="cite">
    On ${datestamp}, at ${timestamp}, ${from} wrote:
    <br /><br />
    <div>${originalEmailContent}</div>
  </blockquote>
```
