### ISSUE TITLE
Webhook event requests failing to verify for requests with more than one event

### ISSUE THREAD

**Issue by liampeng1** [sendgrid/sendgrid-nodejs#1278]
### Issue Summary
Webhook event requests failing to verify for requests with more than one event.

### Steps to Reproduce
1. Implement and run the below code with a request with one event.
2. Implement and run the below code with a request with more than one event.

### Code Snippet
```node
'use strict'

const { EventWebhook, EventWebhookHeader } = require('@sendgrid/eventwebhook')

const sendgridWebhook = app => {
  const esClient = app.get('esClient')
  const logger = app.get('logger')

  const verifyRequest = function (publicKey, payload, signature, timestamp) {
    console.log('publicKey', publicKey)
    console.log('payload', payload)
    console.log('signature', signature)
    console.log('timestamp', timestamp)
    const eventWebhook = new EventWebhook()
    const ecPublicKey = eventWebhook.convertPublicKeyToECDSA(publicKey)
    console.log('ecPublicKey', ecPublicKey)
    return eventWebhook.verifySignature(ecPublicKey, payload, signature, timestamp)
  }

  app.post('/sendgrid-webhook', async (request, response) => {
    try {
      const signature = request.get(EventWebhookHeader.SIGNATURE())
      const timestamp = request.get(EventWebhookHeader.TIMESTAMP())
      const publicKey = process.env.SENDGRID_WEBHOOK_KEY
      const payload = JSON.stringify(request.body) + '\r\n'

      const verRes = verifyRequest(publicKey, payload, signature, timestamp)
      console.log(verRes)
      if (verRes) {
        const allEvents = request.body
        const sgEvents = []
        for (const event in allEvents) {
          if (event.env === process.env.GOOGLE_CLOUD_PROJECT) {
            sgEvents.push(event)
          }
        }
        if (sgEvents.length > 0) {
          const body = sgEvents.flatMap(sgEvent => [{ index: { _index: 'sendgrid-events' } }, sgEvent])
          const esRes = await esClient.bulk({ refresh: true, body })
          const isErrors = esRes && esRes.body && esRes.body.errors
          if (!isErrors) {
            response.status(200).send()
          } else {
            logger.error('sendgrid-webhook elasticsearch error', esRes)
            response.status(500).send()
          }
        } else {
          response.status(200).send()
        }
      } else {
        logger.error('sendgrid-webhook verification failed', verRes)
        response.status(500).send()
      }
    } catch (error) {
      logger.error('sendgrid-webhook error', error)
      response.status(500).send()
    }
  })
}

module.exports = sendgridWebhook

```

### Exception/Log
```
Example payload that passes verification:

[{"email":"liam+5@ready.net","env":"local","event":"open","ip":"66.102.6.8","messageId":"UFzN8nkBnvb7cPPJ7xIg","recipientId":1
 

Example payload that fails verification:

[{"email":"liam+5@ready.net","env":"local","event":"processed","messageId":"MFzG8nkBnvb7cPPJtBJG","recipientId":1019,"send_at":0,"sg_event_id":"cHJvY2Vzc2VkLTE4MDc2NjIzLU1NSFZqUTRkVF91U0l6LU5vc1BDdFEtMA","sg_message_id":"MMHVjQ4dT_uSIz-NosPCtQ.filterdrecv-79b856d5bc-sl9tr-1-60C13903-55.0","smtp-id":"<MMHVjQ4dT_uSIz-NosPCtQ@geopod-ismtpd-canary-0>","timestamp":1623275779},{"email":"liam+5@ready.net","env":"local","event":"delivered","ip":"167.89.22.172","messageId":"MFzG8nkBnvb7cPPJtBJG","recipientId":1019,"response":"250 2.0.0 OK 1623275780 z2si1305597pgu.245 - gsmtp","sg_event_id":"ZGVsaXZlcmVkLTAtMTgwNzY2MjMtTU1IVmpRNGRUX3VTSXotTm9zUEN0US0w","sg_message_id":"MMHVjQ4dT_uSIz-NosPCtQ.filterdrecv-79b856d5bc-sl9tr-1-60C13903-55.0","smtp-id":"<MMHVjQ4dT_uSIz-NosPCtQ@geopod-ismtpd-canary-0>","timestamp":1623275780,"tls":1}]
```

### Technical details:
* sendgrid-nodejs version: 7.4.4
* node version: v15.8.0

**Comment by liampeng1** [comment]
I am assuming Its about how the body is getting parsed but I cannot figure it out.

**Comment by jordanpwood** [comment]
I am also having this problem.  It took me forever to figure out, but I can verify the signature on a message which contains a single event, but it fails on messages with more than one event in the array (such as the webhook test message which is sent from the "Test your Integration" button in the SendGrid portal).  I am also using version 7.4.4 of the webhook node library.

**Comment by jordanpwood** [comment]
I have one other wrinkle to add to this issue.  I have some tests for my webhook code which are able to both sign and verify messages with more than one event included in it.  Here is one of those tests: 

`    

      const ecdsa = require('starkbank-ecdsa');
      const Ecdsa = ecdsa.Ecdsa;
      const privateKey = new PrivateKey();
      const { EventWebhook } = require('@sendgrid/eventwebhook');

      function getBase64SignatureForMessage(message) {
        const signature = Ecdsa.sign(message, privateKey);
        return signature.toBase64();
      }


     describe(`When a well formatted message is sent >`, async function () {

      const webhookBody = [
        {
          "email": `${userIds[0]}@example.com`,
          "timestamp": 1621515786,
          "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
          "event": "dropped",
          "category": queueDigestEmail.WEEKLY_DIGEST_CATEGORY_ARRAY,
          "sg_event_id": "aBDKPbShfO4fjaYycKWH7Q==",
          "sg_message_id": "14c5d75ce93.dfd.64b469.filter0001.16648.5515E0B88.0",
          "reason": "Bounced Address",
          "status": "5.0.0"
        },
        {
          "email": `${userIds[1]}@example.com`,
          "timestamp": 1621515786,
          "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
          "event": "spamreport",
          "category": queueDigestEmail.WEEKLY_DIGEST_CATEGORY_ARRAY,
          "sg_event_id": "vlTpBe2cyGjbOQrWvuPRWg==",
          "sg_message_id": "14c5d75ce93.dfd.64b469.filter0001.16648.5515E0B88.0"
        },
        {
          "email": `${userIds[2]}@example.com`,
          "timestamp": 1621515786,
          "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
          "event": "group_unsubscribe",
          "category": queueDigestEmail.WEEKLY_DIGEST_CATEGORY_ARRAY,
          "sg_event_id": "x1TKj0k2KukWkBXgPUu0qg==",
          "sg_message_id": "14c5d75ce93.dfd.64b469.filter0001.16648.5515E0B88.0",
          "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
          "ip": "255.255.255.255",
          "url": "http://www.sendgrid.com/",
          "asm_group_id": 10
        },
      ];

      it(`should update user enrollment statuses`, async function () {
        const expectedResults = [
          {
            digest_email_enrollment_status: queueDigestEmail.REMOVED_ENROLLMENT_STATUS,
            email: `${userIds[0]}@example.com`,
            id: userIds[0],
          },
          {
            digest_email_enrollment_status: queueDigestEmail.SPAM_REPORT_ENROLLMENT_STATUS,
            email: `${userIds[1]}@example.com`,
            id: userIds[1],
          },
          {
            digest_email_enrollment_status: queueDigestEmail.UNSUBSCRIBED_ENROLLMENT_STATUS,
            email: `${userIds[2]}@example.com`,
            id: userIds[2],
          },
          {
            digest_email_enrollment_status: queueDigestEmail.WEEKLY_ENROLLMENT_STATUS,
            email: `${userIds[3]}@example.com`,
            id: userIds[3],
          },
        ];

        const messageString = getPayloadStringForSignatureVerification(webhookBody);
        const messageStringWithTimestamp = messageTimestamp + messageString;
        const signature = getBase64SignatureForMessage(messageStringWithTimestamp);

        await request(cms)
          .post('/email-events')
          .send(webhookBody)
          .set('X-Twilio-Email-Event-Webhook-Signature', signature)
          .set('X-Twilio-Email-Event-Webhook-Timestamp', messageTimestamp)
          .expect(200);

        const rows = await db.query(`
        SELECT digest_email_enrollment_status, email, id FROM users
        WHERE id = ANY($1)
        ORDER BY id
      `, [userIds]);

        rows.should.deepEqual(expectedResults);
      });

    });
`

As you can see, I am using the signing function available in `starkbank-ecdsa` with a private/public key pair I'm generating for the test.

**Comment by shwetha-manvinkurke** [comment]
Hi there. The problem in both your cases is that Sendgrid expects `\r\n` after each event and not just after the end of the entire message. Give [this](https://github.com/sendgrid/sendgrid-nodejs/blob/main/packages/eventwebhook/src/eventwebhook.spec.js#L48) a try and see if it works for you.

**Comment by liampeng1** [comment]
That works for me! Thank you @shwetha-manvinkurke !

**Comment by jordanpwood** [comment]
I ended up using the `verify` function on `express.json` to do my signature verification instead.  You have access to the raw buffer there, and no longer need to worry about reconstructing the original body.
