### ISSUE TITLE
Dynamic Template Internal Issue

### ISSUE THREAD

**Issue by alastairtechnologies** [sendgrid/sendgrid-nodejs#1283]
### Issue Summary
I currently have a working system that can send messages in plaintext. I was attempting to update my system to allow it to use Dynamic Templates for a cleaner look. This, however, causes what seems like an error in the request formatting provided by `@sendgrid/mail`.

### Steps to Reproduce
1. Generate a message with a To, From, Template ID, and Data
2. Pass this into the Sendgrid wrapper to be sent
3. Error Thrown.

### Code Snippet
```node
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENAPI);



(async () => {
	let msg = {
		to: "testemail@mydomain.com",
		from: "robotsender@mydomain.com",
		templateID: "randomTemplateID",
		dynamic_template_data: {
			item1: "test1",
			item2: "test2"
		}
	};
	sgMail.send(msg, (err, res) => {
		if(err) console.log(err);
		else console.log("Email Sent!", msg);
	})
})();
```

### Exception/Log
```
ResponseError: Bad Request
    at node_modules/@sendgrid/client/src/classes/client.js:146:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 400,
  response: {
    headers: {
      server: 'nginx',
      date: 'Tue, 06 Jul 2021 01:21:55 GMT',
      'content-type': 'application/json',
      'content-length': '646',
      connection: 'close',
      'access-control-allow-origin': 'https://sendgrid.api-docs.io',
      'access-control-allow-methods': 'POST',
      'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
      'access-control-max-age': '600',
      'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html',
      'strict-transport-security': 'max-age=600; includeSubDomains'
    },
    body: { errors: [Array] }
  }
}
```

### Technical details:
* sendgrid-nodejs version: 7.4.5
* node version: 12.22.1

### Note
Sorry if this is a repost, I have been digging around support, the docs, and this repo to see if this was mentioned anywhere, but I couldn't see it.

**Comment by shwetha-manvinkurke** [comment]
Hi @alastairtechnologies I would double check the data in the request that you are passing through. [This](https://github.com/sendgrid/sendgrid-nodejs/blob/main/TROUBLESHOOTING.md#viewing-the-request-body) might help.

**Comment by alastairtechnologies** [comment]
@shwetha-manvinkurke, it seems to be stripping the `templateID` and the `dynamic_template_data`. I was trying to find documentation on how to use it, and this seems like the right way, but I am trying to migrate the concept from a tutorial using curl, so...

**Comment by shwetha-manvinkurke** [comment]
Is [this](https://docs.sendgrid.com/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates) the documentation you followed? Have you configured the [handlebars](https://docs.sendgrid.com/for-developers/sending-email/using-handlebars) right? Here's some code samples that might help: 
https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/transactional-templates.md
https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/kitchen-sink.md

**Comment by alastairtechnologies** [comment]
That worked! Thanks @shwetha-manvinkurke!
