### ISSUE TITLE
SendGrid not working on Netlify Functions

### ISSUE THREAD

**Issue by m-glass** [sendgrid/sendgrid-nodejs#1284]
### Issue Summary
When creating a function using Netlify which utilizes the SendGrid Node JS package to send an email, locally everything works as expected (mails getting delivered). But as soon as I deploy the site (with the function) on Netlify in production and I am triggering the mail sender, the function is getting executed but no mail is arriving. In SendGrid's email 'Activity Feed' nothing is logged.

### Steps to Reproduce
1. Create a Netlify function in your project
2. Test it locally using Netlify CLI - this should work
3. Push your code and let Netlify deploy your site
4. Go on the production site and test the function (triggered from the frontend in my case)

### Code Snippet
```node
import client from '@sendgrid/mail'

function sendEmail (client) {
  return new Promise((resolve, reject) => {
    const emails = [
      // First mail
      {
        from: {
          email: 'sender1@example.com',
          name: 'Example1'
        },
        to: 'receiver1@example.com',
        templateId: 'd-XXXXX',
        dynamicTemplateData: {
          subject: 'Example',
        }
      },
      // Second mail
      {
        from: {
          email: 'sender2@example.com',
          name: 'Example2'
        },
        to: 'receiver2@example.com',
        templateId: 'd-XXXXX',
        dynamicTemplateData: {
          subject: 'Example',
        }
      }
    ]

    client
      .send(emails)
      .then(([response]) => {
        resolve(response)
      })
      .catch(error => reject(error))
  })
}

export async function handler (event) {
    const {
      SENDGRID_API_KEY
    } = process.env

    client.setApiKey(SENDGRID_API_KEY)

    sendEmail(client)
    // return statements would be here
}
```

### Technical details:
* sendgrid-nodejs version: ^7.4.5
* node version: v14.17.0

**Comment by Hrishikesh-K** [comment]
I've responded to your question on Netlify Forums here: https://answers.netlify.com/t/sendgrid-not-sending-from-netlify-functions/41294.

**Comment by m-glass** [comment]
[Okay I got the solution](https://answers.netlify.com/t/sendgrid-not-sending-from-netlify-functions/41294/4?u=m_glass): log in to SendGrid, go to IP Access Management and disable your IP Allow List (when this list is activated, only IP addresses listed in there are granted access - including API requests).

**Comment by davist11** [comment]
Is this still working for you? I have the exact same problem where it works locally but not on Netlify. I removed all records from the IP Allow List too.
