### ISSUE TITLE
An unclear error message send by Sendgrid

### ISSUE THREAD

**Issue by Mik-Drove** [sendgrid/sendgrid-nodejs#1286]
Hello

I've been corresponding with Sendgrid support for a while and they couldn't figure out how to solve the issue I was asking about so they direct me to this forum

The Request number is **6506441** (if you wish to read all the info in a conversation format)

I'm pasting here the data that seems relevant

When our clients are sending emails (via your service) we send you an object with a list of fields: to,  bcc, from name, from email,  subject, HTML content, headers, customArgs. The emails are being sent but one of our log errors appeared and it seems that something with the data that you received from us caused the problem. On our side, it seems that the data are valid.

* We are using SendGrid SDK ("@sendgrid/mail": "7.4.5")

Extra details:

"message": "Bad Request",
    "name": "Error",
    "stack": "Error: Bad Request\n    at /node_modules/@sendgrid/client/src/classes/client.js:146:29\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "code": 400

This is the core issue that is causing the Bad Request within the library itself: "Error: Bad Request\n    at /node_modules/@sendgrid/client/src/classes/client.js:146:29\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"

Appreciate your help with understanding the errors message that we receive from you
Thanks

**Comment by shwetha-manvinkurke** [comment]
@Mik-Drove looking at the zendesk history, I believe the json data that you posted is an output of `JSON.stringify(msg)`? It would help to look at the raw `request` body since that's where the issue lies. [Here](https://github.com/sendgrid/sendgrid-nodejs/blob/main/TROUBLESHOOTING.md#viewing-the-request-body) is how you can get that info. Would you be able to provide us that payload?

**Comment by Mik-Drove** [comment]
Hello shwetha-manvinkurke,

I've attached the raw JSON object to the conversation on the SendGrid site.
Please see attached image that shows to which message in the conversation the file was attached. 
I'm not attaching it here because I'm not sure that this thread is private. 
Please enter the conversation on the SendGrid site and download the raw JSON file from there

Thanks
Mickey
![Screen Shot 2021-08-11 at 9 54 01](https://user-images.githubusercontent.com/88386280/128983381-4e6b7017-d590-4e27-a9a3-b458e274babb.png)

**Comment by eshanholtz** [comment]
Hi @Mik-Drove 

Can you please post a code snippet of how you are using the sendgrid-nodejs helper library to build that JSON payload, as well as how you are obtaining the raw JSON payload output?

Thanks

**Comment by Mik-Drove** [comment]
Hello Elise

I would start by saying that I already sent all the data in the support case on Sendgrid so I can't figure why you won't take it from there and why should I repeat all of it from the start?

Attached here below the code snippet

Regarding the output: we receive an error message which we can't figure why is it being sent

Thanks



     msg = {
        to: emailAddress,
        bcc: bccAddresses,
        from: {
          name: removeSpecialCharacters(fromUserName) || 'Drove',
          email: fromEmail,
        },
        subject,
        html: content,
        headers: {
          'List-Unsubscribe': unsubscribeList,
        },
        customArgs: {
          notification: notificationId,
          activity: activityId,
          newsletter: newsletterId,
          environment: process.env.AWS_ENV || 'local',
        },
      }
      msg = addSandboxConfig(msg)

      if (replyToMail) {
        msg.reply_to = { email: replyToMail.trim() }
      }

      const sent = await sgMail.send(msg)

 
      log.error(err, msg ? JSON.stringify(msg) : msg, 'Unable to send email notification')
 
  }

**Comment by shwetha-manvinkurke** [comment]
Hi @Mik-Drove we want to look at the raw request body and not just your json stringified `msg`. Could you do something like the following and show us the output?

```node
 const {
  classes: {
    Mail,
  },
} = require('@sendgrid/helpers');

msg = {
    to: emailAddress,
    bcc: bccAddresses,
    from: {
      name: removeSpecialCharacters(fromUserName) || 'Drove',
      email: fromEmail,
    },
    subject,
    html: content,
    headers: {
      'List-Unsubscribe': unsubscribeList,
    },
    customArgs: {
      notification: notificationId,
      activity: activityId,
      newsletter: newsletterId,
      environment: process.env.AWS_ENV || 'local',
    },
  }
  msg = addSandboxConfig(msg)

  if (replyToMail) {
    msg.reply_to = { email: replyToMail.trim() }
  }

  const mail = Mail.create(msg);
  const body = mail.toJSON();
  console.log(JSON.stringify(body));

  const sent = await sgMail.send(msg)

```

**Comment by Mik-Drove** [comment]
Hello Elise

Attached to this message is the full data from our log, I understand from your message that this is the data you are asking for.

A few notes:

1-I changed some private data (e.g.: email address)
2-we are using sgMail from '@sendgrid/mail' and not '@sendgrid/helpers' and you wrote on your message
3- I've attached all this data already in the chat I had with your customer service team so you can take it from there as well

[from logs.TXT](https://github.com/sendgrid/sendgrid-nodejs/files/7005429/from.logs.TXT)

Thanks
Mickey

**Comment by eshanholtz** [comment]
Hi Mickey,

As mentioned both here and in the related support ticket, the data in the files you included is **not** the data we need in order to solve this issue. The data you sent has been the output of `JSON.stringify(msg)`. However, we need to see the **raw request body** that gets compiled by `sgMail.send(msg)`, which can be extracted with the following code:
```node
const {
  classes: {
    Mail,
  },
} = require('@sendgrid/helpers');
const mail = Mail.create(msg);
const body = mail.toJSON();
console.log(JSON.stringify(body));
```

Please include the output from this code in this GitHub issue thread so we can further help you resolve this issue.

**Comment by Mik-Drove** [comment]
Hello Elise

I've followed the instructions in your last message and added the code lines you sent to our code.
Attached are the logs.
I added the text "raw request body" before printing the JSON.stringify(body) so you can search for this text in order to see where the JSON.stringify(body) starts.

Thanks
Mickey
[25.8.21.TXT](https://github.com/sendgrid/sendgrid-nodejs/files/7043816/25.8.21.TXT)

**Comment by Mik-Drove** [comment]
Hello Elise

Attached is the same payload for a request that worked successfully
Hope that this data will help to understand what is the cause of this problem
Thanks
Mickey

[successful.TXT](https://github.com/sendgrid/sendgrid-nodejs/files/7081755/successful.TXT)

**Comment by eshanholtz** [comment]
Hi Mickey,
I've inspected both requests and I'm not seeing anything that suggests your issue is stemming from your use of the helper library. I've gone ahead and reached out to the Support Engineer who was handling your case through SendGrid support and reopened your support ticket through there. This is not an issue we can help you solve through GitHub, so you will need to continue troubleshooting your issue through SendGrid Support.

I'm going to go ahead and close this GitHub issue.
