### ISSUE TITLE
bypass_unsubscribe_management

### ISSUE THREAD

**Issue by guri2323** [sendgrid/sendgrid-nodejs#1291]
### Issue Summary

1. I am using 7.4.4 version of @sendgrid/mail but I don't see option "bypass_unsubscribe_management" in node modules file.

2. I want to bypass global unsubscribe list

3. This is the link to SendGrid documentation for accessing bypass_unsubscribe_management: https://docs.sendgrid.com/ui/sending-email/index-suppressions#bypass-suppressions

###Current email settings interface for SendGrid in node modules:
```export interface MailSettings {
  bcc?: {
    enable?: boolean;
    email?: string;
  };
  bypassListManagement?: {
    enable?: boolean;
  };
  footer?: {
    enable?: boolean;
    text?: string;
    html?: string;
  };
  sandboxMode?: {
    enable?: boolean;
  };
  spamCheck?: {
    enable?: boolean;
    threshold?: number;
    postToUrl?: string;
  };
}
```

### Technical details:
* sendgrid-nodejs version: 7.4.4
* node version: 14.17.0

**Comment by JenniferMah** [comment]
Hi @guri2323,
As long as you set the `bypassListManagement` filter to `true` your message will bypass all unsubscribes and suppressions in **all** lists. 

We don't currently support the more granular filters like `bypass_spam_management`, `bypass_bounce_management`, and `bypass_unsubscribe_management` in this library. Feel free to submit a PR with the changes.

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by acanimal** [comment]
Any news on this feature?

**Comment by acanimal** [comment]
I need this with some urgency. For any other that arrives here I'm working in a PR.
