### ISSUE TITLE
Update Axios Version To 0.21.4

### ISSUE THREAD

**Issue by LuisOsta** [sendgrid/sendgrid-nodejs#1294]
### Issue Summary
Recently axios released a new version 0.21.2 that patched the security issue described [here](https://github.com/axios/axios/issues/3979).

Currently
Since the SendGrid client uses the old version of axios, it will doesn't have the patch fix. You can see the version it specifies [here](https://github.com/sendgrid/sendgrid-nodejs/blob/1843e8689bd850b60e4550443fdf8722a51c7c68/packages/client/package.json#L31)

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by LuisOsta** [comment]
@eshanholtz Thanks for the quick reply! I've gone ahead and made the [PR ](https://github.com/sendgrid/sendgrid-nodejs/pull/1296) necessary to fix this issue.

It actually turns out that the necessary fix version is 0.21.4

**Comment by LuisOsta** [comment]
You can see here that 0.21.4 doesn't have this vulnerability - https://www.sourceclear.com/vulnerability-database/libraries/axios/javascript/npm/lid-11324/summary

**Comment by LuisOsta** [comment]
Just an update that the PR is ready and approved but just hasn't been merged in yet. In case anyone is following this thread
