### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by alexandr-kazakov** [sendgrid/sendgrid-nodejs#1298]
I finded this page https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/README.md#email-use-cases after I click at the bottom link of the page ["How to View Email Statistics"](https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/email-stats.md) I went to the page and there is a broken link [Event Webhook](https://docs.sendgrid.com/API_Reference/Webhooks/event.html)

**Comment by shwetha-manvinkurke** [comment]
Should be fixed now
