### ISSUE TITLE
Please upgrade axios in the @sendgrid/client since it has security issue

### ISSUE THREAD

**Issue by RezaRahmati** [sendgrid/sendgrid-nodejs#1316]
### Issue Summary

`@sendgrid/client` has dependecy to `axios@0.21.4`, and that version of axios has a high severity security issue (as per whitesource) Please see below image, and seems issue is resolved on any version higher than 0.21.4.

![image](https://user-images.githubusercontent.com/10086092/140574407-2f521e69-0f60-4044-9c93-b8ed37a49904.png)

### Technical details:
* sendgrid-client version: 7.6.0 
* node version: 16

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by snuffykl** [comment]
Hi @eshanholtz any update on upgrading axios@0.21.4 to the latest to fix security vulnerability in @sendgrid/client ?

**Comment by prashant93** [comment]
Hi @eshanholtz  any update on this, If need any detail or help let me know? Due to this issue our production release on hold.
This has been since November.

**Comment by villesau** [comment]
@eshanholtz it's. high severity issue. Should help with prioritization.

**Comment by RezaRahmati** [comment]
if you are using npm >8.3.0, you can add `"overrides": {}` section to your package.json and force another version of axios, until this is fixed, please make sure you will do regression in case there was a breaking change

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by villesau** [comment]
@eshanholtz @thinkingserious looks like similar issue was last time fixed within days: https://github.com/sendgrid/sendgrid-nodejs/issues/1237 why now months of silence?

**Comment by Sujay-shetty** [comment]
@RezaRahmati tried to use overrides property of package.json but couldn't succees.
Could you please share code change for the same?

Node : 14.19.0
npm : 6.14.16

**Comment by RezaRahmati** [comment]
> @RezaRahmati tried to use overrides property of package.json to override axios version to 0.25.0 but couldn't succeed. sample 1 :
> 
> ```
> {
>     "dependencies": {
>         "@sendgrid/mail": "^7.6.0",
>         "bluebird": "^3.5.1",
>     }
>     "overrides": {
>          "axios": "0.25.0"
>     }
> }
> ```
> 
> sample 2 :
> 
> ```
> {
>     "dependencies": {
>         "@sendgrid/mail": "^7.6.0",
>         "bluebird": "^3.5.1",
>     }
>     "overrides": {
>          "@sendgrid/mail": {
>              "@sendgrid/client": {
>                   "axios": "0.25.0"
>               }
>          }
>     }
> }
> ```
> 
> Could you please share code change for the same?
> 
> Node : 14.19.0 npm : 6.14.16

please read my answer again, it needs node >= 8.3.0
