### ISSUE TITLE
Multi-language support in Sendgrid with a WYSIWYG template

### ISSUE THREAD

**Issue by svenzz10** [sendgrid/sendgrid-nodejs#1323]
We want to offload the creation/maintaining of templates to our marketing guys, only these people aren't programmers, so we need plain WYSIWYG templates per language. Having 1 separate version per language would be the answer to our problem.

The following would be even better:

1 - the ability to set a default version ( when no version is selected, or invalid version is provided the default version would take over )
2 - just have an extra parameter in the POST /mail/send API to add a version

Right now, first setting the required template to active, then sending an email would result in concurrency problems where wrong templates will be chosen.

Potential solutions for multi-language
Option 1:
Add a "version" parameter to the API, and just send version provided to (language version, remove need for activation)

Option 2
Add localized parameters to a template. This way we can use the template for multiple languages by only translating the parameters. Drawback of this approach is that some sentence constructs dont work for each language.

Option 3
Translation tab for each module, where you can have different translations of modules all in the same template.

Seems that Sendgrid has not done any work to support this.

Only options we have now:

- Apply handlebars E.G {{#if}}, drawback to this is that you can't work with a WYSIWYG way of making templates.
You also have to specify booleans for each language, because you can't check with a string. E.G
dutch: false
french: true
{{#if dutch}}
{{#else if french}}
This is not a neat way of approaching this.
Non-support of WYSIWYG style editor.

- Create a different template for each language and e-mailtype. This is way too immersive.

- Use the versions approach with the risk of e-mails being sent at exactly the same time, which confuses the API activation request with the risk of sending the email with the wrong translation. Basically not usable.

Kind regards,

Sven

**Comment by childish-sambino** [comment]
Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at [support.sendgrid.com](https://support.sendgrid.com/hc/en-us).
