### ISSUE TITLE
/v3/marketing/contacts/import CSV body field

### ISSUE THREAD

**Issue by Enijar** [sendgrid/sendgrid-nodejs#1328]
### Issue Summary

There is no documentation for how to upload a CSV file to the `/v3/marketing/contacts/imports` endpoint.

### Steps to Reproduce

```javascript
await request({
  method: "PUT",
  url: "/v3/marketing/contacts/imports",
  body: {
    list_ids: ["example-list-id"],
    file_type: "csv",
  },
})
```

The response is `200`, but I don't know how to upload a CSV file via this API.

### Technical details:
* sendgrid-nodejs version: 7.4.3
* node version: 16.13.0

**Comment by beebzz** [comment]
Hi @Enijar! Please file a ticket with [SendGrid customer support](https://github.com/sendgrid/sendgrid-php/issues/1077) in order to properly debug this issue.
