### ISSUE TITLE
Broken sticker and link in the readme file

### ISSUE THREAD

**Issue by IObert** [sendgrid/sendgrid-nodejs#1343]
### Issue Summary
 The first line of the readme file of each package contains a broken sticker (link AND image are broken). 

![Screenshot 2022-02-28 at 14 36 45](https://user-images.githubusercontent.com/1873245/155992537-ce3df1c9-d800-4000-8d45-1bddb51e399f.png)

When I click the link, it sends me to this page where I see a Heroku error message: <https://dx.sendgrid.com/newsletter/nodejs>

### Steps to Reproduce
1. Click on broken sticker in any of the these packages:
- <https://github.com/sendgrid/sendgrid-nodejs/tree/main/packages/client>
- <https://github.com/sendgrid/sendgrid-nodejs/tree/main/packages/contact-importer>
- <https://github.com/sendgrid/sendgrid-nodejs/tree/main/packages/helpers>
- <https://github.com/sendgrid/sendgrid-nodejs/tree/main/packages/inbound-mail-parser>
- <https://github.com/sendgrid/sendgrid-nodejs/tree/main/packages/mail>

**Comment by JenniferMah** [comment]
Closed by #1342

**Comment by IObert** [comment]
Hi @JenniferMah,
actually the issue is still open. The PR only affected the SendGrid logo in the bottom. I wasn't sure where these stickers should point to, so I couldn't fix that one.
Can you please reopen the issue?

**Comment by JenniferMah** [comment]
Hi @IObert, Thanks for bringing this to my attention. I've gone ahead and reopened the issue! We no longer run the service that sends an email when a new package is released. The email notification badge just needs to be removed completely.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-nodejs/commit/d684055c541ff688c4a7e5fa29cde1bccc13c875
