### ISSUE TITLE
Question: What is the structure of the error object?

### ISSUE THREAD

**Issue by NoelAbrahams** [sendgrid/sendgrid-nodejs#144]
Hi,

Given the following example:

```JavaScript
sendgrid.send({
  to:       'example@example.com',
  from:     'other@example.com',
  subject:  'Hello World',
  text:     'My first email through SendGrid.'
}, function(err, json) {
  if (err) { return console.error(err); }
  console.log(json);
});
```

I would like to know the structure of the `err` object. Debugging a bit into this shows it to have a `message` property but no error code.

What is the official structure for this error object? And how do I obtain the HTTP error code from the request?

Thanks.

**Comment by mtheoryx** [comment]
Have you tried logging the err object itself?
```javascript
sendgrid.send({
  to:       'example@example.com',
  from:     'other@example.com',
  subject:  'Hello World',
  text:     'My first email through SendGrid.'
}, function(err, json) {
  console.log(err);
  if (err) { return console.error(err); }
  console.log(json);
});
```

**Comment by NoelAbrahams** [comment]
yes, did that. Just wanted to know the official supported API.

**Comment by elbuo8** [comment]
We relay the exact object from the API.

**Comment by eddiezane** [comment]
The error is a direct error from the [request](https://github.com/request/request) library https://github.com/sendgrid/sendgrid-nodejs/blob/master/lib/sendgrid.js#L50-L53
