### ISSUE TITLE
Allow uploading of files as streams

### ISSUE THREAD

**Issue by YourDeveloperFriend** [sendgrid/sendgrid-nodejs#148]
Currently, you can upload files in the form of [a buffer, a path to a file, or a url](https://github.com/sendgrid/sendgrid-nodejs#addfile). I assume that all of these are eventually turned into a stream. It would be great if you could upload an actual stream:

```Javascript
var stream = fs.createReadStream(filename).pipe(customTransformer);
email.addFile({
  filename: 'icon.jpg',
  contentType: 'image/png',
  stream: fs.createReadStream(filename)
});
```

I'm doing some intense stream transformations and I hope to upload the stream directly to the request object, but I'm having to do something like this:

```Javascript
var stream = fs.createReadStream(filename).pipe(customTransformer);
var result = [];
stream.on('data', function(buff) {
  result.push(buff.toString());
});
stream.on('end', function() {
  email.addFile({
    filename: 'icon.jpg',
    contentType: 'image/png',
    content: result.join('')
  });
});
```

This will create memory issues for us down the road.

**Comment by inolasco** [comment]
+1

**Comment by sourabhdesai** [comment]
+1

**Comment by sourabhdesai** [comment]
Im gonna give this a go and then make a PR. Will probably stick to the API that @YourDeveloperFriend suggested:

```
var stream = fs.createReadStream(filename).pipe(customTransformer);
email.addFile({
  filename: 'icon.jpg',
  contentType: 'image/png',
  stream: fs.createReadStream(filename)
});
```

**Comment by thinkingserious** [comment]
Hello Everyone,

For those that want to continue following the progress on this thread, please refer to this pull request: https://github.com/sendgrid/sendgrid-nodejs/issues/219

Thanks!

Elmer
