### ISSUE TITLE
1.3.0 causes 'HPE_INVALID_CONSTANT' errors

### ISSUE THREAD

**Issue by davidbeers** [sendgrid/sendgrid-nodejs#150]
We've recently been seeing 'HPE_INVALID_CONSTANT' errors or occasional 'SyntaxError: Unexpected end of input JSONPARSEERROR when parsing' errors from a nodejs application that has been using SendGrid without issue for over a year.  This occurs in the callback from sendgrid.send().  The error is consistently reproducible when running in a deployed state (on Heroku) but doesn't seem to occur when running a node script on a local machine that sends the same email.

For the time being we've been able to resolve the issue by changing our package config to use 1.2.4 of sendgrid instead of 'latest'.

Using node 0.10.18

**Comment by eddiezane** [comment]
It looks like this was a previous [issue](https://github.com/sendgrid/sendgrid-nodejs/issues/80).

The only major difference between 1.2.4 and 1.3.0 is the removal of shrinkwrap.json, which shouldn't have been in the library.

What version of request did it pull down for you?

**Comment by eddiezane** [comment]
Also, any chance you can update your version of node and test?

**Comment by eddiezane** [comment]
@davidbeers any chance to test on an updated version of node?
