### ISSUE TITLE
ECONNREFUSED when sending

### ISSUE THREAD

**Issue by tjsail33** [sendgrid/sendgrid-nodejs#151]
whenever I try to send an email from my application, all i get in response is 

```
01:55:32 web.1    | { [Error: connect ECONNREFUSED]
01:55:32 web.1    |   code: 'ECONNREFUSED',
01:55:32 web.1    |   errno: 'ECONNREFUSED',
01:55:32 web.1    |   syscall: 'connect' }
01:55:32 web.1    | null
```

This is the `err` part of the callback printed before the `json` part, which is null.

I am using `require('sendgrid')('username', 'password', {api: 'smtp', port: 465})` to initialize my sendgrid instance. Any ideas?

This is with node 0.10.35 and sendgrid 1.4 and 1.5.

**Comment by eddiezane** [comment]
This library only supports our web api. You can find usage examples [here](https://github.com/sendgrid/sendgrid-nodejs#sendgrid-nodejs).

If you are looking for smtp support, you can use [nodemailer](https://github.com/andris9/nodemailer-smtp-transport#usage).
