### ISSUE TITLE
1.6.0 causes HPE_INVALID_CONSTANT errors

### ISSUE THREAD

**Issue by hodnett** [sendgrid/sendgrid-nodejs#156]
Previously reported in #150 but also referenced in #80.

Output of `npm ls sendgrid` is... 

    pathbrite-worker-email@0.0.1 /home/pathbrite/worker_email
    └── sendgrid@1.6.0

Output of `node -v` is...

    v0.10.33

Contents of package.json is...

    {
        "name": "pathbrite-worker-email",
        "version": "0.0.1",
        "scripts": {
            "start": "node index"
        },
        "dependencies": {
            "amqp": "*",
            "sendgrid":"*",
            "mu2":"*",
            "underscore":"*"
        }
    }

Error message reported is...

    { [Error: Parse Error] bytesParsed: 137, code: 'HPE_INVALID_CONSTANT' }

We were able to get around this error by downgrading to Sendgrid 1.2.7 as suggested in #150 but we loose access to some of the methods that were later added. We'd really like to avoid updating Node.js. Any help would be much appreciated.

**Comment by eddiezane** [comment]
What version of [request](https://github.com/request/request) got pulled down?

**Comment by hodnett** [comment]
Looks like request@2.53.0.

The full list is...


    pathbrite-worker-email@0.0.1 /home/pathbrite/worker_email
    ├─┬ amqp@0.2.4
    │ └── lodash@1.3.1
    ├── mu2@0.5.20
    ├─┬ sendgrid@1.6.0
    │ ├── lodash@2.4.1
    │ ├── mime@1.3.4
    │ ├─┬ request@2.53.0
    │ │ ├── aws-sign2@0.5.0
    │ │ ├─┬ bl@0.9.4
    │ │ │ └─┬ readable-stream@1.0.33
    │ │ │   ├── core-util-is@1.0.1
    │ │ │   ├── inherits@2.0.1
    │ │ │   ├── isarray@0.0.1
    │ │ │   └── string_decoder@0.10.31
    │ │ ├── caseless@0.9.0
    │ │ ├─┬ combined-stream@0.0.7
    │ │ │ └── delayed-stream@0.0.5
    │ │ ├── forever-agent@0.5.2
    │ │ ├─┬ form-data@0.2.0
    │ │ │ └── async@0.9.0
    │ │ ├─┬ hawk@2.3.1
    │ │ │ ├── boom@2.6.1
    │ │ │ ├── cryptiles@2.0.4
    │ │ │ ├── hoek@2.11.1
    │ │ │ └── sntp@1.0.9
    │ │ ├─┬ http-signature@0.10.1
    │ │ │ ├── asn1@0.1.11
    │ │ │ ├── assert-plus@0.1.5
    │ │ │ └── ctype@0.5.3
    │ │ ├── isstream@0.1.1
    │ │ ├── json-stringify-safe@5.0.0
    │ │ ├─┬ mime-types@2.0.9
    │ │ │ └── mime-db@1.7.0
    │ │ ├── node-uuid@1.4.2
    │ │ ├── oauth-sign@0.6.0
    │ │ ├── qs@2.3.3
    │ │ ├── stringstream@0.0.4
    │ │ ├─┬ tough-cookie@0.12.1
    │ │ │ └── punycode@1.3.2
    │ │ └── tunnel-agent@0.4.0
    │ └── smtpapi@1.1.0
    └── underscore@1.8.2

**Comment by eddiezane** [comment]
Interesting. I'm unable to reproduce this on `0.10.33`. Could you please tell me more about what you're doing? Attaching files? Using the smtpapi header? Anything that stands out?

**Comment by hodnett** [comment]
We're instantiating an email object with the to, toname, from, fromname, subject, text, html and date parameters, then invoking the setCategories(), setUniqueArgs() and setFilters() methods before finally calling send().

The thought occurred to me that we may be sending invalid syntax in either the html parameter or as arguments to the methods but #150 implies we can't parse the response Sendgrid is actually sending?

**Comment by eddiezane** [comment]
Hmmm. What environment is your app running in? Heroku? Server?

I'm going to continue to try and reproduce it.

**Comment by hodnett** [comment]
Amazon EC2 instance running Ubuntu 10.04.4 LTS.

**Comment by krunkosaurus** [comment]
I am a coworker of @hodnett.  As an update we tried moving from Node v0.10.33 to v0.12.0 and now get the error: 'SyntaxError: Unexpected end of input JSONPARSEERROR when parsing' as discussed in issue #150.

**Comment by eddiezane** [comment]
I'm unable to reproduce this on Heroku or an Ubuntu 10.04 vps.

Can you please isolate and share a reproducible snippet (please remove sensitive information)?

**Comment by elbuo8** [comment]
@hodnett @krunkosaurus are you by any chance doing file uploads?

**Comment by krunkosaurus** [comment]
Hi @elbuo8 and @eddiezane. I have zipped up our node script and emailed it to @elbuo8. Please let me know if there's any questions.

**Comment by krunkosaurus** [comment]
I don't believe we are doing file uploads. This script listens to a Rabbitmq job queue that does a lot of things, among them, email jobs.  We have downgraded back to the old Sendgrid 0.2.7 and things are working again but there are some newer features we may need.

**Comment by elbuo8** [comment]
Using 0.12 won't work since `request` doesn't work for it yet.

@krunkosaurus the source code you sent me is using 0.2.7. Please send me your attempt with the latest version of the lib? And please clean up account credentials as I'm no longer a SG employee (and its a good practice anyways).

**Comment by krunkosaurus** [comment]
Whoops. :3

Yeah I realized that about  0.12 after I posted the previous message.  I will clean and pack the new attempt.

**Comment by hodnett** [comment]
While @krunkosaurus works on the new zip archive...

I have a parallel project written in PHP that also needed to send emails. I used Composer (the PHP equivalent of NPM) to grab version 2.2.1 from https://github.com/sendgrid/sendgrid-php and it worked flawlessly. And this project also used file uploads.

This makes me think I'm sending something badly formatted to Sendgrid (problem 1) and we can't parse the error message coming back (problem 2). Hopefully @elbuo8 will see what I've formatted incorrectly once he gets the code but now I'm leaning towards a subtle bug in a sendgrid-nodejs dependency.

**Comment by molekilla** [comment]
I'm getting the same with 0.10.35 and 0.10.37 using it through `"nodemailer-sendgrid-transport": "^0.1.0"`. Appreciate any fix or workaround

**Comment by eddiezane** [comment]
@molekilla can you please provide me with the code snippet you are using? Please remove sensitive information.

Having a hard time narrowing this down. I am really thinking it's in node core.

**Comment by molekilla** [comment]
I figured out it was the attachments entry being null. No issues now.
Thanks.

**Comment by nlindley** [comment]
I was seeing this error when trying to add files by URL, but the error went away when I added the filename property. From the README it wasn’t immediately obvious this was necessary. I can provide non-working and working examples if desired.

**Comment by molekilla** [comment]
Maybe throw a detailed error description by validating arguments.

**Comment by eddiezane** [comment]
Thanks @nlindley. I just updated the README with a note.

@molekilla that is something we should check for if this strange error is the outcome.
