### ISSUE TITLE
Mails going into the same thread!

### ISSUE THREAD

**Issue by chinnichaitanya** [sendgrid/sendgrid-nodejs#157]
I tried sending mails using the example codes and every time, though I change the 'subject' of the mail, the mail goes into the same thread instead of a new thread if 'from address' is same. Do I need to include some more variables for that ?

**Comment by eddiezane** [comment]
You need to make noticeably different changes to the subject or add a nonce or random hash to your from address.

http://webapps.stackexchange.com/a/5036
