### ISSUE TITLE
Query its Feature

### ISSUE THREAD

**Issue by noConnection** [sendgrid/sendgrid-nodejs#159]
Using sendgrid-nodejs to send image attachment, does it store the image on server or it can directly send the image,without occupying space on server.

**Comment by eddiezane** [comment]
The [addFile](https://github.com/sendgrid/sendgrid-nodejs#addfile) function works with an url that makes an HTTP request and stores the contents into a buffer in memory. Relevant [code](https://github.com/sendgrid/sendgrid-nodejs/blob/master/lib/file_handler.js#L81-L113).
