### ISSUE TITLE
Getting JSONPARSEERROR while sending mail 

### ISSUE THREAD

**Issue by rajit-daffodil** [sendgrid/sendgrid-nodejs#161]
Hello,
  
We are getting this type of error's while sending mails
  
ERROR: {"message":"SyntaxError: Unexpected token < JSONPARSEERROR when parsing: \r\n\r\n 
\r\n\r\n\n at Request._callback (/mnt/applaneservers/production3/node_modules/sendgrid/lib/sendgrid.js:60:25)\n at Request.self.callback (/mnt/applaneservers/production3/node_modules/request/request.js:373:22)\n at Request.EventEmitter.emit (events.js:98:17)\n at Request. (/mnt/applaneservers/production3/node_modules/request/request.js:1318:14)\n at Request.EventEmitter.emit (events.js:117:20)\n at IncomingMessage. (/mnt/applaneservers/production3/node_modules/request/request.js:1266:12)\n at IncomingMessage.EventEmitter.emit (events.js:117:20)\n at _stream_readable.js:919:16\n at process._tickDomainCallback (node.js:463:13)"}

I am using latest version of sendgrid npm module i.e. version 1.6.1

I am able to send mails from my code too and the error comes only sometimes, and mostly mails are send successfully, So I think our code and mail-options is not an issue, so request you to please help us with appropriate solution.

Thank you very much..........

**Comment by eddiezane** [comment]
What version of node are you using?

**Comment by rajit-daffodil** [comment]
Hi,

We are using node of version 0.10.28

**Comment by eddiezane** [comment]
Is the issue still occurring? Is there anything else you can share? We have no other reports of malformed responses.

**Comment by rajit-daffodil** [comment]
Yes, We are still getting the same error, we are doing nothing special..

**Comment by eddiezane** [comment]
Can you share further logs or any other stack traces? What if you catch the error and log it?

**Comment by eddiezane** [comment]
Sounds like we may have traced this down to attaching a file by url but not sending the `content-length` header.

Is this still an issue for you?

**Comment by rajit-daffodil** [comment]
no

On Fri, Jun 19, 2015 at 7:31 PM, Eddie Zaneski <notifications@github.com>
wrote:

> Sounds like we may have traced this down to attaching a file by url but
> not sending the content-length header.
>
> Is this still an issue for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sendgrid/sendgrid-nodejs/issues/161#issuecomment-113524210>
> .
>



-- 

Thanks and Regards,

Rajit Garg
*Daffodil Software Ltd.*
rajit.garg@daffodilsw.com
www.daffodilsw.com
