### ISSUE TITLE
content-transfer-encoding: quoted-printable

### ISSUE THREAD

**Issue by doowb** [sendgrid/sendgrid-nodejs#163]
According to [this document](https://support.sendgrid.com/hc/en-us/articles/200182068-HTML-Formatting-Issues) at sendgrid, it seems like I need to set some "MIME" setting to allow setting the `content-transfer-encoding` header to `7bit` for html emails instead of `quoted-printable`.

Is there a way to do this through the node api? I'm not finding any settings in my sendgrid profile to change this. I also reviewed the original content from an email I received from sendgrid and it had "Content-Transfer-Encoding: 7bit" for the html part of the email.

Thanks for any help on this.

**Comment by eddiezane** [comment]
Our Web API does not currently support the ability to change that header. It is however supported via SMTP. Definitely on our roadmap for the next upcoming version.

Apologies if it caused you a headache.

**Comment by devinus** [comment]
@eddiezane Was this added recently?

**Comment by elbuo8** [comment]
@devinus he doesn't work at SG anymore. Hi @eddiezane :dancers: 

And no. v3 of the send endpoint has not been released. No changes to v2 either.
