### ISSUE TITLE
Can I change the port that the mail is getting sent with?

### ISSUE THREAD

**Issue by griffind** [sendgrid/sendgrid-nodejs#165]
What port does the api default to? Also, I tried using ```  {"uri":"http://sendgrid.org:587/send"} ``` on init, but I get refused by the server. The reason I am trying to change the port is that I have reason to believe that I am getting blocked by certain mail ISPs.

**Comment by eddiezane** [comment]
Hi @griffind,

This library uses SendGrid's [Web API](https://sendgrid.com/docs/API_Reference/Web_API/mail.html) as opposed to SMTP. It is required to communicate over the HTTPS port 443.

I recommend reaching out to our [support team](https://support.sendgrid.com/hc/en-us/articles/203979566-How-do-I-contact-Support-).

**Comment by griffind** [comment]
@eddiezane So currently sendgrid is using port 443 to send the mail? I would be surprised if .edu domains block that port. Maybe something else is going on.

Thanks for your help.

**Comment by eddiezane** [comment]
Apologies for the confusion. This library simply makes HTTP requests to SendGrid's API servers. It has no part in how SendGrid's servers delivers mail after that.

**Comment by JongSikLim** [comment]
Can't change port when i send yet?
