### ISSUE TITLE
sendAt issues

### ISSUE THREAD

**Issue by richardpenner** [sendgrid/sendgrid-nodejs#166]
I'm trying to set the SMTPAPI header using the sendAt() function. The sendgrid.send() callback returns no errors, and the JSON returned has `message`: `success`, but in my email activity, it says `Invalid SMTPAPI header`.

**Comment by richardpenner** [comment]
I've logged the headers here:
```
2015-05-20T15:01:29.152Z - info: Header: {
    "version": "1.1.0",
    "header": {
        "to": [
            "sinktest1@sink.sendgrid.com",
            "sinktest10@sink.sendgrid.com"
        ],
        "sub": {
            "%unsubscribe_link%": [
                "https://<redacted>",
                "https://<redacted>"
            ]
        },
        "unique_args": {},
        "category": [],
        "section": {},
        "filters": {},
        "send_at": 1432134300000,
        "send_each_at": [],
        "asm_group_id": {}
    }
}

**Comment by richardpenner** [comment]
I was sending milliseconds, not seconds. I have to say, just the smallest bit of documentation around the sendAt() method could have helped.

**Comment by eddiezane** [comment]
Appologies for the confusion and glad you were able to sort it out. I'll see about getting the docs spiffed up a bit.

**Comment by thierryskoda** [comment]
Hi Richard, I just posted an new issue with send_at. My send_at doesn't work and you will be very very nice if you could help me with that.. :( Thank you very much

**Comment by HemalR** [comment]
+1 on clarifying the documentation to be explicit about 'seconds' vs milliseconds.
Been bashing my head against the wall for a few hours wondering why my scheduled time of 3 minutes in advance (for testing purposes) kept throwing up an error 400 - 'Scheduling more than 72 hours in advance is forbidden'

Pages that a couple of edits will go a long way in helping:

1. https://sendgrid.com/docs/API_Reference/SMTP_API/scheduling_parameters.html
2. https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Cheers to OP for the thread that eventually let me figure this out!

**Comment by thinkingserious** [comment]
@HemalR,

I'm happy to make the updates to our documentation, but I'm not quite sure I understand the issue. The send_at field requires a unix timestamp given in seconds, as shown in the example. Could you give me an example of what the updated documentation would look like?

**Comment by HemalR** [comment]
Thanks @thinkingserious 

I guess it's because I'm beginner to the point of not recognising that the example digit was in seconds (what I had learned about Unix timestamps is that they are in ms). If I had to, I would simply put in:  '(in seconds)' in the documentation. Like this:

<img width="835" alt="docs" src="https://cloud.githubusercontent.com/assets/15634303/19812095/ccbcef04-9d66-11e6-9ea1-3f6ab9b79743.png">


That said, I recognise this may be an extremely silly suggestion and very obvious to most devs more experienced than me (this experience in itself has made it so that I am unlikely to ever make the same mistake again).

Cheers anyway!

**Comment by thinkingserious** [comment]
Thanks for the suggestion @HemalR!

Our docs are open source, would you like to make a PR? Otherwise, I'll go ahead and make the PR.

**Comment by HemalR** [comment]
I'll do the pull request. Never done one before (hence my procrastination)-
but it'll be a good learning experience.

I'll do it now.

Cheers

**Comment by thinkingserious** [comment]
Awesome, thanks!

<https://www.sendgrid.com>
Elmer Thomas
Developer Experience Engineer | Product

**Comment by tetreault** [comment]
sorry to bump the thread @thinkingserious but i was curious since I couldn't find it in the docs -- is there a max time the `sendAt` feature allows? for example if I wanted to programmatically send an email with the `sendAt` time set for 2-5 days from now?
