### ISSUE TITLE
Image attachments do not have 'inline' header when cid is specified

### ISSUE THREAD

**Issue by lloydho** [sendgrid/sendgrid-nodejs#171]
I am trying to inline several images attachments in my email. 

I am specifying the files as attachment like this:

    { 
        cid : attachment.cid,
        path : attachment.path,
    }

For some reason the Content-disposition is always set to `attachment` instead of `inline`.

    --B_3517325085_6981126
    Content-type: image/png; name="barChart-30044-51909.png";
     x-mac-type="504E4766"
    Content-ID: <barChart1>
    Content-disposition: attachment;
	    filename="barChart-30044-51909.png"
    Content-transfer-encoding: base64

This causes the image to always show up in the bottom of the email. Is there a way to set the Content-disposition to `inline`?

I am using the smtp api.

**Comment by eddiezane** [comment]
Could you please share what your `<img>` tag looks like?

This might help? http://stackoverflow.com/questions/30876416/sendgrid-use-attachment-on-body-with-sendgrid-php/30879400#30879400

**Comment by lloydho** [comment]
Here's an example:
    \<img class="bar-chart" alt="Log in to view daily revenue chart" src="cid:barChart1" width="410" style="margin-left: -11px;">

The Content-ID has a < > around it while the cid in the img src doesn't. Is this an issue? I don't believe we are adding the < > in the code.

**Comment by eddiezane** [comment]
I understand what you are experiencing but I can't seem to reproduce it. Is there anything else you can provide? Perhaps more of a code snippet?

The `< >` are expected.

```javascript
email.html = '<div>Our old logo:<img src="cid:logo-cid"></div><div>Our new logo:<img src="cid:new-logo-cid"></div>';

email.addFile({
  cid: 'logo-cid',
  path: './logo.png',
  filename: 'old-logo.png'
});

email.addFile({
  cid: 'new-logo-cid',
  path: './new-sendgrid-logo.png',
  filename: 'new-logo.png'
});

```

```
--===============0312220021873466787==
Content-Type: image/png
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-ID: <logo-cid>
Content-Disposition: inline; filename="old-logo.png"
X-Attachment-Id: logo-cid

...

--===============0312220021873466787==
Content-Type: image/png
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-ID: <new-logo-cid>
Content-Disposition: inline; filename="new-logo.png"
X-Attachment-Id: new-logo-cid
```

**Comment by lloydho** [comment]
I believe the only difference I can spot is that we are not setting a filename when adding a file. I will try when I get to a computer (am on a backpacking trip with only my phone right now).

**Comment by lloydho** [comment]
Still no luck after adding the filename.
Here's our code:

      // Create a collection of attachments
      attachments.push ({
        cid      : name,
        path     : absPath,
        filename : Path.basename(absPath)
      });

      // Replace the images with cid in the HTML.
      htmlAsString = stringHelpers.replaceAll(
        htmlAsString,
        absPath,
        'cid:'+name
      );

      // Send the email
      sendgrid = require('sendgrid')(config.username, config.password);

      // Click-tracking
      smtpapi = (new sendgrid.smtpapi()).setFilters({
        clicktrack : { settings : { enable : 1 }}
      });

      email = new sendgrid.Email(_.extend(messageOptions, {
        smtpapi,
        html     : htmlAsString,
        files    : attachments,
        fromname : messageOptions.fromName,
        bcc,
      }));

      sendgrid.send(email, callback);

**Comment by eddiezane** [comment]
Ah that's the issue. You need to be using our `email.addFile()` method since it turns it into a [FileHandler](https://github.com/sendgrid/sendgrid-nodejs/blob/master/lib/file_handler.js) and pushes that into the array.

Can you please modify and test that?

**Comment by lloydho** [comment]
Still not working, here's the updated code:

      images = [{ name: 'image1', absPath: '/path/to/img' }, ...]
      for (image in images) {
        // Create a collection of attachments
        attachments.push ({
          cid      : image.name,
          path     : image.absPath,
          filename : Path.basename(image.absPath)
        });

        // Replace the images with cid in the HTML.
        htmlAsString = stringHelpers.replaceAll(
          htmlAsString,
          image.absPath,
          'cid:'+image.name
        );
      }

      // Send the email
      sendgrid = require('sendgrid')(config.username, config.password);

      // Click-tracking
      smtpapi = (new sendgrid.smtpapi()).setFilters({
        clicktrack : { settings : { enable : 1 }}
      });

      email = new sendgrid.Email({
        smtpapi  : smtpapi,
        html     : htmlAsString,
        fromname : messageOptions.fromName,
        bcc      : bcc
      });

      # Add attachments
      _.forEach(attachments, function (attachment) {
        email.addFile(attachment);
      });

      sendgrid.send(email, callback);

**Comment by eddiezane** [comment]
Sorry, I just saw that we do that for you if you pass them in.

Let's get you on a support ticket since I'm unable to reproduce what you're seeing.

Can you please shoot me an email to my GitHub username [at] sendgrid.com with your SendGrid username?
