### ISSUE TITLE
`setSendAt` not working if using heroku addon "Starter" account 

### ISSUE THREAD

**Issue by codynguyen** [sendgrid/sendgrid-nodejs#172]
Hi,

I'm having an issue where `setSendAt` works (emails are scheduled correctly as programmed) when using a Sendgrid account that I manually registered from the Sendgrid website, but fails (emails are sent instantly instead of being scheduled) if using a Sendgrid account taken from a heroku app with "Starter" Sendgrid addon. 

I've tried this many times using different heroku apps / addons but the problem still exists so I think there's some limitations in the Sendgrid Starter addon accounts. However there doesn't seem to be any online documents regarding this matter.

Below is the code snippet I'm using (in my ExpressJS project):

```
var email = new sendgrid.Email({
  to: user.email,
  from: 'hello@me.com',
  subject: 'Welcome to XXX!',
  html: _.template(data)({request: req})
});
email.setSendAt((Date.now() / 1000) + (60 * 60 * 24)); // Delay 24 hours
sendgrid.send(email, function(err, json) { });
```

Please let me know if my suspicion is right. Thanks!

**Comment by eddiezane** [comment]
Apologies for the inconvenience. I've reached out to the product owner to see if this is intended and will update you what I learn.

**Comment by johnvajda** [comment]
Hi. Have you tried setting the date.now value to be a Unix Time Stamp? That is the correct format we look for when setting send at messages in our email queues.

**Comment by eddiezane** [comment]
You may need to wrap it in a `Math.floor()` call because it's not an integer.

```javascript
(Date.now() / 1000) + (60 * 60 * 24)
1435774356.462
```

Will do some testing.

**Comment by eddiezane** [comment]
Hey @codynguyen,

Just wanted to let you know that I've replicated what you are seeing. We are looking into it. Appologies for the delay and hassle.

In the meantime, please use a non Heroku SendGrid account for scheduled sending.

**Comment by codynguyen** [comment]
@eddiezane Thank you! I asked the sendgrid support team on Heroku to help and they fixed the account in trouble some time ago, and I totally forgot about this issue here in Github. 

However the problem seems to happen to all heroku-addon Sendgrid accounts, so a complete fix would be much appreciated!

**Comment by siboulet** [comment]
Any update on this? Just stumbled into that same issue on our production environment and having some difficulty getting the SendGrid support to help.

**Comment by thierryskoda** [comment]
Same here

**Comment by thinkingserious** [comment]
Hello Everyone,

I believe this issue is now resolved. If not, please feel free to reopen this issue.

With Best Regards,

Elmer
