### ISSUE TITLE
Sendgrid-mustacher

### ISSUE THREAD

**Issue by thebergamo** [sendgrid/sendgrid-nodejs#176]
Hello!

I'm develop a module that can help us to using sendgrid module to send batch emails and using a template engine for customising any new email.

I would this module is useful =D

https://www.npmjs.com/package/sendgrid-mustacher

**Comment by eddiezane** [comment]
This does look pretty cool! Thanks for sharing! We should get this added to the docs /cc @mbernier

**Comment by mbernier** [comment]
Thanks! I added it to the list of updates to make.

**Comment by thebergamo** [comment]
Ideas to improve are very welcomed!
