### ISSUE TITLE
Error: Empty from email address (required)

### ISSUE THREAD

**Issue by guy-codefresh** [sendgrid/sendgrid-nodejs#178]
I'm using the latest npm module version and when I try, even the simplest test, I'm getting the following error:
Error: Empty from email address (required)

This is the example code we are testing.
Up until few days ago all was working

var sendgrid = require("sendgrid")(API_KEY);

sendgrid.send({
    to:       'example@example.com',
    from:     'other@example.com',
    subject:  'Hello World',
    text:     'My first email through SendGrid.'
}, function(err, json) {
    if (err) { return console.error(err); }
    console.log(json);
});

**Comment by eddiezane** [comment]
It looks like the upstream dependency [request](https://github.com/request/request) was updated today. Pinning it to the previous version `2.58.0` fixes things. Will roll out a new version locking it there until we can figure out what's up.

**Comment by eddiezane** [comment]
I just released version `1.9.1` with a pinned request version below `2.59.0`. Will need to figure out what changed and write a better test to catch it.

Sorry for any trouble this caused you.

**Comment by eddiezane** [comment]
It looks like the `_send` method needs to be rewritten. It was originally created to build out `req.form()` before the next event loop pass.

From the docs
> For advanced cases, you can access the form-data object itself via r.form(). This can be modified until the request is fired on the next cycle of the event-loop. (Note that this calling form() will clear the currently set form data for that request.)

It seems that the `content-type` is now not set when doing this via https://github.com/request/request/pull/1650.
