### ISSUE TITLE
add an array dynamically to cc

### ISSUE THREAD

**Issue by amitpanchall** [sendgrid/sendgrid-nodejs#181]
[Error: Invalid email address amitpanchall81@gmail.com,vaibhav.oza@landmarkindia.net] 'amitpanchall81@gmail.com,vaibhav.oza@landmarkindia.net'

my code is below :

function NS_lockLoginpwd() {
    //var params = ['amit.panchal@landmarkindia.net', 'this is testmail', 'amit.panchal@landmarkindia.net', 'Test Subject'];
    mssql.query('EXEC dbo.NS_lockLoginpwd', {
        success: function(results) {
            //["amitpanchall81@gmail.com","vaibhav.oza@landmarkindia.net"]
            SendMail(results[0].ToMail, results[0].cc);
        },
        error: function(err) {
            console.log(err);
        }
    });

}

function SendMail(to, cc) {
    var sendgrid = require('sendgrid')('username', 'password');
    var email = new sendgrid.Email({
        //to: ["amit.panchal@landmarkindia.net","vaibhav.oza@landmarkindia.net"],
        //cc:["amitpanchall81@gmail.com","vaibhav.oza@landmarkindia.net"],
        to: to,
        cc: cc
        from: 'lissupport@landmarkindia.net',
        subject: 'Subject goes here',
        html: 'Hello world'
    });
    sendgrid.send(email, function(err, json) {
        if (err) { return console.error(err); }
        console.log(json);
    });
}

however i will put the static string to SendMail function which is commented. it will be send mail successfully... i will try it to push into array but not working.
![screenshot_1](https://cloud.githubusercontent.com/assets/7031020/9038122/71f0c30e-3a0f-11e5-89f3-08670e6a6027.png)

Please help me..
I m using this in azure mobile service scheduler.

Error logs below:

**Comment by thinkingserious** [comment]
Hello @amitpanchall,

Thank you for reporting this issue to us!

This library will be replaced with this one in a few weeks: https://github.com/sendgrid/sendgrid-nodejs/tree/v3beta. It uses the v3 /mail/send endpoint https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html which should make this process easier. Please see this example: https://github.com/sendgrid/sendgrid-nodejs/tree/v3beta/examples/helpers/mail

Thanks for your support!

With Best Regards,

Elmer
