### ISSUE TITLE
Module returns success every time even on fail.

### ISSUE THREAD

**Issue by yanosh-igor** [sendgrid/sendgrid-nodejs#182]
Hi there,
We are using this module, it works good, but last 2 weeks(from 23 July) we have noticed that when we make sendgrid.send(email, function(err, json) {} we received error: null, json:  { message: 'success' }
but some emails doesn't sent at all and doesn't displayed on sendgrid site(statistics).

I've tested for same user sent same email 5 times and receive only 3 emails. Every 5 times I've got response { message: 'success' }. On sendgrid site also displayed only 3 emails.

Could you please check this issue. Maybe you can suggest something.
Feel free to ask about additional information. 
Sendgrid support also notified about this issue.

PS: tried versions 1.8.0 and 1.9.2

**Comment by mbernier** [comment]
Please check your email stats to make sure some of the emails were not dropped.

**Comment by yanosh-igor** [comment]
Yes, I've checked. Its only displays 3 emails that was processed.
that 2 emails even was not listed on sendgrid at all.

**Comment by mbernier** [comment]
My suggestion would be to reach out to the support team - support@sendgrid.com and they can help you figure out what's happening!
