### ISSUE TITLE
Modifying Object.prototype causes Sendgrid to crash/cause unexpected behavior

### ISSUE THREAD

**Issue by analytalica** [sendgrid/sendgrid-nodejs#183]
In my app, I've found that any modification to `Object.prototype` causes `sendgrid` to fail or produce unexpected behavior. At first I thought it was simply a namespacing issue, but it turns out any new properties attached to the `Object.prototype` object will cause issues. I've managed to reproduce the issue with a minimal amount of code:

Consider the following code, which works fine (API key has been hidden, replaced with `my-api-key`):

    var sendgrid = require('sendgrid')('my-api-key');

    sendgrid.send(new sendgrid.Email({
        to: 'test@test.com',
        from: 'destination@test.com',
        subject: 'test mail',
        html: 'test body',
    }), function(err, json) {
        if(err) console.log(err);
        console.log(json);
    });

Result: `{ message: 'success' }`

Now consider the same code with a slight modification:

    var sendgrid = require('sendgrid')('my-api-key');

    Object.prototype.myNewCustomFunction = function () {};

    sendgrid.send(new sendgrid.Email({
        to: 'test@test.com',
        from: 'destination@test.com',
        subject: 'test mail',
        html: 'test body',
    }), function(err, json) {
        if(err) console.log(err);
        console.log(json);
    });

Result: 

    { [Error: socket hang up] code: 'ECONNRESET' }
    null

I'm using sendgrid `1.9.2` on node `0.12.7`.

**Comment by thinkingserious** [comment]
Hello @analytalica,

Thank you for the detailed report!

This library will be replaced in a few weeks with this one: https://github.com/sendgrid/sendgrid-nodejs/tree/v3beta

If you still experience this issue with the new library, please open a new issue.

With Best Regards,

Elmer
