### ISSUE TITLE
Best way to send a large volume of emails?

### ISSUE THREAD

**Issue by pensierinmusica** [sendgrid/sendgrid-nodejs#184]
Let's say I have a long list of email addresses, for example 10 or 100 M, and I need to bulk send the same email to all of them using SendGrid's API and NodeJS.

- What is the best way to do it?
- How can I estimate how long it should take to complete the job?
- How can I be sure that the process is completed, or if there are any issues along the way it can resume from where it stopped? 

Thanks!

**Comment by thinkingserious** [comment]
Hello @pensierinmusica,

I suggest you reach out to our support team for guidance: https://www.sendgrid.com

Thanks for your support!

With Best Regards,

Elmer
