### ISSUE TITLE
Instances of .Email() object isn't being updated properly

### ISSUE THREAD

**Issue by dransk** [sendgrid/sendgrid-nodejs#185]
Back on version 1.8.0 the following code worked as supposed when requested for multiple users.

var email = new sendgrid.Email(); //this variable is global
email.from = mail;

exports.sendWelcome = function(data,callback) {
  var self = email;

  self.to = data.to;
  self.html = "&nbsp;";
  self.subject = data.subject;
  self.addSubstitution('-name-',data.actorName);
  self.addFilter("templates","enable",1);
  self.addFilter("templates","template_id",templateId);

  sendgrid.send(self,function(err,json) {
    if(err) {
      callback(err);
    }else {
      callback(null);
    }
  });
}

With the current 1.9.2 version it no longer works. The second email, despite having the data.actorName, is being sent with the previous value from the first email.

In order to get it working we had to force it to create a new instance of .Email().

function createEmail() {
  var email = new sendgrid.Email();
  email.from = mail;
  return email;
}

exports.sendWelcome = function(data,callback) {
  var self = createEmail();

  self.to = data.to;
  self.html = "&nbsp;";
  self.subject = data.subject;
  self.addSubstitution('-name-',data.actorName);
  self.addFilter("templates","enable",1);
  self.addFilter("templates","template_id",template_id);

  sendgrid.send(self,function(err,json) {
    if(err) {
      callback(err);
    }else {
      callback(null);
    }
  });
}

**Comment by thinkingserious** [comment]
@dransk,

Thanks for reporting this issue and workaround, we appreciate it!

This library is about to be replaced with this one in a few weeks: https://github.com/sendgrid/sendgrid-nodejs/tree/v3beta. The issue you are experiencing should not happen with the new version.

Thank you for your support!

With Best Regards,

Elmer
