### ISSUE TITLE
Fix README mistype

### ISSUE THREAD

**Issue by XEuRoMAN** [sendgrid/sendgrid-nodejs#189]
```
email.addHtml('<div>Our logo:<img src="cid:the_logo"></div>');`
```

`addHtml` function does not exist it must be `setHtml` instead.

**Comment by csaroff** [comment]
Based on the other sections of the README, this looks correct.  Are you guys going to pull in the associated PR or what?  This is still broken in the README two months after the issue was opened and a PR was submitted.

**Comment by thinkingserious** [comment]
Hello @csaroff,

Please see https://github.com/sendgrid/sendgrid-nodejs/issues/190 for an update.

Thanks!
