### ISSUE TITLE
Permission denied, wrong credentials

### ISSUE THREAD

**Issue by rubenstolk** [sendgrid/sendgrid-nodejs#191]
I'm getting this error randomly when I'm sending an attachment using `filename`. If I set `filename` to something short like `export.csv` the error does not occur but if it is a bit longer than that, it randomly fails.

Anyway the error is incorrect and very confusing to me as a developer, I'm very sure that the credentials are always correct.

**Comment by jackson-sandland** [comment]
I'm having the same issue using the SendGrid API, and a go email service. I'm positive I'm using the correct key.

**Comment by tushdante** [comment]
Hey @rubenstolk @jackson-sandland . Can you send me the exact steps to replicate the issue so we can get this figured out?

**Comment by RazvanMaris** [comment]
Did anyone find a solution?

**Comment by thinkingserious** [comment]
@RazvanMaris,

If you have this issue, please contact us at https://support.sendgrid.com

Thanks!

**Comment by RazvanMaris** [comment]
I already did: https://support.sendgrid.com/hc/en-us/requests/693844. Thank you!
