### ISSUE TITLE
sender header question

### ISSUE THREAD

**Issue by andyhol** [sendgrid/sendgrid-nodejs#193]
HI,

We are developing a node.js script to send our emails in behalf of our clients 
We do not control the domain used in the from and reply to .. they are our customers and they will not allow us to make changes and its not an option to have them make those changes
I want to add a sender header inside our emails using one of our domains
this will sign all emails even if the from and reply to are from different domains to the sender one
for example .. we are sending with the following :
from me@domain.com
reply to me@domain.com
However these emails will be sign with  my own domain where I can be sure that spf, dkim are ok
I have seen that headers can be added when using node.js library
this feature is also added .. for a sender header ?
this is present on many sending software's out there .. and I know it can be added in php and other languages

**Comment by thinkingserious** [comment]
Hello @andyhol,

Please reach out to our support team at https://support.sendgrid.com.

Thanks!

Elmer
