### ISSUE TITLE
Can't install v2 using npm

### ISSUE THREAD

**Issue by danielcrisp** [sendgrid/sendgrid-nodejs#194]
`npm install sendgrid` is still installing v1.9.2.

I think maybe you need to push a new tag

**Comment by danielcrisp** [comment]
`npm install sendgrid/sendgrid-nodejs` works

**Comment by jaderabbit** [comment]
Doesn't look like a release has been done

**Comment by thinkingserious** [comment]
Thanks for sharing the solution @danielcrisp!

The new version of this library is quickly approaching: https://github.com/sendgrid/sendgrid-nodejs/tree/v3beta
