### ISSUE TITLE
No npm release to reflect the new version update

### ISSUE THREAD

**Issue by csaroff** [sendgrid/sendgrid-nodejs#196]
I saw that the README has been updated to explain breaking changes to the API with the new 2.0 release of sendgrid-nodejs.  Unfortunately, the npm repository is still on version 1.9.2.

Please create a new 2.0 release in npm so that users may simply `npm install sendgrid`

**Comment by JordanAdams** [comment]
+1 I was literally stuck with a bug for an hour because of this :angry:

**Comment by thinkingserious** [comment]
Thanks to @csaroff and @JordanAdams for bringing this to our attention, we greatly appreciate it!

I have made the necessary updates.
