### ISSUE TITLE
setSendAt is not working

### ISSUE THREAD

**Issue by thierryskoda** [sendgrid/sendgrid-nodejs#197]
Hi,

I'm using this in my app 
```
var email = new sendgrid.Email({
      to:   'example@example.com'
      from:     'me.com',
      subject:  'Title'
})

email.setSendAt(Math.round((Date.now() / 1000) + (60 * 60 * 24 * 4)))      

    console.log("going to send the promo email");
    sendgrid.send(email, function(err, json) {
      if (err) { return res.status(500).end(); }
      console.log("json email promo response ->", json);
      res.status(200).end();
  })
```

I receive the response "Success" in my callback but when I go see in my Sendgrid dashboard activity, The mail is tagged as "Drops" and it says "REASON: Invalid SMTPAPI header".

Thank you very much for all the help.

**Comment by thierryskoda** [comment]
It works when  I put simple timestamp like : 1447700363. But it does not work with  :Math.round((Date.now() / 1000) + (60 * 60 * 24 * 4))  ... :(

**Comment by richardpenner** [comment]
@thierryskoda I'm trying and failing to find where I read this, but I believe `send_at` may not support scheduling 4 days in advance. Have you tried just 24 hours?

**Comment by thierryskoda** [comment]
I never tried, but I think I've might found something ! I now use moment.js and create unix timestamp with this library. It seems to work for now. 

But Thank you !

**Comment by thierryskoda** [comment]
It is not working .. :(. I once tried 7 adds later and it worked and now i'm using 4 days and it isn't .. :(

**Comment by richardpenner** [comment]
This works for me:
```
    var email = new sendgrid.Email({…});
    var sendDate = new Date();
    var unixTimestamp = (0+sendDate.getTime()) / 1000;
    email.setSendAt( unixTimestamp );
```

**Comment by thierryskoda** [comment]
What is the "0" in  (0+sendDate.getTime()) ?

**Comment by richardpenner** [comment]
oh, just remnants of a sloppy refactor; ignore that: `sendDate.getTime() / 1000` should do it.

**Comment by thierryskoda** [comment]
Oh okay I understand. But what if I want to send my email 4 days or 5 days later ? :O

**Comment by thierryskoda** [comment]
Because I can send the email now. It works. But it's when I try to add days that it doesn't work.. :( Here is what I have now : 

```
var now = moment();
    now.add(4, 'days');
    var unix = now.unix();
    email.smtpapi.header.send_at = unix;
```


But this doesn't work .. :(

**Comment by richardpenner** [comment]
You can modify your date variable (most easily using moment.js), but as stated earlier, I don't think SendGrid supports scheduling more than 24 hours in advance. Admittedly I can no longer find that in their documentation, but if you're having an issue, dial it down to say 6 hours, then try 12…

**Comment by thierryskoda** [comment]
Okay I will try ! thank you ! :)

**Comment by thinkingserious** [comment]
Hello @thierryskoda,

If you continue to have trouble with the timing, please reach out to our support team at https://support.sendgrid.com.

Thanks!

Also, thanks @richardpenner for your help!

With Best Regards,

Elmer
