### ISSUE TITLE
Adding css files to email html body

### ISSUE THREAD

**Issue by sabachanna** [sendgrid/sendgrid-nodejs#199]
Is there any way to add css file to give style to the email body. We can give HTML to email body using setHTML() I want to give css files for this HTML too. Is there any way?

**Comment by thinkingserious** [comment]
Hello @sabachanna,

Have you tried using inline CSS? Or our template feature: https://sendgrid.com/docs/User_Guide/Transactional_Templates/index.html

Thanks!

Elmer

**Comment by dandv** [comment]
@thinkingserious: I think the OP was referring to actually inlining CSS, e.g. [as Sparkpost does](https://www.sparkpost.com/blog/automatic-css-inlining-sparkpost/).

Does Sendgrid have an equivalent feature?
