### ISSUE TITLE
Add support for new Marketing Campaigns API

### ISSUE THREAD

**Issue by heitortsergent** [sendgrid/sendgrid-nodejs#202]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/index.html

**Comment by thinkingserious** [comment]
Hi @heitortsergent,

We have added this to the roadmap. Our goal is to fully implement all Web API v3 endpoints across all libraries.

Please keep a look out for a v3_beta branch.

Thanks!

**Comment by heitortsergent** [comment]
Awesome, thanks @thinkingserious :D
