### ISSUE TITLE
addSubstitution multiple recepient issue

### ISSUE THREAD

**Issue by ivanrkv** [sendgrid/sendgrid-nodejs#203]
Hello guys,
Great job on the project. 

Noticed one small bug, or maybe my stupidity. 
When having multiple recipients, for some reason, add subStitution only substitutes the placeholders in the first email, with the consecutive emails being substituted with blank space. 

So let's say I have a SendGrid template with a [test] tag.

"This email is coming from [test] and notifies you of absolutely nothing".

    var email = new sendgrid.Email();
    email.addTo('user1@email.com');
    email.addTo('user2@email.com');
    email.subject = "Blah";
    email.text = ' ';
    email.html = ' ';
    email.from = 'system@email.com';
    email.fromname = 'Some Service';
    email.addFilter('templates', 'enable', 1);
    email.addFilter('templates', 'template_id', 'xxxxx--x-x-xxx-sometemplate');
    email.addSubstitution('[test]', 'abc123');
    
    sendgrid.send(email, function(err, json) {
    });

This results in user1 properly receiving an email saying "This email is coming from abc123 and notifies you of absolutely nothing", while user2 receives an email with [test] subbed by a space, so "This email is coming from and notifies you of absolutely nothing".

Any idea what could be causing this?

**Comment by wbzgatsby** [comment]
it's the same issue as #192 .. The team should fix this asap..

**Comment by thinkingserious** [comment]
Will resolve in issue #192
