### ISSUE TITLE
file.filename is required even when providing url

### ISSUE THREAD

**Issue by id0Sch** [sendgrid/sendgrid-nodejs#205]
Hi,
iv'e been trying to send an email with an inline image,
as the documentation states i should do

```
email.addFile({
                url: image,
                cid: 'customer-image-url'
            });
```
however this didnt work and the image was not attached,
when debugging sendgrid.js iv'e noticed that form.files was form.files[undefined] (sendgrid.js line:97)

**Comment by thinkingserious** [comment]
Hello @id0Sch,

This functionality has changed in the new version of this library, which is set to get out of beta in a few weeks. Here is an example using the new library: https://github.com/sendgrid/sendgrid-nodejs/blob/v3beta/examples/helpers/mail/example.js#L67

With Best Regards,

Elmer
