### ISSUE TITLE
Styles in templates not working

### ISSUE THREAD

**Issue by sydcanem** [sendgrid/sendgrid-nodejs#208]
I had set inline styles in my templates but it won't appear when email is sent through this library. But inline styles are applied when doing "Send Test" in sengrid dashboard.

Any help is appreciated. Thanks.

**Comment by sydcanem** [comment]
It's good to mention in the readme that setting only the text (setText) without setting the html (setHtml) will only send text version of the email.

**Comment by thinkingserious** [comment]
Thanks for the feedback! We'll get the README updated.
