### ISSUE TITLE
Difficult to stub send() for testing

### ISSUE THREAD

**Issue by deaks-kt** [sendgrid/sendgrid-nodejs#212]
Due to the fact that the send() function is not a prototype function of Sendgrid, I am having difficulty making a stub of it for testing without exposing the object instance created by the application.

I was wondering if I am missing something and there is another way to accomplish this?

**Comment by udaka** [comment]
I have the same issue, and since require('sendgrid') needs api-key argument and call the constructor again it makes it even more difficult to create stubs.
Is there a way to create the instance first and then set the key later (when my config object is loaded)?
like:
       sendgrid = require('sendgrid')();
       ... // later
       sendgrid.setAPIKey(xxx);

**Comment by deaks-kt** [comment]
Hi @udaka. Actually you can use it as you want and set the API after the `require` e.g.:

```
var Sendgrid  = require('sendgrid');
...
var mail = Sendgrid(<API KEY>);
...
mail.send(.....);
```

**Comment by thinkingserious** [comment]
Thanks for the support @deaks-kt!

Were you able to create the stub you needed for testing?

**Comment by udaka** [comment]
Had to write a wrapper around sendgrid to achieve what I wanted and its fine now, thanks!

**Comment by thinkingserious** [comment]
Awesome, thanks for the follow up!
