### ISSUE TITLE
Question: WebAPI support

### ISSUE THREAD

**Issue by renarsvilnis** [sendgrid/sendgrid-nodejs#214]
Hi,
With the current state of the library is it possible to call Web API endpoints? For example creation of a a mailing list recipient at [`v3/contactdb/recipients`](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Add-Recipients-POST). I don't see any documentation on the library covering it.

Thanks,
Renārs

**Comment by thinkingserious** [comment]
We are working on an update that will allow you to access all of the Web API v3 endpoints. Please keep an eye on this repo for updates.

Thanks!

**Comment by renarsvilnis** [comment]
Great to hear, can't wait.
