### ISSUE TITLE
Substitutions bug

### ISSUE THREAD

**Issue by kas84** [sendgrid/sendgrid-nodejs#215]
I'm using the library to send an email template with substitutions for several recipients. In this case, substitutions are only achieved for the first recipient, not for others.

I've looked through the forums and I've seen a hack by a C# developer so I translated it into JS adding substitutions 'n' times, being 'n', the number of recipients, which I think the API should take care of.

**Comment by thinkingserious** [comment]
Thank you for taking the time to report this issue! We have added it to our backlog.

**Comment by leobudima** [comment]
+1

**Comment by thinkingserious** [comment]
@kas84, @leobudima,

Please follow issue #192, thanks!
