### ISSUE TITLE
Error when passing JS date object in email JSON (node sendgrid v1.9.2)

### ISSUE THREAD

**Issue by krunkosaurus** [sendgrid/sendgrid-nodejs#218]
Starting this morning 4/1/2016 both our QA and production servers stopped being able to send emails. We got a very generic "Unexpected error" in the return JSON from Sendgrid.

It took us about 2 hours to track down the issue and it was resolved when we removed `date: new Date()` in the email json we send Sendgrid. We've had this in our code for several years with no issue. We are using Sendgrid Node library version 1.9.2

This ticket is to help other who may be experiencing the same issue. Perhaps better error messaging when the Sendgrid servers get this date obj would be appropriate.

We are running Node 0.10.4 if that helps. (Yeah we haven't touched this code in years)

**Comment by thinkingserious** [comment]
Thank you for the error report!

We have added this to our backlog for further investigation.

For my own notes:

Seems like our internal data representation has changed (guessing it's on the API side): https://github.com/sendgrid/sendgrid-nodejs#setdate

**Comment by thinkingserious** [comment]
I'm passing this along to our support team.
