### ISSUE TITLE
How to iterate array of objects in Sendgrid template?

### ISSUE THREAD

**Issue by sabapk** [sendgrid/sendgrid-nodejs#221]
Mandrill provides support for Handlebars template and so looping is supported. As I read, Sendgrid doesnot support `each` like directive. So how do the sendgrid users tackle this shortcoming?

I want to loop through the products, as shown in below object.

```
products:
[ { name: 'VEEBA SWEET CHILLI SAUCE 1KG',
   qty: 2,
   price: 145,
   packSize: '1 KG',
   itemSubTotal: 290,
   comments: null },
 { name: 'Chilled French Fries',
   qty: 1,
   price: 85,
   packSize: '1 KG',
   itemSubTotal: 85,
   comments: null } ]
```

**Comment by thinkingserious** [comment]
Hello @sabapk,

Please open a ticket at https://support.sendgrid.com. Thanks!

**Comment by adamreisnz** [comment]
is this supported yet by the templating engine?

**Comment by thinkingserious** [comment]
@adamreisnz,

I'm checking with our product team for an update, thanks!

**Comment by thinkingserious** [comment]
@adamreisnz,

This is on our radar for implementation, but there is no estimate on timeline yet.

**Comment by adamreisnz** [comment]
Ok thanks for the update. I guess a work around would be to generate the looped HTML manually and pass that in as a substitution. Crude, but it would work.

**Comment by eupharis** [comment]
@thinkingserious I am subscribed to this issue. Is there another way I could subscribe for notifications about for loop implementation in sendgrid templates?

**Comment by thinkingserious** [comment]
Hello @eupharis,

Please make sure the email you have in your SendGrid account settings is up to date. We send product announcements to that email address.

Thanks!

Elmer

**Comment by free4ride** [comment]
Hi @thinkingserious 
What is status of this issue?
When is it coming live? 

marcin

**Comment by thinkingserious** [comment]
Hi @free4ride,

There is still no estimate on timeline yet.

The best option to be notified of any updates on this issue is to make sure the email you have in your SendGrid account settings is up to day.

Thanks!

Elmer

**Comment by davidhagg** [comment]
As @adamreisnz commented, sending the array in as a HTML might work, however we are experiencing problems with the substitutions being too large, exceeding 10000 bytes

**Comment by stephengardner** [comment]
Sendgrid, I thought, was a pretty good alternative to Mandrill.

No looping?

That's actually ridiculously surprising from such a large service....

It's impossible to even create a checkout order success form, because you need to loop through the items purchased and display them.

Oh well, another one down.

**Comment by thinkingserious** [comment]
Hello @stephengardner,

Have you tried using substitutions with our templates? [Check this out](https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#transactional_templates).

If that does not fit your need, let me know and I'll try to figure out how to help you achieve the results you need.

Thanks!

With Best Regards,

Elmer

**Comment by adamreisnz** [comment]
Substitutions don't work for listing a table of purchased products for example, because they can only replace one value, and not an array of values, let alone an array of objects with more detailed values.

What we need is support to loop through products and have a template for each product that then gets repeated depending on how many products you supply for the substitution.

The only way around it is kind of half-baked -- you'd have to generate the HTML on the server, and send that whole chunk of HTML as a single substitution. Clearly that is not ideal as you then have part of the layout sitting in server side code instead of nicely in the online template where designers can edit it.

**Comment by thinkingserious** [comment]
Thanks @adamreisnz,

I have reached out to the product team that owns this functionality. I will update this thread when I learn more.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hi @stephengardner, @adamreisnz,

Your votes have been added to give this feature higher priority for implementation.

Please make sure the email you have on file for your account is up to date, that is how we would notify you of the implementation of the feature.

With Best Regards,

Elmer

**Comment by psavard** [comment]
I would like to vote up this feature too. This is a must for you system.

Thanks ;)

**Comment by free4ride** [comment]
Completely agree. Up-vote from me and my team! Please add this feature asap.

**Comment by thinkingserious** [comment]
Thanks @free4ride, your vote has been added.

**Comment by eupharis** [comment]
+1! Iterators would be awesome!!

**Comment by thinkingserious** [comment]
@arg20, @eupharis,

Your votes have been counted, thanks!

**Comment by MaxShv** [comment]
Any ETA on this?

**Comment by etyp** [comment]
@thinkingserious any update on this? We're likely to move off of Sendgrid in the coming week if there's no affirmative movement on it. We can't afford to compromise the quality of our emails because a standard feature like this isn't supported by a large service.

**Comment by thinkingserious** [comment]
Hi @MaxShv, @etyp,

I have added your votes and passed this additional feedback to our product team.

I don't have any new insights into the progress on this, but once I do find that there is movement, I will update this thread.

With Best Regards,

Elmer

**Comment by 9mm** [comment]
The fact you don't have this is a complete a utter joke.

**Comment by thinkingserious** [comment]
You vote has been added @9mm, thanks!

**Comment by futhr** [comment]
Hi @thinkingserious, thanks for a great service, what is the progress of this? You would be so much more awesome if you can add e.g. Handlebars support without forcing your clients to use an external webhook service like Sendwithus.

Thanks

**Comment by 9mm** [comment]
Everyone in this should just use https://www.sendwithus.com 

I ended up getting tired of waiting and SWU is amazing, it lets you do everything you could ever want in a template and more.

It is slightly expensive though but exceeds my expectations.

**Comment by thinkingserious** [comment]
Thanks for the suggestion, @9mm, SendWithUs is amazing and a [solid partner](https://support.sendwithus.com/esp_accounts/connect_sendgrid/).

I also have some exciting news for everyone on this thread (well, at least I think it's exciting :)). In just a few short weeks, we're about to get started on how best to implement this feature. 

If you would like to be part of the discussion for the templates functionality, Matt Bernier our Developer Experience Product Manager is digging into customer needs about templates. Please sign up for a time here https://calendly.com/matt-bernier/template-conditionals.

I can't wait! Thanks again for taking the time to voice your concerns to help this issue gain priority, I really appreciate it!

With Best Regards,

Elmer

**Comment by adamreisnz** [comment]
Great news, I've signed up for a chat.

We definitely need template iteration, but I think it would be even better (and simpler!) if Sendgrid were to support Handlebars templates. Then there's no need to reinvent the wheel!

**Comment by mbernier** [comment]
I am excited to chat with anyone who has some ideas or opinions on the templates. We need your feedback!!

**Comment by kardamom** [comment]
I need loops as well - is there a ticket I can track, vote for? I can't see how to find other people's tickets in the support interface.

Many thanks

**Comment by thinkingserious** [comment]
Hello @kardamom,

Your comment on this thread counts as a vote and any updates will be posted here.

Thanks!

With Best Regards,

Elmer

**Comment by mbernier** [comment]
@etyp thank you so much for the feedback and information on template logic! If you go here, https://dx.sendgrid.com/swag, you can grab some swag as our thanks for your time.

**Comment by ameesme** [comment]
Also waiting on this. Implementing Sendgrid in our platform has been troublesome to say the least, with the lack of basic functionalities like this or the excessively complicated structure of the old nodejs-module. It's kind of silly having to chain multiple templating-engines.

**Comment by mbernier** [comment]
@futhr, @hf2186, @katehlee  Please click the following link to get your swag, we really appreciate your feedback about this! https://dx.sendgrid.com/swag 

For anyone else who is interested, please feel free to grab a time on my calendar at the link above.

**Comment by mbernier** [comment]
@ameesme we are collecting feedback about template conditionals right now, so that we are building the right thing.

**Comment by adamreisnz** [comment]
Great chat last week with @mbernier and @ben-grid about templates and various use cases for iteration and conditionals etc. Hopeful that support for template iteration will be implemented in the near future! 😃

**Comment by kylemantesso** [comment]
@mbernier unfortunately its a bit hard to book a time with Matt to give feedback, because of the different time zone, but happy to provide more info over email if you have any specific questions... 

We really need this feature to continue using SendGrid, which has otherwise been a great product.

**Comment by dmorrow** [comment]
Here to cast my vote for conditionals and iterating.  I've set up a time to chat with @mbernier

**Comment by arg20** [comment]
Support for something like handlebars would be amazing.

**Comment by mbernier** [comment]
@ameesme Thanks again for your feedback! Please grab some swag here: https://dx.sendgrid.com/swag !

**Comment by mbernier** [comment]
@dmorrow Thanks to you too for the feedback, friend. Check out https://dx.sendgrid.com/swag for some stuff.

**Comment by mbernier** [comment]
@kylemantesso my email is just my username here at sendgrid.com - hit me up

**Comment by ameesme** [comment]
Thanks a lot @mbernier. Really cool of you guys! :)

**Comment by thinkingserious** [comment]
@ameesme,

Could you please send your zip code over to dx@sendgrid.com? Thanks!

**Comment by kurtisdavis** [comment]
We need to have this loop feature as well. We're using SendGrid for mostly everything,but are still using a different vendor for this functionality. Seems like a fairly simple feature to implement. Please let us know updates on this feature as they come available.

**Comment by thinkingserious** [comment]
Hello @kurtisdavis,

If you would like to be part of the discussion for the templates functionality, Matt Bernier our Developer Experience Product Manager is digging into customer needs about templates. Please sign up for a time here https://calendly.com/matt-bernier/template-conditionals.

With Best Regards,

Elmer

**Comment by kamelsalah** [comment]
@thinkingserious What's the status of this feature ?
Can you please confirm if it has a due date or anything like that ?
We here at Atypon use SendGrid for millions of emails but we can't yet use the templates due to its limitations !!
Using vm templates functionalities within your templates would be a great solution to solve all you problems, as the guys mentioned above you don't have to reinvent the wheel ! Thank you.

**Comment by thinkingserious** [comment]
Hello @kamelsalah,

This feature is currently under development. If you would like to have a voice and learn more, please setup a time to meet with our Developer Experience Product Manager, Matt Bernier: https://calendly.com/matt-bernier/template-conditionals

Thanks!

With Best Regards,

Elmer

**Comment by mbernier** [comment]
@kamelsalah Thanks you for the feedback! Check out https://dx.sendgrid.com/swag :)

**Comment by mbernier** [comment]
Thank you @capecoder, thank you for the call this morning! Please check out  https://dx.sendgrid.com/swag for a SendGrid t-shirt :)

**Comment by mbernier** [comment]
Hey, everyone! 

We're close!! As a last step, we want to ask you questions about the specific steps you will take to move from a current "transactional template" to include support for handlebars. 

If you are available and are currently using our transactional templates, could we please chat about migrating templates? If so, please grab a time on the following calendly link from our designer, Travis, and Product Manager, Ben. https://calendly.com/travisterwilligar/templates



Thank you!

**Comment by kjanoudi** [comment]
@mbernier just wondering, is this solution being worked on at the API level or at the nodejs package level?

**Comment by adamreisnz** [comment]
@kjanoudi at the API level from what I understand, so not just for Node.

**Comment by ben-grid** [comment]
Just to confirm, @adamreisnz is correct. It will be available via SendGrid Templates, for all languages. (I am the other SendGrid PM working on this w/ @mbernier )

**Comment by OwlLaboratory** [comment]
Hi,
I have just discovered your service and i'm very interested but i want to know if you have a release date for this feature ?
Thanks ;)

**Comment by mamartins** [comment]
Hello,

What is the current status of this feature? We were thinking on implementing our email service on top of sendgrid but this is a must have feature.

**Comment by ben-grid** [comment]
Hey folks, 

I can't offer you a release date for this feature set yet, but I will say we are in the early stages of building a solution. I'll definitely update this thread as soon as we have a firm commitment on a release date and if anyone is interested in beta testing late this year and early next year we'd really appreciate your feedback as we iterate to a releasable solution. 

If you are interested in beta testing, let me know here in this thread, or drop an email to ben@sendgrid.com with your name, email, company, and username. 

Thanks for all the great feedback you've provided via this issue thread and interviews, we really appreciate it and know we couldn't build great products without it!

**Comment by mtucker** [comment]
+1 on this as well.

I'd also be interested in beta testing.

**Comment by ben-grid** [comment]
@mtucker what's a good contact email for you, and your sendgrid username? I'll reach out with more info when we get the beta going.

**Comment by chamini2** [comment]
@ben-grid, I sent you an email. I'm really interested in the beta.

**Comment by ben-grid** [comment]
@chamini2 Yes, absolutely Matteo, you are on the list. 😄

**Comment by onemartini** [comment]
+1 @ben-grid I'd like to be on the list as well for Beta testing, please

**Comment by ben-grid** [comment]
@onemartini Can you throw me your email, company, and SG username? Either here or to ben@sendgrid.com, and I'll get you on my list. Thanks for offering to participate!

**Comment by nhwilly** [comment]
Was super excited and architecting my solution around SG, until I found out I couldn't process arrays.  Ouch.  Since I was just getting started, I haven't lost too much.  Hope you get it for the others.  G/L

**Comment by leachad** [comment]
Anxiously awaiting the release of this feature.

**Comment by atnmorrison** [comment]
This would be a great feature!

**Comment by marsalp** [comment]
What's the status of this feature?

**Comment by themizzi** [comment]
+1 we would like to be a part of the Beta as well.

**Comment by Eplumecocq** [comment]
@ben-grid, just sent you an email, really interested for beta testing too!

**Comment by ben-grid** [comment]
Thanks for your email @Eplumecocq ! @marsalp @themizzi if you're interested in participating in the beta, shoot me an email to ben@sendgrid.com with your email, company, and SG username. Thanks!

**Comment by jamie3** [comment]
We are looking to migrate our transactional templates to Send Grid. Has this been implemented? Thank you.

**Comment by liorpaz** [comment]
vote up +1 please.

**Comment by jonodrew** [comment]
On tenterhooks - are we close?

**Comment by chuksleo** [comment]
chuks@axumtechnologies.com  am interested

**Comment by vjaitly** [comment]
+1 on this.

**Comment by jtspencer** [comment]
Please need this asap.. we are current customer and there is no work around.

**Comment by b3nl** [comment]
My thinking today: 
Let’s start with sendgrid today ... and stopped using sendgrid today. This feature is an absolute must.

**Comment by chuksleo** [comment]
Hello guys i need to do some iteration in my sendgrid mail and ran into this issue for now i had a temporal workaround which solved the problem. here is how i worked around it
- created a txt file and loaded my html template there 
- Note areas i wanted to iterate on i replaced with a sendgrid variable e.g  %list of items%
-  read the txt file into a string 
- create a string builder and pass all iterated object into the  %list of items% variable 

the send the whole string content as message through sendgrid

`public void sendSimpleMessage(String message,
			String subject, 
			String toEmail,
			String fromEmail){

			 Email from = new Email(fromEmail);
			 Email to = new Email(toEmail);
			 Content content = new Content("text/html", message);
			 Mail mail = new Mail(from, subject, to, content);

			
			 SendGrid sg = new SendGrid(sendgridApiKey);
			 Request request = new Request();
			 try {
			      request.method = Method.POST;
			      request.endpoint = "mail/send";
			      request.body = mail.build();
			      sg.api(request);
			 } catch (IOException ex) {
			      ex.printStackTrace();
			}
	}`

hope it helps someone

**Comment by thinkingserious** [comment]
Thanks @chuksleo!

**Comment by ben-grid** [comment]
Hey everyone,

First of all, thank you VERY much to the many of you who have reached out to participate in the beta and in interviews. I still can't offer you a release date just yet, but I will say we are actively developing a solution. I'll definitely update this thread as soon as we have a firm commitment on a release date and, again, anyone interested in beta testing please let me know.

If you are interested in beta testing, please drop an email to ben@sendgrid.com with your name, email, company, and username.

Thanks for all the great feedback you've provided via this issue thread and interviews, we really appreciate it and know we couldn't build great products without your help!

**Comment by jtspencer** [comment]
I too did a similar workaround, essentially do the substitution myself and send the whole body to sendgrid.
Currently we develop the template in sendgrid editor, then I copy to code. Will eventually attempt to read the active template and cache in memory.
Planning on working up my own tags to delimit a repeating chunk of template, something like html  , <<REP>>…<</REP>>
Then I can parse the repeater from the template too, and keep all html in sendgrid.

Sent from Mail for Windows 10

**Comment by thinkingserious** [comment]
Thanks @jtspencer!

**Comment by mattisx** [comment]
We are probably changing provider because of this missing feature, which seems like one of the first things one would build.

**Comment by adamreisnz** [comment]
@mattisx and others, be patient. I've seen some of the work that is being done on this feature, and it's looking very promising. If you can hold on for a bit longer and do the iteration in your own server side code for now you won't be disappointed with the new templating engine.

**Comment by jmagnusson** [comment]
[sendwithus](https://www.sendwithus.com/), which is very competent for programmatic usage (through supporting [jinja](http://jinja.pocoo.org/)), has just announced that they will not be supporting GDPR, therefore losing all European accounts after May 25th. As Sendgrid is committed to GDPR it could become a worthy alternative to sendwithus as long as loops are introduced. Could create a lot of new customers for you. So I'd urge you to implement as soon as possible so we can consider it.

**Comment by mikkelking** [comment]
+1 for this, I have just hit the same limitation of 10k - I am sending an email digest at the end of day, and because all the css styling needs to go in the email, I hit the limit at just 6 messages, which is not alot.

I would gladly help with the beta testing, and I'm about to do my own workaround as suggested by @chuksleo , which I know will work.

I have a suggestion: _Why don't you simply relax the 10k limit, or have a setting on the user account so that only users that need it will turn it on_.

**Comment by chrisbuttacavoli** [comment]
I've waited too long for this to get implemented without hearing about any progress, I signed up for the beta months ago and still haven't heard anything from that either...

**Comment by siassaj** [comment]
+1 I'm going to have to move my client off sendgrid because we need conditionals and loops

**Comment by MFFoX** [comment]
I signed up today based on the transactional email templating but, about an hour in I am going to have to go to another provider with better templating functionality :( It's really too bad. The documentation, examples and overall product is amazing, but this is a big miss. Maybe I'll get the opportunity to come back and try this product again when support for basic logical templates is implemented. Good luck on this and from the looks of it, I'm sure you'll nail it!

**Comment by hyperborea** [comment]
This is unfortunately also a showstopper for us. Can the new templating functionality be expected within the upcoming weeks or is there a way for us to participate in the beta?

**Comment by ben-grid** [comment]
Hey everyone,

First of all, thank you VERY much to the many of you who have reached out to participate in the beta and in product interviews. I don't quite have a FIRM time commitment to offer yet, but I can give you SOME update on the timeline for the beta. Depending on your use case, we'll be inviting those participating to the beta starting in Mid-April and into May. 

If you are interested in beta testing and haven't gotten in touch with me already, please drop an email to ben@sendgrid.com with your name, email, company, and username.

Thanks again for all the great feedback you've provided via this issue thread and interviews, we really appreciate it and know we couldn't build great products without your help!

**Comment by siassaj** [comment]
@ben-grid did this take so long because there was only string substitution in place, and you had to build a parsing engine just because of this feature?

**Comment by adamreisnz** [comment]
@siassaj I think that's correct, they're essentially switching from the simple parsing engine they had in place to using Handlebars which supports if statements, for loops, helper transforms, etc. So it will be a lot more flexible.

**Comment by NoPretzel** [comment]
sendgrid pls

**Comment by wenbinke** [comment]
@thinkingserious   please use liquid as email template engine to do this. It is important to have something like "if-else" "foreach". It is not that hard.
http://shopify.github.io/liquid/basics/introduction/

**Comment by wenbinke** [comment]
@adamreisnz I hate handlebars. For email template engine, we should use liquid, it is powerful and handy.

**Comment by karledurante** [comment]
+1 for the feature.

What is the actual timeline for release here?

**Comment by adamreisnz** [comment]
@wenbinke ok, you are entitled to your opinion of course :) But I think the ship has already sailed, and they're nearly done with the handlebars implementation.

**Comment by buzzub** [comment]
Another +1 for this issue - been wanting this for years.

**Comment by thinkingserious** [comment]
Thanks @buzzub!

Please join the beta when you have a moment by requesting access from ben@sendgrid.com with your name, email, company and username.

With Best Regards,

Elmer

**Comment by ben-grid** [comment]
Hey @mikkelking , I got your email and responded on March 13th, at least I think that's you. ;-) Different email address from what is on your github profile. We are getting quite close to giving those of you who are participating in the beta access to the new feature set. As Elmer said above, if your interested and haven't emailed me yet, please drop a line to ben@sendgrid.com with your name, email, company and username.

Thanks for your patience!!

**Comment by ben-grid** [comment]
@mikkelking No problem! Really appreciate the offer to help! I'll be in touch again soon.

**Comment by musa11971** [comment]
What's the status on this feature? Will this be available to the public soon?

Would love to see this in sendgrid!

**Comment by ben-grid** [comment]
Hey there, 

We do not yet have a release date, as that date will depend on beta feedback, as well as some ongoing work related to scale. Rest assured I will update this thread as soon as we do have a date. 

The beta, however, is just around the corner, so if you would like to participate please drop me an email with your sendgrid username and I'll get you an invite.

**Comment by boggddan** [comment]
I'm waiting too. +1

**Comment by msmith521** [comment]
As am I. +1

**Comment by machinshin** [comment]
man, what timing! :( 😆 :| I literally just got a feature request today that requires looping. I really hope the beta starts soon, I would rather not have to macguyver it into production and only for the handlebars support to be implemented!

**Comment by ben-grid** [comment]
Hey all, the beta is up and running. We are doing phased invites, so if you'd like to participate and haven't done so already, please drop me an email, ben@sendgrid.com. Cheers!

**Comment by ronneyramon** [comment]
I´m interest in this too!!!

**Comment by gferrin** [comment]
WTF is wrong with you guys. I wish I read this before signing up for SendGrid. How has it taken you OVER TWO YEARS to implement such a basic feature!

**Comment by ameesme** [comment]
We have decided to switch to Mailjet, which does support features like (multi-dimensional) looping, if-statements, variables and some functions for dynamically generating blocks, with a Node.js-wrapper on Github as well.

The development of this feature takes way too long.

**Comment by thinkingserious** [comment]
Thanks for all of the additional votes to get this completed, we can't wait for this to be released also!

This feature is already in active development and if you would like to be added to the beta, please send an email to ben@sendgrid.com. 

Thanks!

**Comment by adamreisnz** [comment]
@thinkingserious and it's looking good! :)

**Comment by iBet7o** [comment]
The turn of the corner seems too far away!

I'm waiting too

**Comment by miller-aaron** [comment]
+1 need this as well

**Comment by subratbasnet** [comment]
Definitely +1 - on the verge of switching to another provider just because of this feature.
I have emailed @ben-grid to see if we can have it enabled for our account.

**Comment by bcarradini** [comment]
We will also be emailing @ben-grid to get on this beta.  +1

**Comment by giedriusr** [comment]
Can't believe it doesn't have such a basic feature.

**Comment by subratbasnet** [comment]
It looks like in the beta, this feature is now there under "transactional" templates. The old templates seems to have been renamed to "legacy"

How do I access this via API @ben-grid , do we have docs for this? The 3.0 API does not seem to have it.

Thanks

**Comment by dbalayan** [comment]
+1
need this to migrate on SendGrid completely without any crutches!

**Comment by ben-grid** [comment]
Hey all, 

I just wanted to give an update here. First of all, A BIG thank you to everyone who has participated in interviews and the beta program. Your feedback has been invaluable! Second, thank you to EVERYONE on this thread for your patience. I've read all of your comments and, candidly, your frustration is completely understandable. You've waited a long time for a very critical feature and I couldn't be happier that we are finally closing that gap. 

If you don't have access already and need it, shoot me an email @ ben@sendgrid.com to get into the beta. We'll also be rolling this out to ALL users just around the corner, and I'll update this thread soon with a firm date. 

Thanks again, you all rock!

**Comment by TimoWestland** [comment]
Hi @ben-grid I've emailed you to get access to the beta but I'm not getting any replies. Is there any way we can get access to this asap? We would really like to use sendgrid as our e-mail engine but this is blocking us...

**Comment by catamphetamine** [comment]
This is kinda retarded.
2 years and still not implemented.
Our company is hitting the 10000 limit which even lies about it because we made parameters less than 10000 bytes and it still complains.

**Comment by catamphetamine** [comment]
This is kinda retarded.
2 years and still not implemented.
People are hitting the 10000 limit which even lies about it because I made parameters less than 10000 bytes by splitting them in half and it still complains.

**Comment by thinkingserious** [comment]
Hello @catamphetamine,

This feature is hitting GA very shortly. If you would like beta access prior to that, please reach out to ben@sendgrid.com.

Thanks!

With Best Regards,

Elmer

**Comment by sendgrid-ryan** [comment]
Hey all! Great news––

### Dynamic content for Transactional Templates is here!
This morning, our team publicly launched dynamic content for transactional templates. It is now available for all customers sending over v3 of our Mail Send API. Iterate over lists, handle conditionals and more, thanks to native support for a subset of Handlebars syntax!

More information can be found in our [blog post announcement](https://sendgrid.com/blog/how-to-use-sendgrids-dynamic-templates-for-your-transactional-emails/).

**Documentation:** 
- [How to Send an Email With Dynamic Transactional Templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html)
- [Using Handlebars](https://sendgrid.com/docs/User_Guide/Transactional_Templates/Using_handlebars.html)
- [API Docs](https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send)

Thank you, on behalf of the entire SendGrid team, for all of the feedback throughout the beta program. 🙌🏻

**Comment by adamreisnz** [comment]
Great news, good work team 💯

**Comment by dougdonohoe** [comment]
This dynamic template stuff is great.  Nice work and great timing for us :-)

**Comment by token-appsolzone** [comment]
{{#each attendee}}
        <table style="border: 1px solid #ccc;
    box-shadow: 0 0 3px #000; font-size: 13px; font-weight: 600">
    <tr>
          <td style="width:120px;">Attendee Name</td>
          <td>:</td>
          <td>{{attendeeName}}</td>
        </tr>
        <tr>
          <td style="width:120px;">Email</td>
          <td>:</td>
          <td>{{attendeeEmail}}</td>
        </tr>
        <tr>
          <td style="width:120px;">Phone</td>
          <td>:</td>
          <td>{{attendeePhone}}</td>
        </tr>
    
    </table>
    {{/each}}

data--
{
    "attendee":[
        {
            "attendeeEmail":"apps@gmail.com",
            "attendeeName":"Token",
            "attendeePhone":"12345678"
        },
         {
            "attendeeEmail":"appsol@gmail.com",
            "attendeeName":"Arnab",
            "attendeePhone":"6483652"
        },
         {
            "attendeeEmail":"appsolz@gmail.com",
            "attendeeName":"Musha",
            "attendeePhone":"9735427"
        }
        
        ]
    }

**Comment by azizjawad** [comment]
Thanks, bro that was really helpful

**Comment by rastiehaiev** [comment]
Hi! Is there any way to have iteration inside iteration?

**Comment by token-appsolzone** [comment]
yes nested iteration is possible 
{{#each first array}}

{{#each innerarray}}
your html or data presentation
{{/each}}

{{/each}}

**Comment by sunykumar** [comment]
@token-appsolzone  Please let me know how to set this data with loop in send grid template
{"publisResult":[
{
 "key":{ "SearchTerm":"flower" }, 
  "data": [
  {
    "PublisImgUrl":"https://abc.png",
    "Name":"Jhon",
    "Title":"gardenflowershop",
	"Description":"Online Flower Shops in delivery Hong Kong"
  },
  {
    "PublisImgUrl":"garden.com",
    "Name":"Jhon Cena",
    "Title":"weddings",
	"Description": "Wedding Flowers and Gifts | 1-800-FLOWERS.COM"
  }
 ]
},
{
 "key":{"SearchTerm" : "Pizza"},
 "data":[
 {
    "PublisImgUrl":"https://abc.png",
    "Name":"Harry",
    "Title":"benny-drinnon.com",
	"Description":"TAMELA C. TODD - Home | Tamela Todd"
  },
  {
    "PublisImgUrl":"gardenflowershop",
    "Name":"Roma",
    "Title":"benny-drinnon.blogspot",
	"Description": "Michelle Morgan Talks Thelma"
  }
 ]
}]}

**Comment by sourabhCofoundry** [comment]
Hello, token-appsolzone Please help me Please create send grid code for this data
{
  "publisResult": [
    {
      "key": {
        "SearchTerm": "flower"
      },
      "data": [
        {
          "PublisImgUrl": "https://picsum.photos/200/300.jpg",
          "Name": "Jhon",
          "Title": "gardenflowershop",
          "Description": "OnlineFlower"
        },
        {
          "PublisImgUrl": "https://picsum.photos/200",
          "Name": "Tommy",
          "Title": "weddings",
          "Description": "Wedding"
        }
      ]
    },
    {
      "key": {
        "SearchTerm": "Pizza"
      },
      "data": [
        {
          "PublisImgUrl": "https://picsum.photos/200/300",
          "Name": "Harry",
          "Title": "benny-drinnon.com",
          "Description": "TAMELAC"
        },
        {
          "PublisImgUrl": "https://picsum.photos/200/300",
          "Name": "Roma",
          "Title": "benny",
          "Description": "Michelle"
        }
      ]
    }
  ]
}

**Comment by sourabhCofoundry** [comment]
Any update on it.
