### ISSUE TITLE
React-native support?

### ISSUE THREAD

**Issue by flizzer** [sendgrid/sendgrid-nodejs#222]
Does this module support use in a react-native app?  I'm looking for a simple way to background mail using an API.  Thanks!

**Comment by penjual** [comment]
![simulator_screen_shot_apr_15__2016__16_40_06](https://cloud.githubusercontent.com/assets/18244216/14557760/00bb23d0-0329-11e6-9267-40b24a7a5348.png)

**Comment by thinkingserious** [comment]
@flizzer,

I have not tested our module in react-native, but based on @penjual's error, perhaps this thread can help: https://github.com/facebook/react-native/issues/4968

Please let me know how it goes. Thanks!

**Comment by rdagger** [comment]
Did you figure out how to get SendGrid working with React Native?  I'm getting the same error message.

**Comment by flizzer** [comment]
@rdagger No, I didn't.  Ended up using a .NET web api 2 web service to interact with SendGrid.  Repo [here](https://github.com/flizzer/ORUMCCaveQuestVBSEmailService/blob/master/ORUMCCaveQuestVBSEmailService/Controllers/SendGridController.cs) if you're interested in having a look.  Good luck!

**Comment by thinkingserious** [comment]
@rdagger, @flizzer,

We are just about to bring v9 out of beta, hopefully that will help you: https://github.com/sendgrid/sendgrid-csharp/tree/v9beta

**Comment by rdagger** [comment]
@thinkingserious Thanks, are you also releasing a new Node.js version for React Native?

**Comment by thinkingserious** [comment]
Hello @rdagger,

We are not releasing a version specifically targeting React Native, but we are working on similar improvements that we made to our C# SDK.

**Comment by rdagger** [comment]
Do you have an ETA for the new Node.js release? Is it possible to try out the beta now?

**Comment by thinkingserious** [comment]
Hello @rdagger,

I don't have an ETA yet. We have not left the planning stages just yet. If you would like to participate, please see the "Mail Helper Enhancement (v3 mail/send)" project here: https://github.com/sendgrid/sendgrid-nodejs/projects

With Best Regards,

Elmer

**Comment by rdagger** [comment]
Thanks.  I've found that using fetch works well for sending simple emails using the web api from React Native:

```
fetch('https://api.sendgrid.com/v3/mail/send', {
  method: 'POST',
  headers: {
	'Authorization': 'Bearer ' + apikey,
	'Content-Type': 'application/json',
  },
  body: JSON.stringify(body),
}).then((response) => {
  this.setState({response: `${response.status} - ${response.ok}`});
});
```

**Comment by jaymjax1** [comment]
@rdagger What all did you contain in your body? And did you have to import any other modules?

**Comment by pcullings** [comment]
@jaymjax1 I used @rdagger 's solution and I used the following format for for 'body':
`{
  "personalizations": [
    {
      "to": [
        {
          "email": "john@example.com"
        }
      ],
      "subject": "Hello, World!"
    }
  ],
  "from": {
    "email": "from_address@example.com"
  },
  "content": [
    {
      "type": "text/plain",
      "value": "Hello, World!"
    }
  ]
}`
I did not have to import any other modules.
