### ISSUE TITLE
Mandrill tags to send emails in Sendgrid?

### ISSUE THREAD

**Issue by jdnichollsc** [sendgrid/sendgrid-nodejs#227]
Hi guys,

What is the correct way to add multiple tags when the emails are sent?

Thanks in advance, Nicholls

**Comment by jdnichollsc** [comment]
The correct way is using categories,

But what is the method to get statistics by categories in Sendgrid?

Thanks

**Comment by djfarrelly** [comment]
Hey @jdnichollsc,
You can use categories by using the `x-smtpapi` header with the constructor:
```js
sendgrid.send({
  to: 'to@example.com',
  from: 'from@example.com',
  subject: 'You\'re invited!',
  text: 'Some body text',
  smtpapi: new sendgrid.smtpapi({
    category: 'invite' // or whatever category you might want
  })
}, function(err, json) {
  // ...
})
```
Find more info on how to use the constructor here: https://github.com/sendgrid/smtpapi-nodejs/blob/master/lib/main.js#L6-L21

More info on the `x-smtpapi` header: https://sendgrid.com/docs/API_Reference/SMTP_API/using_the_smtp_api.html

**Comment by thinkingserious** [comment]
@jdnichollsc @djfarrelly,

Thank you for your feedback!

With the new version of our /mail/send endpoint the X-SMTPAPI header is integrated: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

To get your statistics by category, please see: https://sendgrid.com/docs/API_Reference/Web_API_v3/Stats/categories.html

Thank you for your support!

With Best Regards,

Elmer

**Comment by jdnichollsc** [comment]
Thanks! :dancers:
