### ISSUE TITLE
Empty from email address (required)

### ISSUE THREAD

**Issue by herkyl** [sendgrid/sendgrid-nodejs#228]
I'm getting `Empty from email address (required)` even though the from email is set.

This is how I am sending the email:
```javascript
var email = new sendgrid.Email();
email.setFrom('from@email.com');
...
sendgrid.send(email, cb);
```

What am I doing wrong?

**Comment by thinkingserious** [comment]
Reference: https://github.com/sendgrid/sendgrid-php/issues/212

**Comment by wizvs** [comment]
@thinkingserious  The issue in node js is due to call backs. Handling callbacks carefully worked for me.

**Comment by thinkingserious** [comment]
Thanks @wizvs!

@herkl was your issue resolved?

**Comment by thinkingserious** [comment]
@herkyl ^

**Comment by herkyl** [comment]
I'm not sure anymore, I don't remember how I fixed it and it's not relevant anymore
