### ISSUE TITLE
Get info of emails sent with Sendgrid like Mandrill

### ISSUE THREAD

**Issue by jdnichollsc** [sendgrid/sendgrid-nodejs#235]
Hi guys,

Is there any way to get the information mails sent with SendGrid? For example email, subject, opens, clicks and the state like Mandrill https://mandrillapp.com/api/docs/messages.nodejs.html#method=search

**Comment by thinkingserious** [comment]
Hello @jdnichollsc,

Our support team will be able to help with this. Please contact them at https://support.sendgrid.com

Thanks!

**Comment by jdnichollsc** [comment]
Done, thanks! :dancers:
