### ISSUE TITLE
I can not send emails 

### ISSUE THREAD

**Issue by eaparango** [sendgrid/sendgrid-nodejs#237]
Dear,

I can not send emails  :(

I get this response:

Error =>> 415
body =>> { "errors": [{ "message": "Content-Type Should be application / json." "field": null, "help": null}]}
headers =>> {server headers: 'nginx'
   date: 'Wed, June 15, 2016 2:56:08 GMT'
   'Content-type' 'application / json'
   'Content-length' '92',
   connection: 'close'
   'X-frame-options' 'DENY'}

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Hello @eaparango,

Thanks for reaching out to us!

I'll need some further details to help you:
1. What version of the library are you using?
2. Can you provide the source code? (With credentials and emails redacted)

**Comment by thinkingserious** [comment]
@eaparango, I just tested using the example in the README and I did not get your error. Please answer the questions above so we can further assist. Thanks!

**Comment by thinkingserious** [comment]
Any luck @eaparango?

**Comment by eaparango** [comment]
It works perfect thanks !!
