### ISSUE TITLE
Docs do not make sense for "substitutions" JSON

### ISSUE THREAD

**Issue by stephengardner** [sendgrid/sendgrid-nodejs#238]
#### Issue Summary

They say this: 
`
"substitutions": {
        "sub": {
          "%name%": [
            "John",
            "Jane",
            "Sam"
          ]
        }
      },
`

This gives a 400 Error with no description.

Why is the extra "sub" object there?

It works for me without the "sub" object.  Use key->value pairs as direct descendants of "substitutions".

v3.0.4

**Comment by thinkingserious** [comment]
@stephengardner you are correct, thanks! I have updated the example and docs.

**Comment by stephengardner** [comment]
Fantastic, thank you!

On Wed, Jun 15, 2016 at 5:46 PM, Elmer Thomas <notifications@github.com>
wrote:

> @stephengardner <https://github.com/stephengardner> you are correct,
> thanks! I have updated the example and docs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sendgrid/sendgrid-nodejs/issues/238#issuecomment-226329887>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHBvdtoOYRClg7dNW-4tPw0P8w6_PbE9ks5qMHKmgaJpZM4I2Cdb>
> .
>



-- 
Stephen Gardner
CTO - Apartminty
Apartminty.com <http://apartminty.com/>
