### ISSUE TITLE
I can not send email with accents

### ISSUE THREAD

**Issue by eaparango** [sendgrid/sendgrid-nodejs#239]
#### Issue Summary

I can not send email with accents

#### Steps to Reproduce

var helper = sendgrid.mail;
var mail = new helper.Mail();
var personalization = new helper.Personalization();
var email = new helper.Email("no-reply@fracttal.com", "Fracttal");

mail.setFrom(email);
mail.setSubject("Servidor áéíóúÑñáéíóúÑñáéíóúÑñ");

email = new helper.Email("xxx@xxxx.com", "áéíóúÑñáéíóúÑñáéíóúÑñáéíóúÑñ");
personalization.addTo(email);

mail.addPersonalization(personalization);

var content = new helper.Content("text/plain", "Servidor áéíóúÑñáéíóúÑñáéíóúÑñ: " + new Date());
mail.addContent(content);

 var sg = sendgrid.SendGrid("xxxxxxxxxxxxxxxxxxx");
var requestPost = sendgrid.emptyRequest;
requestPost.method = 'POST';
requestPost.path = '/v3/mail/send';
requestPost.body = mail.toJson();
sg.API(requestPost, function (response) {
        console.log(response.statusCode);
        console.log(response.body);
        console.log(response.headers);
    });

ERROR:
400
{"errors":[{"message":"Bad Request","field":null,"help":null}]}
{ server: 'nginx',
  date: 'Wed, 15 Jun 2016 16:14:22 GMT',
  'content-type': 'application/json',
  'content-length': '63',
  connection: 'close',
  'x-frame-options': 'DENY' }

#### Technical details:

* sendgrid-nodejs Version: 3.0.4
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
@eaparango this is a library problem. I was able to successfully send your email through these examples: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/curl_examples.html

So I'm filing this one as a bug and we will figure out a fix.

**Comment by thinkingserious** [comment]
OK, I think I've found the fix:
https://github.com/sendgrid/nodejs-http-client/blob/master/lib/client.js#L76
needs to be Buffer.byteLength(body)

**Comment by thinkingserious** [comment]
The fix is in place in version 3.0.5. I've tested against your code above and it now works.

The issue was in the way I was calculating the content-type length. I did not account for the varying byte lengths of unicode characters.
