### ISSUE TITLE
Template substitutions not being applied after the first email

### ISSUE THREAD

**Issue by jasonpang** [sendgrid/sendgrid-nodejs#243]
[Referencing this issue](https://github.com/sendgrid/sendgrid-nodejs/issues/192), there still seems to be an issue when applying templates to an email. Rarely, one of my emails will have the templates applied (the first one I send after a while), but subsequent emails have the placeholder blank.

Here's the code I'm using. Is there something I'm doing wrong?

```js
 var helper = sendgrid.mail;
 var from_email = new helper.Email("no-reply@site.com");
 var to_email = new helper.Email("recipient@gmail.com");
 var content = new helper.Content("text/html", "This is some content.");
 var mail = new helper.Mail(from_email, 'Subject', to_email, content);

 var username = "username";
 var email = "recipient@gmail.com";

 var personalization = new helper.Personalization();
 personalization.addTo(to_email);
 personalization.addSubstitution(new helper.Substitution("%username%", username));
 personalization.addSubstitution(new helper.Substitution("%email%", email));
 personalization.addSubstitution(new helper.Substitution("%confirmation_url%", `http://localhost/confirm`));
 mail.setTemplateId("2245cf86-6587-46c0-a384-6d8109491ee3");
 mail.addPersonalization(personalization);

 var sg = sendgrid.SendGrid(apiKey);
 var requestBody = mail.toJSON();
 var request = sg.emptyRequest();
 request.method = 'POST';
 request.path = '/v3/mail/send';
 request.body = requestBody;
 return await new Promise(resolve => {
     sg.API(request, function(response) {
         console.log(response);
         resolve(response);
     });
 });
```

My goal is to send transactional emails using a SendGrid template and substituting variables.

Using version 3.0.5 (latest) of the sendgrid library.

**Comment by BrandesEric** [comment]
This is happening for me as well, using the v2 apis and 2.0.0 of the Node library.  For me it occurs EVERY time there are multiple recipients.  The first recipient gets the replacement as expected, but subsequent emails have blank spaces instead of the replacement text.

**Comment by thinkingserious** [comment]
@jasonpang @BrandesEric This issue is similar to this one: https://github.com/sendgrid/sendgrid-java/issues/114 -- please read the solution there.

I'll officially address this ticket and make the same updates to the documentation as soon as I can.

**Comment by BrandesEric** [comment]
@thinkingserious I'm not sure I understand - we're not doing anything with multiple personalization objects. We're just creating a sendgrid.Email() object and setting substitutions.  In our case, we have two recipients, but we specify a single replacement substitution (that is, we want the same value to be replaced in both emails)

**Comment by thinkingserious** [comment]
@BrandesEric Ah, sorry I missed that you are using v2 apis. Could you please open a separate ticket and include the relevant source code? Thanks!

**Comment by thinkingserious** [comment]
@jasonpang,

The substitutions used to be an array that matched index for index with the recipients array. Now, each substitution goes to a personalization. 

Previously, you would do the following: 

to: email1, email2, email3
substitutions: name = sam, jane, mike 

Now, you would do the following:

personalization1:
- email: email1
- substitution: name = sam

personalization2:
- email: email2
- substitution: name = jane

personalization3:
- email: email3

etc..

For more on the changes between v2 and v3, please review: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html
