### ISSUE TITLE
Not Getting Substitutions in "BCC or CC"

### ISSUE THREAD

**Issue by harshitanand** [sendgrid/sendgrid-nodejs#245]
#### Issue Summary

if have been using transaction templates of sendgrid to send mails. We too have substitutions in mail templates. I am setting {CC and BCC} in every mail but not getting substitutions there in CC'ed mails.

#### Steps to Reproduce

1. send mail to someone using sendgrid templates and add cc mail.
2. Don't forget to add substitutions.
3. You won't be able to see subtitution in cc'ed mails.

#### Technical details:

* sendgrid-nodejs Version: 2.0.0 
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Hello @harshitanand,

Thanks for the issue report. We are tracking this problem here: https://github.com/sendgrid/sendgrid-nodejs/issues/243

Thanks!

**Comment by angus-ics** [comment]
Lines 617 - 630 in helpers/mail/mail.js

```javascript
this.addSubstitution = function(substition) {
    if(this.substitions == undefined){
      this.substitions = {}
    }
    this.substitions[Object.keys(substition)[0]] = substition[Object.keys(substition)[0]]
  }

  this.getSubstitutions = function() {
    return this.substitions
  }
```

Did you mean to use substitutions instead of 'substitions'.

**Comment by thinkingserious** [comment]
@angus-ics yes, there is a pull request to fix this: https://github.com/sendgrid/sendgrid-nodejs/pull/250

I'm hoping to get that merged soon. If we don't get the CLA shortly, we will go ahead and make the fix.

Thanks for following up!

**Comment by julio-vaz** [comment]
Please do the merge. This bug is affecting the whole community.

**Comment by ambles** [comment]
How come this ticket is closed? I am still experiencing this issue --> Not Getting Substitutions in "BCC"!

Ruby Gems
- sendgrid (1.2.4)
- sendgrid-ruby (1.1.6)

Ruby
- ruby 2.2.3p173

**Comment by swarm1** [comment]
It seems the problem is still not solved in v.2.0.0

**Comment by thinkingserious** [comment]
@swarm1,

Could you please give us some example code? I'm happy to investigate. Thanks!

**Comment by Jatinthakkar** [comment]
I am using java API V2, how do i fix this ?

**Comment by thinkingserious** [comment]
Hi @Jatinthakkar,

Thanks for reaching out to us!

Could you please post your question [here](https://github.com/sendgrid/sendgrid-java) along with some sample code so that I may try and reproduce the error?

Thanks!
