### ISSUE TITLE
Why is `require('sendgrid-rest')` repeated so much in `/lib/sendgrid.js`?

### ISSUE THREAD

**Issue by zacharynevin** [sendgrid/sendgrid-nodejs#246]
#### Issue Summary

When looking through `/lib/sendgrid.js`, I noticed that `require('sendgrid-rest')` was placed everywhere. I'm fairly sure thats bad practice and that you should include it only once in the top of the file.

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Hello @zacharynevin,

Thanks for the feedback!

I have tagged this issue for consideration for the next iteration of updates for this library. Any additional feedback/ideas/suggestions you may have is greatly appreciated!

With Best Regards,

Elmer

**Comment by adambuczynski** [comment]
@zacharynevin this is now addressed by https://github.com/sendgrid/sendgrid-nodejs/pull/261
If you could +1 there that would be helpful for the Sendgrid team to push it through for merge.

**Comment by thinkingserious** [comment]
@adambuczynski,

Thanks for relating this ticket :)

I've added the +1 on our side already.

**Comment by adambuczynski** [comment]
Cheers thanks :)

**Comment by thinkingserious** [comment]
Fixed with https://github.com/sendgrid/sendgrid-nodejs/releases/tag/v4.0.0
