### ISSUE TITLE
`reply_to` doesn't seem to be respected

### ISSUE THREAD

**Issue by jmonster** [sendgrid/sendgrid-nodejs#247]
#### Issue Summary

When configuring a `reply_to` attribute, emails are still being received without any mention of it. I can get the desired behavior by setting `from` but I'm concerned this may lead to issues as being identified as spam/fake/etc by filters.

#### Steps to Reproduce

```js
SendGrid.send({
    to:      "dashboard-feedback@heroku.com",
    from:    "dashboard-feedback@heroku.com",
    reply_to: { name: payload.name, email: payload.email },
    subject:  `Dashboard feedback from ${payload.email}`,
    /* ... */
```

#### Technical details:

* sendgrid-nodejs Version: latest
* Node.js Version: 4.4.5

**Comment by thinkingserious** [comment]
Hello @jmonster,

That should definitely not be the case. Thanks for letting us know. We'll dig deeper and see what's going wrong.

**Comment by thinkingserious** [comment]
Hello @jmonster,

This is no longer an issue with the v3 version of our API. A full example that utilizes the reply_to field can be found [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L130).

Please let me know if you run into any other issues.

Thanks!
