### ISSUE TITLE
415 error when sending an email

### ISSUE THREAD

**Issue by yonib05** [sendgrid/sendgrid-nodejs#248]
#### Issue Summary
Response when sending an email:
`{ statusCode: 415,
  body: '{"errors":[{"message":"Content-Type should be application/json.","field":null,"help":null}]}',
  headers: 
   { server: 'nginx',
     date: 'Tue, 21 Jun 2016 15:41:30 GMT',
     'content-type': 'application/json',
     'content-length': '92',
     connection: 'close',
     'x-frame-options': 'DENY' } }
`

#### My code

        var helper = require('sendgrid').mail;
        var mail = new helper.Mail();
        var email = new helper.Email("**myemail**", "Team");
        mail.setFrom(email);

        mail.setSubject("Select your pack");

        for(var i=0; i< list.length; i++) {
            var personalization = new helper.Personalization();
            var substitution;
            email = new helper.Email('**myemail**', '**myname**');
            personalization.addTo(email);
            substitution = new helper.Substitution("%src%", "https://example.com/");
            personalization.addSubstitution(substitution);
            mail.addPersonalization(personalization);
        }

        mail.setTemplateId('my-template-id');

        
        var toSend = mail.toJSON();

        var requestBody = toSend;
        var request = sg.emptyRequest();
        request.method = 'POST';
        request.path = '/v3/mail/send';
        request.requestBody = requestBody;
        sg.API(request, function (response) {
         console.log(response);
        });

#### Technical details:

* sendgrid-nodejs Version: 3.0.5
* Node.js Version: 6.2.0

**Comment by yonib05** [comment]
Seems the issue is with line  line 
          request.requestBody = requestBody;
I took it from
https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L146
should be 
requestPost.body = requestBody

Might want to update this so that others don't have a similar issue

**Comment by thinkingserious** [comment]
Hello @yonib05,

Thank you for taking the time to give us the heads up and share the fix. We'd like to send some swag your way.

Please email us at dx@sendgrid.com with your T-shirt size.

Thanks!
