### ISSUE TITLE
Using Unix timestamps rather than YYYY-MM-DD formatting for stats APIs

### ISSUE THREAD

**Issue by brokyo** [sendgrid/sendgrid-nodejs#249]
I just moved up to the v3 API (which is great!) but the `start_date` and `end_date` parameters in the stats APIs seem to introduce a lot of unnecessary complexity. Instead of just using a date object for an arbitrary time (one week ago here) I have to do to a convoluted set of conversions:

```
	var unixdate = Date.now();
	var oneWeekAgo = unixdate - 604800000;
	var oneWeekAgoObject = new Date(oneWeekAgo);

	var startDateMonth = ('0' + (oneWeekAgoObject.getMonth()+1)).slice(-2);
	var startDateDate = ('0' + oneWeekAgoObject.getDate()).slice(-2);
	var startDateYear = oneWeekAgoObject.getFullYear();
	var startDateString = String(startDateYear + '-' + startDateMonth + '-' + startDateDate);
```

This seems like a bit much but it's possible I'm just doing something stupid! Is this the recommended way? If so is there a reason this is preferable to to just using Unix time?

Thanks! I really do appreciate the library but I just want to be sure I've got this one right.

**Comment by thinkingserious** [comment]
Hello @brokyo,

Could you please open up a ticket at https://support.sendgrid.com? Thanks!
