### ISSUE TITLE
Recipient_Id?

### ISSUE THREAD

**Issue by fmarcheski** [sendgrid/sendgrid-nodejs#253]
A Recipient_Id is required for a lot if the ContactDB calls but I'm having trouble finding documentation on how to get a recipient_id.

The recipient_id isn't in the response when I create one. What am I missing?

**Comment by thinkingserious** [comment]
Hello @fmarcheski,

Apologies for the confusion. You can find the recipient_id in the "persisted_recipients" section here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#-Recipients. I know that is not clear and we will figure out a better way to describe that functionality.

Thank you!
