### ISSUE TITLE
Category parameter for /categories/stats/sums

### ISSUE THREAD

**Issue by brokyo** [sendgrid/sendgrid-nodejs#255]
Apologies as the documentation is a bit unclear on this. Is it possible to use a category parameter in this call like you would in GET /categories/stats? I'm attempting this now and it's not being respected but I can't tell if that's an issue in my code or the design of the API.

Doing this currently: 

```
	var request = sendgrid.emptyRequest();
		request.queryParams.start_date = startDateString;
		request.queryParams.end_date = endDateString;
		request.queryParams.aggregated_by = 'month';
		request.queryParams["categories"] = 'aCategory;
		request.method = 'GET';
		request.path = '/v3/categories/stats/sums';
		sendgrid.API(request, function (response) {
			// do some stuff
                })

```

but getting responses from all categories. Am I overlooking something or is this a feature request and not a bug?

**Comment by thinkingserious** [comment]
Hi @brokyo,

No apology needed :)

That endpoint provides the sum of all categories, please see: https://sendgrid.com/docs/API_Reference/Web_API_v3/Stats/categories.html#-GET-Sums

So the issue is the API design.

**Comment by brokyo** [comment]
My apologies! I was careless in reading the docs. Appreciate the help!
