### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by wayofthefuture** [sendgrid/sendgrid-nodejs#258]
We need a simple NodeJS v3 example. I'm sure it's somewhere in the HUGE folder of examples... The search continues...

**Comment by thinkingserious** [comment]
Hello @wayofthefuture,

The simplest examples are here: https://github.com/sendgrid/sendgrid-nodejs

What endpoint(s) are you interested in?

Thanks!

**Comment by IonicaBizau** [comment]
@thinkingserious Same here... Struggling with this for about one hour.
The docs should contain a really simple/minimal example.

**Comment by thinkingserious** [comment]
@IonicaBizau,

I'm sorry to hear that.

Did you use the examples in the README? Where did you look? 

With regards to the mail helper, we have on our roadmap to make it more user friendly. I've added the votes on this thread to that task so that it may climb higher in our queue.

I'm going to close this ticket and point you here for tracking: https://github.com/sendgrid/sendgrid-nodejs/issues/252

Thanks!

**Comment by IonicaBizau** [comment]
@thinkingserious Great, I commented there. In fact, I really liked they way how `2.0.0` was working.

**Comment by thinkingserious** [comment]
@IonicaBizau,

We like how 2.0.0 was working too. We will get back to that level of ease of use soon, especially given all the great feedback the community has been giving us.

Thanks again for taking the time to let us know your thoughts.

**Comment by IonicaBizau** [comment]
@thinkingserious What it was confusing, too, was the fact that the first result for `sendgrid nodejs example` is the version two: https://sendgrid.com/docs/Integrate/Code_Examples/v2_Mail/nodejs.html

That's definitely not compatible with `3.x.x`, but there is no big alert like:

> ⚠️  **This is using version `2.x.x`** or something.**

What is missing in the current version is just a nice high level function which receives the human readable properties and does its job in a nice way (like `client.send` was doing). 🚀

**Comment by thinkingserious** [comment]
@IonicaBizau,

Excellent! I've let our documentation team know.

The high level function is coming, It will be implemented in the mail helper.
