### ISSUE TITLE
CC and BCC not working for Web_API_v3

### ISSUE THREAD

**Issue by shijuamt** [sendgrid/sendgrid-nodejs#262]
I'm try to send email with "**_cc_**" and "_bcc_" using the API Request
**POST https://api.sendgrid.com/v3/mail/send HTTP/1.1** . I got an error  like this

{"errors":[{"message":"The to array is required for all personalization objects, and must have at least one email object with a valid email address.","field":"personalizations.1.to","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"},{"message":"The to array is required for all personalization objects, and must have at least one email object with a valid email address.","field":"personalizations.2.to","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"}]}

 using the data part like this
 --data '{"personalizations": [{"to": [{"email": "example@email.com"}]},{"cc": [{"email": "example@email.com"}]},{"bcc": [{"email": "example@email.com"}]}],"from": {"email": "example@email.com"},"subject": "Hello, World!","content": [{"type": "text/plain", "value": "Heya!"}]}'

**Comment by thinkingserious** [comment]
Hello @shijuamt,

It looks like we are returning the wrong error. The issue was that the cc and bcc need to be included in the personalization object:

```json
{
  "content": [
    {
      "type": "text/plain",
      "value": "Heya!"
    }
  ],
  "from": {
    "email": "example@email.com"
  },
  "personalizations": [
    {
      "to": [
        {
          "email": "example@email.com"
        }
      ],
      "cc": [
        {
          "email": "example@email.com"
        }
      ],
      "bcc": [
        {
          "email": "example@email.com"
        }
      ]
    }
  ],
  "subject": "Hello, World!"
}
```

I'll work with the team on returning the correct error.
