### ISSUE TITLE
Is it possible to leave blank 'Cc' and 'Bcc'?

### ISSUE THREAD

**Issue by ronakvbhatt07** [sendgrid/sendgrid-nodejs#263]
I am working on a sending mail option where i am using Code of sending mail _**Without mail helper class**_. Now the thing is i am binding _to_,_cc_ and _bcc_ dynamically. There might be possibilities that need to pass blank _cc_ and _bcc_ as well. So in that case what should i do to prevent generating error?  

    request.body = {
      "personalizations": [
        {
          "to": [
           {
              "email": "test@example.com"
            }
          ],
          "cc":[],
          "bcc":[]
          "subject": "Hello World from the SendGrid Node.js Library!"
        }
      ],
      "from": {
        "email": "test@example.com"
      },
      "content": [
       {
          "type": "text/plain",
          "value": "Hello, Email!"
       }
     ]
    };

**Comment by thinkingserious** [comment]
@ronakvbhatt07,

When they are empty, you can leave out the cc and bcc objects:

```json
request.body = {
  "personalizations": [
    {
      "to": [
       {
          "email": "test@example.com"
        }
      ],
      "subject": "Hello World from the SendGrid Node.js Library!"
    }
  ],
  "from": {
    "email": "test@example.com"
  },
  "content": [
   {
      "type": "text/plain",
      "value": "Hello, Email!"
   }
 ]
};
```

e.g.: http://stackoverflow.com/a/5310331

**Comment by ronakvbhatt07** [comment]
@thinkingserious  thank you mate. Yes tried the same thing. And its working. :dart:

**Comment by thinkingserious** [comment]
Awesome! Thanks for the follow up!
