### ISSUE TITLE
Response data should be valid json objects

### ISSUE THREAD

**Issue by mrfelton** [sendgrid/sendgrid-nodejs#266]
#### Issue Summary

Currently, the data that you get from `SendgridError.response` is a stringified json. That means in order to inspect it you have to parse it with `JSON.parse`. Thats a pain in the ass to do. The same is true of the response body for successful calls. This leads to code like `const response = JSON.parse(response.body)` everywhere in order to actually use the result of API calls or `const body = JSON.parse(err.response.body)` in order to get the details from any errors.

I think it would make sense to parse this data in the library so that users of the library don't have to.

* sendgrid-nodejs Version: master
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Hi @mrfelton,

Great feedback! This is going on the backlog.

To get it raised up higher in the queue, we consider:
- +1s
- pull requests with a signed CLA

With Best Regards,

Elmer

**Comment by hugoduraes** [comment]
Submitted PR #319 for this issue.

**Comment by thinkingserious** [comment]
Fixed by https://github.com/sendgrid/sendgrid-nodejs/releases/tag/v4.6.0

Thanks @hugoduraes

**Comment by hugoduraes** [comment]
You are welcome! :)
