### ISSUE TITLE
Substitutions Not working in CC'ed mail (Java, Send-Grid-2.0.0)

### ISSUE THREAD

**Issue by Jatinthakkar** [sendgrid/sendgrid-nodejs#267]
Issue Summary:-

I have been using manual templates of sendgrid to send mails. We too have substitutions in mail templates. I am setting {CC } in every mail but not getting substitutions there in CC'ed mails.

Steps to Reproduce

1.send mail to someone using sendgrid templates and add cc mail.
2.Don't forget to add substitutions.
3.You won't be able to see subtitution in cc'ed mails.

Technical details:
sendgrid-java Version: 2.0.0

**Comment by thinkingserious** [comment]
Thanks for reporting this error @Jatinthakkar,

Do you mind sharing the relevant source code? I've seen this error happen when you create a new personalization object instead of adding to the one created for you when you use the constructor: https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L10

Thanks!

**Comment by thinkingserious** [comment]
Hi @Jatinthakkar,

If you are still having trouble, please feel free to re-open this issue.

**Comment by Jatinthakkar** [comment]
email.addCc(ccDataArray);                 

               String arr[];
		arr = new String[1];
		arr[0] = comments;
		
		String arr2[];
		arr2 = new String[1];
		arr2[0] = replyLink;
		
		email.addSubstitution("-auditorComments-", arr);
		email.addSubstitution("-replyLink-", arr2);

This is the code snipett. The issue is that auditor comments and reportLink, values get substituted in the mail which is being sent to email.to(sender), but they do not get substituted in email.addCc(ccDataArray).	

Thanks!

**Comment by thinkingserious** [comment]
Hello @Jatinthakkar,

Thanks for the update, I have added this to our backlog for review.

**Comment by thinkingserious** [comment]
Hi @Jatinthakkar,

The Java library is now at v3.2.1. Could you please check it out and let us know if you are still having issues? You can find it here: https://github.com/sendgrid/sendgrid-java

Thanks!

Elmer
