### ISSUE TITLE
How to use maxSockets?

### ISSUE THREAD

**Issue by yanosh-igor** [sendgrid/sendgrid-nodejs#270]
I'm trying to limit the number of sockets.
Does module version v4.0.1 support this option?
If yes then can you provide some example, please.

**Comment by thinkingserious** [comment]
Hello @yanosh-igor,

No we do not. I have added a ticket for this here: https://github.com/sendgrid/nodejs-http-client/issues/3

To that ticket higher in our queue, it needs +1s, comments or a pull request with a signed CLA

Thanks!
