### ISSUE TITLE
Meta: Bug in Bug Report Contribution instructions linking to Bug Report Template that doesn't exist.

### ISSUE THREAD

**Issue by meteormanaged** [sendgrid/sendgrid-nodejs#271]
#### Issue Summary

Bad link in contribution guide.

#### Steps to Reproduce

1. Go to contribution guide.
2. Check link for sample bug report template

https://github.com/sendgrid/sendgrid-nodejs/.github/ISSUE_TEMPLATE

Does not exist

**Comment by thinkingserious** [comment]
Thank you! 

https://github.com/sendgrid/sendgrid-nodejs/commit/439e1732a743098fe38b5b8d02b93ca03208b0d7
