### ISSUE TITLE
No Email is being sent

### ISSUE THREAD

**Issue by Pashtunzoy** [sendgrid/sendgrid-nodejs#272]
I'm trying to send an email but it isn't going through. 
I used your example on README and also used the non Helper method one but none of them seems to work. 

```js
        import { mail } from 'sendgrid';
        const helper = mail;
        const from_email = new helper.Email('admin@test.com');
        const to_email = new helper.Email('someuser@test.com');
        const subject = 'Testing';
        const content = new helper.Content('text/plain', 'Test Description');
        const email = new helper.Mail(from_email, subject, to_email, content);
        const sg = require('sendgrid')(process.env.SENDGRID_API_KEY);
        const request = sg.emptyRequest({
          method: 'POST',
          path: '/v3/mail/send',
          body: email.toJSON()
        });
        sg.API(request, function(error, response) {
          console.log(response.statusCode);
          console.log(response.body);
          console.log(response.headers);
        });
```

The first console.log spits out the status code which 202.
The second console.log spits out nothing.
The last console.log spits out this:

```js
 { 
     server: 'nginx',
     date: 'Mon, 15 Aug 2016 08:59:42 GMT',
     'content-type': 'text/plain; charset=utf-8',
     'content-length': '0',
     connection: 'close',
     'x-message-id': 'kQdayBbvSKSb9ZlVDCUKTg',
     'x-frame-options': 'DENY' 
}
```

**Comment by thinkingserious** [comment]
Hello @Pashtunzoy,

Status code 202 means the email was queued for delivery and there should be no response body. The headers look correct.

Perhaps the email was filtered or sent to SPAM. Can you try using your email client to send to the same email address with the same test subject and body?

You can also check your activity feed to help debug: https://app.sendgrid.com/email_activity?

**Comment by Pashtunzoy** [comment]
@thinkingserious I actually did check that and I did receive emails through using my email client but won't go through Sendgrid? 
I looked at the activity section of my Sendgrid Dashboard and not a single activity has gone through.

**Comment by Pashtunzoy** [comment]
Btw, I also used the curl command example from your website and it still didn't work.

**Comment by thinkingserious** [comment]
Thanks for the update!

We will need our support team to dig deeper into your account. Could you please open a ticket at https://support.sendgrid.com?

**Comment by alfiepoleon** [comment]
Any further progress? I have the same issue, mails were sending, then they don't send anymore. Code is 202, which I was still getting when the mail was being sent.

**Comment by HemalR** [comment]
Did this get resolved at all?

**Comment by thinkingserious** [comment]
@HemalR,

Are you having a similar issue? If so, could you provide some details? Thanks!

**Comment by HemalR** [comment]
I was, then inexplicably, restarting my server and/or changing the test email addresses to live email addresses (my own), seemed to resolve the issue :/

So all good on my end (though I wish I had a definite answer as to what fixed it).

Thanks for the response though @thinkingserious

**Comment by thinkingserious** [comment]
Hi @HemalR 

I'm glad you got it figured out and thanks for following up!

**Comment by babaMar** [comment]
Hi @thinkingserious I'm actually experiencing the same issue, I checked my activity log and I see the email as processed, though I haven't got that. Here's my header:

`Server: nginx
Date: Thu, 24 Nov 2016 18:36:02 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: close
X-Message-Id: f3prb6QYRB2LxjkX2ltvnQ
X-Frame-Options: DENY
`

**Comment by thinkingserious** [comment]
@babaMar,

You may be having an issue with your account. Could you please contact our support team at https://support.sendgrid.com

Thanks!
