### ISSUE TITLE
Support throttling/retries to avoid Sendgrid API rate limits.

### ISSUE THREAD

**Issue by mrfelton** [sendgrid/sendgrid-nodejs#273]
#### Issue Summary

Sendgrid has [rate limits](https://sendgrid.com/docs//API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/rate_limits.html) on all of its web API's. These limits can be easy to hit if you are processing multiple items in some kind of loop.

This package should support these rate limits and enable automatic queueing of requests once the  limits have been reached, and automatic retries of failed messages.

**Comment by thinkingserious** [comment]
Great idea @mrfelton!

We have added this to our backlog. For it to move up our queue faster, we need +1s, comments or a pull request with a signed CLA.

**Comment by albert-the-creator** [comment]
+1

**Comment by thinkingserious** [comment]
Thanks for the upvote @albert-the-creator!

**Comment by mrfelton** [comment]
Initial concept added in https://github.com/sendgrid/sendgrid-nodejs/pull/278
