### ISSUE TITLE
How run the test suite?

### ISSUE THREAD

**Issue by mrfelton** [sendgrid/sendgrid-nodejs#274]
#### Issue Summary

Hi, I'm working on building something for #273 but I'm unsure how to run the test suite locally against a mocked backend. There is a lot of duplicated code scattered throughout the test suite that looks like you should be able to set `MOCK_HOST` to something in order to run the tests against something other than the live api.

Please can you explain how these tests are supposed to be run and any recommendations for developing locally? Thanks!

**Comment by thinkingserious** [comment]
That's awesome @mrfelton,

Apologies on the testing documentation, I've just updated it: https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#testing

We will be automating this soon, as we do here: https://github.com/sendgrid/sendgrid-python/blob/master/test/test_sendgrid.py#L19

Thanks!
