### ISSUE TITLE
Not able to figure out how to use substitutions

### ISSUE THREAD

**Issue by blanchma** [sendgrid/sendgrid-nodejs#276]
Here I paste the code I'm using to try to send substitutions. The email is sent with the template. The issue is I have in the template a `:variable` and `-variable-` and they are not replaced.

What am I missing? Thanks

var mailer = require('sendgrid')(process.env.SENDGRID_KEY);

var request = mailer.emptyRequest({
  method: 'POST',
  path: '/v3/mail/send'});
 

  request.body = {
    "from": {
       "email": "no-reply@test.com",
       "name": "Test"
     },
     "subject": "Hello, World!",
     "template_id": "80d243b2-383a-4378-9414-a94b824fa0e3",
     "personalizations": [
       {
        "to": [{
          "email": "tute@test.com",
          "name": "John Doe"
        }],
        "sub": {
          ":variable": [
            "TEST"
          ],
          "-variable-": [
            "TEST"
          ]
      },
      "filters": {
        "templates": {
          "settings": {
            "enable": 1,
            "template_id": "80d243b2-383a-4378-9414-a94b824fa0e3",
          }
        }
      }
    }
   ]
  }

  mailer.API(request, function (error, response) {
   console.log(response.statusCode)
   console.log(response.body)
   console.log(response.headers)
 });

**Comment by thinkingserious** [comment]
Please try replacing 'sub' with 'substitutions', please see https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/mail/mail.js

Thanks!

**Comment by blanchma** [comment]
@thinkingserious I did and now I get a Bad Request without mucho more info:

`var request = mailer.emptyRequest({
  method: 'POST',
  path: '/v3/mail/send'});

  request.body = {
    "from": {
       "email": "no-reply@avi-on.com",
       "name": "Avi-on Test"
     },
     "subject": "Hello, World!",
     "template_id": "80d243b2-383a-4378-9414-a94b824fa0e3",
     "personalizations": [
       {
        "to": [{
          "email": "tute@scvsoft.com",
          "name": "John Doe"
        }],
        "substitutions": {
          ":variable": [
            "TEST"
          ],
          "-variable-": [
            "TEST"
          ]
      }
    }
   ]
  }

  mailer.API(request, function (error, response) {
   console.log(response.statusCode)
   console.log(response.body)
   console.log(response.headers)
 });`

**Comment by blanchma** [comment]
I found the solution. I have to say: the documentation is far from clear. Thanks, @thinkingserious

**Comment by thinkingserious** [comment]
Glad you figured it out @blanchma!

We are working on an update to the docs, especially for templates. 

Is there anything specific you want us to make sure to cover?

Thanks!

**Comment by blanchma** [comment]
@thinkingserious Right now I'm migrating from mailchimp (who have a beautiful node library but we have problems to get out of black list) to sendgrid and for the moment the only inconvenient was substitutions in templates. Maybe later on I'll have more questions that would be great to be adressed in future doc's updates .

**Comment by thinkingserious** [comment]
We look forward to your feedback! Please feel free to open issues here as needed.

Welcome aboard!

**Comment by dan335** [comment]
I'm trying to figure out the same thing.  What was the solution?

**Comment by thinkingserious** [comment]
@dan335,

Can you share your code with us?

**Comment by dan335** [comment]
I got it working.  substitutions: {name:var} in the personalizations worked.  I never could get sections to work but don't need it anymore.

**Comment by thinkingserious** [comment]
Thanks for following up @dan335!
