### ISSUE TITLE
No 'Access-Control-Allow-Origin' header present

### ISSUE THREAD

**Issue by HR** [sendgrid/sendgrid-nodejs#281]
#### Issue Summary

I'm using the example code to send data from a webform submission to an email but it is failing to send it because of an inadequate request header. I'm using browserify to bundle sendgrid with js.

I'm getting the following error in console:

```
Fetch API cannot load https://api.sendgrid.com/v3/mail/send. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 405. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Error: Failed to fetch
```

I'm sending the request from the client side with the following headers:

``` js
headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
          'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept'
        }
```
#### Technical details:
- sendgrid-nodejs Version: master (latest commit: [69ed562e4c46e216dcb79f040a3577101508547d])
- Node.js Version: 6.3.0

**Comment by thinkingserious** [comment]
Have you tried:
```javascript
request.headers['Access-Control-Allow-Origin'] = '*'
```

I'm not sure why you are getting this error in the first place. Are you trying to send the email through the client side?

**Comment by HR** [comment]
I have but it doesn't work. I am sending it from client-side

**Comment by thinkingserious** [comment]
@HR,

A fix is in the works, but I don't know when it will be live. I suggest you comment on this thread: https://github.com/sendgrid/docs/issues/1417

For now, can you make an AJAX call to a server side script instead?

**Comment by mbernier** [comment]
Our API is setup to disallow CORS for browser requests, and maybe browserify is causing the requests to look like a web browser to the request client?

**Comment by duongtungls** [comment]
> @HR,
> 
> A fix is in the works, but I don't know when it will be live. I suggest you comment on this thread: [sendgrid/docs#1417](https://github.com/sendgrid/docs/issues/1417)
> 
> For now, can you make an AJAX call to a server side script instead?

For now 2019 this issue still occurs with request to `https://api.sendgrid.com/v3/mail/send` send from sendgrid-nodejs SDK

**Comment by remnahush** [comment]
Ok lets be honest... Why disable something that is my responsability? I'm storing the apiKey at Google Firebase for an app VueJS + Fibrebase, and it's not possible to figure out...! Hello man, it's an MVP... It's supposed to be fast and easy... If I cannot figure out I will move with another transactional mail provider... Seriously!

**Comment by aroach** [comment]
Generally speaking, this issue isn't something that will be resolved on the SendGrid side.  CORS enforcement is done by the browser.  You will need to refactor your app to not make an AJAX request to a different domain (e.g., api.sendgrid.com) from within the browser.  Here's a decent write up with alternative approaches: https://daveceddia.com/access-control-allow-origin-cors-errors-in-react-express/ , here's a document that we provide in the error message https://sendgrid.com/docs/for-developers/sending-email/cors/, and some background from Mozilla on CORS https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

You can see from the headers that SendGrid only allows cross origin calls from `https://sendgrid.api-docs.io`, which is our API reference documentation site.

```
> GET /v3/mail/send HTTP/1.1
> Host: api.sendgrid.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 405 Method Not Allowed
< Server: nginx
< Date: Wed, 08 May 2019 02:29:50 GMT
< Content-Type: application/json
< Content-Length: 76
< Connection: keep-alive
< Allow: POST
< Access-Control-Allow-Origin: https://sendgrid.api-docs.io
< Access-Control-Allow-Methods: POST
< Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
< Access-Control-Max-Age: 600
< X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
```

**Comment by m1cl** [comment]
just give me a solution.... I use nodejs and tried to send an email. If I cannot send an email with this lib, it s useless and should be deleted.

**Comment by austinbakker** [comment]
same problem, is really anoying

**Comment by childish-sambino** [comment]
Closing this as a non-library issue. The overall impression I'm getting is this is happening when attempting to invoke mail-send from a browser. Generally speaking, this should not be done. Placing this library in client-side code/scripting requires auth to be given to the client which exposes the auth to the end-user. API calls such as this should be made from a back-end server. Please open a separate issue if this is not the case.
