### ISSUE TITLE
How do I update the email of the recipient?

### ISSUE THREAD

**Issue by tomoktan** [sendgrid/sendgrid-nodejs#284]
Hello.
#### Issue Summary

How do I update the email of the recipient?
### My Code

```
var request = sendgrid.emptyRequest()
  request.body = [
    {
      email: newEmail
    },
    {
      email: preEmail
    }
  ];
  request.method = 'PATCH';
  request.path = '/v3/contactdb/recipients';
  return sendgrid.API(request)
  .then(result => console.log(result.body));
```
### Result Log

```
'{"error_count":0,"error_indices":[],"new_count":1,"persisted_recipients":["PRE_EXISTED_RECIPIENT_ID","NEW_EXISTED_RECIPIENT_ID"],"unmodified_indices":[0],"updated_count":0}'
```

> https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Update-Recipient-PATCH

will not be able to update the Recipient that already exists in Contactdb like this ?
#### Technical details:
- sendgrid-nodejs Version: master (latest commit: [commit number])
- Node.js Version: 5.4.0

**Comment by thinkingserious** [comment]
Hello @tomoktan,

I have added this to my backlog to investigate, but I suggest that you reach out to https://support.sendgrid.com as you will probably get a faster response time.

Thanks!

**Comment by Zakini** [comment]
@tomoktan what did support come back with? Is there a way of updating a recipient's email address?

**Comment by lunchbag** [comment]
+1 on this.
Looks like we're unable to update a recipient by recipient_id either. My guess is that they won't allow you to change the e-mail of the recipient since that action is also blocked on the web UI. Maybe you'll just have to delete and re-create the user under a different e-mail address..

**Comment by thinkingserious** [comment]
Hello @lunchbag,

Please [open a ticket with support](https://support.sendgrid.com/) as well. I'm hoping that we can increase the visibility of this issue.

Thank you!

With Best Regards,

Elmer

**Comment by rlwy** [comment]
+1 on this for me too.
I tried the API but all I got was a new entry to the global contact list with the new email. I didn't realize it was an issue until I saw this!

**Comment by childish-sambino** [comment]
`email` is a required field when calling this API so you inherently can't change the contact's email address. As @lunchbag commented, re-creating the user is the best bet.

**Comment by jer-tx** [comment]
This is a pretty basic feature. Surely theres a better/more streamlined way of doing this..?

Are you saying the recommendation is to _delete_ the user (and all analytics tied to them) and re-create them??

**Comment by vinoses** [comment]
Sendgrid support response:

At this time the email address is the unique identifier for the contact. Therefore, at this time, the contact will need to be deleted and readded if you want to edit the contact. That said, this is not permanent and we are going to have the unique ID for the contact something that is not the email address. You'll be able to change the email address with the contact ID. I'm not sure when that will be released but I know it's what we are planning on doing. Let me know if you have any questions.

**Comment by brunolemos** [comment]
Arrived here by a Google search. This seems to be possible now according to the docs:

`PATCH https://api.sendgrid.com/v3/contactdb/recipients`

```js
[
  {
    "email": "new-email@example.com",
    "last_name": "Jones"
  },
  {
    "email": "pre-existing_email@example.com"
  }
]
```

https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Update-Recipient-PATCH

**Comment by Iversongandy** [comment]
A year later and this STILL isn't fixed?? This is a pretty basic feature. I will be transitioning to a new system, as I have a mobile app that I was going to Sendgrid to store members as contacts, but if a member updates their email, I can't update that in Sendgrid. Sendgrid should be pretty embarrassed by this.
