### ISSUE TITLE
How to insert dynamic blocks of html inside email

### ISSUE THREAD

**Issue by yanosh-igor** [sendgrid/sendgrid-nodejs#285]
I'm using web API v3.
Trying to generate  personalization object which includes many recipients. Each recipient has 1 email with data that related to current recipient (pass with substitutions)
here example:
```
personalizations: [{
      to: [{email: 'example@mail.com'}],
      subject: 'Hello, :name!',
      substitutions: {':name': 'John', ':info_section_html':'<p>Some useful block1</p><p>Some useful block2</p>'}
    },
{
      to: [{email: 'example@mail.com'}],
      subject: 'Hello, :name!',
      substitutions: {':name': 'John', ':info_section_html':'<p>Some useful block1</p><p>Some useful block2</p><p>Some useful block3</p><p>Some useful block4</p><p>Some useful block5</p><p>Some useful block6</p>'}
    }
],
    from: {email: 'send@example.com'},
    content: [{type: 'text/html', value: 'Hello, :name! </br> Here are your very usefull info</br> :info_section_html'}]
```

When substitution :info_section_html has a lot of such blocks it crossed a limit of 10000 bytes.
My blocks have a lot more HTML than in example.
Each recipient can have a different number of blocks that's why I can't include them in content attribute.

Also was thinking about sections attribute where I can pass HTML of my info_section_html.
But can't pass array of data in substitution.

Can you please suggest how to overcome this?

**Comment by thinkingserious** [comment]
Hello @yanosh-igor,

Please reach out via https://support.sendgrid.com. We will do our best to help!
