### ISSUE TITLE
How do I add attachments?

### ISSUE THREAD

**Issue by RichardJECooke** [sendgrid/sendgrid-nodejs#287]
Our emails are sending fine and we now want to add an attachment. So we copied this example: https://github.com/sendgrid/sendgrid-nodejs/blob/93763a74a85969382d59fcb3708d22051498f998/examples/helpers/mail/example.js

And made code like so:

``` Typescript
const sendgrid: any = require('sendgrid')(process.env.sendgrid_key);

sendEmail(data: IEmailData): void {
    const email: any = new sendgrid.Email();
    email.addTo(data.emailTo);
    for (let attachment in data.attachments)
      this.addAttachment(email, attachment);
    sendgrid.send(email, (error: any, json: string) => {
      if (error)
        console.log(error);
    });
  }

  addAttachment(email: any, attachmentData: any): void {
    const attachment = new sendgrid.Attachment();
    attachment.setContent(attachmentData.content);
    attachment.setType(attachmentData.type);
    attachment.setFilename(attachmentData.filename);
    attachment.setDisposition(attachmentData.disposition);
    email.addAttachment(attachment);
  }

```

But when calling `sendEmail` we get told `sendgrid.Attachment is not a function` (first line of the second function).

I printed out the sendgrid object and it looks like this:

``` json
{ api_key: 'SG.DaV0L',
  api_user: null,
  options: 
   { uriParts: 
      { protocol: 'https',
        host: 'api.sendgrid.com',
        port: '',
        endpoint: '/api/mail.send.json' },
     uri: 'https://api.sendgrid.com/api/mail.send.json' },
  version: '1.9.2',
  Email: [Function: Email],
  smtpapi: [Function: smtpapi],
  send: [Function] }
```
- Is the example wrong? 
- Should we get the attachment helper class some other way?

Thank you,
Richard.

**Comment by RichardJECooke** [comment]
Figured out after reading the code. That example in github is totally wrong. Should be like this:

```typescript
addAttachment(email: any, attachmentData: any): void {    
    email.addFile(attachment);
  }
```

**Comment by thinkingserious** [comment]
Thanks @RichardJECooke,

We will investigate further and fix the example. Thanks for taking the time to share the solution!

If you email us at dx@sendgrid.com with your mailing address and T-shirt size, we would love to send you some swag. 

Thanks!

**Comment by thinkingserious** [comment]
We now have an attachment example here: https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#attachments

**Comment by MichaelBiermann** [comment]
The example currently shows a 404 ( https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md ). Same does the npm docu link for examples: https://www.npmjs.com/package/sendgrid#usage -> Examples

**Comment by thinkingserious** [comment]
Hello @lvh1g15,

I think you need to add a `disposition: inline`, [like so](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#attachments).

With Best Regards,

Elmer

**Comment by piavgh** [comment]
@thinkingserious : Hi, do you know how to send an attachment with the transactional template?

**Comment by devmohitagarwal** [comment]
@thinkingserious  is there a way I can add a URL attachment to my email, what are the other ways I can add attachment to my email. couldn't exactly find a doc stating the ways attachment work On Sendgrid.

Regards,
Mohit

**Comment by mike-seekwell** [comment]
> @thinkingserious : Hi, do you know how to send an attachment with the transactional template?

if you're using the v3 API, just added a `attachments` key. `content` needs to be Base64 encoded

https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

```
email = {
   "from":{  
      "email":"contact@seekwell.io"
   },
   "personalizations":[  
      {  
         "to":[  
            {  
               "email" : "contact@seekwell.io"
            }
         ],
         "dynamic_template_data": {
         }
      }
   ],
   "attachments": [
       {
           "content": "",
           "filename" ""
       }
   ]
   "template_id":"someid"
}
```

**Comment by rob5408** [comment]
> The example link is not working.
> This is the new link:
> https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/attachments.md

The new new link: https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/attachments.md
