### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by sedouard** [sendgrid/sendgrid-nodejs#291]
#### Issue Summary

Module doesn't expose root function

#### Steps to Reproduce

1. This is the first step
```
// According to the README this should work
// produces error:
// TypeError: require(...) is not a function
var sg = require('sendgrid')(process.env.SENDGRID_API_KEY);
```
Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-nodejs Version: 3.0.11
* Node.js Version: 5.12.0

Either the documentation needs to be updated to use `require('sendgrid').SendGrid` constructor or the module needs to expose the function specified in the README correctly.

Happy to send a PR for the README.

**Comment by sedouard** [comment]
Woops -- realize I'm a complete version off! how embarassing.

**Comment by thinkingserious** [comment]
@sedouard no problem! Thanks for supporting SendGrid :)
