### ISSUE TITLE
REST API details should not need to be included for sending email

### ISSUE THREAD

**Issue by mikemaccana** [sendgrid/sendgrid-nodejs#297]
#### Issue Summary

Helper shouldn't require user to care about methods or paths: it should help people send emails with sensible defaults, like every other API client on npm. 

#### Steps to Reproduce

1. Look at sendgrid v2. 
2. Use sendgrid v4 and wonder why helper.Email() (at least according to the examples) code requires lower level concepts. I don't care about what your endpoint is, unless I'm overriding it, that's why I;m sing you library rather than raw requests. Have sensible defaults.

**Comment by eizzo** [comment]
> it should help people send emails with sensible defaults, like every other API client on npm

Unfortunately this module behaves more like a basic helper set for constructing sendgrid payloads. And it ought to prevent malformatted json from hitting the API in the first place. At the very least, proper documentation would be preferred to learning of the module's shortcomings through errors in the API response body. Definitely needs more polish all around.

**Comment by thinkingserious** [comment]
Hello @mikemaccana, 

You are correct and changes are coming soon, please see: https://github.com/sendgrid/sendgrid-nodejs/issues/290

@eizzo,

Yes, the purpose of this first rewrite was to get low level support for all of the v3 Web API going, while removing the tight coupling the previous library had on the previous mail send endpoint. We invite you to join us on that journey, please take a look at this when have a moment: https://github.com/sendgrid/sendgrid-nodejs/issues/290

I'm looking forward to both of your feedback as we continue down the road of fully implementing this library.

Thanks for your support!

I'm closing this ticket; however, please feel free to open new issues or pull requests with specific implementation details or ideas.

**Comment by honkskillet** [comment]
Any help coming soon to remove/sidestep this helper madness?

**Comment by thinkingserious** [comment]
Hi @honkskillet,

Yes :)

Please follow the [Mail Helper Enhancement (v3 mail/send) project](https://github.com/sendgrid/sendgrid-nodejs/projects) if you would like to follow or contribute. @adamreisnz will propose the new helper interface there for community feedback.

With Best Regards,

Elmer
