### ISSUE TITLE
Helper class not work on node 6?

### ISSUE THREAD

**Issue by lrcry** [sendgrid/sendgrid-nodejs#298]
#### Issue Summary

I tried the helper class which described in [README](https://github.com/sendgrid/sendgrid-nodejs#with-mail-helper-class) on node 6.5.0, it seemed not to work.

In the case of mine, it got stuck at the following step:

``` javascript
var request = sg.emptyRequest({
  method: 'POST',
  path: '/v3/mail/send',
  body: mail.toJSON(),
});
```

While when I used the API without the helper class, it worked fine.

I am trying to read the source codes to find it out.
#### Steps to Reproduce
1. Just run the example with helper class on node v6.5.0.
#### Technical details:
- sendgrid-nodejs Version: 4.3.0 (found from [npm](https://www.npmjs.com/package/sendgrid))
- Node.js Version: 6.5.0

**Comment by thinkingserious** [comment]
Hello @lrcry,

We don't currently test against 6.5. Could you please let us know what the error is, so we can help troubleshoot?

Thanks!

**Comment by lrcry** [comment]
G'day @thinkingserious ,

As far as I could see, it just got stuck there instead of giving me anything in a few minutes I waited.

I will do some deeper investigation to find out what is happening. At present it seems okay to use the API without the helper class in my case.

I am a newbie to nodejs actually. Just wondering what more details I can provide to help resolve it?

Warm regards,

**Comment by fyockm** [comment]
FWIW, I'm using the helper class with Node v6.6 and it's working fine for me.

**Comment by thinkingserious** [comment]
Thanks for the confirmation @fyockm.

@lrcry,

Could you please give me the full source you are running so I can try to duplicate your error? You can send it to dx@sendgrid.com if you prefer.
