### ISSUE TITLE
Create a simple web server that can consume Incoming Parse data

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#302]
Acceptance Criteria:
- Should be deployable locally and on Heroku
- Setting are configured in an external configuration file
- There should be two endpoints, / and inbound (set in configuration). The former should accept GETs and the latter POSTs
- When receiving an Inbound Parse payload, return a 200 status to SendGrid

Reference:
- https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/inbound/app.py
- https://sendgrid.com/docs/Classroom/Basics/Inbound_Parse_Webhook/setting_up_the_inbound_parse_webhook.html
- https://sendgrid.com/docs/API_Reference/Webhooks/parse.html

**Comment by techpool** [comment]
Hey I would like to take a lead on this, can someone just give me a basic guideline and understanding about this issue in brief? That would be great then.

**Comment by thinkingserious** [comment]
My apologies @techpool,

This one has been completed: https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/inbound-mail-parser

Over the next few days I'm going to be cleaning up the issues and tagging them appropriately for Hacktoberfest. I'm looking forward to working with you!
