### ISSUE TITLE
The Mail helper object doesn't work without a content body and a subject line

### ISSUE THREAD

**Issue by BillBrower** [sendgrid/sendgrid-nodejs#306]
#### Issue Summary

The Mail helper object doesn't set `from_email` or add personalizations if either a content body or a subject line isn't provided on instantiation. Which creates unexpected behavior around templates. A template with a predefined subject, for example, wouldn't be sendable without overriding the subject and providing additional content.

Note that I'm using 2.0.0 on a legacy project but the latest code in master still seems to expect a subject and content.

```
if (from_email && subject && to_email && content) {
    this.setFrom(from_email);
    var personalization = new Personalization();
    personalization.addTo(to_email);
    this.addPersonalization(personalization);
    this.setSubject(subject);
    this.addContent(content);
}
```
#### Steps to Reproduce
1. Make a transactional email template, with one substitution ('-url-), in the SendGrid web app.
2. Define default subject line for the above transactional email template
3. Set the SENDGRID_API_KEY environment variable to your SendGrid API key
4. Run this code:

```
sendgrid = require('sendgrid')(process.env.SENDGRID_API_KEY);
var email = new sendgrid.Email();
email.addTo('test@example.com');
email.setFrom('test@example.com');
email.setFromName('Example');
email.addFilter('templates', 'enable', 1);
email.addFilter('templates', 'template_id', '13b8f94f-bcae-4ec6-b752-70d6cb59f932');
email.setSubstitutions({
    '-url-': 'example.com'
});
sendgrid.send(email, function (err, json) {
    if (err) console.log(err);
});
```
#### Technical details:
- sendgrid-nodejs Version: 2.0.0
- Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Hello @BillBrower,

The subject and content is no longer necessary when using a template. 

I have added this to our backlog for a fix. Thanks!

**Comment by blakeembrey** [comment]
I believe I just run into this issue as well. Wouldn't it be reasonable to make them all `||` instead? Or, even better, just always call it? It's pretty unexpected that you can't omit a parameter - I run into it omitting `content` because I had two bodies I needed to add but the rest was following the README example.

**Comment by adamreisnz** [comment]
The mail helpers are severely broken it seems. I can't send out an email anymore when I don't provide content in the `Mail` constructor, but use `mail.addContent()` instead.

**Comment by thinkingserious** [comment]
Thanks for the votes of confirmation @blakeembrey and @adamreisnz. That will help move this issue up our queue.

In the mean time, for your use cases, do not use the Mail constructor, instead, please follow this method: https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L15

Thanks everyone!

**Comment by thinkingserious** [comment]
This will be fixed with https://github.com/sendgrid/sendgrid-nodejs/pull/378
