### ISSUE TITLE
incorrect typescript type definition file

### ISSUE THREAD

**Issue by rickyk586** [sendgrid/sendgrid-nodejs#307]
Type definition in index.d.ts does not match method signature from documentation

index.d.ts:
`API(request: SendGrid.Rest.Request, callback: (response: SendGrid.Rest.Response) => void): void;`

documentation:
```
//With promise
sg.API(request)
```
and
```
//With callback
sg.API(request, function(error, response) {
```

**Comment by thinkingserious** [comment]
cc @SPARTAN563

**Comment by thinkingserious** [comment]
Thanks for reporting this @rickyk586. I've added this to our backlog for a fix.

**Comment by SPARTAN563** [comment]
Sure, will take a look in a second.

**Comment by SPARTAN563** [comment]
@rickyk586  I have added a pull request adding an overloaded method for the promise use case, let me know if that satisfies your requirement or if you'd like me to expand it further.

**Comment by rickyk586** [comment]
@SPARTAN563 Works perfectly! Thanks!
