### ISSUE TITLE
Send a Single Email to a Single Recipient

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#312]
Acceptance Criteria:
- A email object that represents the response body payload
- A mail object that handles sending email objects, data validation and error handling

Reference:
- https://github.com/sendgrid/sendgrid-nodejs/tree/master/lib/helpers/mail
- https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md
- https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

**Comment by Puigcerber** [comment]
Hi @thinkingserious!

Trying to find my fourth PR for this year #hacktoberfest I've seen [those exclusive pins](https://sendgrid.com/blog/happy-hacktoberfest/) and I would like to give it a go.

As I've never used Sendgrid before I'm a bit lost on where to start and understanding the issue. Is about extending the mail helper? Documenting how to send a single mail? I would love some clarifications.

Cheers, Pablo.

**Comment by thinkingserious** [comment]
Hello Pablo,

First, I suggest you review the entire "Mail Helper Enhancement (v3 mail/send)" [project](https://github.com/sendgrid/sendgrid-nodejs/projects).

We want to refactor the mail helper so that it makes executing the use cases defined in this project as simple as possible.

For example now our hello world to send a single email looks like this:

```javascript
var helper = require('sendgrid').mail;
var from_email = new helper.Email('test@example.com');
var to_email = new helper.Email('test@example.com');
var subject = 'Hello World from the SendGrid Node.js Library!';
var content = new helper.Content('text/plain', 'Hello, Email!');
var mail = new helper.Mail(from_email, subject, to_email, content);

var sg = require('sendgrid')(process.env.SENDGRID_API_KEY);
var request = sg.emptyRequest({
  method: 'POST',
  path: '/v3/mail/send',
  body: mail.toJSON(),
});

sg.API(request, function(error, response) {
  console.log(response.statusCode);
  console.log(response.body);
  console.log(response.headers);
});
```

One way to improve it could be:

```javascript
var mail = require('sendgrid').mail;
mail.AddFromEmail('test@example.com');
mail.AddToEmail('test@example.com');
mail.AddSubject('Hello World from the SendGrid Node.js Library!');
mail.AddContent('text/plain', 'Hello Email!');

var sendgrid = require('sendgrid')(process.env.SENDGRID_API_KEY);
sendgrid.send(mail, function(error, response) {
  if(error) {
      console.log(error.message);
      console.log(error.response.statusCode);
      console.log(error.response.body);
      console.log(error.response.headers);
  } else {
    console.log(response);
  }
});
```

**Comment by Puigcerber** [comment]
Ok, so it's a complete refactor. I'll try to find some time to give it a try.

**Comment by thinkingserious** [comment]
In progress here: #378
