### ISSUE TITLE
Send a Single Email to Multiple Recipients

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#313]
Acceptance Criteria:
- A email object that represents the response body payload
- A mail object that handles sending email objects, data validation and error handling

Reference:
- https://github.com/sendgrid/sendgrid-nodejs/tree/master/lib/helpers/mail
- https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md
- https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

**Comment by thinkingserious** [comment]
In progress here: #378

**Comment by tetreault** [comment]
Can this be reflected more accurately on the docs? It doesn't seem great to have to trawl thru github to find a clear example of such a common use case.

**Comment by thinkingserious** [comment]
Hi @tetreault,

Yes, we will be updating the docs as well. You will find the new examples [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md).

Thank you for your feedback!

With Best Regards,

Elmer

**Comment by tetreault** [comment]
Awesome, glad to hear it @thinkingserious. That was my only gripe haha otherwise SendGrid has been great, am using it in conjunction with Azure for a client project right now.

**Comment by thinkingserious** [comment]
Thanks @tetreault!

Always feel free to reach out if you have any other hiccups :)
