### ISSUE TITLE
Send Multiple Emails to Multiple Recipients

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#314]
Acceptance Criteria:
- A email object that represents the response body payload
- A mail object that handles sending email objects, data validation and error handling

Reference:
- https://github.com/sendgrid/sendgrid-nodejs/tree/master/lib/helpers/mail
- https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md
- https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

**Comment by adamreisnz** [comment]
Is this supported at all by the Sendgrid API? All I could find was sending the same email to multiple recipients, with substitutions, but that's not really the same as sending multiple different/pre-generated emails to multiple recipients.

**Comment by thinkingserious** [comment]
Hello @adamreisnz,

I believe this is the use case: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/personalizations.html#-Sending-Two-Different-Emails-to-Two-Different-Groups-of-Recipients

**Comment by adamreisnz** [comment]
Ah yes, I found that out a couple of days ago, thanks!

**Comment by thinkingserious** [comment]
In progress here: https://github.com/sendgrid/sendgrid-nodejs/pull/378
