### ISSUE TITLE
Automate StopLight.io's Prism mock server on Travis CI and locally

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#316]
#### Issue Summary

In the Travis CI and local environment:
1. Download the appropriate Prism binary (if it does not exist on the system)
2. Start Prism, using SendGrid's swagger (oai) definition
3. Run the Unit Tests
4. Shut Down Prism
#### References

https://stoplight.io/prism
https://raw.githubusercontent.com/sendgrid/sendgrid-oai/master/oai_stoplight.json

We have already done this in these libraries:

Python:
https://github.com/sendgrid/sendgrid-python/blob/master/.travis.yml#L14
https://github.com/sendgrid/sendgrid-python/blob/master/test/prism.sh
https://github.com/sendgrid/sendgrid-python/blob/master/test/test_sendgrid.py#L22

PHP:
https://github.com/sendgrid/sendgrid-php/blob/master/.travis.yml#L3
https://github.com/sendgrid/sendgrid-php/blob/master/test/prism.sh
https://github.com/sendgrid/sendgrid-php/blob/master/test/unit/SendGridTest.php#L13

C#:
https://github.com/sendgrid/sendgrid-csharp/blob/master/.travis.yml#L9
https://github.com/sendgrid/sendgrid-csharp/tree/master/prism
https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/UnitTest/UnitTest.cs#L23

Go:
https://github.com/sendgrid/sendgrid-go/blob/master/.travis.yml#L4
https://github.com/sendgrid/sendgrid-go/blob/master/prism.sh
https://github.com/sendgrid/sendgrid-go/blob/master/sendgrid_test.go#L35

**Comment by tsriram** [comment]
I'd like to take this up!

**Comment by thinkingserious** [comment]
Thanks @tsriram! That's awesome!

Could you please send over a [signed CLA](https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#cla) so that we will be able to merge your changed? Thanks!

**Comment by tsriram** [comment]
@thinkingserious do I need to physically sign the CLA, scan and send it by email? Or just filling in the details & sending it by email will do?

**Comment by thinkingserious** [comment]
Hello @tsriram,

You can scan and email it. You can also use a PDF app that allows you to digitally sign or a service like www.docusign.com.

**Comment by tsriram** [comment]
@thinkingserious I'm going to be on vacation till Oct 23 and couldn't start work on this yet. Will start once I'm back if nobody is taking it up till then.

**Comment by thinkingserious** [comment]
@tsriram,

Congrats on the vacation, see you when you get back. Enjoy!

**Comment by thinkingserious** [comment]
Hi @tsriram,

How are things going? Is there anything I can do to help?

**Comment by tsriram** [comment]
@thinkingserious sorry for responding late. Have been caught up with a lot of work after vacation as we have a release in early November. I'm afraid if I'll be able to work on this till then :frowning_face:

**Comment by thinkingserious** [comment]
@tsriram,

No worries, thanks for following up!

**Comment by SendGridDX** [comment]
Hello @tsriram,

Are you still interested in continuing this work? We are currently [beginning work on a redesign](https://github.com/sendgrid/sendgrid-nodejs/pull/378) and completing this would be very helpful.

With Best Regards,

Elmer

**Comment by tsriram** [comment]
Hey @SendGridDX, I won't be able to work on this now as I've too many things to look after. Sorry guys :(

**Comment by SendGridDX** [comment]
No problem @tsriram,

Thanks for letting us know.

**Comment by thinkingserious** [comment]
Completed with this release: https://github.com/sendgrid/sendgrid-nodejs/releases/tag/v5.1.0
