### ISSUE TITLE
Update nodejs-http-client dependency to v2.3.0

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#317]
https://github.com/sendgrid/nodejs-http-client/releases/tag/v2.3.0

**Comment by matankb** [comment]
From what I saw in the release, this won't actually require any changes in the codebase, just an upgrade in `package.json` - is that correct?

**Comment by aszx87410** [comment]
I want to work on this issue. thanks.

**Comment by thinkingserious** [comment]
That's awesome @aszx87410! Thanks!

Please take a moment to [sign our CLA](https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#cla) so we can merge your changes.

**Comment by thinkingserious** [comment]
Received! Thanks!
