### ISSUE TITLE
Breaking Change in 4.7 Release

### ISSUE THREAD

**Issue by csaroff** [sendgrid/sendgrid-nodejs#324]
In the previous version of of sendgrid that I was using(4.3.0), the batch api returned a promise which resolved to an object whose body was a string.

``` javascript
sg.API({
  method: 'POST',
  path: '/v3/mail/batch'
})
.then((response) => {
  console.log(response.body);
  console.log(response.body.batch_id);
  console.log(JSON.parse(response.body).batch_id);
})
.catch(console.trace);
// { batch_id: 'mybatchid' }
// undefined
// mybatchid
```

It appears that in 4.7.0 the batch api returns a promise which resolves to an object whose body is an object.  My code that was using 4.3.0 had to call JSON.parse in order to grab the batch_id.  The new output of the above code is this.

```
{ batch_id: 'mybatchid' }
mybatchid
Trace: [SyntaxError: Unexpected token o]
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

This seems like a pretty serious breaking change to me.  I thought it might be considered as a patch except that, as far as I am aware, there is no standardization that allows the API consumer to know that the previous behavior was a defect.  AFAIK, the implementation _is_ the standard.

What this really boils down to is that module consumers who have pinned the major version of this library will have broken code when attempting to reinstall their node_module dependencies.

Ultimately, I really like and appreciate the change, but IMO it belongs in 5.x instead of 4.x.  I believe this change was discussed in #266.
- sendgrid-nodejs Version: 4.3.0 -> 4.7.0
- Node.js Version: 5.11.1

**Comment by thinkingserious** [comment]
My apologies and thanks for taking the time to detail the issue!

I will [unpublish](https://docs.npmjs.com/cli/unpublish) the breaking version and re-publish as a major version bump.

If you have a moment, [please fill out this form](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) and we'll get some swag over to you :)
