### ISSUE TITLE
SendAt - recipient timestamp = time email was scheduled VS time it gets sent

### ISSUE THREAD

**Issue by HemalR** [sendgrid/sendgrid-nodejs#326]
Not entirely sure whether this is by design or an error.

#### Issue Summary

When I send an email that is scheduled to be sent in the future, when it does get sent, the 'time received' on the recipient side is the date/time that the original scheduling event happened (as opposed to the time the email was actually sent).

#### Example scenario

In the app I am building, I wish to remind users about an upcoming appointment, e.g 1 hour prior to the appointment time.

1. Appointment time is originally put in to the app, e.g. 2 days prior
2. Reminder email is set to be sent 1 hour prior to event
3. Email gets sent by Sendgrid at the specified time, but, when the recipient opens it, they see it as having been sent 2 days ago as opposed to the time they actually received it.

- - - 

Just wondering if this is by design or something that can/will be fixed. If by design then I will need to do the scheduling on my end else my users are going to think that they missed their appointment due to the timestamp not adding up.

Thanks!

**Comment by thinkingserious** [comment]
Hello @HemalR,

Could you please open up a ticket at https://support.sendgrid.com so this can get on our queue for resolution? 

Thanks!

**Comment by SherifMedhat** [comment]
@HemalR Did you find a fix for this issue?

**Comment by HemalR** [comment]
@SherifMedhat Nope! The closest workaround I got was to not schedule emails at all and just use a frequently firing cron job (not ideal by any means!).

I didn't get a response from the support ticket I raised and I found an older Github bug report referencing the exact same thing as well so I suspect this is not on their priority list to fix.

Anyway, this issue, Sendgrid has been solid to work with, so comes down to how critical you feel this is.

**Comment by SherifMedhat** [comment]
@HemalR This is very a weird behavior from SendGrid!!

@thinkingserious Are you going to fix this issue soon??

**Comment by thinkingserious** [comment]
@HemalR,

Can you please send me your support ticket number? dx@sendgrid.com

@SherifMedhat,

We are not best equipped to help with this issue, since it is not related to the SDK. Could you please open up a ticket with our [support team](https://support.sendgrid.com)? Thanks!

With Best Regards,

Elmer

**Comment by HemalR** [comment]
Yup - Request #786653

Ticket lodged on October 28th. It's been marked on your internal Zendesk as 'solved' :S 

[Zendesk support.pdf](https://github.com/sendgrid/sendgrid-nodejs/files/856728/Zendesk.support.pdf)

**Comment by thinkingserious** [comment]
Thank you @HemalR,

I will follow up.

**Comment by tetreault** [comment]
is this an actual issue? i rely on sendgrid a lot and will soon be using the scheduling "sendAt" feature and don't want to stumble on this bug if it hasn't been resolved @thinkingserious

**Comment by thinkingserious** [comment]
@tetreault,

I don't think so. I doubled checked with our support team.

@HemalR,

It looks like one of our support members reached back out in March to follow up. Did you receive that email?

**Comment by HemalR** [comment]
@thinkingserious 

😕Not to my knowledge no. What March are we referring to here? 2017 or 2018?

I can't really comment on this issue any more regardless - due to the bug, we ended up transitioning our email elsewhere and haven't had a reason to change again/retry Sendgrid.

**Comment by thinkingserious** [comment]
Thanks for the follow up @HemalR!

Please let me know if you run into any issues @tetreault.

**Comment by vmal** [comment]
@HemalR Can you tell me which email service did you transition to. Because, even i encountered this issue and would prefer an api that lets me schedule email with some analytics. Thanks in advance!

**Comment by HemalR** [comment]
I'm using Postmark (and Mailjet in another related app) - but the scheduling is now all in-house (so I guess from the scheduling perspective, it isn't really relevant anymore)

**Comment by dandv** [comment]
This is a major issue. Has it been resolved? It basically renders the entire `sendAt` feature semi-useless. :-/
