### ISSUE TITLE
Question: Is it possible to use a template from my Node project's `views` folder?

### ISSUE THREAD

**Issue by NetOperatorWibby** [sendgrid/sendgrid-nodejs#331]
I understand that there is a template function with Sendgrid, but I want to know if it is at all possible for me to use a template from my project folder to send email.

I'm using `hbs` and `hbs-utils` so I can do things like create layouts and then put `{{{ body }}}` where I want content to go. Is this possible with email?

**Comment by thinkingserious** [comment]
Hello @NetOperatorWibby,

Unfortunately, I do not have any experience with this use case. Could you please reach out to our support team at https://support.sendgrid.com? Thanks!

**Comment by mylastore** [comment]
> I understand that there is a template function with Sendgrid, but I want to know if it is at all possible for me to use a template from my project folder to send email.
> 
> I'm using `hbs` and `hbs-utils` so I can do things like create layouts and then put `{{{ body }}}` where I want content to go. Is this possible with email?

Has sendgrid responded to this question? I also want to be able to send hb templates
