### ISSUE TITLE
Get list of all emails sent

### ISSUE THREAD

**Issue by jaspersorrio** [sendgrid/sendgrid-nodejs#334]
#### Issue Summary

How do I get a list of the previous emails sent?

**Comment by thinkingserious** [comment]
Hello @jaspersorrio,

Either through the [SendGrid dashboard](https://sendgrid.com/docs/User_Guide/email_activity.html) or via our [Event Webhook](https://sendgrid.com/docs/API_Reference/Webhooks/event.html).
