### ISSUE TITLE
Error message when trying to send transactional email

### ISSUE THREAD

**Issue by tommaton** [sendgrid/sendgrid-nodejs#337]
Hi,

I keep on getting the following error when trying to send a transactional email using a template I've setup within sendGrid.

**Status code:** 400
**Error message:** message: 'Bad Request', field: null, help: null

I've followed the following example: https://github.com/sendgrid/sendgrid-nodejs#without-mail-helper-class and have developed the following, its probably something simple i've missed or missunderstood. 

````
            const subject = 'Email subject';
            const templateId = 'myTemplateId';
            const sg = require('sendgrid')(myapikey);
            const request = sg.emptyRequest({
                method: 'POST',
                path: '/v3/mail/send',
                body: {
                    "personalizations": [
                        {
                            "to": userEmails, // aray of user emails
                            "substitutions": {
                                "-userName-": userDetails.name,
                                "-productPrice-": productDetails.price,
                                "-productUrl-": productDetails.url,
                                "-productName-": productDetails.name,
                            },
                            "subject": subject
                        }
                    ],
                    "from": {
                        "email": "myemail",
                        "name": "myname"
                    },
                    "content": [
                        {
                            "type": "text/html"
                        }
                    ],
                    "template_id": templateId
                }
            });

            sg.API(request, function (error, response) {
                if (error) {
                    console.log('Error response received');
                }
                console.log(response.body.errors);
            });
````

#### Technical details:

* sendgrid-nodejs Version: 4.7.1
* Node.js Version: 6.6

Thanks in advance.
Tom

**Comment by thinkingserious** [comment]
Hello Tom,

I believe you should either remove the `content` block or add a `value`.

You might also try working through this example: https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#without-mail-helper-class

With Best Regards,

Elmer

**Comment by tommaton** [comment]
@thinkingserious I forgot to update this, I found the issue.

The value of `productDetails.price` was a number (189.95) once I converted this to a string it now works.

**Comment by thinkingserious** [comment]
@tommaton,

Sorry you had to work through that and you are not the first one :(

One of the things we will be adding to the new version of the mail helper is auto-conversion to string.
