### ISSUE TITLE
Uncaught Syntax Error: Unexpected token < (in lib/sendgrid.js triggered on a response object)

### ISSUE THREAD

**Issue by iamgollum** [sendgrid/sendgrid-nodejs#339]
#### Issue Summary

After sending out a templated email using SendGrid's email helper utility. The server response from SendGrid's API is returning invalid JSON according to this wrapper (sendgrid-nodejs).

```
Uncaught SyntaxError: Unexpected token <
      at Object.parse (native)
      at node_modules/sendgrid/lib/sendgrid.js:110:42
      at IncomingMessage.<anonymous> (node_modules/sendgrid/node_modules/sendgrid-rest/lib/client.js:108:9)
      at endReadableNT (_stream_readable.js:921:12)
```

Line 110 is:

```
  //Use callback
  self.client.API(request, function(response) {
    response.body = response.body ? JSON.parse(response.body) : response.body;
```

#### Steps to Reproduce

1. Ensure sendgrid node package -->"sendgrid": "^4.7.1",
2. Create a template with substitutions in SendGrid and activate that template
3. Create a full email for the template using the email helper. apply .toJSON at end.

Example:
```
const BaseWelcomeEmail = (function(){
    const helper = require('sendgrid').mail,
        from_email = new helper.Email(testEmail),
        to_email = new helper.Email(testEmail),
        subject = "Welcome to Bedly",
        content = new helper.Content("text/plain", "hello"),

        mail = new helper.Mail(from_email, subject, to_email, content),
        personalization = new helper.Personalization();

    let substitution = new helper.Substitution(":firstname", "Aaron");

    personalization.addSubstitution(substitution);
    substitution = new helper.Substitution(":lastname", "Elk");
    personalization.addSubstitution(substitution);
    substitution = new helper.Substitution(":address", "96 Washington Avenue");
    personalization.addSubstitution(substitution);
    substitution = new helper.Substitution(":neighborhood", "Washington Heights");
    personalization.addSubstitution(substitution);
    substitution = new helper.Substitution(":unitNumber", "N/A");
    personalization.addSubstitution(substitution);
    substitution = new helper.Substitution(":roomNumber", "2J");
    personalization.addSubstitution(substitution);

    mail.addPersonalization(personalization);
    
    return mail;
})();
```

You can even create a mocha test, I ran this from this test environment:

```
    describe('Test Email Template', function () {
        it('test template ${TEMPLATE_ID} is active and is complete', function (done) {
            BaseWelcomeEmail.setTemplateId(TEMPLATE_ID);
            SendEmailImpl.sendEmail(BaseWelcomeEmail.toJSON(), done, function(error, response){
                assert_OKResponse(error, response, done);
            });
        });
    });
```

The sendEmail function contains the normal POST V3 setup to call the APIas described in the documents.

#### Technical details:

* sendgrid-nodejs Version: 4.7.1
* Node.js Version: 4.6.1

**Comment by thinkingserious** [comment]
Hello @iamgollum,

Thanks for taking the time to submit an issue! I have added this to our backlog for review.

Meanwhile, perhaps this will help: https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#transactional_templates

Thanks!

**Comment by glennslaven** [comment]
I'm having a similar issue, I'm not using a template, just sending a plain email. Here's my code

```
'use strict';

var helper = require('sendgrid').mail;

module.exports = (config) => {

    var client = {};

    client.sendEmail = (email, subject, body_content, attachments) => {

        var sg = require('sendgrid')(config.apiKey);

        var from_email = new helper.Email(config.from);
        var to_email = new helper.Email(email);
        var content = new helper.Content('text/plain', body_content);
        var mail = new helper.Mail(from_email, subject, to_email, content);

        if (Array.isArray(attachments)) {
            attachments.forEach((file) => {
                var attachment = new helper.Attachment();
                var base64File = new Buffer(file.content).toString('base64');
                attachment.setContent(base64File);
                attachment.setType('application/text');
                attachment.setFilename(file.name);
                attachment.setDisposition('attachment');
                mail.addAttachment(attachment);
            })
        }

        var request = sg.API({
          method: 'POST',
          path: '/v3/mail/send',
          body: mail.toJSON(),
        });

        return sg.API(request);
    };

    return client;
};
```

The call errors & outputs

> undefined:1
> &lt;html>
> ^
> 
> SyntaxError: Unexpected token <
>     at Object.parse (native)
>     at /vagrant/functions/node_modules/sendgrid/lib/sendgrid.js:95:46
>     at IncomingMessage.<anonymous> (/vagrant/functions/node_modules/sendgrid/node_modules/sendgrid-rest/lib/client.js:109:9)
>     at emitNone (events.js:72:20)
>     at IncomingMessage.emit (events.js:166:7)
>     at endReadableNT (_stream_readable.js:923:12)
>     at nextTickCallbackWith2Args (node.js:458:9)
>     at process._tickDomainCallback (node.js:413:17)
> 

The email still actually sends, but my program exits with that error.

I put a `console.log` on line [108 of client.js](https://github.com/sendgrid/nodejs-http-client/blob/master/lib/client.js#L108) just before the callback in the sendgrid-rest library & this was the response

```
{ statusCode: 404,
  body: '<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n',
  headers:
   { server: 'nginx',
     date: 'Mon, 05 Dec 2016 09:40:30 GMT',
     'content-type': 'text/html',
     'content-length': '162',
     connection: 'close' } }
```

**Comment by glennslaven** [comment]
Following on from that, I put a console log after constructing the request and I get this

```
{ host: 'api.sendgrid.com',
  method: 'POST',
  path: '/v3/mail/send',
  headers:
   { Authorization: 'Bearer <key>',
     Accept: 'application/json',
     'User-Agent': 'sendgrid/4.7.1;nodejs',
     'Content-Length': 338,
     'Content-Type': 'application/json' },
  body: {},
  queryParams: {},
  test: false,
  port: '' }
{ host: 'api.sendgrid.com',
  method: undefined,
  path: undefined,
  headers:
   { Authorization: 'Bearer <key>',
     Accept: 'application/json',
     'User-Agent': 'sendgrid/4.7.1;nodejs' },
  body: {},
  queryParams: {},
  test: false,
  port: '' }
{ statusCode: 404,
  body: '<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n',
  headers:
   { server: 'nginx',
     date: 'Mon, 05 Dec 2016 09:53:10 GMT',
     'content-type': 'text/html',
     'content-length': '162',
     connection: 'close' } }
```

So it looks like it makes the correct request, then tries to make a request with a bunch of undefined properties

**Comment by thinkingserious** [comment]
@iamgollum,

Are you still having an issue?

**Comment by adamsingle** [comment]
I'm having this issue. And I'm using a transactional template as in the link you posted.

**Comment by thinkingserious** [comment]
Hmm, I'm thinking this issue is related: https://github.com/sendgrid/sendgrid-nodejs/issues/347

I'm reclassifying this one as a bug and will check them out together.

**Comment by thinkingserious** [comment]
@adamsingle,

Meanwhile, do you have a code sample we can use to help reproduce? Thanks!

**Comment by iamgollum** [comment]
@thinkingserious I will try and provide a code sample this weekend. I am coming back to sendgrid now at work and going to revisit everything.

**Comment by bradseefeld** [comment]
Bah! Have been getting this exact problem for a few hours. Turns out the path is sensitive to the leading slash. 
```
var request = sendgrid.emptyRequest({
    method: 'POST',
    path: '/v3/mail/send',
    body: mail.toJSON()
});
```

vs

```
var request = sendgrid.emptyRequest({
   method: 'POST',
   path: 'v3/mail/send',
   body: mail.toJSON()
});
```

The first snippet works, whereas the second will give you the json parse error :(

We've been a long time sendgrid customer, but just started playing with the api and this lib. Perhaps this detail is well documented and I have overlooked it? Would be nice for the lib to automatically prefix the slash if we omit it.

**Comment by thinkingserious** [comment]
@bradseefeld,

Sorry you had to deal with that :(

We are working on a better helper that hides all of those details from you. You should not have to care about any of the parameters.

You can follow the project here: https://github.com/sendgrid/sendgrid-nodejs/projects

Thanks!

**Comment by bradseefeld** [comment]
No worries. We love the service!

**Comment by thinkingserious** [comment]
The new helper is in development here: https://github.com/sendgrid/sendgrid-nodejs/pull/378
