### ISSUE TITLE
Duplicate emails causes batch sending to fail

### ISSUE THREAD

**Issue by cjevning** [sendgrid/sendgrid-nodejs#345]
#### Issue Summary

When sending an email to multiple recipients, if one of those recipients is duplicated (in the to: or cc:), then the entire batch of emails fails to send with `{ Sendgrid Error: Response Error }` and no additional info. Have not confirmed if this only happens with the mail helper (where I'm experiencing it) or not.

#### Steps to Reproduce

1. Create an email to send to multiple recipients using the mail helper (addTo, etc.)
2. Duplicate one of the emails (i.e. addTo or addCc with one of the emails already added)
3. Try to send the email. Sendgrid API spits out the above error.

I would assume that it should either strip out the duplicate, or just send it twice. Or at LEAST give more detailed error information.

#### Technical details:

* sendgrid-nodejs Version: 4.7.1
* Node.js Version: 6.2.0

**Comment by thinkingserious** [comment]
Thanks for taking the time to report this issue. I will get this feedback back to the API team for a better error and I'll look into including a duplicate email validator in the mail helper.

**Comment by thinkingserious** [comment]
Hello @cjevning,

This is expected behavior. Duplicate emails are not allowed within the same personalization. To gain further details from your errors, please follow [this example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md#error).

Thanks!

With Best Regards,

Elmer
