### ISSUE TITLE
sendgrid.send gives {"code":"EPROTO","errno":"EPROTO","syscall":"write"}

### ISSUE THREAD

**Issue by danielflippance** [sendgrid/sendgrid-nodejs#346]
#### Issue Summary

My nodeJS integration is returning a lot of the following errors when calling sendgrid.send:

{"code":"EPROTO","errno":"EPROTO","syscall":"write"}

I don't know what this error message means or whether this has prevented my email from being sent. Any idea what this means, what it's impacts are or how I can address it?

#### Technical details:

* sendgrid-nodejs Version: version: "2.0.0",
* Node.js Version: 4.5.0

**Comment by thinkingserious** [comment]
Hello @danielflippance,

I have not seen this issue myself (seems its dependent on your server settings), but in this epic thread, it looks like there are several possible solutions: https://github.com/nodejs/node/issues/3692

I hope that helps.
