### ISSUE TITLE
eml file in attchments recieved in outlook as outlook item file

### ISSUE THREAD

**Issue by dudilugasi** [sendgrid/sendgrid-nodejs#350]
#### Issue Summary

when i am sending an eml file as attachment with node mailer i see it in my outlook inbox as an outlook item file and the content is different from the original attachment. its weights less then the original. if i am trying to send the same attachment regular from the outlook it is received ok.

#### Steps to Reproduce

var helper = require('sendgrid').mail;
var from_email = new helper.Email('test@outlook.com');
var to_email = new helper.Email('test@outlook.com');
var subject = 'Hello World from the SendGrid Node.js Library!';
var content = new helper.Content('text/plain', 'Hello, Email!');
var mail = new helper.Mail(from_email, subject, to_email, content);
var fs = require("fs");
var attachment = new helper.Attachment();
var file = fs.readFileSync('C:/Users/user/Desktop/test.eml');
var base64File = new Buffer(file).toString('base64');
attachment.setContent(base64File);
attachment.setFilename('test.eml');
attachment.setDisposition('attachment');
mail.addAttachment(attachment);

var sg = require('sendgrid')("API_KEY");
var request = sg.emptyRequest({
  method: 'POST',
  path: '/v3/mail/send',
  body: mail.toJSON(),
});

sg.API(request, function(error, response) {
  console.log(response.statusCode);
  console.log(response.body);
  console.log(response.headers);
});

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Hello @dudilugasi,

Could you send me the .eml file (dx@sendgrid.com) along with what the expected results look like vs. the truncated results? Please reference this issue in your email.

Thank you!
