### ISSUE TITLE
Including Numeric `custom_args` Breaks Sending Emails

### ISSUE THREAD

**Issue by droppedoncaprica** [sendgrid/sendgrid-nodejs#351]
#### Issue Summary

So basically (after porting over our code from this library to a raw HTTP call to the API), I found out that Sendgrid's V3 Send Email API will error out if you include a number value inside the `custom_args` object.  This breaks whether or not you use the helpers or the JSON option for sending emails.

This happens even when POST'ing to the Sendgrid API endpoint without using the library, so this is more an API issue than this library's, but with a little work could solve some gotchas that people will run into in the future.  

My thought is to at least update the documentation to notate that custom_args should be a string value, and possibly converting values set through the `helper.CustomArgs` method to strings.

#### Steps to Reproduce

1. Set up an email with custom_args set up.
2. Have one of the values be a number
3. Send the email using the SendGrid.API call
4. Get an error back

Example Using Helpers

```
// Set contents of email.
var textContent = new MailHelper.Content("text/plain", "Test");
var htmlContent = new MailHelper.Content('text/html', "<h1>Test</h1>");
mail.setSubject("Testing Emails");
mail.addContent(textContent);
mail.addContent(htmlContent);

var from = new MailHelper.Email('someone@somewhere.com');
mail.setFrom(from);

// Begin the "personalization" object creation.
var personalization = new MailHelper.Personalization();

var to = new MailHelper.Email('your@email.here');
personalization.addTo(to);

var custom_arg = new helper.CustomArgs("This_Will_Break", 400)
personalization.addCustomArg(custom_arg)

mail.addPersonalization(personalization);

var request = SendGrid.emptyRequest({
  method: "POST",
  path: "/v3/mail/send",
  body: mail.toJSON()
});

SendGrid.API(request, function(e, resp) {
  if( e ) {
    cb(e);
  } 

  // Additional resp.statusCode checks.
});
```

Example Using JSON:

```
var request = sg.emptyRequest()
request.body = {
  "content": [
    { "type": "text/plain", "value": "Test" },
    { "type": "text/html", "value": "<h1>Test</h1>" }
  ],
  "subject": "Subject: Pricing for Your Notary Bond, Bill | SuretyBonds.com ",
  "from": { "email": "admin@suretybonds.com" },
  "personalizations": [{ "to": [ { "email": "albert@suretybonds.com" } ] } ],
  "custom_args": { "This_Will_Break": 400 }
};
request.method = 'POST'
request.path = '/v3/mail/send'
sg.API(request, function (error, response) {
  console.log(response.statusCode)
  console.log(response.body)
  console.log(response.headers)
})
```

#### Technical details:

* sendgrid-nodejs Version: 4.7.1
* Node.js Version: 6.9.1

**Comment by thinkingserious** [comment]
Hello @droppedoncaprica,

Thank you for the detailed issue! I have added this to our backlog. We'll update the helper to catch this error and perform the conversion on your behalf. 

I'll also notify the documentation team. 

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
@droppedoncaprica,

Please follow this issue for a fix. Thanks!

**Comment by soryy708** [comment]
Still happens for boolean values.
