### ISSUE TITLE
Multiple send with different attachments

### ISSUE THREAD

**Issue by simonemazzoni** [sendgrid/sendgrid-nodejs#352]
#### Issue Summary

Related to issue [#349](https://github.com/sendgrid/sendgrid-nodejs/issues/349)

I need to send multiple emails with different personalizations and different attachments. Up to now the helper library doesn't allow this. How can I do this?

#### Technical details:

* sendgrid-nodejs Version: 4.7.1 (from npm)
* Node.js Version: 6.1.9

**Comment by simonemazzoni** [comment]
Hello @thinkingserious, I wrote to Sendgrid support and they told me to contact you directly to get help on my issue.

**Comment by thinkingserious** [comment]
Hello @simonemazzoni,

To achieve your desired result, you would need to execute a separate API call for each attachment. Our API does not currently support specifying attachments within the personalization.

Here is a full example using the helper: https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L15

And without the helper: https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/mail/mail.js#L31

And here is an example for sending an attachment specifically: https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#attachments

I hope that helps.

Thanks!

With Best Regards,

Elmer

**Comment by simonemazzoni** [comment]
@thinkingserious thanks for the answer. I already implemented this solution Two days ago.
My concern regards the fact that up to now it's possible to specify different personalizations, but now different attachments. I thinks is a pretty common and useful use case since it allow developers to execute only one rest call instead of multiple rest calls.

Do you plan to add this feature in future realeases?
More in deep, is this feature compatible with Sendgrid endpoints?

Thanks

**Comment by thinkingserious** [comment]
@simonemazzoni,

There are no plans to add this functionality in the near future. But every vote counts, so I would suggest you create a separate issue specifically for this feature. Then, as more people vote on it with either a +1 or comment, the issue will move up our queue.

Thanks!

**Comment by sreekanth6495** [comment]
@thinkingserious 

Is this functionality added in the last two years.

I need to send a single email to multiple recipients but different personalizations and a different attachment file for each recipient.

Thanks

**Comment by thinkingserious** [comment]
Hello @sreekanth6495,

No, this feature is not available as described. You will need a separate API call for each email.

With Best Regards,

Elmer

**Comment by AlanPBourke** [comment]
So I can't send an email to 1000 of my customers, with their own individual PDF invoice image attached, without hitting the API 1000 times?
