### ISSUE TITLE
API docs?

### ISSUE THREAD

**Issue by brandonmp** [sendgrid/sendgrid-nodejs#355]
Specifically interested in the `helper` class.

I see a lot of examples, which are helpful, but is there anywhere I can look (besides src code) to see the methods and properties etc. enumerated and explained? 

e.g., this line from the examples:
`var mail = new helper.Mail(from_email, subject, to_email, content)`

It's not clear to me what arguments the constructor takes besides those included here, or which arguments are required, etc. etc. 

I see the `helper class` [doc section here](https://github.com/sendgrid/sendgrid-nodejs/tree/master/lib/helpers/mail), but all it has is the link to the examples and  a page in Sendgrid docs that don't seem to say anything about this specific library (only the endpoint).

**Comment by thinkingserious** [comment]
Hello @brandonmp,

That constructor is only designed for that basic use case. For full usage, please check out this example: https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L15

For further documentation, check out: https://sendgrid.com/docs/API_Reference/api_v3.html

Please let me know if I can further assist. Thanks!

With Best Regards,

Elmer

**Comment by brandonmp** [comment]
thanks @thinkingserious . the examples are helpful, but was hoping for more traditional docs of the SDK itself. understand if they're not available, though.

Can you tell me, though, in general: if I want to leave all of the params of the email (subject, body, etc.) to the `template`, and only provide the `to`, `from`, and any `%variables%` in my API call, how do I do that? 

I've been trying to work through the examples, but so far it seems like if I omit `content` or `subject` I get an exception. 

for example: 

````
// @flow
const Sendgrid = require('sendgrid')
const helper = Sendgrid.mail

type CreateEmailInputs = {
  from: string,
  to: string,
  subject?: string,
  content?: string,
  templateId: string,
  variables: { [varName: string]: string }[]
};

const createEmail = (
  { from, to, subject, content, templateId, variables }: CreateEmailInputs,
  sendgridInstance: typeof Sendgrid) => {

  const from_email = new helper.Email(from)
  const to_email = new helper.Email(to)

  // not clear on why i need this, but w/o actual
  // html in content, the template won't send'
  const mailContent = new helper.Content('text/html', '<div />')

  const mail = new helper.Mail(from_email, subject, to_email, mailContent)
  mail.setTemplateId(templateId)

  if (variables && Array.isArray(variables)) {
    variables.forEach((v) => {
      const varName = Object.keys(v)[0]
      mail.personalizations[0].addSubstitution(
        new helper.Substitution(varName, v[varName])
      )
    })
  }
  const request = sendgridInstance.emptyRequest({
    method: 'POST',
    path: '/v3/mail/send',
    body: mail.toJSON(),
  })

  return request

}
````

When I call this function with a valid to/from, 1 template variable, and `undefined` content/subject, I'm getting this exception:

````
   TypeError: Cannot read property '0' of undefined
        at variables.forEach.v (/home/bmp/storage/code/wayhome/micro-functions/src/utils/create-email.js:30:7)
        at Array.forEach (native)
        at createEmail (/home/bmp/storage/code/wayhome/micro-functions/src/utils/create-email.js:28:15)
        at /home/bmp/storage/code/wayhome/micro-functions/src/wayhome-invitation/handle-invitation-deletion.js:47:19
        at Generator.next (<anonymous>)
        at step (/home/bmp/storage/code/wayhome/micro-functions/src/wayhome-invitation/handle-invitation-deletion.js:1:191)
        at /home/bmp/storage/code/wayhome/micro-functions/src/wayhome-invitation/handle-invitation-deletion.js:1:361
        at process._tickDomainCallback (internal/process/next_tick.js:129:7)
````

Even in the example you linked to, the `subject` is provided to the constructor: 

`email = new helper.Email("test@example.com", "Example User")`

Is there a way to omit subject & content & simply defer to whatever values the `template` has?

**Comment by thinkingserious** [comment]
Hello @brandonmp,

I'll have to give that a try (without subject and content). Meanwhile, maybe this example will help: https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#transactional-templates

**Comment by thinkingserious** [comment]
We will be updating the docs for this repo when we merge this PR: https://github.com/sendgrid/sendgrid-nodejs/pull/378
