### ISSUE TITLE
Substitution tag as section index not DRY.

### ISSUE THREAD

**Issue by xaphiris** [sendgrid/sendgrid-nodejs#360]
Currently the only way to repeat the same piece of content across multiple emails is to define each section ONCE, then have it substituted for tags across EACH recipient. This doesn't seam very "DRY".

Couldn't you type-cast substitution values and when there are multiple recipients but a single string given, iterate the value across personalizations for each recipient? Seems a more efficient way instead of handling API calls with arrays filled with the same values.

**Comment by thinkingserious** [comment]
Hello @xaphiris,

Could you please provide a code sample that illustrates the issue? Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hi @xaphiris,

I think [this PR](https://github.com/sendgrid/sendgrid-nodejs/pull/378) will make this easier for you, please follow along there. Thanks!
