### ISSUE TITLE
X-SMTPAPI header

### ISSUE THREAD

**Issue by walshe** [sendgrid/sendgrid-nodejs#366]
#### Issue Summary

can you provide a Nodejs example of how to add a unique argument to the X-SMTPAPI header so that I can see this downstream in the webhook event also

**Comment by thinkingserious** [comment]
Hi @walshe,

Here is an example at the [personalization](https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L46) and [global level](https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L92).

I hope that helps!

With Best Regards,

Elmer
