### ISSUE TITLE
Get sent message in MIME format after/before sending?

### ISSUE THREAD

**Issue by byjoh** [sendgrid/sendgrid-nodejs#375]
I am doing the following to send mail:

```
let helper = require('sendgrid').mail;
let mail = new helper.Mail(from_email, subject, to_email, content);
mail.addAttachment(attachment);

let request = sgClient.emptyRequest({
    method: 'POST',
    path: '/v3/mail/send',
    body: mail.toJSON(),
});

sgClient.API(request)
    then(response => {...
```

and would like to then save the message in MIME format to S3 though it doesn't look like I can get it anywhere on the response object and I can't see anything on the request object that allows me to convert to MIME and cache in S3 before I send.  Am I missing something that would make this possible?

**Comment by SendGridDX** [comment]
Hello @byjoh,

We don't currently have a means to do that with our SDK or API. 

I suggest that you bcc the email to our [Inbound Email Parse Webhook](https://sendgrid.com/docs/API_Reference/Webhooks/inbound_email.html), then process and store the email when you receive the webhook.

With Best Regards,

Elmer
