### ISSUE TITLE
Sending Template as attachment

### ISSUE THREAD

**Issue by ubreddy** [sendgrid/sendgrid-nodejs#376]
#### Issue Summary

I am trying to send an email with attachment. The attachment is of the same format as a template. Did not find any documentation that helps generate a file from transaction template or if there is a way to do it.

nodejs sdk is being used.

**Comment by SendGridDX** [comment]
Hi @ubreddy,

I hope this helps: https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#attachments

With Best Regards,

Elmer
