### ISSUE TITLE
Test Endpoint

### ISSUE THREAD

**Issue by couturecraigj** [sendgrid/sendgrid-nodejs#377]
I looked to see if there is any information about this anywhere and was having a hard time locating it so maybe this will be helpful for others if there is a simple solution to this.

So I ran into an issue when you stopped supporting nodemailer and it resulting in my system crashing every time a person triggered a transaction that would result in an email being sent.  Is there any test endpoint that we can use for tests just to validate that our transactions are still working if there is another breaking change that ever gets introduced.  If not is there a process to request test endpoints be added.

**Comment by SendGridDX** [comment]
Hello @couturecraigj,

You can setup your own local test SendGrid API server using this process: https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#testing
