### ISSUE TITLE
How to also include a text version of your message (text/plain)

### ISSUE THREAD

**Issue by psabharwal3** [sendgrid/sendgrid-nodejs#380]
Hi
I got this from mail-checker:
-1.105	MIME_HTML_ONLY	Message only has text/html MIME parts
You should also include a text version of your message (text/plain)
how do i add text/plain version along with text/html version?
I am using - https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/mail/mail.js#L31
thanks

**Comment by thinkingserious** [comment]
Hello @psabharwal3,

Your content object would look like this:

```javascript
  "content": [
    {
      "type": "text/html", 
      "value": "<html><p>Hello, world!</p><img src=[CID GOES HERE]></img></html>"
    },
    {
      "type": "text/plain", 
      "value": "Hello, world!"
    },
  ],
```

With Best Regards,

Elmer
