### ISSUE TITLE
How to get the precompiled library file

### ISSUE THREAD

**Issue by ss513546039** [sendgrid/sendgrid-nodejs#381]
#### Issue Summary - How to get the compiled version of lib file

We planning to call this sendgrid api from our other third party system, so is any way we can get a full compiled lib file, so we can include this in our script and calling this api from our script.

#### Sample

1. <script type="text/javascript" src="https://cdn.rawgit.com/xxx/xxxxjs/a8df744f/xxxx.js "></script>

 if you already have the hosted library where the script src can be pointed or if we can get precompiled version we can include in our script and call your api.

Thanks,
Suresh S

**Comment by thinkingserious** [comment]
Hello @ss513546039,

The supported method of installing this SDK is: https://github.com/sendgrid/sendgrid-nodejs#install-package

I hope that helps, thanks!

Elmer
