### ISSUE TITLE
Error message is not clear

### ISSUE THREAD

**Issue by pashaseliverstov** [sendgrid/sendgrid-nodejs#387]
{"message":"Response error","response":{"statusCode":400,"body":{"errors":[{"message":"Bad Request","field":null,"help":null}]},"headers":{"server":"n
ginx","date":"Wed, 26 Apr 2017 01:14:46 GMT","content-type":"application/json","content-length":"63","connection":"close","x-frame-options":"DENY","ac
cess-control-allow-origin":"https://sendgrid.api-docs.io","access-control-allow-methods":"POST","access-control-allow-headers":"Authorization, Content
-Type, On-behalf-of, x-sg-elas-acl","access-control-max-age":"600","x-no-cors-reason":"https://sendgrid.com/docs/Classroom/Basics/API/cors.html"}}}

**Comment by thinkingserious** [comment]
Hello @pashaseliverstov,

I agree, that error message is not clear at all. Could you please provide some additional details so I can get to the root of the problem and discover what the real error is?

1. Do you mind providing the source code that generated that error?
2. What is the value of `requestBody` before you make the API call?
3. Was [this](https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md#error-messages) how you retrieved the error?

Thanks!

With Best Regards,

Elmer

**Comment by temitope** [comment]
I have this same issue. did you find a solution @pashaseliverstov @thinkingserious ?

**Comment by thinkingserious** [comment]
@temitope,

What version of the library are you using?

With Best Regards,

Elmer

**Comment by temitope** [comment]
Thanks @thinkingserious i am using this endpoint `/v3/mail/send` so I am assuming it is v3. Oddly it MAY be working if I change the destination email to a different value I think. super weird. still investigating. thanks

**Comment by thinkingserious** [comment]
Hi @temitope,

I am referring to the [SDK version](https://github.com/sendgrid/sendgrid-nodejs/releases). Thanks!

And yes, we do not allow duplicate emails.

With Best Regards,

Elmer

**Comment by temitope** [comment]
Thank you so much for the timely response. It was version `5.1.0` and yes that duplicate address is the issue. I wish there was a specific error message/code reflecting that duplication issue, or simply a reduction/removal of one of the addresses, but I'm glad to finally know.  @thinkingserious

**Comment by thinkingserious** [comment]
Thanks @temitope!

I believe you will find the [error handling](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#successfailureerrors) to be superior in v6.X of this library.

With Best Regards,

Elmer

**Comment by temitope** [comment]
@thinkingserious wow, things got so much better and simpler in 6.X i see. thank you guys!

**Comment by thinkingserious** [comment]
@temitope,

@adamreisnz deserves the lion's share of the thanks :)

**Comment by temitope** [comment]
indeed! thank you @adamreisnz  you made my email-sending life a lot easier as a dev.

**Comment by adamreisnz** [comment]
@temitope no problem! It made my own life easier as well, so it's a win-win ;)

**Comment by abhi9720** [comment]
hii @ thinkingserious i am getting this erro can u please help me with this 

const message = {
		to: email,
		from: 'verified email ',
		subject: ''some text ",
		html: ` '<h1>some text </h1>'`,
	};

sgMail.setApiKey(SENDGRID_KEY);
	sgMail
		.send(message)
		.then((response) => {
			console.log(response[0].statusCode);
			console.log(response[0].headers);
		})
		.catch((error) => {
			console.error(error);

		});

ResponseError: Bad Request
    at C:\Users\91972\Desktop\LMS\node_modules\@sendgrid\client\src\classes\client.js:146:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 400,
  message: 'Bad Request',
  response: {
    headers: {
      server: 'nginx',
      date: 'Mon, 05 Jul 2021 17:27:38 GMT',
      'content-type': 'application/json',
      'content-length': '204',
      connection: 'close',
      'access-control-allow-origin': 'https://sendgrid.api-docs.io',
      'access-control-allow-methods': 'POST',
      'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
      'access-control-max-age': '600',
      'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html',
      'strict-transport-security': 'max-age=600; includeSubDomains'
    },
    body: { errors: [Array] }
  }
}
