### ISSUE TITLE
How to send datetime stamp in .ics file with sendgrid node.js api?

### ISSUE THREAD

**Issue by Jyoti1009** [sendgrid/sendgrid-nodejs#388]
I wish to send a .ics file together with a datetime stamp using nodejs sendgrid API. I am able to attach a .ics file but could not find any example for integrating the time and date in the invite. Can someone please help?

**Comment by thinkingserious** [comment]
Hi @Jyoti1009,

To send an attachment with this library, please see [this example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#attachments).

With regards to creating an .ics file, [this resource](https://en.wikipedia.org/wiki/ICalendar) may help.

With Best Regards,

Elmer

**Comment by Jyoti1009** [comment]
@thinkingserious  Thank for the response. However, as I mentioned, I am able to successfully attach a calendar invite to the mail. However, I want to set a time on the calendar invite that I am sending. I am unable to find how to specify a datetime stamp to the attachment.

**Comment by thinkingserious** [comment]
HI @Jyoti1009,

As far as I can tell, you specify the datetime stamp in the .ics file itself. What specifically have you tried?

**Comment by Jyoti1009** [comment]
@thinkingserious  Thank you for the hint. I got this working with the below code:
    var icsMSG = "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//XYZ//NONSGML v1.0//EN\nBEGIN:VEVENT\nDTSTART:" + startDT +"\nSUMMARY:Meeting \nEND:VEVENT\nEND:VCALENDAR";
    var attachment = new helper.Attachment();
    var base64text = new Buffer(icsMSG).toString('base64');
    attachment.setContent(base64text);
    attachment.setType('text/calendar');
    attachment.setFilename('Meeting Invite.ics');
    attachment.setDisposition('attachment');
    mail.addAttachment(attachment);
