### ISSUE TITLE
.ics file has wrong date if new Date() from javascript is used.

### ISSUE THREAD

**Issue by Jyoti1009** [sendgrid/sendgrid-nodejs#389]
I used the below code to add 2 days to current time:

    var startDT = new Date(new Date().setTime(new Date().getTime() + days * 86400000));

also tried this:

    var startDT = new Date(new Date().setTime(new Date().getTime() + days * 86400000)).toISOString();

The date is logged correctly in logs. However, the .ics file that is received has a wrong date: **Wed 02/01/1901**

The code I have used is mentioned here:
https://github.com/sendgrid/sendgrid-nodejs/issues/388

**Comment by thinkingserious** [comment]
Hello @Jyoti1009,

This is not a library or SendGrid API issue, so I'm closing this issue.

However, perhaps this library can help you? https://github.com/adamgibbons/ics
