### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by gupta-abhi** [sendgrid/sendgrid-nodejs#390]
#### Issue Summary
I have gone through the documentation but couldn't find anything to enable proxy support. IS it possible to add proxy into the request ?

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Hello @gupta-abhi,

It is not currently possible. I will add this to our backlog for implementation. It would need to be added [here](https://github.com/sendgrid/nodejs-http-client/).

This issue can gain priority in our backlog by others commenting and adding reactions. The best way to move this up our queue is with a PR.

Thanks!

With Best Regards,

Elmer

**Comment by NickLiffen** [comment]
@gupta-abhi @thinkingserious this is something that we would need to use as well!

**Comment by thinkingserious** [comment]
Thanks for your vote @NickLiffen!

**Comment by kavu** [comment]
@thinkingserious Count me in. We really need it too. Speaking about possible PR — where should we start, in current implementation, if we want integrate it seamlessly? 
Thanks!

**Comment by kavu** [comment]
Oh! It looks like now you are using `request` package, which means we finally have support of `HTTP_PROXY` & `HTTPS_PROXY` env. variables! Going to test it right now.

**Comment by thinkingserious** [comment]
Thanks @kavu! Please let us know what you discover.

**Comment by QuynhNguyen** [comment]
@thinkingserious isn't this already supported out of the box with `request` package?

```
const client = require('@sendgrid/client');
client.setDefaultRequest('proxy', 'https://proxy.sendgrid.com/');
```

**Comment by kavu** [comment]
@thinkingserious Totally missed to answer you. I double (triple) checked it and it works perfectly now, thanks for your transition to `request`.

**Comment by thinkingserious** [comment]
Thanks for the follow up @kavu!
