### ISSUE TITLE
Node sendgrid not consistently filling in substitutions 

### ISSUE THREAD

**Issue by ejames17** [sendgrid/sendgrid-nodejs#393]
Issue Summary

Hi guys,
I can't seem to get sendgrid to consistently fill in substitution tags. I am not using a loop or anything just sending 1 email with a couple of Bccs.
It seems to be happening intermittently

Here is my code

 const personalizations = new Helper.Personalization();
  const orderIdSub = new Helper.Substitution('-orderId-', transaction.id.toString());
  const userPaypalSub = new Helper.Substitution('-paypalEmail-', transaction.paypalid);
  const totalOffer = new Helper.Substitution('-totalOffer-', `$ ${transaction.totaloffer.toFixed(2)}`);
  const dateSub = new Helper.Substitution('-date-', moment(transaction.date).format('YYYY-MM-DD').toString());
  const usernameSub = new Helper.Substitution('-username-', transaction.userid.user_nicename);

  const orderDetails = _.chunk(details, 35);//eslint-disable-line
  // sendgrid subsitution limitation. Lets chunk it so we don't hit our data limit
  console.log('order details  chunk ', orderDetails);
  return Promise.map(orderDetails, (orderData) => {
    const orderDataSub = new Helper.Substitution('-orderData-', getOrderDataHTML(orderData));
    personalizations.addBcc(bccHarry);
    personalizations.addBcc(bccSupport);
    const content = new Helper.Content('text/html', 'Hello, Email!');
    personalizations.addTo(toEmail);
    personalizations.addSubstitution(orderIdSub);
    personalizations.addSubstitution(userPaypalSub);
    personalizations.addSubstitution(dateSub);
    personalizations.addSubstitution(totalOffer);
    personalizations.addSubstitution(usernameSub);
    personalizations.addSubstitution(orderDataSub);
    console.log('personalization ', personalizations);
    console.log('content ', content);
    const mail = new Helper.Mail(fromEmail, subject, toEmail, content);

    mail.addPersonalization(personalizations);

    mail.setTemplateId('3f567463-1e20-4bda-a06e-451b8b13b267');
Am I doing anything wrong ?

Technical details:

Node 6.7
Sendgrid version 4.7.1

**Comment by thinkingserious** [comment]
Hi @ejames17,

I think you might be adding the substitutions to the wrong personalization object, please see: https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#transactional-templates

To help debug, you should inspect `mail.toJSON()` before you send the API call to see if the request object is properly formed.

I hope that helps!

With Best Regards,

Elmer

**Comment by ejames17** [comment]
@thinkingserious  sweet. You are correct i was adding it to the wrong one. The  personalizations is an array of Personalization objects. The mail.toJSON() helped.
Now time to drink.

**Comment by thinkingserious** [comment]
Awesome! Thanks for following up!
