### ISSUE TITLE
sendgrid doesnt allow readable stream as email attachments

### ISSUE THREAD

**Issue by kksharma1618** [sendgrid/sendgrid-nodejs#394]
Sendgrid currently doesn't allow readable stream as email attachments. 

From the examples: https://github.com/sendgrid/sendgrid-nodejs/blob/77e49732bc8912e8b2b66a182d38794ce672c03d/USE_CASES.md#attachments
```
var attachment = new helper.Attachment();
var file = fs.readFileSync('my_file.txt');
var base64File = new Buffer(file).toString('base64');
attachment.setContent(base64File);
attachment.setType('application/text');
attachment.setFilename('my_file.txt');
attachment.setDisposition('attachment');
mail.addAttachment(attachment);
```

fs.readFileSync in production app is a really bad idea. 
It will be helpful if we can attach readable stream to helper.Attachment. It should stream the file content directly to sendgrid server, instead of pulling it in a buffer first. 

See https://github.com/sendgrid/sendgrid-nodejs/pull/219#issuecomment-307537586

**Comment by thinkingserious** [comment]
Hello @kksharma1618,

Thanks for the feedback! I've added this to our backlog for implementation.

With Best Regards,

Elmer

**Comment by TunedMidja** [comment]
I'd like to implement this one!

**Comment by mbernier** [comment]
Please do @TunedMidja!!

**Comment by RaulTsc** [comment]
What is needed for this to be implemented? Willing to accept a PR for it? Hard to believe it's not been implemented 1 and a half years after it was reported. It also looks like a common production use case.

**Comment by thinkingserious** [comment]
Hi @RaulTsc,

Thanks for taking the time to comment on this issue. I've added your vote to this issue in our backlog. 

One of the reasons this one is still relatively de-prioritized with respect to our entire backlog is that there is currently a workaround. That said, we do plan to merge that PR as soon as we can.

With Best Regards,

Elmer

**Comment by esco** [comment]
Hi @thinkingserious, what would that workaround be?

**Comment by thinkingserious** [comment]
Hello @esco,

[Here you go](https://github.com/sendgrid/sendgrid-nodejs/blob/77e49732bc8912e8b2b66a182d38794ce672c03d/USE_CASES.md#attachments). Thanks!

With Best Regards,

Eler

**Comment by bathos** [comment]
Could this be reopened? The #514 PR was about accepting a buffer. It still isn’t possible to stream attachments with this client as far as I can tell.

I should note that, in case there’s some confusion here: the test that PR included is mislabeled. Note that the test is passing the return value of `readFileSync`, which is not a stream.

https://github.com/sendgrid/sendgrid-nodejs/blob/b3b2092b7a150ffc5d68c9bb6575810a5827f69e/packages/helpers/classes/attachment.spec.js#L28-L35

The changelog incorrectly reports readable stream support as well, so even if support for streaming isn’t added, the misinfo is worth addressing:

> PR #514: Allow readable stream as email attachments. Big thanks to TunedMidja for the PR!

**Comment by sam-huckaby** [comment]
Checking in to see if any thoughts have changed about streaming attachments. readFileSync is absolutely not usable in a production environment, which means this library can't be used in many cases which defaults us to using the deprecated nodemailer helper library which already supports attachment via stream.

For those interested in the deprecated nodemailer sendgrid transport, it can be found [here](https://github.com/sendgrid/nodemailer-sendgrid-transport)

An example of a streamed file attachment using nodemailer can be found [here](https://nodemailer.com/message/attachments/).

**Comment by zeluspudding** [comment]
See a workaround [here](https://gitmemory.com/issue/sendgrid/sendgrid-python/949/728233046)
