### ISSUE TITLE
Do you generate any unique email id? Cause it returns only {message: success}

### ISSUE THREAD

**Issue by metalshan** [sendgrid/sendgrid-nodejs#397]
#### Response of the email is only a flag

The response I get after sending the mail is just a {message: "success"} json. Is there a way to get the unique id of that mail?
Or I need to append my own uuid and append it somewhere as mentioned in the tracking document?

* sendgrid-nodejs Version: 1.5.0
* Node.js Version: 7.10.0

**Comment by metalshan** [comment]
Thanks @thinkingserious

**Comment by SirPhemmiey** [comment]
Hi @thinkingserious, the link you is not found. 

I am currently in need of a workaround this problem too. 

Thanks in anticipation.
