### ISSUE TITLE
"x-no-cors-reason" header present when using node.js on AWS Lambda

### ISSUE THREAD

**Issue by dillonbailey** [sendgrid/sendgrid-nodejs#400]
#### Issue Summary
Brief summary - when firing off API requests from node.js where API keys are secure we are still getting a response header that disallows CORS.

There may be some ways to manipulate this in our Lambda function before a response is returned from AWS, but it seems a little hacky and weird.

```
const sg = require('sendgrid')(process.env.SENDGRID_API_KEY);
const helper = require('sendgrid').mail;

const hello = (event, context, callback) => {

  const personalization = new helper.Personalization();
  const mail = new helper.Mail();

  const payload = JSON.parse(event.body);

  const content = new helper.Content('text/plain', payload.message);
  const emailFrom = new helper.Email('dillon@honestfox.com.au');

  mail.setFrom(emailFrom);
  mail.setSubject(payload.subject);
  mail.addContent(content);

  const emailTo = new helper.Email('nerds@honestfox.com.au');
  personalization.addTo(emailTo);

  mail.addPersonalization(personalization);

  const request = sg.emptyRequest({
    method: 'POST',
    path: '/v3/mail/send',
    body: mail.toJSON(),
  });

  // With promise
  sg.API(request)
    .then(response => {
      const responseString = JSON.stringify(response);

      callback(null,  {
        statusCode: 200,
        body: responseString,
      });
    })
    .catch(error => {
      const errorString = JSON.stringify(error.response);

      // error is an instance of SendGridError
      // The full response is attached to error.response
      callback(null,  {
        statusCode: 400,
        body: errorString,
      });
  });
};

export default hello;
```

#### Steps to Reproduce

1. Setup an AWS Lambda function with the above code
2. Setup an API Gateway that receives a POST method to trigger the lambda function via proxy
3. You can Post a request to your new endpoint with the following body:
```
{
	"subject": "test subject",
	"message": "test message"
}
```
4. The response will include "x-no-cors-reason" and thus start throwing issues around in the chrome console disallowing a successful response using fetch.

<img width="912" alt="screen shot 2017-07-07 at 6 25 55 pm" src="https://user-images.githubusercontent.com/1067872/27949750-35e71454-6342-11e7-9b6f-40f356b0cdd0.png">

#### Technical details:

* sendgrid-nodejs Version: 5.1.1
* Node.js Version: nodejs6.10

**Comment by thinkingserious** [comment]
Hello @dillonbailey,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
