### ISSUE TITLE
Unable to send attachments

### ISSUE THREAD

**Issue by mevillep** [sendgrid/sendgrid-nodejs#401]
I am unable to send attachments. In the email, I see the attachment with the correct name, but when I click on it to open, it says, "Failed to load PDF document".

I have followed the step in demo examples.

` var attachment = new helper.Attachment();
              var file = fs.readFileSync('/home/vcap/app/common/models/scc.txt');
              var base64File = new Buffer(file).toString('base64');
              attachment.setContent(base64File);

              attachment.setType("application/pdf")
              attachment.setFilename("TheBeast.pdf")
              attachment.setDisposition("attachment")
              mail.addAttachment(attachment);`

**Comment by thinkingserious** [comment]
Hi @mevillep,

Based on the extension (scc.txt), it may be that the file is not a PDF. Can you please double check? Thanks!

With Best Regards,

Elmer

**Comment by mevillep** [comment]
Thanks for your prompt reply. Let me try that.

**Comment by mevillep** [comment]
attachment.setContent('myBase64FileHere');   
              attachment.setFilename("TheBeast.pdf");
              attachment.setDisposition("attachment");
              attachment.setType('application/pdf');
              mail.addAttachment(attachment);

I am trying to put a base 64 file as an argument in the first line. For some reason I am unable to work it out. Anything that I am doing wrong?

**Comment by thinkingserious** [comment]
How are you generating the base64 encoding?

**Comment by mevillep** [comment]
So, I have a base64 file in my database. And I am querying it to be able to send as an attachment.
It looks something like this, "data:application/pdf;base64,myActualBAse64File". And It doesn't work.
Now, when I use only "myActualBAse64File" like attachment.setContent('myActualBAse64File')
It does not work.
Ia m not sure what wrong I am doing here.

**Comment by thinkingserious** [comment]
Can you please try removing the header (this part: data:application/pdf;base64,) and try again? Thanks!

**Comment by mevillep** [comment]
Yeahh, I tried that too. I had removed it and tired, It had still not worked.
like >>  attachment.setContent('myActualBAse64File');

**Comment by thinkingserious** [comment]
Can you please send the file you are having trouble with to dx@sendgrid.com?

**Comment by thinkingserious** [comment]
HI @mevillep,

I just sent you an email with my findings, please let me know how it goes. Thanks!

**Comment by harsh5692** [comment]
Hi @thinkingserious 
I am facing exact same issue with attaching PDFs in email.
The email I get has the attachments but it just a blank page, no the file I sent.
Also I checked the contents of attachments, it has some gibberish which does not open with a PDF reader.

Here is sample code for reference. Can you help me with this ?
```
var helper = require('sendgrid').mail;
var fileUrl = " A s3 File URL for PDF file"
var filename = "filename.pdf"
var mail = new helper.Mail(); // Main mail object
// Do a ton of stuff with mail object.

// fetch attachment file from s3 and add it to mail object.
S3.get(fileUrl, function(err, attach) {
  if (err || !attach)
    return callback(err);

  if (!err && attach) {
    var att = new helper.Attachment()
    // encode content of file in base64. required by SG.
    var encodedString = new Buffer(attach).toString('base64');
    att.setContent(encodedString);
    att.setType("application/pdf")
    att.setFilename(filename);
    att.setDisposition("attachment");
    mail.addAttachment(att);
    var toSend = mail.toJSON();
    
    // send the mail object to send function.
    // sg_send(sendgrid, toSend, callback);
  }
});
```

**Comment by thinkingserious** [comment]
Hi @harsh5692,

Can you please send us (dx@sendgrid.com) the original file and the base64 excoded string. Please send the latter in a .txt file.

Usually the issue is improper base64 encoding.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Here is what worked for me:

```bash
mkdir nodejs
cd nodejs
mkdir node_modules
npm install --save sendgrid
cp ~/Downloads/your.pdf .
vi temp.js
node temp.js
```

Following is the contents of temp.js:

```javascript
var helper = require('sendgrid').mail;
var sg = require('sendgrid')(process.env.SENDGRID_API_KEY);
var fs = require('fs');

var mail = new helper.Mail();
var email = new helper.Email('dx@sendgrid.com', 'Example User');
mail.setFrom(email);

mail.setSubject('Hello World from the SendGrid Node.js Library');

var personalization = new helper.Personalization();
email = new helper.Email('elmer.thomas@sendgrid.com', 'Example User');
personalization.addTo(email);
mail.addPersonalization(personalization);

var content = new helper.Content('text/html', '<html><body>some text here</body></html>')
mail.addContent(content);

var attachment = new helper.Attachment();
var file = fs.readFileSync('your.pdf');
var base64File = new Buffer(file).toString('base64');
attachment.setContent(base64File);
attachment.setType('application/pdf');
attachment.setFilename('my_file.pdf');
attachment.setDisposition('attachment');
mail.addAttachment(attachment);

var request = sg.emptyRequest({
  method: 'POST',
  path: '/v3/mail/send',
  body: mail.toJSON(),
});

sg.API(request, function(err, response) {
  console.log(response.statusCode);
  console.log(response.body);
  console.log(response.headers);
});
```

I'm guessing your original .pdf is not being loaded correctly.

**Comment by Abdul993** [comment]
I am getting the same issue as  @harsh5692 is getting.

**Comment by hborgthorsson** [comment]
Evening, I am also struggling with this, my attachments come through with correct name and bytesize but wont open, prompted with "damage file / incorrectly decoded". 

Here is my code:

    const msg = {
        to: req.body.sendEmail,
        from: req.body.email,
        subject: 'Lets attach it',
        html: output,
        attachments: [
        {
            content: new Buffer(req.body.filetoSync).toString('base64'),
            filename: req.body.filetoSync,
            type: 'plain/text',
            disposition: 'attachment',
            contentId: 'mytext'
        },
    ],
};

**Comment by Shroet** [comment]
I have the same problem: attachment sent via email but when I tried to open it - appeared notification, which said that the file is broken. C# code;

`var attachment = new[] { Attachment.FromStream(file, "Certificate of analisys.pdf" ) };`
