### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by franciscocpg** [sendgrid/sendgrid-nodejs#402]
What is the default connection timeout?
Is there a way to change this value?

**Comment by thinkingserious** [comment]
Hi @franciscocpg,

I believe it's [two minutes](https://stackoverflow.com/questions/23874954/is-there-a-default-timeout-in-nodejs-for-http-request).

If you want us to implement configurability, please open an issue [here](https://github.com/sendgrid/nodejs-http-client/issues), thanks!

With Best Regards,

Elmer
