### ISSUE TITLE
Fix index.d.ts file for addCustomArg()

### ISSUE THREAD

**Issue by bradacina** [sendgrid/sendgrid-nodejs#403]
The definition file states: pass an object containing 2 properties: key, value
(
https://github.com/sendgrid/sendgrid-nodejs/blob/master/index.d.ts#L58,
https://github.com/sendgrid/sendgrid-nodejs/blob/master/index.d.ts#L364
)

The implementation: will look at the object passed in and grab the first key name and its value as the custom arg (https://github.com/sendgrid/sendgrid-nodejs/blob/master/lib/helpers/mail/mail.js#L633)

**Comment by thinkingserious** [comment]
Thanks @bradacina,

I have added this to our backlog for a fix. This issue can gain priority with +1's from others and the biggest priority bump would come from a PR.

With Best Regards,

Elmer
