### ISSUE TITLE
Allow the ability to set port in request

### ISSUE THREAD

**Issue by apat183** [sendgrid/sendgrid-nodejs#405]
#### Issue Summary

So I have a node server setup behind a corporate proxy. I've setup the server to use the proxy on all http and https request. However, my requests were getting blocked when trying to use the SendGrid node library. The reason they were getting blocked is either the proxy or the firewall wasn't letting the request past since it was using https but wasn't using port 443 in the request.

I noticed that the SendGrid node lib uses the sendgrid-rest lib to construct the request, I noticed the returned request has a empty port. Looking at the code I see that a basic request construction uses the following object:

```
// request holds the request to an API Call
var request = {
  host: '',
  method: '',
  path: '',
  headers: {},
  body: {},
  queryParams: {},
  test: false, // use this to allow for http calls
  port: ''     // set the port for http calls
}
```
And then uses the 'buildrequest' function to receive the endpoint request and update the values. But never updates the port.  If I manually override the port value above to '443' the requests work. 
```
 function buildRequest (globalRequest, endpointRequest) {
    var request = JSON.parse(JSON.stringify(globalRequest))
    request.host = endpointRequest.host || globalRequest.host
    request.method = endpointRequest.method

    // build URL
    request.path = !isEmpty(endpointRequest.queryParams)
      ? buildPath(endpointRequest.path, endpointRequest.queryParams)
      : endpointRequest.path

    // add headers
    if (!isEmpty(endpointRequest.headers)) {
      for (var attrname in endpointRequest.headers) {
        request.headers[attrname] = endpointRequest.headers[attrname]
      }
    }

    // add the request body's content length
    if (!isEmpty(endpointRequest.body)) {
      body = JSON.stringify(endpointRequest.body)
      request.headers['Content-Length'] = Buffer.byteLength(body)
      request.headers['Content-Type'] = 'application/json'
    }

    return request
  }
```

It would be nice if you could pass a port in the endpointRequest and have that applied to the port value on the request. We already allow it to pass the host and path etc, so would be just an extra field and and one extra check.

**Comment by thinkingserious** [comment]
@apat183,

Nice! Thanks for taking the time to describe your need in detail. I've added this to our backlog for implementation.

For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

With Best Regards,

Elmer

**Comment by apat183** [comment]
Submitted PR on the nodejs-http-client. Thanks

**Comment by thinkingserious** [comment]
@apat183,

Do you mind submitting a pull request at sendgrid-nodejs to update the dependency? Thanks!

**Comment by apat183** [comment]
I submitted PR with updated package.json file to reflect new version of nodejs-http. Is this what you meant? Sorry slightly confused since it was using ^ caret in version so would have picked up new version. Let me know if there is something else.

**Comment by thinkingserious** [comment]
Mainly, we want to surface the new functionality and we should add a test or two. I'll comment on your PR. Thanks!

**Comment by apat183** [comment]
Sounds good.
