### ISSUE TITLE
Disabling Certificate Verification

### ISSUE THREAD

**Issue by karatechops** [sendgrid/sendgrid-nodejs#409]
I have a remote server which uses a self signed certificate, is it possible to disable the certificate verification?

This is the current error I am receiving:
```
{ SendGridError: Response error
    at /opt/mount1/brand-central-cms/node_modules/sendgrid/lib/sendgrid.js:123:19
    at ClientRequest.<anonymous> (/opt/mount1/brand-central-cms/node_modules/sendgrid-rest/lib/client.js:120:7)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  message: 'Response error',
  response:
   { statusCode: 500,
     body:
      { message: 'self signed certificate in certificate chain',
        name: 'Error',
        stack: 'Error: self signed certificate in certificate chain\n    at Error (native)\n    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:185:7)\n    at TLSSocket._finishInit (_tls_wrap.js:610:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)' },
     headers: {} } } { statusCode: 500,
  body:
   { message: 'self signed certificate in certificate chain',
     name: 'Error',
     stack: 'Error: self signed certificate in certificate chain\n    at Error (native)\n    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:185:7)\n    at TLSSocket._finishInit (_tls_wrap.js:610:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)' },
  headers: {} }
```

I've tried adding the following to my `emptyRequest` body to no avail.
```
"require_tls": false,
"require_valid_cert": false
```

Additionally this returns the same self signed certificate error
```
sg.emptyRequest({
  method: 'PATCH',
  path: '/v3/user/settings/enforced_tls',
  body: {
    "require_tls": false,
    "require_valid_cert": false
  }
});
```

**Comment by thinkingserious** [comment]
Hi @karatechops 

This is not possible now. Support for this would likely need to be added [here](https://github.com/sendgrid/nodejs-http-client/blob/master/lib/client.js#L61).

For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

With Best Regards,

Elmer

**Comment by karatechops** [comment]
After some deep diving on this I've discovered this is not a certificate issue but a proxy issue. If my request looks like the following the email will send on my remote server.
```
{ host: 'proxy.my-company.net',
  method: 'POST',
  path: 'https://api.sendgrid.com/v3/mail/send',
  headers:
   { Authorization: 'Bearer MY_API_KEY',
     Accept: 'application/json',
     'User-Agent': 'sendgrid/5.1.2;nodejs',
     'Content-Length': 369,
     'Content-Type': 'application/json',
     Host: 'api.sendgrid.com'
  },
  test: false,
  port: 8080 }
```

I believe the only way to get an http request is by setting the request `test` parameter to true. @thinkingserious does setting `test` to true have any implications with how Sendgrid would handle the email on their end?

**Comment by thinkingserious** [comment]
Hello @karatechops,

I don't think so, but I think there may be a security concern since when you set [test to be equal to true](https://github.com/sendgrid/nodejs-http-client/blob/master/lib/client.js#L91), you lose https support.

With Best Regards,

Elmer

**Comment by karatechops** [comment]
Understood, the proxy is only available on http so it will need to remain this way.  I'll close this, thanks for the help!
