### ISSUE TITLE
Official way to identify a message from webhook.

### ISSUE THREAD

**Issue by hifall** [sendgrid/sendgrid-nodejs#412]
When I send an email using the SG node.js API, I got the response which contains a field: 'x-message-id': 'evEK_IhZSlKus235aGfxIQ'. This x-message-id field seems to identify the message.

Then I got the event data passed in by my webhook called by Sendgrid, and the data contains a field: 'sg_message_id':'evEK_IhZSlKus235aGfxIQ.filter0361p1las1-11880-5978131E-23.0'. Note that the first part of sg_message_id split by '.' is the same as x-message-id.

So in order to identify the message when my webhook is called by Sendgrid, is it a reliably way to simply split sg_message_id, and use the first part to identify the message?

I found another option on SO: https://stackoverflow.com/questions/33664494/how-to-associate-sendgrid-webhook-sg-message-id-to-sent-mail, which suggests passing a unique argument when sending the email, and retrieve it in webhook to identify the message.

Which way is more reliable?

Thanks!

**Comment by thinkingserious** [comment]
Hello @hifall,

I suggest that you set the custom arguments so that you have maximum control. [Here is an example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L46) of how to do so.

With Best Regards,

Elmer

**Comment by KaitaniLabs** [comment]
@thinkingserious - the link you gave to an example is dead. Any update on the location?

**Comment by thinkingserious** [comment]
@KaitaniLabs,

[Here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#kitchen-sink---an-example-with-all-settings-used) you go. Thanks!

**Comment by jamesdixon** [comment]
@thinkingserious this works in the case of sending a single message, but when sending using `sendMultiple`, a custom argument isn't going to work to identify each individual message. Is the OPs original comment about `sg_message_id` reliable/valid?

**Comment by thinkingserious** [comment]
In that case @jamesdixon, you would want to do [this](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#customization-per-recipient). I hope that helps!

**Comment by acomito** [comment]
@thinkingserious I'm having trouble locating the option for passing in a custom argument to sgMail.send

https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/single-email-single-recipient.md
