### ISSUE TITLE
NodeJS - Out of the box Email Error

### ISSUE THREAD

**Issue by rnabeeh-infosol** [sendgrid/sendgrid-nodejs#414]
#### Issue Summary

I have created an application using react js and uploaded to heroku. When attempting to use sendgrid's sample minimum code my application produced this error:

![fetcherrorsendgrid](https://user-images.githubusercontent.com/30155538/28729389-226fba94-7381-11e7-8481-2d861234532b.PNG)

#### Steps to Reproduce

1. Included SendGrid addon to heroku
2. npm installed sendgrid
3. Added api key
4. Copied sample code to react component 
5. Uploaded to heroku

I am not sure if this is just an error with the flow of my application or with connecting to send grid out of the box. I attempted to email sendgrid support and they redirected me to this location to get help. Previously I had used php to send emails and I expected this code to work similarly to php's mail function or even php mailer.

#### Technical details:

* sendgrid-nodejs Version: 5.2.0
* Node.js Version: 8.1.0

**Comment by thinkingserious** [comment]
Hello @rnabeeh-infosol,

It looks like you have run into the issue described on [this thread](https://github.com/sendgrid/docs/issues/1417). [Here](https://sendgrid.com/docs/Classroom/Basics/API/cors.html) is our suggested solution.

With Best Regards,

Elmer
