### ISSUE TITLE
Sendgrid.API(...) type signature is wrong

### ISSUE THREAD

**Issue by paavohuhtala** [sendgrid/sendgrid-nodejs#416]
The SendGrid.API(...) method has the wrong type in [index.d.ts](https://github.com/sendgrid/sendgrid-nodejs/blob/master/index.d.ts#L468). According to the types the callback only takes a response parameter,  even though [it actually is](https://github.com/sendgrid/sendgrid-nodejs/blob/master/lib/sendgrid.js#L125) a Node.js style `(error, result)` callback.

**Comment by thinkingserious** [comment]
Thanks for the heads up @paavohuhtala!

For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

With Best Regards,

Elmer
