### ISSUE TITLE
10,000 byte limit on personalizations is too low

### ISSUE THREAD

**Issue by kylemantesso** [sendgrid/sendgrid-nodejs#419]
#### Issue Summary

The limit of 10,000 bytes on personalizations is too low. Templates need some way of doing iterations or raise the limit.

**Comment by thinkingserious** [comment]
Hi @kylemantesso,

We are currently working on upgrading the templating experience, please see [this thread](https://github.com/sendgrid/sendgrid-nodejs/issues/221) for progress. Thanks!

With Best Regards,

Elmer
