### ISSUE TITLE
All href attributes with substitutions get stripped

### ISSUE THREAD

**Issue by Fabiantjoeaon** [sendgrid/sendgrid-nodejs#420]
I'm trying to use a transactional template to send informational emails like account validation etc.
I created one main transactional template which should have a button that has a different text and href for each mail.

My substitution for the button text works, and if I replace it with the URL, I get to see the URL too in text, but when I try to append the url to the href attribute it disappears, it simply strips the href attribute from my anchor tags. This happens everywhere, whether I'm setting the button url in the visual builder, in an HTML snippet, or in my mail body, it doesn't matter. Setting a URL manually tho, without substitution, seems to work.

I also tried using %value% as substitution, and multiple mail clients (gmail, outlook) but to no avail.. See my function to send informational emails below:

```
const sendInformationalEmail = async (to, subject, body, substitutions) => {
    const fromMail = new helper.Email(SENDGRID_FROM_MAIL);
    const toMail = new helper.Email(to);
    const content = new helper.Content('text/html', body);
    const mail = new helper.Mail(fromMail, subject, toMail, content);
    mail.setTemplateId(process.env.SENDGRID_INFORMATIONAL_TEMPLATE_ID);

    Object.keys(substitutions).map(substitution => {
        mail.personalizations[0].addSubstitution(
            new helper.Substitution(`-${substitution}-`, substitutions[substitution])
        );
    });
    
    const request = sendgrid.emptyRequest({
        method: 'POST',
        path: '/v3/mail/send',
        body: mail.toJSON()
    });

    return await sendgrid.API(request, function(err, response) {
      console.log(response.statusCode);
      console.log(response.body);
      console.log(response.headers);
    });
}
```

#### Technical details:

* sendgrid-nodejs Version: ^5.1.0
* Node.js Version: 7.10.0

**Comment by thinkingserious** [comment]
Hello @Fabiantjoeaon,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by dcurletti** [comment]
@Fabiantjoeaon I'm running into a similar problem myself, did u resolve it?

**Comment by Fabiantjoeaon** [comment]
Yes, this was my solution also, I totally overlooked it.
Glad you solved it @dcurletti
