### ISSUE TITLE
email.addSubVal is not a function

### ISSUE THREAD

**Issue by umesh191994** [sendgrid/sendgrid-nodejs#421]
I was making use of V2 to send email in sendgrid.  But now I migrated from V2 to V3 sendgrid@5.2.0.
In the updated sendrid verison iam facing an issue with addSubVal() function which was working in previous verison, so i just need to know the alternative for addSubVal() fuction in V3.

I tried to investigate here in the below link: 
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html

I couldn't find any solution for addSubVal().

**Comment by thinkingserious** [comment]
Hello @umesh191994,

I believe [this is the example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md#transactional_templates) you need. Please let me know if that is not the case.

With Best Regards,

Elmer

**Comment by umesh191994** [comment]
Hi Elmer

Thanks for your support, I gone through the link you provided and made use of 
" mail.personalizations[0].addSubstitution(new helper.Substitution('-name-', 'Example User')); "
in place of addSubVal() and please let me know is this the correct one and where to track this in sendgid.

And now I have a different issue after updating Node "request.emit" function is not working.

result = {
                    'success': success,
                    'message': response
                };
request.emit('output', result);
                      ^
TypeError: request.emit is not a function

Thanks,
Umesh.K

**Comment by thinkingserious** [comment]
I believe that is just a function to print out the results. You can do that now with `console.log` as shown in the example I linked to earlier. 

I hope that helps!

With Best Regards,

Elmer

**Comment by adamreisnz** [comment]
@umesh191994 if you can, please migrate to 6.0.0 which has a new API and should be easier to use and less error prone. Let me know if that solves your issue.
