### ISSUE TITLE
Mail send successfully but browser shows an error

### ISSUE THREAD

**Issue by ervaibhavsinghal** [sendgrid/sendgrid-nodejs#422]
![screenshot from 2017-08-16 14 15 40](https://user-images.githubusercontent.com/16643006/29356443-f2d97124-8291-11e7-9fcd-ca25395238aa.png)
#### Issue Summary

Mail send successfully but browser shows this error:
`{"error":{"code":500,"status":"INTERNAL","message":"function execution attempt timed out"}}`

#### Steps to Reproduce
Step 1) echo "export SENDGRID_API_KEY='YOUR_API_KEY'" > sendgrid.env
echo "sendgrid.env" >> .gitignore
source ./sendgrid.env

Step 2) npm install --save sendgrid

Step 3) Use With Mail Helper Class
var helper = require('sendgrid').mail;
var fromEmail = new helper.Email('test@example.com'); //change my email address
var toEmail = new helper.Email('test@example.com');   //change my email address
var subject = 'Sending with SendGrid is Fun';
var content = new helper.Content('text/plain', 'and easy to do anywhere, even with Node.js');
var mail = new helper.Mail(fromEmail, subject, toEmail, content);

var sg = require('sendgrid')(process.env.SENDGRID_API_KEY);
var request = sg.emptyRequest({
  method: 'POST',
  path: '/v3/mail/send',
  body: mail.toJSON()
});

sg.API(request, function (error, response) {
  if (error) {
    console.log('Error response received');
  }
  console.log(response.statusCode);
  console.log(response.body);
  console.log(response.headers);
});

#### Technical details:

* sendgrid-nodejs Version: 5.2.1
* Node.js Version: 7.10.0

**Comment by thinkingserious** [comment]
Hi @ervaibhavsinghal,

From your error logs, it looks like something is trying to send request headers after the HTTP request is already sent. [Here](https://stackoverflow.com/questions/7042340/error-cant-set-headers-after-they-are-sent-to-the-client) is a good explanation of the issue.

With Best Regards,

Elmer

**Comment by ervaibhavsinghal** [comment]
@thinkingserious what about this error "info: Execution took 60004 ms, finished with status: 'timeout'", I'll fix the header issue.

**Comment by thinkingserious** [comment]
It looks like you have a function that is timing out, maybe it's the same one that is trying to send additional headers.

I don't think it was the SendGrid function, because you received the success message back.
