### ISSUE TITLE
Question: From name on v3 where and how to add.

### ISSUE THREAD

**Issue by diegoddox** [sendgrid/sendgrid-nodejs#423]
I'm trying to add the`fromname` on my object but I'm not sure if is the right way I'm doing.

```
sg.emptyRequest({
    method: 'POST',
    path: '/v3/mail/send',
    body: {
      personalizations: [
        {
          to: emailTo,
          fromname: 'Namehere', // <== I've try fromName as well
        },
      ],
      fromname: 'Namehere', // <== I've try fromName as well
      from: {email: 'example@example.com'},
      content: [{
        type: 'text/html',
        value: '<p></p>',
      }],
      template_id: 'id_here'
    },
  });
```

I do get the email but not with the `fromname`, any idea why or where I add the `fromname` `field`?

**Comment by thinkingserious** [comment]
Here are some examples:
https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/mail/mail.js#L73
https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L19

Basically, `from: {email: 'example@example.com'}` becomes `from: {email: 'example@example.com', name:'Namehere'}`

**Comment by diegoddox** [comment]
Hi @thinkingserious, thanks a lot!

**Comment by astromme** [comment]
The example links are dead, can you update them? I'm struggling with the same thing.

**Comment by thinkingserious** [comment]
HI @astromme,

If you are using the latest version of the SDK, any of the following should work:

```Name <test@example.org>```
```{name: 'Name', email: 'test@example.org'}```

With Best Regards,

Elmer

**Comment by mbernier** [comment]
Hey just a heads up - the from object is outside of personalizations, not inside due to deliverability issues of sending from domains that don't match your whitelabeled domain or DKIM/SPF settings. 

The original block above would be more like this in v3/mail/send:

`sg.emptyRequest({
    method: 'POST',
    path: '/v3/mail/send',
    body: {
      personalizations: [
        {
          to: emailTo,
          fromname: 'Namehere', // <== I've try fromName as well
        },
      ],
      content: [{
        type: 'text/html',
        value: '<p></p>',
      }],
      template_id: 'id_here'
    },
    from: {
       email: 'example@example.com',
       name: 'Namehere'
    },
  });`
