### ISSUE TITLE
Question about sending an email to various emails

### ISSUE THREAD

**Issue by johhansantana** [sendgrid/sendgrid-nodejs#424]
Trying to send a single email to various emails.

Would this code work?
`const toEmail = new helper.Email('foo@example.com, bar@example.com');`

**Comment by thinkingserious** [comment]
Hi @johhansantana,

No that would not work. Please see this example: https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/helpers/mail/example.js#L15

Let me know if you need further assistance. Thanks!

With Best Regards,

Elmer

**Comment by johhansantana** [comment]
thank you!
