### ISSUE TITLE
Support simple sending method as documented in the Azure docs

### ISSUE THREAD

**Issue by Iiridayn** [sendgrid/sendgrid-nodejs#426]
#### Issue Summary

A well designed API wrapper simplifies common usage scenarios. [The Azure docs suggest](https://docs.microsoft.com/en-us/azure/store-sendgrid-nodejs-how-to-send-email),
```
sendgrid.send({
    to: 'john@contoso.com',
    from: 'anna@contoso.com',
    subject: 'test mail',
    text: 'This is a sample email message.'
});
```

should be enough to send an email. This is a good API wrapper. For some reason this library no longer supports this very reasonable call.

#### Steps to Reproduce

1. `npm install sendgrid`
2. `const sendgrid = require('sendgrid')(/* api key or un/pw */);`
3. Paste the above code example or the like
4. `TypeError: sendgrid.send is not a function`

This breaks compatibility with the Azure docs, and removes a very simple way to send an email, for which there appears to be no well documented replacement.

#### Workaround

```
var sg = require('sendgrid')(/* api key, etc */);
var api = sg.API; // prevent warning about uppercase function names are only for `new`ing
api(sg.emptyRequest({ // not empty. I'm passing an object.
    method: 'POST', path: '/v3/mail/send', body: {
        personalizations: [{
            to: [{ email: 'john@contoso.com' }],
            subject: 'test mail',
        }],
        from: { email: 'anna@contoso.com' },
        content: [{ type: 'text/plain', value: 'This is a sample email message.' }],
    }
}));
```

As you can see, this is a poor solution - I've doubled the lines of code and bits and bobs specified, thereby doubling my potential for errors. The proposed "helper" of course makes this code much more complex.

Please re-provide simple wrappers for common tasks, such as using sendgrid to send an email.

**Comment by thinkingserious** [comment]
Hi @Iiridayn,

This is currently in progress, please follow along [here](https://github.com/sendgrid/sendgrid-nodejs/pull/407). Thanks!

With Best Regards,

Elmer

**Comment by Iiridayn** [comment]
I'll look forward to the result then.
