### ISSUE TITLE
Update contact-importer to support v6.X

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#427]
#### Issue Summary

The current version of [contact-importer](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/contact-importer) needs to be updated to leverage the new [@sendgrid/client](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/client).

#### Acceptance Criteria

- Passing Tests
- README.md

**Comment by thinkingserious** [comment]
cc @mrfelton

**Comment by adamreisnz** [comment]
Probably released as a new package under `@sendgrid/contact-importer` too
