### ISSUE TITLE
Documentation Frustrations

### ISSUE THREAD

**Issue by nikmartin** [sendgrid/sendgrid-nodejs#439]
#### Issue Summary

https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#transactional_templates Seems to do a good job explaining how to use Transactional Templates, but none of the example actually work

#### Steps to Reproduce
Define a Transactional Template:
```
<html>
<head>
    <title></title>
</head>
<body>
Hello -name-,
<br /><br/>
I'm glad you are trying out the template feature!
<br /><br/>
<%body%>
<br /><br/>
I hope you are having a great day in -city- :)
<br /><br/>
</body>
</html>
```
2. Setup a mail like:

```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
sgMail.setSubstitutionWrappers('{{', '}}'); // Configure the substitution tag wrappers globally
const msg = {
  to: 'recipient@example.org',
  from: 'sender@example.org',
  subject: 'Hello world',
  text: 'Hello plain world!',
  html: '<p>Hello HTML world!</p>',
  templateId: '13b8f94f-bcae-4ec6-b752-70d6cb59f932',
  substitutions: {
    name: 'nikmartin',
    city: 'Denver',
  },
};
sgMail.send(msg);
```
3. I receive the email, but with:
"Hello -name-,"
not
"Hello nikmartin"

#### Technical details:

sendgrid-nodejs @sendgrid/mail": "^6.1.1",

What Are sgMail.setSubstitutionWrappers('{{', '}}') supposed to be set to, if the Template Body defines tags like: "-name-", and the substitutions item is "name"?
Should they be set like:  
`<body>Hello -name-, <br /><br/>`
`sgMail.setSubstitutionWrappers('-', '-');`
`substitutions: {  name: 'nikmartin'}`

Or what? Neither of these seem to work. Also, is this properly documented anywhere? Because this documentation for substitutions is just more confusing in the contect of using the node.js lib: https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/smtpapi.html

**Comment by nikmartin** [comment]
Update: I created a new version of the template using the HTML Code editor not the designer, using `=name=` in the tags, and in `.setSubstitutionWrappers('=', '=');` and 
`substitutions: {   name: member.fname   }` And it worked. Setting them to '-' or '{{}}' and using a template from the designer doesn't work.

**Comment by thinkingserious** [comment]
Hi @nikmartin,

My apologies, we had a typo in the [Transactional Template example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#transactional_templates), I have just fixed it. Generally, the substitution wrapper is whatever you decide.

With Best Regards,

Elmer
