### ISSUE TITLE
old sendgrid examples ?

### ISSUE THREAD

**Issue by walshe** [sendgrid/sendgrid-nodejs#443]
wheres all the old node examples that use the old version of the lib ?  e.g.

```
const sendGrid = require('sendgrid');

var sendGridHelper = sendGrid.mail;

var mail = new sendGridHelper.Mail();

mail.setFrom(fromEmail);
mail.setReplyTo(replyToEmail);

mail.setTemplateId(templateId);
```

etc etc ?

**Comment by thinkingserious** [comment]
Hi @walshe,

[Here](https://github.com/sendgrid/sendgrid-nodejs/tree/c29a5c4928c5875c1adfa7146efcc5149eae3d32) was the last release before v6.X.

With Best Regards,

Elmer
