### ISSUE TITLE
Issue on calling multiple times sendgrid api 

### ISSUE THREAD

**Issue by veereshthotygar** [sendgrid/sendgrid-nodejs#447]
#### Issue Summary

Below is the code snippet in nodeJS,
      `CODE

       sendEmail: function (to,subject,body,callback) {
        var email = new helper.Email(sendingEmail);
        mail.setFrom(email);
        mail.setSubject(subject);
        var personalization = new helper.Personalization();
        email = new helper.Email(to);
        personalization.addTo(email);
        mail.addPersonalization(personalization);
        var content = new helper.Content('text/html',body);
        mail.addContent(content);
        var attachment1 = new helper.Attachment();
        var file1 = fs.readFileSync(imgPath+'logo.png');
        var base64File_1 = new Buffer(file1).toString('base64');
        attachment1.setContent(base64File_1);
        attachment1.setType('image/png');
        attachment1.setFilename('logo.png');
        attachment1.setContentId('cim@Logo');
        attachment1.setDisposition('inline');
        mail.addAttachment(attachment1);
        var request = sendGrid.emptyRequest({
            method: 'POST',
            path: '/v3/mail/send',
            body: mail.toJSON(),
        });
        sendGrid.API(request, function(err, response) {
            if(typeof callback == "function") {
                callback(err,response.statusCode);
            } 
        });
    }`

I'm calling this above function method multiple times, say like for 10 users i'm iterating.
Only for the first user call I get response as statusCode 202 and for the remaining I get statusCode 400.

#### Technical details:

* Node.js Version: sendgrid@4.10.0

**Comment by thinkingserious** [comment]
Hello @veereshthotygar,

I suggest you upgrade to the latest version of this SDK, which is a big improvement over v4. Please check it out [here](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail).

That said, you should be able to capture the 400 error [like so](https://github.com/sendgrid/sendgrid-nodejs/blob/c29a5c4928c5875c1adfa7146efcc5149eae3d32/TROUBLESHOOTING.md#error).

With Best Regards,

Elmer

**Comment by veereshthotygar** [comment]
Hi @thinkingserious ,

As suggested I tried with latest version SDK, but I encountered the below error in @sendgrid/mail.

```
node_modules\@sendgrid\mail\src\mail.js:6
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (NodeJs\sendGrid-v6.js:8:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by veereshthotygar** [comment]
Hey @thinkingserious , got resolved the above issue,I just updated my Node JS to 6.1.3.

Thank you for the support.
