### ISSUE TITLE
If 'to' parameter has name and email, and the name has comma, it breaks the email address.

### ISSUE THREAD

**Issue by rafalohn** [sendgrid/sendgrid-nodejs#448]
#### Issue Summary

Using  @sendgrid/mail 6.1.4, when sending emails with the to parameter with both name and email:

```
to: {
    name: 'Some One',
    email: 'someone@example.org',
},
```

Works fine. But if the 'name' has commas as:

```
to: {
    name: 'Friend, his wife, his dog and friends',
    email: 'friendwifeanddog@example.org',
},
```

It does not work. In that scenario sendgrid dashboard drops the email considering 'friend' as the invalid email instead of 'friendwifeanddog@example.org'.

**Comment by thinkingserious** [comment]
Hello @rafalohn,

This is an API level issue as described [here](https://github.com/sendgrid/sendgrid-php/issues/368). There is also a work around described at that issue.

I’ve passed along your feedback to the product team to help build priority.

With Best Regards,

Elmer
