### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by polkhovsky** [sendgrid/sendgrid-nodejs#450]
#### Issue Summary

Using the latest version of Meteor 1.5.2.2. After adding @sendgrid/mail to the project, the application crashes. This is the code that produces the error:

```
const client = require('@sendgrid/client');
const {
  classes: {
    Mail,
  },
} = require('@sendgrid/helpers');
```
Logs:

W20171003-20:28:45.340(-4)? (STDERR) packages/modules.js:18016
W20171003-20:28:45.342(-4)? (STDERR) const {
W20171003-20:28:45.342(-4)? (STDERR)       ^
W20171003-20:28:45.345(-4)? (STDERR) 
W20171003-20:28:45.346(-4)? (STDERR) SyntaxError: Unexpected token {
W20171003-20:28:45.347(-4)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20171003-20:28:45.348(-4)? (STDERR)     at /Users/alex/projects/shopping-app/.meteor/local/build/programs/server/boot.js:332:30

Line 18016 in modules:
![screen shot 2017-10-03 at 8 35 11 pm](https://user-images.githubusercontent.com/4451400/31155221-7b7b5e1c-a87a-11e7-8ab4-c5f879c423ff.png)

**Comment by thinkingserious** [comment]
Hi @polkhovsky,

Was your issue resolved? 

With Best Regards,

Elmer

**Comment by polkhovsky** [comment]
I found a similar issue in your list. The problem is Meteor 1.5 is using Node 4. I had to upgrade to 1.6 RC to make this work. Thank you!

**Comment by thinkingserious** [comment]
Thanks for following up!
