### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#452]
We want to make it easier to test and/or contribute to this repo utilizing Docker. This has been completed in [Python](https://github.com/sendgrid/sendgrid-python/tree/master/docker), please use that example as a reference.

Key features:
* Setup the environment as specified in the CONTRIBUTING.md file
* Prism should be running on launch
* The README and USAGE file should help the user get up and running quickly

**Comment by jaydp17** [comment]
🖐 I'll give it a shot

**Comment by thinkingserious** [comment]
Thank you @jaydp17! It's all yours :)

**Comment by jaydp17** [comment]
@thinkingserious  https://github.com/sendgrid/sendgrid-nodejs/pull/461

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-nodejs/pull/1112
