### ISSUE TITLE
Auto Generate Plain Text Content from HTML

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#453]
We require both HTML and Plain Text content for improved deliverability. In some cases, only HTML may be available. We need a function that automatically converts a given HTML string to the Plain Text equivalent.

**Comment by uniOpifex** [comment]
Clarify what you mean. The HTML file is already in plain text. Do you want a function that removes all the html <tags>

**Comment by uniOpifex** [comment]
gave it a shot

**Comment by raindogg** [comment]
I also submitted [one](https://github.com/sendgrid/sendgrid-nodejs/pull/455), I had closed this window when I began working on it. Sorry for the duplication!
