### ISSUE TITLE
Package is not properly compiled (Unexpected token: keyword (const))

### ISSUE THREAD

**Issue by emmya** [sendgrid/sendgrid-nodejs#456]
#### Issue Summary

For loop in the convertKeys method causes an Uglify build error.

#### Steps to Reproduce

When attempting to build my app for production, I run into this error:
![image](https://user-images.githubusercontent.com/8542439/31194198-3d631062-a8fb-11e7-979c-832c9191e78b.png)

Locating the error in the build file (line 14811):
![image](https://user-images.githubusercontent.com/8542439/31194385-e81ca298-a8fb-11e7-9b14-f511f65b24c6.png)

Search for the culprit:
![image](https://user-images.githubusercontent.com/8542439/31194485-2bfaba2c-a8fc-11e7-9cd6-c4b454a0b62a.png)

This did not occur prior to installing sendgrid.

#### Technical details:

* sendgrid-nodejs Version: 6.1.4 (have @sendgrid/client and @sendgrid/mail)
* Node.js Version: 7.7.2
* npm version: 5.3.0

**Comment by emmya** [comment]
Upon further investigation, it looks like the entire package isn't compiled properly.
I am using Webpack 3.5.1.

**Comment by mbernier** [comment]
Thank you for adding this issue!

**Comment by thinkingserious** [comment]
Hi @emmya,

Could you please send us (dx@sendgrid.com) your `webpack.config.js`? I believe there is a dependency conflict somewhere. One solution I've seen is to replace `uglify-js` with `uglify-es`.

With Best Regards,

Elmer

**Comment by emmya** [comment]
@thinkingserious As a rule, my config ignores the node_modules folder when transpiling from es6 with babel - I feel like the standard is for modules to already be transpiled.

**Comment by emmya** [comment]
Installing the latest Uglifyjs webpack plugin worked :)

**Comment by thinkingserious** [comment]
Thanks for the follow up @emmya!

**Comment by ctbucha** [comment]
I ran into this problem today since it seems that `uglifyjs-webpack-plugin` no longer supports ES6 (https://github.com/gruntjs/grunt-contrib-uglify/issues/477). I am trying to transpile this package with babel in my webpack 4 config, but I haven't gotten it to work yet.
