### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on AWS with Node.js using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#462]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to AWS](https://aws.amazon.com/blogs/devops/automatically-deploy-from-github-using-aws-codedeploy/).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by geekguy** [comment]
@thinkingserious - should the code be in a separate repo?

**Comment by rkkautsar** [comment]
I'll give it a try ✋
