### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on Heroku with Node.js using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#463]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to Heroku](https://devcenter.heroku.com/articles/heroku-button).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by sw-yx** [comment]
claiming

**Comment by sw-yx** [comment]
you have a lot of tutorial requests - what is one already-developed and approved tutorial that we can work with to ensure your standards?

**Comment by mbernier** [comment]
We wanted to give people lots of options for hacktoberfest :) 

One tutorial that is solid is the "getting started" tutorial on this library. that's a good guide for the type of thing we're looking for - something easy to follow.

**Comment by sw-yx** [comment]
i asked for help in person and got help! working on this :)
