### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on Digital Ocean with Node.js using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#464]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-set-up-automatic-deployment-with-git-with-a-vps).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by devchas** [comment]
I can give this a shot

**Comment by devchas** [comment]
Submitted [this PR](https://github.com/sendgrid/sendgrid-nodejs/pull/510) for your reference
