### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on IBM Blue Mix with Node.js using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#465]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to IBM Blue Mix](https://www.ibm.com/blogs/bluemix/2016/01/deploy-to-bluemix-button-example/).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by childish-sambino** [comment]
Closing as this feels like more of a blog post than library documentation and use cases.
