### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on Microsoft Azure with Node.js using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#467]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to Microsoft Azure](https://docs.microsoft.com/en-us/azure/app-service/app-service-deploy-local-git).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by SarasArya** [comment]
I would like to give this one a shot. ✋🏻

**Comment by SarasArya** [comment]
Any update @thinkingserious ?

**Comment by thinkingserious** [comment]
@SarasArya,

Please add it here: https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md

Thank you!

With Best Regards,

Elmer

**Comment by SarasArya** [comment]
Hi Elmer

Should the tutorial reiterate the steps mentioned in the doc? Or just skip to the end, where I assume the app is already deployed and running on Azure? and going to a particular endpoint actually sends an email. 
I don't see a point in reiterating the same steps.

**Comment by thinkingserious** [comment]
It should be sufficient to reference the Azure docs for the steps specified there.

**Comment by SarasArya** [comment]
@thinkingserious  #490 done
