### ISSUE TITLE
Create a tutorial to create a Slack event integration with Node.js using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#470]
Create a tutorial that explains how to create a simple [integration with Slack](https://api.slack.com/events-api) that allows an email to be triggered based on some [defined event](https://api.slack.com/events).

The example should utilize best practices for storing credentials.

Please add the tutorial to USE_CASES.md.

**Comment by WiNloSt** [comment]
I'd like to work on this issue.

Can i just assumed users will already have a node server set up. So i can focus on how to deal with Slack payload.
