### ISSUE TITLE
Copy-pasting Sendgrid 'add recipients' example results in the error 'sg.API is not a function'

### ISSUE THREAD

**Issue by THook** [sendgrid/sendgrid-nodejs#474]
#### Issue Summary

Bug using Graphcool's SSR and es6 code example

#### Steps to Reproduce

1. create a SSR on user creattion
2. Copy-paste your code model on relevant ssr
3. Receive request timeout from logs

**Comment by thinkingserious** [comment]
Hello @THook,

Could you please provide the steps you took to install the SendGrid library?

Thanks!

With Best Regards,

Elmer

**Comment by THook** [comment]
Hello @thinkingserious , I submitted a PR some days ago about this issue. See here : https://github.com/graphcool/templates/pull/88/commits/d58d6a7cc9461246a8f13fc9951e80335268e3cd

**Comment by thinkingserious** [comment]
Hi @THook,

I have added this to our backlog for further investigation.

A quick look reveals that you might want to update to the [latest version of our SDK](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail), it has been greatly improved.

With Best Regards,

Elmer

**Comment by THook** [comment]
Aaaaw, I just realised I didn't submit the issue on the appropriate repository. My first comment was related to a Graphcool template using Sendgrid's API... Sorry for the inconvenience
