### ISSUE TITLE
Check type of callback before executing

### ISSUE THREAD

**Issue by nitish24p** [sendgrid/sendgrid-nodejs#487]
With reference to https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/src/mail.js#L105

This may not be a real issue, but i was wondering if a check can be made to ensure that the type of callback is a function and only then execute it, due to the dynamic nature of JS if an object is passed, it break the entire client. Just a suggestion to add

```javascript
      if (cb && typeof cb === 'function') {
        cb(error, null);
      }
```

Comments welcome here.

**Comment by nitish24p** [comment]
@thinkingserious  your views here.. :)

**Comment by thinkingserious** [comment]
Hi @nitish24p,

That seems like a good idea to me.

What do you think @adamreisnz?

With Best Regards,

Elmer

**Comment by nitish24p** [comment]
@thinkingserious If @adamreisnz also feels its a good idea i can make a PR. Do let me know :)

**Comment by adamreisnz** [comment]
@thinkingserious @nitish24p You are not expected to pass in any other type of variables for the callback, and if you do, it will throw an error so that you know something is wrong. If we add in the check, this would now silently fail and you might not know what is going on.

However, we can throw a specific error to notify the user, for example by adding in something like this here https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/src/mail.js#L53:

```js
if (cb && typeof cb !== 'function') {
  throw new Error('Callback passed is not a function');
}
```

If you could create a PR for that that'd be great 👍

**Comment by nitish24p** [comment]
Cool will do. This to be done at all places where there are callbacks? Or only specific files..

**Comment by adamreisnz** [comment]
I don't think there's too many places, most internal logic uses promises, it's only the external facing API that has callback support for backwards-ish compatibility.

**Comment by nitish24p** [comment]
Cool.. also do i need to update test cases.. for code coverage?

**Comment by adamreisnz** [comment]
Yep that'd be good. We're at or near 100% coverage now, so would be nice to keep it up. It'd be a simple test passing an invalid callback and making sure an error is thrown 👍

**Comment by nitish24p** [comment]
Cool

**Comment by nitish24p** [comment]
Umm i was wondering what if the below line
```javascript
if (cb && typeof cb !== 'function') {
  throw new Error('Callback passed is not a function');
}
```
could be added to 
https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/src/client.js#L131
as this is the center point for all callbacks being executed?

**Comment by adamreisnz** [comment]
Seems sensible!
