### ISSUE TITLE
Prevent secrets from sending in email

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#496]
Add a method that will check the content of the email before sending, to make sure that specific strings or patterns are not included.

For example, SG API keys look like this: SG.[a-zA-Z0-9_].[a-zA-Z0-9\-].

So the function could take a list of regex or specific strings to compare against. If a string is found, the mail/send should throw an exception

**Comment by spelcaster** [comment]
Follow #502

**Comment by thinkingserious** [comment]
Thanks @spelcaster!
