### ISSUE TITLE
Allows users to submit rfc822 formatted email addresses

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-nodejs#511]
#### Issue Summary

Similar to: https://github.com/sendgrid/sendgrid-python/pull/348

Where the user can submit email addresses as:
`example@example.com`
or 
`example example <example@example.com>`

**Comment by brandon93s** [comment]
It looks like this may be handled already by [split-name-email](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/helpers/helpers/split-name-email.js) which is consumed by [EmailAddress:fromData](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/helpers/classes/email-address.js#L27-L46).

Is there somewhere else this is not handled correctly?

**Comment by mbernier** [comment]
Nope, I just missed it. Thank you! @brandon93s
