### ISSUE TITLE
ES6-ify Inbound mail parser

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-nodejs#533]
#### Issue Summary

Refactor inbound mail parser to make more use of ES6 standards

**Comment by mukulmishra18** [comment]
I want to work on it. Thanks

**Comment by rafaelverger** [comment]
@mukulmishra18 I saw that u've wanted to do this but never sent any change suggestion so I did it.

**Comment by mukulmishra18** [comment]
@rafaelverger Great! But I saw that PR #534 is already submitted for this issue.

**Comment by rafaelverger** [comment]
Weird... I didn't see it mentioned here... sorry :s
