### ISSUE TITLE
Improve inline documentation

### ISSUE THREAD

**Issue by itaditya** [sendgrid/sendgrid-nodejs#537]
#### Issue Summary

The inline documentation is not completely following https://esdoc.org/manual/tags.html#object.
Becuase according to the rules, if a parameter is an object then all it's keys have to be documented as well.

Eg - 
```js
@param {Object} config inbound configuration object
function Parse(config, request) {
}
```
Here config is an object which is passed to Parse constructor function but it's keys are not documented

**Comment by mbernier** [comment]
Hey, @itaditya! Thanks for this issue. To help, I added esdoc config in #549, along with a coverage report! Hopefully, this will help other contributors (and us) to add more documentation.

**Comment by itaditya** [comment]
Ok great
