### ISSUE TITLE
ReferenceError: sendgrid is not defined while running tests

### ISSUE THREAD

**Issue by divyanshu013** [sendgrid/sendgrid-nodejs#541]
#### Issue Summary

I'm getting the following error while setting up the repo and running `yarn test`:
```
yarn run v1.2.1
$ npm run test:all -s


  test_contact_importer
    1) "before each" hook for "test_contact_importer sends items in batches"


  0 passing (7ms)
  1 failing

  1) test_contact_importer "before each" hook for "test_contact_importer sends items in batches":
     ReferenceError: sendgrid is not defined
      at Context.<anonymous> (packages/contact-importer/src/importer.spec.js:2:89)

```

#### Steps to Reproduce

1. Clone the repo
2. Install dependencies
3. Set up api key
4. Run tests `yarn test`

I think this is probably because of [this statement](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/contact-importer/src/importer.spec.js#L7) which causes `sendgrid is not defined`. A `require` of the correct package will probably fix this.

Let me know if I can help further or send a PR for this

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: 094260f1588d4ab80502faac2fb529a2d3db828b)
* Node.js Version: v8.6.0
* Ubuntu 16.04 (linux x64)

**Comment by rafaelverger** [comment]
PR #542 solves it
