### ISSUE TITLE
Create a PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#543]
#### Issue Summary

We would like to have a template for describing what has changed in the pull request being submitted.

[Github docs on this](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) 

You can use [this file](https://github.com/sendgrid/open-source-library-data-collector/blob/master/.github/PULL_REQUEST_TEMPLATE.md) as an example

**Comment by duncanleung** [comment]
Hi @thinkingserious can I take this one up?

**Comment by duncanleung** [comment]
Aw bummer. @thinkingserious are we going by who calls dibs, or did shivakaushal get this one already?

Either way, thanks!

**Comment by mbernier** [comment]
@duncanleung if you submit it - let me know, I'll take care of you!

**Comment by duncanleung** [comment]
Hi @mbernier thanks!

I'll get it submitted this weekend! Thanks again!

**Comment by duncanleung** [comment]
@mbernier working on this now! Thanks.
