### ISSUE TITLE
Add a .env_sample file

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#545]
Our preference is that users have an environment file when using the SendGrid API, because it is less likely that someone would commit their credentials to github.

Please make a couple changes:
- make a .env_sample file that contains: `export SENDGRID_API_KEY=''`
- make (or add) a .gitignore file and include `.env`
- add instructions to the README file about how to copy .env_sample to .env and add the API Key

**Comment by annnfrann** [comment]
Hi. I'd like to take this on.

**Comment by mbernier** [comment]
@annnfrann Awesome!!
