### ISSUE TITLE
Add a USAGE.md file

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#546]
Usage files are really nice when they exist in a repo, because it makes it really obvious where to look for information about how to use this tool. It can be frustrating when you expect this file to be there and it's not. 
Please add a USAGE.md file, you can see an example of this 
[here](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md)

Please make sure you modify the file for this repo (hint: Most of this information should be in the README file)

**Comment by duncanleung** [comment]
Aw bummer. @thinkingserious are we going by who calls dibs? Or did shivakaushal get this one already?

Either way, thanks!

**Comment by igauravsehrawat** [comment]
PR for this issue has been merged.
This issue can be closed, right?

Thanks

**Comment by thinkingserious** [comment]
You are correct @igauravsehrawat, thanks for the heads up!
