### ISSUE TITLE
Fix "file_lines" issue in packages/helpers/classes/personalization.spec.js

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#552]
File `personalization.spec.js` has 641 lines of code (exceeds 250 allowed). Consider refactoring.

Move each example out to its own file and add a markdown that links to each example.

https://codeclimate.com/github/sendgrid/sendgrid-nodejs/packages/helpers/classes/personalization.spec.js#issue_59f39f42b5ec1a000100006c

**Comment by Hugainz** [comment]
@thinkingserious can I take a swing at this?

**Comment by t2013anurag** [comment]
@thinkingserious - I will pick this up.
