### ISSUE TITLE
Broken link to handling errors in troubleshooting docs 

### ISSUE THREAD

**Issue by shubham-padia** [sendgrid/sendgrid-nodejs#574]
#### Issue Summary
 
In [error messaging section](https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md#error-messages) of troubleshooting.md, the link to the example is broken

#### Steps to Reproduce

1. Go to https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md#error-messages
2. Click on the example link
3. The example link is https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#successfailureerrors
 which redirects to the top of the page instead of the required section.
4. Next Step: Fix the broken link
Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

**Comment by shubham-padia** [comment]
Sending a PR for this

**Comment by mbernier** [comment]
Thank you!
