### ISSUE TITLE
Fix "file_lines" issue in packages/helpers/classes/mail.js

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#578]
File `mail.js` has 383 lines of code (exceeds 250 allowed). Consider refactoring.

https://codeclimate.com/github/sendgrid/sendgrid-nodejs/packages/helpers/classes/mail.js#issue_59f69ca8ae637e0001000090

**Comment by ruinedshit** [comment]
@thinkingserious can you elaborate this issue? noob here.

**Comment by martiuslim** [comment]
this appears to be a duplicate issue #553
