### ISSUE TITLE
Fix "method_complexity" issue in packages/helpers/helpers/array-to-json.js

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#579]
Function `exports` has a Cognitive Complexity of 6 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sendgrid/sendgrid-nodejs/packages/helpers/helpers/array-to-json.js#issue_59f69ca8ae637e0001000097

**Comment by afischer12** [comment]
I'll see what i can do!
