### ISSUE TITLE
Add CodeCov support to .travis.yml

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-nodejs#582]
Issue Summary

Add this to our travis.ci configuration so that code coverage tests will run!
https://github.com/codecov/example-node/blob/master/.travis.yml

**Comment by sevfitz** [comment]
I would like to do this! 

I had a question, though--I came across this other codecov example with an after_success script that isn't in the example pasted above:
[https://github.com/codecov/codecov-node/blob/master/.travis.yml](https://github.com/codecov/codecov-node/blob/master/.travis.yml)

That's not needed here, correct (I should match the example-node as you said)?

Thank you!
