### ISSUE TITLE
Hacktoberfest: SendGrid Current Status

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-nodejs#588]
## SendGrid DX team current status:
- Wow
- OMG
- THANK YOU

Hacktoberfest 2017 has completely blown us away. We have had over 900 pull requests from over 300 contributors all in the last 30 days. That is more PRs than we normally get in 2 years! 
We are actively working to review, comment, and/or merge as many PRs as we possibly can as quickly as we can.

We are currently working on “intaking” all the PRs that have come in, oldest first (we have about 400 remaining to go through). We are making sure that each PR we review is one we have a chance of merging - there have been a couple spammy items that came through. Due to the massive influx of requests so far, @thinkingserious and @mbernier have been working nights and weekends all month just to keep up! We’re not even mad, this is amazing!  
## Hey, that’s great for you - but what about my shirt!
If you have signed the CLA before 11/1, but haven’t had a PR merged yet, do not despair! We know we are behind on even just commenting on every PR to show you that we received it (something we typically do). If you submitted a mergeable (non-spam, actually adds value to the project) PR during October 2017, we will grant access to [this page](https://dx.sendgrid.com/swag) to redeem your shirt, sticker, and hacker pin. Next year, we will be sure to communicate this information sooner. We are sorry for any confusion we have caused. We appreciate those of you who have reached out to find out what’s going on! 

## What can I do to help move things along?
**Have you signed the CLA yet?** 
We can only merge items from contributors who signed the CLA

**Can you help another contributor?** 
If you can identify potential problems, add suggestions, or even leave a comment with your review of another PR (Looks good to me! Or I approve this change), that would help us review those PRs much faster, making it easier to get to your PR.

**Do you even write tests, friend?** 
If you see a place where we could have a test to validate a piece of functionality, add it in. We know We know! It’s just another PR we have to review and merge. You’re right, it is! However, the more tests we have, the earlier our CI tool can catch issues, saving us a review as well as back and forth time. 

@adamreisnz, @anthonyjuan, @bharatzvm, @devanp92, @devchas, @ElPonito, @HeroProtagonist, @hicks2evan, @itaditya, @Kunalgarg2100, @mcmilo, @mp-ffx, @mptap, @phgroe, @pranavrajs, @Remorax, @SarasArya, @shubham-padia, @SidduH, @spelcaster, @thepriefy, @TheWillG, @TunedMidja, @ugurnc, @WiNloSt

**Comment by adamreisnz** [comment]
Great stuff!

**Comment by mbernier** [comment]
It has been amazing, nuts, and we are all tired (and a bit loopy from it all). It's kind of fantastic!

**Comment by nitish24p** [comment]
@mbernier have these left? or in progress?

**Comment by Remorax** [comment]
Yeah, I want to know too. Its been a month, so is there any way we could track it? Thanks :)

**Comment by HeroProtagonist** [comment]
Have people received their shirts from sendgrid?

**Comment by itaditya** [comment]
Not yet

**Comment by TheWillG** [comment]
I have not.

**Comment by thinkingserious** [comment]
@nitish24p @Remorax @HeroProtagonist @itaditya @TheWillG 

Our swag fulfillment house has everything now. Due to having over 500 contributors when we were expecting less than 100, we had to print new shirts, stickers, and pins. So it took a little longer than we thought it would. You should see an email soon from us or from KotisDesigns telling you all about the shipment information.

Thanks for your contributions and patience!

With Best Regards,

Elmer

**Comment by valerianpereira** [comment]
No signs about this yet :/

**Comment by HeroProtagonist** [comment]
I got mine a few days ago. Thanks sendgrid!

**Comment by thinkingserious** [comment]
Hello @valerianpereira,

It looks like some countries take a bit longer to receive our swag. Our provider believes all swag should be delivered by the end of this month.

With Best Regards,

Elmer

**Comment by Remorax** [comment]
@thinkingserious @mbernier I still haven't received the swag :/
I'm from India, any ideas when it would reach here?

**Comment by thinkingserious** [comment]
Hi @Remorax,

Yes India is a country where shipping is delayed. Unfortunately, we don't have good tracking resources there, but know that shipments are still being delivered. Once we get word that all shipments should have arrived, I'll check back to make sure you received it. 

Apologies for the delay and thank you for your patience. 

With Best Regards,

Elmer
