### ISSUE TITLE
Fix "method_complexity" issue in packages/helpers/helpers/array-to-json.js

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#589]
Function `exports` has a Cognitive Complexity of 6 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sendgrid/sendgrid-nodejs/packages/helpers/helpers/array-to-json.js#issue_59f808a77f269e0001000091

**Comment by afischer12** [comment]
I'll look into this

**Comment by childish-sambino** [comment]
Cognitive Complexity not currently an issue.
