### ISSUE TITLE
Add Code Review to Contributing.md

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#593]
- Add a "Code Reviews" section on CONTRIBUTING.md
- Put the following under the header:
> If you can, please look at open PRs and review them. Give feedback and help us merge these PRs much faster! If you don't know how, Github has some great [information on how to review a Pull Request](https://help.github.com/articles/about-pull-request-reviews/).
- Link the header in the Contributing.md Table of Contents
- Add a link to the README.md file: [Review Pull Requests]("CONTRIBUTING.md#Code-Reviews") under "Contributing Section"

**Comment by mptap** [comment]
@thinkingserious: PR: https://github.com/sendgrid/sendgrid-nodejs/pull/595
