### ISSUE TITLE
Create a Use Cases Directory

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#596]
Due to the success we have seen from hacktoberfest, we are seeing more people create use cases. This is amazing! 
We want to make sure that everyone can find them. Please help us to break up this file and make it easier to read and manage:
- Create a Use Cases Directory
- Put a README.md in this directory
- Make a file in the new directory for each individual Use Case from USE_CASES.md, copy the content to this file
- For each file you've created, link to it from the README you created
- Organize the links in the README by type
- Make sure the names of the files you created are related to the Use Case
Thank you!

**Comment by shriyash** [comment]
Hi @thinkingserious - working on this right now!
