### ISSUE TITLE
Substitutions not working

### ISSUE THREAD

**Issue by holotrek** [sendgrid/sendgrid-nodejs#604]
#### Issue Summary

I can't seem to get substitutions to work correctly, using a Transactional template. My template has the substitution tag `{ClientUrl}` in it.

The email continues to only show `{ClientUrl}` rather than the actual URL replacement.

This is the code that I'm using (with personal info removed): https://github.com/holotrek/sendgrid-node-test/blob/master/index.js

I've also tried various other formats for the substitution, including:
* `[ClientUrl]`
* `[#ClientUrl]`
* `%ClientUrl%`
* `<%ClientUrl%>`

#### Steps to Reproduce

1. Create transactional template with `{ClientUrl}` anywhere in the content in addition to `<%body%>`. Grab template ID and SendGrid API key.
2. `git clone https://github.com/holotrek/sendgrid-node-test.git`
3. Replace strings in `<>` with your particular keys/emails. *(Note: I know not to put the API key right in the code, but for the purpose of this demo, I've attempted to make it as easy as possible to replicate.)*
4. `node index.js`
5. Check for sent email
6. See that it still says `{ClientUrl}`
7. **Expected**: `{ClientUrl}` to be replaced with `http://localhost:4200`

#### Technical details:

* sendgrid-nodejs Version: 6.1.4
* Node.js Version: 6.9.1

**Comment by thinkingserious** [comment]
Hello @holotrek,

My guess is that you may have not specified the substitution wrappers in your code, [like so](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#transactional-templates).

Please take a look and let me know what you think.

With Best Regards,

Elmer

**Comment by holotrek** [comment]
Oh, that explains it, thanks. I was reading the [SendGrid documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html) about it going right into the substitution section and didn't realize that the Node.js library did it slightly differently.
