### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by nharbo** [sendgrid/sendgrid-nodejs#611]
#### Issue Summary
I'm trying to send an email from my backend, which is build on a (Parse) NodeJS server. When I get to the sendgrid.send-function, my server crashes with the following:

TypeError: Cannot read property 'call' of undefined
    at IncomingMessage.<anonymous> (/Users/....../node_modules/sendgrid-nodejs/lib/sendgrid.js:74:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

#### Steps to Reproduce

installed the sendgrid-nodejs npm package
Imported var SendGrid = require('sendgrid-nodejs').SendGrid; in my class
Set var sendgrid = new SendGrid("sendgrid username here", "api key here");

And then running:
sendgrid.send({
		  to: 'aa@bb.one',
		  from: 'bb@aa.one',
		  subject: 'Hello World',
		  text: 'My first email through SendGrid'
		});

#### Technical details:

* Node.js Version: 3.10.10

**Comment by nitish24p** [comment]
Can you try the following as per the new docs

```bash
npm install --save @sendgrid/mail
```


```javascript
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'test@example.com',
  from: 'test@example.com',
  subject: 'Sending with SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};
sgMail.send(msg);
```

Also before this please please remove all node_module pacakges pertaining to sendgrid

**Comment by etisdew** [comment]
This seems like quite an old version of node. Is it possible that its not finding support or a polyfill for the call method? Please disregard if I am totally off base.
