### ISSUE TITLE
How to enable sandbox

### ISSUE THREAD

**Issue by SimoMay** [sendgrid/sendgrid-nodejs#612]
#### Issue Summary

How to enable "sandbox" mode, using only "@sendgrid/mail"

#### Technical details:

* @sendgrid/mail: 6.1.4
* Node.js Version: 8.9.0

**Comment by thinkingserious** [comment]
Hi @CrazyGentleMan,

My apologies, it seems that we have left out that use case [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#kitchen-sink). It should be within `mail_settings`. [Here](https://sendgrid.com/docs/API_Reference/api_v3.html) is the complete payload for reference.

I've added this to our backlog.

For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

Thanks! 

With Best Regards,

Elmer

**Comment by victor-ponce** [comment]
Does the email show up in the dashboard when sandbox mode is enabled?

**Comment by thinkingserious** [comment]
@victor-ponce,

I don't think so.

**Comment by notdmart** [comment]
#850 to add this documentation

**Comment by ferarnoled** [comment]
For V3 here's the snippet

```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'recipient@example.org',
  from: 'sender@example.org',
  subject: 'Hello world',
  text: 'Hello plain world!',
  html: '<p>Hello HTML world!</p>',
  templateId: 'd-f43daeeaef504760851f727007e0b5d0',
  dynamic_template_data: {
    subject: 'Testing Templates',
    name: 'Some One',
    city: 'Denver',
  },
  **mail_settings: {
    sandbox_mode: {
      enable: true
    }
  },**
};
sgMail.send(msg);
```

**Comment by jamespedid** [comment]
The Mail#toJson method is not properly converting mailSettings to mail_settings or sandboxMode to sandbox_mode, as far as I can tell.

**Comment by malimccalla** [comment]
Is this not possible? My current sendgrid file looks like this

```ts
import sgMail from '@sendgrid/mail';

const sendGridApiKey = process.env.SENDGRID_API_KEY;

if (!sendGridApiKey) {
  throw new Error('The sendgrid api key has not been set in the environment variables');
}

sgMail.setApiKey(sendGridApiKey);

// I need to be able to do something like this
sgMail.enableSandbox(process.env.NODE_ENV !== 'production')

export { sgMail };
```

It would be great if eventually sendgrid allowed you to generate sandbox api keys much like stripe test keys

**Comment by childish-sambino** [comment]
PR merged to add this to the docs.

@malimccalla That's not currently supported. Since it's not quite the same as the original request, could you open a new issue to track this?

**Comment by malimccalla** [comment]
@childish-sambino Done! #1128
