### ISSUE TITLE
Request to take this issue.

### ISSUE THREAD

**Issue by etisdew** [sendgrid/sendgrid-nodejs#614]
#### Issue Summary
sendgrid-nodejs/packages/helpers/classes/personalization.js
# Similar blocks of code found in 3 locations. Consider refactoring.
  - line 99  ```setTo(to) {```
  - line 122  ```setCc(cc) {```
  - line 145  ```setBcc(bcc) {```
These can be combined into a single function. If you agree, I request the chance to make this change. See...
https://codeclimate.com/github/sendgrid/sendgrid-nodejs/packages/helpers/classes/personalization.js#

**Comment by mbernier** [comment]
Do it!

**Comment by mbernier** [comment]
Oops, sorry about closing this. It's all yours!!

**Comment by etisdew** [comment]
Thank you, confirming I have seen this. Can I message you here if I run into any decisions or considerations?

**Comment by etisdew** [comment]
To be clear the primary content of this file is handling type checking of something that would simply be defaulted in a perfect world. Would it be an anti pattern to abstract the behavior to the class properties in the initial definition?
eg this.property = validationFunction(options.property) || [];

**Comment by etisdew** [comment]
Please don't allow me to block this issue from being fulfilled. Taking another moment to better understand the scope of this file.

**Comment by etisdew** [comment]
Where is the sanitation of data handled? Will it be checked with a regular expression in the pipeline prior to being applied here or should we cover injection cases?

**Comment by mbernier** [comment]
These functions are trying to do some "pre-validation" of the data before it gets passed to the "EmailAddress" class. I believe what codeclimate is saying is that, since we are doing the same thing 3 times - it might make sense to do this once, inside the EmailAddress class. 

Specifically, if the type checks for undefined and isArray were done in EmailAddress.create, then the code would be less repetitive.

```
  setCc(cc) {
    if (typeof cc === 'undefined') {
      return;
    }
    if (!Array.isArray(cc)) {
      cc = [cc];
    }
    this.cc = EmailAddress.create(cc);
  }
```

**Comment by etisdew** [comment]
Indeed, I also see there is a lot of redundancy in ^`set<Something>` methods, I would like to reduce this to a single method that handles each case aswell. My concern is learning how to grep and finding these methods being called and replacing them with a generalized call to set. Trying to find a clean alternative to grouping these error messages to still offer informative direction as expected type goes out the window with my solution.

**Comment by thinkingserious** [comment]
Hi @etisdew,

I'm not sure what you mean by client side sterilization procedure, could you please elaborate?

Thanks!

With Best Regards,

Elmer

**Comment by etisdew** [comment]
My inquiry might be misplaced in regards to the execution path as I am still very green but I would like to verify no security concerns regarding this section of code. It does seem that the redundant methods contained within Personalization and EmailAddress would best be handled as its own helper set but with some policing of what would be acceptable for your digestion. ie regex, I am assuming that this occurs earlier at the input phase.

**Comment by etisdew** [comment]
In deeper investigation I am unable to discern potential liabilities and breaks on forks resulting from class refactoring, the spirit of reducing lines maybe better placed in tracing possible injection through these fields with regex removal of \`,~,',/,,,.,),;etc I have no impedance to inject at this endpoint and desperately little time to elevate myself to understanding the trace back into the main program, if that is relevant to you.
