### ISSUE TITLE
Email still being sent to unsubscribed email

### ISSUE THREAD

**Issue by alexwalling** [sendgrid/sendgrid-nodejs#616]
#### Email still being sent to unsubscribed email

I'm using the ASM groups along with the unsubscribe tracking through SendGrid. It's properly tracking the unsubscribes, but I'm unsure how to make sure an email isn't being sent to the unsubscribed users. I've tested it with my own email(i.e. I unsubscribe and send an email to myself) and the email is still sent.

I'm not sure if I'm just missing something, or if something is going wrong. Here's the code:

```
                      let fromEmail = new helper.Email('me@myemail.com');
                      let toEmail = new helper.Email(email);
                      let subject = 'Subject';
                      let content = new helper.Content('text/html', html);

                      let mail = new helper.Mail(fromEmail, subject, toEmail, content);

                      let category = new helper.Category('mycategory');
                      let primCategory = new helper.Category('mycategoryprim');
                      mail.addCategory(category);
                      mail.addCategory(primCategory);

                      let ASM = new helper.Asm(4215);
                      mail.setAsm(ASM);

                      let sg = require('sendgrid')('********************************');
                      let request = sg.emptyRequest({
                        method: 'POST',
                        path: '/v3/mail/send',
                        body: mail.toJSON()
                      });

                      sg.API(request)
                      .then((response) => {
                        resolve(username);
                      })
                      .catch((error) => {
                        reject(error.response);
                      });
```

#### Technical details:

* Node.js Version: v8.0.0

**Comment by thinkingserious** [comment]
Hello @alexwalling,

Thanks for letting us know about this issue.

A couple of data points will help us trouble shoot for you:

1. Could you please verify what emails are in ASM group 4215?
2. Could you post the result of `mail.toJSON()` before you call `sg.API`?

Also, you might want to upgrade to the [latest version of this SDK](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail).

Thanks!

With Best Regards,

Elmer
