### ISSUE TITLE
Can't see how to send a plain text only email

### ISSUE THREAD

**Issue by joelanman** [sendgrid/sendgrid-nodejs#623]
#### Issue Summary

I can't see any docs to say how to send a plain text only email. My guess was to simply to fill in the `text` property of the message, and not the `html`. However when I do this, Sendgrid automatically also sends an html version of my email. In this version the newlines are stripped out. How do I just send plain text?

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-nodejs Version: @sendgrid/mail@6.1.4
* Node.js Version: 8.9.1

**Comment by joelanman** [comment]
OK so I found the account setting which autoconverts to html, which is default to on:

https://sendgrid.com/docs/User_Guide/Settings/mail.html#-Plain-Content

I found this to be an unexpected default, and would be useful to be linked from more of the docs eg here in the client docs, and [this page that comes up in google for plain text](https://sendgrid.com/docs/Classroom/Build/Format_Content/plain_text_emails_converted_to_html.html) that doesnt mention it

**Comment by thinkingserious** [comment]
Hello @joelanman,

Thanks for taking some time to share feedback with us, it is greatly appreciated!

We send both HTML and text because this helps improve your email deliverability. One of the items some SPAM filters looks at is whether you have both text and HTML versions of your email.

With Best Regards,

Elmer

**Comment by elpaso2** [comment]
@thinkingserious thats not cool, i am using a parsing system that requires text format only, now it doesn't work

**Comment by thinkingserious** [comment]
Hello @elpaso2,

What version of the SDK are you using?

**Comment by elpaso2** [comment]
not cool at all, not everyone need the html, i also send to parsing system, spent days before knowing its not my code

**Comment by elpaso2** [comment]
version "sendgrid/sendgrid": "~7",

**Comment by pselle** [comment]
Following, also looking for this setting for a user who's requested non-HTML emails

**Comment by aroach** [comment]
there’s a way in Mail Settings to enable plain only globally (see below).
If you have more questions, I'd recommend pinging our support team @
https://support.sendgrid.com

https://app.sendgrid.com/settings/mail_settings

You want to disable:


Plain Content
: Convert your plain text emails to HTML.

**Comment by thinkingserious** [comment]
Hi @pselle, @elpaso2,

You should also be able to do something [like this](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/single-email-single-recipient.md#send-a-single-email-to-a-single-recipient), but simply leave off the html parameter.

With Best Regards,

Elmer
