### ISSUE TITLE
Heroku get started docs are different to the docs here

### ISSUE THREAD

**Issue by joelanman** [sendgrid/sendgrid-nodejs#624]
#### Issue Summary

The docs on [your Heroku page](https://devcenter.heroku.com/articles/sendgrid#node-js) give different, more complicated 'get started' instructions than you give on this repo, and refer to a different npm module

**Comment by mbernier** [comment]
As someone who is not super familiar with Heroku setup, would you be willing to let me know which one worked the best for you? We will work to make sure they are syncd up, so the experience is the same in both places!

**Comment by mzc9** [comment]
I would like to take this up, if I may

**Comment by thinkingserious** [comment]
We need to work with Heroku on updating the docs there. For now, I would recommend following the instructions in this repo. Thanks!
