### ISSUE TITLE
Setting an array of email address for 'to' results in error `Error: Provide at least one of to, cc or bcc`

### ISSUE THREAD

**Issue by warnero** [sendgrid/sendgrid-nodejs#625]
#### Issue Summary

I have tried multiple different formats to send to multiple email addresses and every single one of them has failed with the error message `Error: Provide at least one of to, cc or bcc`. I can find no clear tutorial or docs to explain why this won't work or what needs to happen to make it work properly.

#### Steps to Reproduce
Here are all the different ways I've tried to se the to inside of my json message:
`to: ['email@xyz.com', 'email@abc.com']`
`to: 'email@xyz.com;email@abc.com'`
`personalizations: [to:{[ { email: 'email@xyz.com' },
{ email: 'email@abc.com' } ]`

#### Technical details:

* sendgrid-nodejs Version: 6.1.4
* Node.js Version: 6.11.5

**Comment by nitish24p** [comment]
From what i can see in the code snippet you've given above.

```javascript
personalizations: [to:{[ { email: 'email@xyz.com' }, { email: 'email@abc.com' } ]
```
is incorrect javascript syntax. Could you please update the issue with the correct code syntax.

**Comment by warnero** [comment]
Sorry it was a quick example, it is correct for when I send it like so:
`personalizations: [to:{[ { email: 'email@xyz.com' }, { email: 'email@abc.com' } ]}]`
Sorry for missing brackets in my haste to get it in the ticket. However this still doesn't change the fact that it doesn't work. A concrete example would be awesome. Every example I've seen linked in previous github tickets point at non-existent pages.

**Comment by nitish24p** [comment]
I'm sorry i still didnt get you `personalizations: [to:{[ { email: 'email@xyz.com' }, { email: 'email@abc.com' } ]}]` is still incorrect syntax. Can you please share your exact code.

**Comment by warnero** [comment]
Here is a nearly full example of what I am attempting to send.
```
{
  "from": "donotreply@test.com",
  "templateId": "xxx",
  "subject": "My Subject
  "personalizations": [
    {
      "to": [
        {
          "email": "test@abc.com"
        },
        {
          "email": "test@xyz.com"
        }
      ]
    }
  ]
}
```

**Comment by warnero** [comment]
Ultimately I want to just use this format (which from what I've seen with other examples should just work, but doesn't):
`to: ['email@xyz.com', 'email@abc.com']`
I have no need for personalizations or text replacement, etc. I just want to send a message to multiple email addresses. Tell me the shortest way to do that and I'll be good!

**Comment by nitish24p** [comment]
```javascript
sgMail.setApiKey(API_KEY);
const msg = {
  to: ['email1@gmail.com' ,'email2@gmail.com', 'email3@gmail.com'],
  from: 'test@example.com',
  subject: 'Sending with SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};
sgMail.send(msg)
```
This should work.

**Comment by warnero** [comment]
When I do that I see no error message (I get a 200 back), but no emails are sent to the email addresses.

**Comment by thinkingserious** [comment]
Hello @warnero,

I believe [this](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#send-a-single-email-to-multiple-recipients) is the example you need.

For the email that gets listed as invalid, could you please email us at dx@sendgrid.com with the specific email?

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Thanks for trying to help @nitish24p!
