### ISSUE TITLE
Reply To

### ISSUE THREAD

**Issue by ericuldall** [sendgrid/sendgrid-nodejs#632]
I can't find a single example of how to customize a Reply-To header with this library. Can you please point me in the right direction?

Currently trying something like this...
```
  let mail = new helper.Mail(
      new helper.Email(this.from),
      this.subject,
      new helper.Email(this.to),
      new helper.Content('text/html', this.content),
      new helper.Header('Reply-To', this.to)
    );
```

**Comment by ericuldall** [comment]
I think I'm getting closer...
I tried this:
```
mail.personalizations[0].addHeader(new helper.Header('Reply-To', this.to));
```

Then got an error:
```
                {
                    "message": "Header can not be one of the reserved keys. Refer to documentation link.",
                    "field": "personalizations.0.headers.Reply-To",
                    "help": "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.headers"
                }
```

Unfortunately there was nothing very helpful in the documentation it pointed me to.

**Comment by thinkingserious** [comment]
Hi @ericuldall,

[Here is an example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#cc-bcc-and-reply-to) with reply to. Please let me know if that works for you. Thanks!

With Best Regards,

Elmer

**Comment by ericuldall** [comment]
Thanks @thinkingserious !

I actually just got it solved using the mail helper as follows...

```
let mail = new helper.Mail(
      new helper.Email(this.from),
      this.subject,
      new helper.Email(this.to),
      new helper.Content('text/html', this.content)
    );
    mail.setReplyTo(new helper.Email(this.to));
```

Works for me!

**Comment by thinkingserious** [comment]
Awesome! Thanks for the follow up!

**Comment by alexandr-efimov** [comment]
https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/cc-bcc-reply-to.md

You can specify the cc, bcc, and replyTo fields for more control over who you send the email to and where people will reply to:

```
const msg = {
  to: 'recipient@example.org',
  cc: 'someone@example.org',
  bcc: ['me@example.org', 'you@example.org'],
  from: 'sender@example.org',
  replyTo: 'othersender@example.org',
  subject: 'Hello world',
  text: 'Hello plain world!',
  html: '<p>Hello HTML world!</p>',
};
```
