### ISSUE TITLE
SendGridError: Response error - Why is it happening?

### ISSUE THREAD

**Issue by snahrvar** [sendgrid/sendgrid-nodejs#633]
#### Issue Summary

We've been using SendGrid for many months on our app and haven't made any updates in the last couple weeks. Tonight, out of nowhere, the SendGrid API is no longer providing a valid response to our request. So here is how our process works: it loops through hundreds of emails and makes individual requests to your API. What has been happening tonight is that a handful of requests will go through, but the entire process will shut down when your node package throws an error: SendGridError: Response Error.

Here's the log:
SendGridError: Response error
    at /home/snahrvar/node_modules/sendgrid/lib/sendgrid.js:123:19
    at IncomingMessage. (/home/snahrvar/node_modules/sendgrid-rest/lib/client.js:112:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

####Additional Notes

This error does NOT occur if I try sending a single email. It only occurs with the bulk email process, and as far as we can tell, it only started happening today. PLEASE help me understand what has changed to cause this error.

#### Technical details:

* sendgrid-nodejs Version: 4.0.2 (also tested with latest version)
* Node.js Version: 6.4.0

**Comment by thinkingserious** [comment]
Hello @snahrvar,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
