### ISSUE TITLE
Unauthorized (401) Permission denied, wrong credentials

### ISSUE THREAD

**Issue by piilupart88** [sendgrid/sendgrid-nodejs#635]
#### Issue Summary
I am quite clueless. I believe I have done everything by the book, but I'm getting Unauthorized 401 error.

#### Steps to Reproduce
1. Created sendgrid account and API key.

2. Edited my API key to have all permissions (POST, GET, etc).

3. In terminal ran commands:
`echo "export SENDGRID_API_KEY='my-API-key'" > sendgrid.env`
`echo "sendgrid.env" >> .gitignore`
`source ./sendgrid.env`

4. In my express app I'm using this code:
`const sendgrid = require('@sendgrid/mail');`
`sendgrid.setApiKey(process.env.SENDGRID_API_KEY);`

`app.get('/', (req, res) => {`
 ` const msg = {`
 `   to: 'my-email@gmail.com',`
 `   from: 'my-other-email@gmail.com',`
`    subject: 'Sending with SendGrid is Fun',`
 `   text: 'and easy to do anywhere, even with Node.js',`
 `   html: '<strong>and easy to do anywhere, even with Node.js</strong>',`
 ` };`

 ` sendgrid.send(msg)`
`    .then(() => {`
`      res.send('OK');`
`      console.log('success!!');`
`    })`
`    .catch(error => {`
`      console.error(error.toString());`
`    });`
`});`

What am I doing wrong?

#### Technical details:

* sendgrid-nodejs Version: 6.4.1
* Node.js Version: 7.10.0
* macOS Version: 10.12.6

**Comment by thinkingserious** [comment]
HI @piilupart88,

Just checking to be sure you closed this because your issue is resolved. Please let us know. 

Thanks!

Elmer
