### ISSUE TITLE
not able to send mail with image

### ISSUE THREAD

**Issue by donno13** [sendgrid/sendgrid-nodejs#636]
```javascript
let message = {
      to: toEmail,
      from: liveCampaign.emailFromAddress,
      subject: liveCampaign.emailSubjectTemplate,
      text: "hi",
      html: '<img src="content_id:myimagecid" alt = "graphics">',
      files: [
        {
          filename: "Christmas2.png",
          content: ("image" | Buffer),
          content_id: "myimagecid",
          contentType: "image/png"
        }
      ]
    };
```

above is the  code  i have wriiten to send mail using sendgrid .but i am getting error as such 
 message: 'Response error',
  response:
```javascript
   { statusCode: 400,
     body: { errors: [Array] },
     headers:
      { server: 'nginx',
        date: 'Tue, 05 Dec 2017 12:21:08 GMT',
        'content-type': 'application/json',
        'content-length': '320',
        connection: 'close',
        'access-control-allow-origin': 'https://sendgrid.api-docs.io',
        'access-control-allow-methods': 'POST',
        'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
        'access-control-max-age': '600',
        'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' } } }
```
please help me

**Comment by nitish24p** [comment]
Are u encoding the image into a base64 string?

**Comment by donno13** [comment]
got the solution but it is attaching the image as a separate attachment.can
you help me in embedding the image in message body

**Comment by sjm2932** [comment]
I'm trying to send an email with an embedded image using the following code and nodemailer module.
It is not working. Please help me    

var transporter = nodemailer.createTransport({
        host: "smtp.sendgrid.net",
        port: 465,
        secure: true, 
        auth: {
            user: "aaa",
            pass: "bbb"
        }
    })
    var mailAttachmentList = [];


    var htmlStr = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\" \"http://www.w3.org/TR/REC-html40/loose.dtd\">"
        + "<html style=\"font-size: 100%; font-family: Tahoma, Verdana, Arial, Helvetica, sans-serif; margin: 0; padding: 0; border: 0;\">"
        + "<head>"
        + "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">"
        + "<title>Test</title>"
        + "</head>"
        + "<body style=\"font-family: Tahoma, Verdana, Arial, Helvetica, sans-serif; line-height: 1; margin: 0; padding: 0; border: 0;\">"
        + "<center>"
        + "&lt;img src='cid:" + md5("testImages") + "'/>"
        + "</center>"
        + "</body>"
        + "</html>";
    mailAttachmentList.push(
        {
            filenname: 'myimage.png',
            filePath: 'C:/myfolder/',
            cid: md5("testImages")
        }
    );
    var mailOptions = {
        from: 'aaa@bbb.ccc',
        to: 'aaa@bbb.ccc',
        subject: 'imagetest',
        html: htmlStr,
        attachments: mailAttachmentList
    };
    transporter.sendMail(mailOptions, function (error, info) {
        if (error) {
            var msgStr = "Email Error: " + error
            console.error(msgStr);
        } else {
            var msgStr = "Email: email sent successfully"
            console.error(msgStr);
        }
    });

**Comment by thinkingserious** [comment]
Thanks for helping out @nitish24p!

Hi @donno13,

Under `contentType`, try adding `disposition: inline`.

Thanks!

Elmer
