### ISSUE TITLE
Send an email with embedded image using nodemailer

### ISSUE THREAD

**Issue by sjm2932** [sendgrid/sendgrid-nodejs#637]
I'm trying to send an email with an embedded image using the following code and nodemailer module.
It is not working. Please help me

var transporter = nodemailer.createTransport({
host: "smtp.sendgrid.net",
port: 465,
secure: true,
auth: {
user: "aaa",
pass: "bbb"
}
})
var mailAttachmentList = [];
var htmlStr = "<html><body><img src='cid:" + md5("testImages") + "'/></body></html>"

mailAttachmentList.push(
    {
        filenname: 'myimage.png',
        filePath: 'C:/myfolder/',
        cid: md5("testImages")
    }
);
var mailOptions = {
    from: 'aaa@bbb.ccc',
    to: 'aaa@bbb.ccc',
    subject: 'imagetest',
    html: htmlStr,
    attachments: mailAttachmentList
};
transporter.sendMail(mailOptions, function (error, info) {
    if (error) {
        var msgStr = "Email Error: " + error
        console.error(msgStr);
    } else {
        var msgStr = "Email: email sent successfully"
        console.error(msgStr);
    }
});

**Comment by thinkingserious** [comment]
Hello @sjm2932,

My apologies for the delayed response.

The Nodemailer repo is [here](https://github.com/sendgrid/nodemailer-sendgrid-transport). 

With Best Regards,

Elmer
