### ISSUE TITLE
substitutions don't work in transactional templates

### ISSUE THREAD

**Issue by MaciejKrawczyk** [sendgrid/sendgrid-nodejs#638]
![screenshot from 2017-12-08 10-36-46](https://user-images.githubusercontent.com/22261988/33759861-1deb7080-dc04-11e7-8433-b241be0c452c.png)
#### Issue Summary

Substitutions don't work when using this library. It works when using curl. 

#### Steps to Reproduce

1. Create a transactional email template in your SendGrid account
2. Have either <%body%> in the template, %firstName% or both (I tried both)
4. Execute this node code (fill in the config)
```
`'use strict';

var config = {
	
	apiKey: '',
	from: '',
	to: '',
	templateId: ''

}
 
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(config.apiKey);
 
async function sendTest() {
 
 var newMsg = {
  
   "from": {
    "name": "Test Script",
    "email": config.from
   },
   "personalizations": [{
    "to": config.to,
    "substitutions": {
     "-firstName-": "Maciejs", 
     "%firstName%": "Maciej",
	 "-first_name": "Maciej",
	 "%first_name%": "Maciej"
    }
   }],
   "subject": "test subject",
   "content": [{
     "type": "text/plain",
     "value": "Hello, %firstName%!"
    },
    {
     "type": "text/html",
     "value": "<html><p>Hello, %firstName%!</html> "
    }],
    "template_id": config.templateId
 }
 
   await sgMail.send(newMsg);
 
}
 
sendTest();`
```
5. Notice that nothing will be replaced in the delivered email. Again, it works perfectly with curl. 

I'm also attaching a screenshot of the template in SendGrid editor and the email I get
![screenshot from 2017-12-08 10-36-26](https://user-images.githubusercontent.com/22261988/33759860-1a8717f0-dc04-11e7-9d1a-6d860edc6173.png)

#### Technical details:

* sendgrid-nodejs Version: 6.1.4
* Node.js Version: 8.9.2

**Comment by kmcurry** [comment]
@MaciejKrawczyk in the previous version the `substitutions` object was not contained by the `personalizations` array. `substitutions` was a root attribute: 

https://www.npmjs.com/package/sendgrid-mailer

Might that be it?

(I'm struggling with substitutions in this version, too.)

**Comment by kmcurry** [comment]
@MaciejKrawczyk Have you tried using `setSubstitutionWrapper` and omitting the wrappers from the `substitutions`?

Ex:
`sgMail.setSubstitutionWrappers('-', '-');`
`"substitutions": {
     "firstName": "Maciejs"
}`

Not sure how you'd do multiple wrappers at once this way, but I was able to get subs working with this version by not specifying the wrappers in the substitution attribute. My subs look like 
`emailOptions.substitutions = {}`
`emailOptions.substitutions.CLIENT_NAME = myClientName`

**Comment by MaciejKrawczyk** [comment]
It works. Thank you!

**Comment by thinkingserious** [comment]
Thanks for jumping in to help @kmcurry!

I'm glad you are up and running @MaciejKrawczyk!

**Comment by LASkuma** [comment]
This should be definitely put in the README! Cost me 2hrs to figure this out!

**Comment by thinkingserious** [comment]
@LASkuma,

That's no good :(

Does [this documentation](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#transactional-templates) help? If so, could you point me where you first looked for help so I can make sure we have a clear link there?

Thanks!

With Best Regards,

Elmer

**Comment by LASkuma** [comment]
@thinkingserious Yes. This doc did help a lot. However, since I came from the official website, where the substitution keys should include the wrapper, I didn't pay too much attention to the use cases.

**Comment by thinkingserious** [comment]
Hi @LASkuma,

When you say you came from the official website, could you please let me know what URL you are referring to? Thanks!

**Comment by LASkuma** [comment]
Hi @thinkingserious,
I was referring to [this page](https://sendgrid.com/docs/API_Reference/api_v3.html). Even the try it out section have substitution keys with the wrappers included. After reading the documentation, I thought the Node library was naturally consistent with the documentation.

**Comment by thinkingserious** [comment]
Thanks @LASkuma!

That's really helpful feedback. 

I'm not quite sure on the solution though. Those documents are for those who wish to interact with our API directly vs. use one of our helper libraries. 

Earlier you mentioned that we should include this documentation in the README. Do you mean [here](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail#quick-start-hello-email)? Should we specifically call out the substitution use case there?

Thanks again for your help!

With Best Regards,

Elmer

**Comment by MaciejKrawczyk** [comment]
This should definitely be on the readme. I tried everything, I read all docs on the SendGrid api reference , everything that's on GitHub (I thought), contacted support and I would be making my own api wrapper if not for @kmcurry I think it would be much more easier and less confusing if the helper library would work exactly like the API itself (see my code at the beginning of the thread).

**Comment by thinkingserious** [comment]
Thanks @MaciejKrawczyk,

This is very good feedback and I've added this to our team's backlog for a deeper dive. We will provide updates on this thread.

Thanks!

With Best Regards,

Elmer

**Comment by sriharrsha** [comment]
Is this done?

**Comment by thinkingserious** [comment]
Hi @sriharrsha,

Have you tried @kmcurry's suggestion?

**Comment by harrshasri** [comment]
Not yet. I will update if it works or not soon.
Sorry for the late reply.

**Comment by tkafka** [comment]
To everyone as desperate as me yesterday: in v3 API you need to use `dynamic_template_data`  instead of `substitutions`, this isn't yet documented anywhere!

Then use `{{var_name}}` in email template and `dynamic_template_data: { var_name: "var_value" }` in API call.

**Comment by thinkingserious** [comment]
Hello Everyone,

Please see [this issue](https://github.com/sendgrid/sendgrid-nodejs/issues/703) for progress. We are currently working on the update for C#, then Java, then this SDK is right after that. Thanks for your patience and my apologies for the delay.

With Best Regards,

Elmer

**Comment by xduseko** [comment]
Hah, `dynamic_template_data`. I solved your little puzzle! :smile:

**Comment by kvarela** [comment]
Thank you @xduseko !
