### ISSUE TITLE
Can't add headers til mail

### ISSUE THREAD

**Issue by Cuias** [sendgrid/sendgrid-nodejs#641]
#### Issue Summary
It appears that headers are added to the body of the request, instead of as headerse to the actual request, which means you can't add X-SMTPAPI headers.

#### Steps to Reproduce
When sending a mail, I'm calling the following: 

```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(config.sendGridApiKey);
const msg = {
    to: email,
    from: 'email address removed',
    subject: title,
    html: body,
    headers: {
        'X-SMTPAPI': '{"category":["' + title.replace(/[^\x00-\x7F]/g, '') + '"]}'
    }
};
sgMail.send(msg);
```

But in client.js, createRequest seems to just take the entire request object, and handle it as if everything should be part of the body. createHeaders(data) doesn't do anything but add the API key.

I might be completely wrong, I just can't seem to find any way in the code, to inject headers. I can also confirm that SendGrid doesn't recognise the header, when sent in the body.

#### Technical details:

* sendgrid-nodejs Version: 6.1.4
* Node.js Version: 8.9.2

**Comment by thinkingserious** [comment]
Hello @Cuias,

With v3 of the Web API, you don't need to use the X-SMTPAPI header. [Here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#specifying-categories) is how you would add a category.

I hope that helps.

With Best Regards,

Elmer

**Comment by Cuias** [comment]
Wow, you're right! I hadn't noticed that at all, but I just tested it, and it works, which is even better than adding headers.

Thanks!

**Comment by thinkingserious** [comment]
Thanks for following up @Cuias!
