### ISSUE TITLE
Add support for SOCKS5 Proxy for request

### ISSUE THREAD

**Issue by Xeoncross** [sendgrid/sendgrid-nodejs#642]
#### Issue Summary

Some ISP's block certain types of traffic or locations (like sendgrid.com) and it would be helpful if there was an option to use a SOCKS5 proxy (easy to setup with `ssh -D` or an app) to create a tunnel outside of the ISP.

#### Technical details:

Sendgrid uses `request` for making HTTP requests and there are several libraries which provide SOCKS5 support:

- https://github.com/mattcg/socks5-http-client
- https://github.com/mattcg/socks5-https-client

To use with Request, just pass a reference to the Agent constructor.

```
var Agent = require('socks5-http-client/lib/Agent');

request({
	url: '....',
	agentClass: Agent,
	agentOptions: {
		socksHost: 'localhost,
		socksPort: 5555
	}
}, function(err, res) {
	console.log(err || res.body);
});
```

### Notes

The overhead of another library probably isn't worth including this by default in every install. Instead, it would be handy if the `request` library object could be replaced with a customized request object _if needed_.

**Comment by thinkingserious** [comment]
Great idea @Xeoncross! This has been added to our backlog.

**Comment by aslafy-z** [comment]
Does this targets the client package ? If it does, it's already possible: 

```
const client = require('@sendgrid/client');
const Agent = require('socks5-http-client/lib/Agent');

client.setDefaultRequest('agentClass', Agent)
client.setDefaultRequest('agentOptions', {
	socksHost: 'localhost,
	socksPort: 5555,
});
```

Maybe we could refactor setDefaultRequest to accept objects and merge it to defaultRequest. Anyway I'd love to help you with this.

WDYT ?

**Comment by aslafy-z** [comment]
Sure, it wont break anything.
