### ISSUE TITLE
SendGrid failing due to "Unhandled promise rejection"

### ISSUE THREAD

**Issue by tylerclark** [sendgrid/sendgrid-nodejs#646]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.
```
(node:4862) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
(node:4862) UnhandledPromiseRejectionWarning: Error: Unauthorized
    at Request.http [as _callback] (node_modules/@sendgrid/client/src/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:4862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4862) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Steps to Reproduce
This seems to occur when you have the latest version of both mongoose and sendgrid-node

#### Technical details:

* sendgrid 6.1.4
* node.js v9.3.0
* mongoose 4.13.8
* mongodb v3.6.1

**Comment by tylerclark** [comment]
I figured out the cause of this issue. I guess "reading between the lines" you can see the `Error: Unauthorized`. For whatever reason, the `process.env.SENDGRID_API_KEY` line does not work for me. When I put the actual key in that line `sgMail.setApiKey(_MYKEY_);` it started working.

Sorry for the false alarm.

**Comment by Astrydax** [comment]
I'm having this same issue, and I need to be able to store my keys in environment variables for security.

Hard coding API keys directly into the code source as a work around isn't really a solution.

**Comment by aroach** [comment]
@Astrydax can you share how you're setting your environment variables?
