### ISSUE TITLE
Web application send email

### ISSUE THREAD

**Issue by Dshinji137** [sendgrid/sendgrid-nodejs#647]
#### Issue Summary

Hello,

I am now trying to use sendgrid to send emails in my web application, it is something like:
when users click a button, they will receive an email, whose template is already written in sendgrid. I used the way as "use-cases" describes, but cannot receive the expected email, the error message is as follow:

Failed to load https://api.sendgrid.com/v3/mail/send: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://sendgrid.api-docs.io' that is not equal to the supplied origin. Origin 'http://localhost:3000' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

It seems that the server side detected the request origin (http://localhost:3000) and regards it as an invalid one, so the emails cannot be sent. I also set the appropriate JSON content in Postman, and it does works. By reading other related issues, it seems that the "Access-Control-Allow-Origin" header cannot be changed to "*" because of some security reasons, can you provide me a way to realize this function?

**Comment by thinkingserious** [comment]
Hello @Dshinji137,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by brachi-wernick** [comment]
@Dshinji137 I'm facing the same issue,  how did you solve this

**Comment by thinkingserious** [comment]
HI @brachi-wernick,

[Here is a description](https://sendgrid.com/docs/Classroom/Basics/API/cors.html) of the issue.

You'll want to do all your email sending in your backend code. You can send a signal from the frontend to the backend to trigger the email, but have the backend do the actual sending.

I hope that helps!

With Best Regards,

Elmer
