### ISSUE TITLE
How to specify which IP address the email should be sent with

### ISSUE THREAD

**Issue by nwkeeley** [sendgrid/sendgrid-nodejs#653]
#### Issue Summary

On our account we will have two IP addresses. One that our marketing emails will be sent on and another IP that will be responsible for our core email functionality (forgot password, welcome email etc.) 

Using the API how do I specify which IP address the email should be sent with. I do not see anything in the documentation for setting this.

#### Technical details:

* sendgrid-nodejs Version: 4.10.0
* Node.js Version: 8.5.0

**Comment by thinkingserious** [comment]
Hello @nwkeeley,

[Here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/USAGE.md#ips) is the documentation for IP management using this SDK. The more general documentation can be found [here](https://sendgrid.com/docs/API_Reference/api_v3.html).

For further assistance with your use case, I suggest you reach out to our [support team](https://support.sendgrid.com). 

Thanks!

With Best Regards,

Elmer
