### ISSUE TITLE
How to attach PDF from URL to Email by using @sendgrid/mail ?

### ISSUE THREAD

**Issue by ShahrokhNiakan** [sendgrid/sendgrid-nodejs#654]
#### Issue Summary
I want to attach url to Email I used some solutions such as getting pdf url by request or read it as file but it didn't work.

#### Technical details:

* sendgrid-nodejs Version: @sendgrid/mail: ^6.2.1
* Node.js Version: 9.2.1

**Comment by thinkingserious** [comment]
Hi @ShahrokhNiakan,

Have you tried the example [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#attachments)? If so, could you please share the code so that we may try to reproduce?

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @ShahrokhNiakan,

Thanks for sharing your solution. 

How about grabbing the file from the url [like so](https://stackoverflow.com/questions/38284765/get-file-from-external-url-with-fs-readfile)?

With Best Regards,

Elmer

**Comment by ShahrokhNiakan** [comment]
@thinkingserious I tested it but PDF file sometimes is not Ok and not be readable

```
request = require('request');

request.get( url, function(err, res) {
 var base64File = new Buffer(res.body).toString('base64');
});

```
Thank You

**Comment by thinkingserious** [comment]
Hi @ShahrokhNiakan,

Are you testing with the same PDF or different ones? 

In the cases where the PDF is not readable, is it possible to verify the source PDF is not corrupted?

**Comment by ShahrokhNiakan** [comment]
Hi dear @thinkingserious 

I tested these PDF link in below :

http://www.africau.edu/images/default/sample.pdf
http://www.pdf995.com/samples/pdf.pdf
https://www.ets.org/Media/Tests/GRE/pdf/gre_research_validity_data.pdf

**Comment by thinkingserious** [comment]
Hi @ShahrokhNiakan,

Thank you. This now on my backlog for a review. 

One thing you may consider in the mean time is that perhaps you are running up against [size limitations](https://sendgrid.com/docs/Classroom/Build/Add_Content/attachments.html).

With Best Regards,

Elmer

**Comment by brafdlog** [comment]
@ShahrokhNiakan since the pdf is binary rather that a string, I think you should specify `encoding: null` in the options you pass to request so the request library won't try to decode it as a utf-8 string.
E.g:
```
request = require('request');

request.get( url, { encoding: null } function(err, res) {
 var base64File = new Buffer(res.body).toString('base64');
 ...
});
```

Quoting from the [README of request](https://github.com/request/request):

> encoding - encoding to be used on setEncoding of response data. If null, the body is returned as a Buffer. Anything else (including the default value of undefined) will be passed as the encoding parameter to toString() (meaning this is effectively utf8 by default). (Note: **if you expect binary data, you should set encoding: null.**)

**Comment by cesargamboa** [comment]
@brafdlog your solution worked for me! thanks!

**Comment by manusis** [comment]
The earlier SendGrid module had support for specifying URLs for attachments. That was very convenient. Why should every sender bother about sending bulky base64 content. Sendgrid should be able to do that.

**Comment by isongjosiah** [comment]
With the request package being depreciated, here is a solution that worked for me using Axios to get the base64 encoding of the file.
`const img = await axios.get(url, {responseType: 'arraybuffer'}).then((res => Buffer.from(res.data, 'binary').toString('base64')))`
