### ISSUE TITLE
404 when trying to install @sendgrid/client

### ISSUE THREAD

**Issue by murphman300** [sendgrid/sendgrid-nodejs#655]
#### Issue Summary

Been a while since i've touched based with the API client for Node. Just read up on it and noticed things changed recently for the NPM repo. 

Tried to update using the specified CLI command on your github and NPM pages: `npm install --save @sendgrid/client` which keeps returning 404 - not found. 

At a bit of a loss here, any insight on why this is happening would be much appreciated.

#### Steps to Reproduce

1. Open terminal in Node project folder
2. enter `npm install --save @sendgrid/client`

#### Technical details:

* sendgrid-nodejs Version: n/a
* Node.js Version:8.5.0
* NPM Version: 5.6.0

Log (redacted for privacy):

> 0 info it worked if it ends with ok
> 1 verbose cli [ '~/.nvm/versions/node/v8.5.0/bin/node',
> 1 verbose cli '~/.nvm/versions/node/v8.5.0/bin/npm',
> 1 verbose cli 'install',
> 1 verbose cli '--save',
> 1 verbose cli '@sengrid/client' ]
> 2 info using npm@5.3.0
> 3 info using node@v8.5.0
> 4 verbose npm-session e83d88197a9a1409
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 http fetch GET 404 https://registry.npmjs.org/@sengrid%2fclient 587ms
> 8 silly fetchPackageMetaData error for @sengrid/client@latest 404 NotFound:@sengrid/client@latest
> 9 verbose stack Error: 404 Not Found: @sengrid/client@latest
> 9 verbose stack at fetch.then.res(~/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
> 9 verbose stack at tryCatcher(~/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
> 9 verbose stack at Promise._settlePromiseFromHandler(~/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
> 9 verbose stack  at Promise._settlePromise(/Users/jean-louismurphy/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
> 9 verbose stack at Promise._settlePromise0(~/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
> 9 verbose stack at Promise._settlePromises(~/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
> 9 verbose stack at Async._drainQueue(~/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
> 9 verbose stack at Async._drainQueues(~/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
> 9 verbose stack at Immediate.Async.drainQueues(~/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
> 9 verbose stack at runCallback (timers.js:781:20)
> 9 verbose stack at tryOnImmediate (timers.js:743:5)
> 9 verbose stack  at processImmediate [as _immediateCallback] (timers.js:714:5)
> 10 verbose cwd ~/IdeaProjects/spotitbackendnode
> 11 verbose Darwin 16.7.0
> 12 verbose argv "~/.nvm/versions/node/v8.5.0/bin/node" "~/.nvm/versions/node/v8.5.0/bin/npm" "install" "--save" "@sengrid/client"
> 13 verbose node v8.5.0
> 14 verbose npm  v5.3.0
> 15 error code E404
> 16 error 404 Not Found: @sengrid/client@latest
> 17 verbose exit [ 1, true ]

**Comment by murphman300** [comment]
PS: strike-throughs on the log line are from Github, not the logfile

**Comment by thinkingserious** [comment]
Hello @murphman300,

I believe that [this](https://www.npmjs.com/package/@sendgrid/mail) might be the package you are looking for. [Here](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail) is the documentation.

I hope that helps!

With Best Regards,

Elmer

**Comment by murphman300** [comment]
Hello again, apologies for the late reply.

Yes your recommendation was the proper designation in the end. Many thanks!

**Comment by thinkingserious** [comment]
Awesome, thanks for confirming!
