### ISSUE TITLE
Sending Multiple different email to multiple recipient in one API call

### ISSUE THREAD

**Issue by jaybauson** [sendgrid/sendgrid-nodejs#656]
#### Issue Summary

Sending Multiple different email to multiple recipient in one API call. 
I tried to play with the personalization onject for this but it doesn't work, and can find any other information about it if it is even possible. It will be good to have this feature, in my case, I need to send a request for approval for several tools that being administered by different admins. If I will to loop it, the loading time will not be reasonable, specially in cases that I need to request for 20 approvals(20 mail send).

**Comment by thinkingserious** [comment]
Hello @jaybauson,

I think [this](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#multiple-emails-multiple-recipients) is the use case you need. Please let me know.

Thanks!

With Best Regards,

Elmer

**Comment by jaybauson** [comment]
Thanks for the response! Yes, this is exactly what I need. Thanks!

Regards,
Jay

**Comment by thinkingserious** [comment]
Awesome, thanks for the follow up!
