### ISSUE TITLE
Can't compile typescript when using sendgrid

### ISSUE THREAD

**Issue by nolazybits** [sendgrid/sendgrid-nodejs#657]
#### Issue Summary

Typescript compiler complains.

#### Steps to Reproduce
Typescript 2.6.1

`node_modules/@sendgrid/client/src/response.d.ts(1,9): error TS2305: Module ''request'' has no exported member 'RequestResponse'.`

#### Technical details:

* sendgrid-nodejs Version: 6.2.1
* Node.js Version: 6.12.3

**Comment by thinkingserious** [comment]
Hi @nolazybits,

Thanks for reporting this to us. I have added this to our backlog for further review.

With Best Regards,

Elmer

**Comment by Strum355** [comment]
Not able to reproduce with node 10.10.0 and typescript 3.0.3

**Comment by Strum355** [comment]
@thinkingserious i had pulled from master on the same day, if thats specific enough

**Comment by thinkingserious** [comment]
Thanks @Strum355!
