### ISSUE TITLE
How can we add url in anchor tag from node side

### ISSUE THREAD

**Issue by vijianrao** [sendgrid/sendgrid-nodejs#659]
Issue Summary:
In Transactional template code, i wrote code like below for anchor tag url: href="%url%"
and code in node side 
.....templateId: MY_TEMPLATE_ID,
                substitutions: {
                    name: data.first_name,
                    url: 'https://windowsapplication.herokuapp.com'',
                },

i am getting email but link is working, help me to resolve this error

**Comment by thinkingserious** [comment]
Hi @vijianrao,

Can you please try with [this example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#transactional-templates)? Thanks!

With Best Regards,

Elmer

**Comment by vijianrao** [comment]
Hi Elmar, 

Thanks for your response, 
I followed below link to resolve the issue with passing value for anchor tag,
https://sendgrid.com/docs/API_Reference/SMTP_API/substitution_tags.html

Code from node side:
 substitutions: {
                    name: data.user_name,
                    id: data.invoice_no,
                },
Sendgrid transactional template code:
<a  href="https://windowsapplication.herokuapp.com/api/checkout/-id-" 

Regards,

Viji
