### ISSUE TITLE
Substitutions not always applied when sending more than 1 mail to multiple recipients

### ISSUE THREAD

**Issue by matthiasgasser** [sendgrid/sendgrid-nodejs#660]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

I want to send the same mail to multiple recipients with custom substitutions (mostly the name) and I do see an erratic behavior. Most emails are being sent as expected but out of 5 emails at least one mail wasn't properly substituted.

I tried different means of batch sending the same message but every time I get the same non-consistent outcome. Without changing a single line of code having the very same "msg" object feed into sendgrid there is always at least one message without proper substitutions.

https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#customization-per-recipient

#### Steps to Reproduce

1. Setup a transactional template

i.e. like:

```
Hi {{name}}
blabla, blabla.
,{{owner_name}}
<%body%> 

```

2. Build a msg object like:

`{"from":"hello@world.com","templateId":"12345","personalizations":[{"to":"test@test.com","subject":"testsubject","substitutions":{"name":"Random Guy","owner_name":"Random Owner"}},{"to":"test2@test.com","subject":"subject2","substitutions":{"name":"Random Guy 2","owner_name":"Random Owner 2"}}]}  `

3. Now send it:

`        const sendgrid = require("@sendgrid/mail");
        sendgrid.setApiKey(sails.config.sendgrid.key);
        sendgrid.setSubstitutionWrappers('{{', '}}');
       sendgrid.send(msg);
`
4. Expected outcome: 2 emails with substitution applied
actual outcome 1 email substitution applied, 1 email just like the template with empty substitutions.

If you increase the number of recipients in the msg object, usually 1 or 2 are failing out of 5-10. Every run another mail is lacking the proper replacements.

I've read about this issue in the c# port of the library but didn't find a proper solution there.

#### Technical details:

 "@sendgrid/mail":  "version": "6.2.1",

node -v: v8.9.3

**Comment by thinkingserious** [comment]
Thanks for taking the time to report this @matthiasgasser,

I've added this to our backlog for further investigation.

With Best Regards,

Elmer

**Comment by remigallego** [comment]
I'd like to claim this issue. 
I tried to replicate the bug with your exact Node version and settings, but everything works fine for me on Debian and on Windows. Could you attach this code to your send function and paste the response here? 

```javascript
sgMail.send(msg).then((res) =>  console.log(res))});
```

**Comment by thinkingserious** [comment]
Thanks for taking the time to help out @remigallego!
