### ISSUE TITLE
@sendgrid/client dependency causes security risk

### ISSUE THREAD

**Issue by havanbaoit** [sendgrid/sendgrid-nodejs#661]
The bellow dependency chain introduces a security risk:

`@sendgrid/client@6.2.1 > request@2.83.0 > hawk@6.0.2 > hoek@4.2.0`

Detail: [https://nodesecurity.io/advisories/566](https://nodesecurity.io/advisories/566)

**Comment by thinkingserious** [comment]
Hi @havanbaoit,

Thanks for reporting this! We have added this to our backlog for a fix.

With Best Regards,

Elmer
