### ISSUE TITLE
Repair potential security vulnerability - moment package

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#662]
#### Issue Summary

Known moderate severity security vulnerability detected in moment < 2.19.3 defined in package-lock.json.
--
update suggested: moment ~> 2.19.3.

**Comment by ctrimm** [comment]
@thinkingserious - I added `moment` as a `devDependencies` via `npm install moment --save-dev` to add it to `package.json`. Then I ran `npm install`. You can verify the `moment` package was installed by looking at the package-lock.json file.

After adding the `moment` package, I received a couple of warnings about the versions of `chai-as-promised` and `dirty-chai` not  - I went ahead and updated those versions as well.

I ran the test suites and they lined up with the previous coverage. I then verified there wasn't any breaking changes via the [moment changelog](https://github.com/moment/moment/blob/develop/CHANGELOG.md).

Let me know if this is what you were looking for.
