### ISSUE TITLE
Using older nodejs version is not possible with the latest SendGrid module

### ISSUE THREAD

**Issue by vgenev** [sendgrid/sendgrid-nodejs#667]
#### Issue Summary

In our project environment we are stuck with node 6.12.x (I know it sucks). We used @sendgrid/client & @sendgrid/mail v6.1.4. When tried to deploy the project on new machine the version 6.1.4 got dependency "@sendgrid/helpers": "^6.1.3", which installs current version 6.2.1 of the helpers and that leads to app to crash, because in the helpers async/await functions are used. 

#### Steps to Reproduce

1. Install sendgrid via npm v3 using ``npm i @sendgrid-client@6.1.4`` 
2. the version of helpers installed is   "@sendgrid/helpers@6.2.1"

I will create a a pull request for that issue.

#### Technical details:

* sendgrid-nodejs Version: 6.1.4
* Node.js Version: 6.12.0

**Comment by thinkingserious** [comment]
Hi @vgenev,

Thanks for the heads up and offering the PR :)

With Best Regards,

Elmer

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-nodejs/commit/034441e2795c5aed68996270de796cd365292aed
