### ISSUE TITLE
Updates for the new Email Activity API (beta)

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#669]
SendGrid has added an API to download information from the Email Activity feed. There are four new endpoints:
* [GET /messages](https://sendgrid.api-docs.io/v3.0/email-activity/filter-all-messages)
* [GET /messages/{msg_id}](https://sendgrid.api-docs.io/v3.0/email-activity/filter-messages-by-message-id)
* [POST /messages/download/](https://sendgrid.api-docs.io/v3.0/email-activity/request-csv)
* [GET /messages/download/{download_uuid}](https://sendgrid.api-docs.io/v3.0/email-activity/download-csv)

A getting started doc for the API is [here](https://sendgrid.com/docs/API_Reference/Web_API_v3/Tutorials/getting_started_email_activity_api.html).

The following items need to be updated in this repo:
* [USAGE.md](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md)
* [/examples](https://github.com/sendgrid/sendgrid-python/tree/master/examples) (create a `messages` folder with a file `messages.py`)
* [Tests](https://github.com/sendgrid/sendgrid-python/blob/master/test/test_sendgrid.py)
* [USE_CASES.md](https://github.com/sendgrid/sendgrid-python/blob/master/USE_CASES.md)

**Comment by Davy-F** [comment]
So is it my understanding that the /messages API does not currently work in @sendgrid/client and I have to do a HTTP request?

**Comment by thinkingserious** [comment]
Hello @Davy-F,

Yes, the `/messages` API endpoint works, but it's not documented in this repo.
