### ISSUE TITLE
Ical events don't show as cards in an recipients email box

### ISSUE THREAD

**Issue by sadzebra** [sendgrid/sendgrid-nodejs#671]
#### Issue Summary

I'm trying to send out calendar events to users using the iCalender standard. I want their inbox to automatically detect the event and display it to the user like the image below.

![image](https://user-images.githubusercontent.com/16684206/37910710-160a1496-3106-11e8-8ba6-9bad5b361399.png)

My isc data is

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:adamgibbons/ics
BEGIN:VEVENT
UID:a8b44b40-30fc-11e8-9cdf-ab421c95fe5f
SUMMARY:Test Event
DTSTAMP:20180326T125000Z
DTSTART:20180529
DTEND:20180530
DESCRIPTION:This is a test event
LOCATION:Somewhere in a building...
STATUS:CONFIRMED
ORGANIZER;CN=Admin:mailto:test@test.com
ATTENDEE;RSVP=TRUE;CN=test@test.com:mailto:test@test.com
END:VEVENT
END:VCALENDAR
```

I'm using the node package 'ics' to make the ics data and the following code to send the email.

```
var encodedEvent = Base64.encode(event)
    var msg = {
        to: to,
        from: from,
        subject: 'Registration an Event',
        text: 'Thanks for registering for an event.',
        html: '<strong>Thanks for registering for an event.</strong>',
        attachments: [{
            content: encodedEvent,
            filename: 'invite.ics',
            type: 'text/calendar',
            disposition: 'attachment',
            contentId: 'mytext'
        }],
        headers: {
            method: "REQUEST"
        }
    }
    sgMail.setApiKey(apiKey)
    sgMail.send(msg)
        .then( (data) => { console.log("data", data) })
        .catch( (err) => { console.log("Error:", err) })
```

Now SendGrid is sending the email and the email has the attachment "invite.ics" but inboxes don't seem to detect it. From my research it might be a problem with headers but i'm not sure, i've tried a few things so far and nothing. 

Any ideas?

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 6.10.2

**Comment by thinkingserious** [comment]
Hello @sadzebra,

Please follow this thread for updates on this issue: https://github.com/sendgrid/sendgrid-php/issues/250

Can you please take a moment to comment on that issue to help increase its priority? Thanks!

With Best Regards,

Elmer

**Comment by eshanholtz** [comment]
Closing as this was marked as a non-library issue.
