### ISSUE TITLE
Update Documentation so That Using Substitutions is Easier

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#681]
#### Issue Summary

Please see the [thread here](https://github.com/sendgrid/sendgrid-nodejs/issues/680#issuecomment-383717535).

**Comment by tkafka** [comment]
To everyone as desperate as me yesterday: in v3 API you need to use `dynamic_template_data`  instead of `substitutions`, this isn't yet documented anywhere!

Then use `{{var_name}}` in email template and `dynamic_template_data: { var_name: "var_value" }` in API call.

**Comment by thinkingserious** [comment]
Thanks for sharing your solution @tkafka!

Please follow [this thread](https://github.com/sendgrid/sendgrid-nodejs/issues/703) for progress.

With Best Regards,

Elmer
