### ISSUE TITLE
Allow method chaining in @sendgrid/mail

### ISSUE THREAD

**Issue by reichert621** [sendgrid/sendgrid-nodejs#682]
#### Issue Summary

Very minor, but it would be nice to allow method chaining in the `MailService` of `@sendgrid/mail` so that setting the API key could be handled on one line:

```js
const mailer = require('@sendgrid/mail').setApiKey(process.env.SENDGRID_API_KEY);

// vs

const mailer = require('@sendgrid/mail');

mailer.setApiKey(process.env.SENDGRID_API_KEY);
```

This is all it would require as far as I can tell:
```js
class MailService {
  // ...

  setClient(client) {
    this.client = client;

    return this; // TODO (optional, but good for consistency)
  }

  setApiKey(apiKey) {
    this.client.setApiKey(apiKey);

    return this; // TODO
  }

  setSubstitutionWrappers(left, right) {
    // ...

    return this; // TODO (optional, but good for consistency)
  }

  // ...
}
```

(It looks like this pattern is used here in `@sendgrid/client` https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/src/classes/client.js#L53-L67 as well.)

#### Steps to Reproduce

1. Install `@sendgrid/mail`
2. Set the API key

#### Technical details:

* sendgrid-nodejs version ^6.2.1

**Comment by thinkingserious** [comment]
Thanks for the suggestion @reichert621!

I've added this to our backlog for consideration.

Please feel free to submit a PR as well :)

**Comment by thinkingserious** [comment]
Thank you @AllUsernamesHaveBeenTaken! It's all yours.
