### ISSUE TITLE
sandbox mode can't be enabled

### ISSUE THREAD

**Issue by jasan-s** [sendgrid/sendgrid-nodejs#683]
#### Issue Summary
`sandbox_mode` will not turn on , email is always sent. 

#### Steps to Reproduce
- add ```mail_settings: { sandbox_mode: { enable: false } }```
- try sending email like so:
```
import sgMail from '@sendgrid/mail'
    const msg = {
      to: rest.sendTo || '',
      from: rest.from || SENDER_EMAIL,
      replyTo: rest.replyTo || REPLY_TO_EMAIL,
      subject: rest.subject || '',
      bcc: rest.bcc || '',
      cc: rest.cc || '',
      mail_settings: { sandbox_mode: { enable: true } },
    }
sgMail.send(msg)
```
I expect when the `enable` flag is set to `false`, email should not be sent out. 

#### Technical details:

* sendgrid-nodejs Version: 6.2.1
* Node.js Version: 9.11.1

**Comment by jamespedid** [comment]
I too am having difficulty with this. I tried using both the camelcase and the snake case variant but neither work.

**Comment by thinkingserious** [comment]
Hello @jamespedid,

Using the latest version of this SDK, the following seems to work:

```node
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'ethomas@twilio.com',
  from: 'dx@sendgrid.com',
  subject: 'Hello world',
  text: 'Hello plain world!',
  html: 'Hello HTML world!',
  mail_settings: {
    sandbox_mode: {
      enable: true,
    },
  },
};
sgMail.send(msg);
```
