### ISSUE TITLE
sendgrid content function not working new SendGrid\Content("text/plain", "hello")

### ISSUE THREAD

**Issue by latestdaikicoin** [sendgrid/sendgrid-nodejs#684]
#### Issue Summary

We use sendgrid api for sending email . we use below code

$from = new SendGrid\Email("", $mail_from);
    
    $to = new SendGrid\Email("", $to);
    
     
   
    $content = new SendGrid\Content("text/plain", $msg);
    
    
    $mail = new SendGrid\Mail($from, $subject, $to, $content);

in this code  $content = new SendGrid\Content("text/plain", $msg);

showing error :can not connect to server.

new SendGrid\Content("text/plain", "hello"); is not working

**Comment by thinkingserious** [comment]
Hello @latestdaikicoin,

It sounds like you are having a connectivity issue. To rule that out, can you try making the API call through our [interactive docs](https://sendgrid.com/docs/API_Reference/api_v3.html)?

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @ktkaushik,

I believe your issue is different @ktkaushik. Please see [this thread](https://github.com/nodejs/node/issues/5436) for details.

With Best Regards,

Elmer

**Comment by adammenges** [comment]
Any updates here? I just started seeing the same as @ktkaushik this morning for no apparent reason. Also status.sendgrid.com shows the following message in Chrome and Safari:

<img width="2560" alt="screenshot 2018-08-10 13 40 48" src="https://user-images.githubusercontent.com/817438/43980868-920c8010-9ca4-11e8-8f1b-a3ce37869780.png">
