### ISSUE TITLE
New sendgrid nodejs module throws error in AWS Lambda, Sendgrid module v^5.2.3 does not.

### ISSUE THREAD

**Issue by tetreault** [sendgrid/sendgrid-nodejs#685]
#### Issue Summary

Using the new sendgrid module (as opposed to sendgrid module `^5.2.3`) throws an error in AWS. The module itself throws an error, coming from src/mail.js (FYI - no further text given, Cloudwatch just logs out an error occurred originating from this file). 

#### Steps to Reproduce

1. Make a directory, install `@sendgrid/mail`
2. create a file called index.js
3. add this code (change the dummy emails of course): 

```
'use strict';

console.log('Loading function');
const AWS = require('aws-sdk');
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey('XXX');

exports.handler = (event, context, callback) => {
  const msg = {
    to: ['recipient1@example.org', 'recipient2@example.org'],
    from: 'sender@example.org',
    subject: 'Hello world',
    text: 'Hello plain world!',
    html: '<p>Hello HTML world!</p>',
  };
  sgMail.send(msg);
  callback(null, 'email sent from aws lambda');
};
```
4. compress the index.js file, packag.json files, and the node modules folder
5. upload the ZIP to AWS Lambda (my lambda script runtime is Node 4.3)
6. test it and check the cloudwatch logs

Was able to consistently reproduce this with `@sendgrid/mail`. Sendgrid module  `^5.2.3` works perfectly without error, and that is what I am using for now. 

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* AWS Lambda Runtime: Node.js Version: 4.3

**Comment by thinkingserious** [comment]
Hello @tetreault,

Thanks for taking the time to report this!

Have you tried [manually logging the errors](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#success-failure-errors)?

With Best Regards,

Elmer

**Comment by tetreault** [comment]
thanks for the reply @thinkingserious - when i have the time this weekend i'll try to add that in and report back! the error appears to get thrown before actually _doing_ anything with sendgrid, as if the error is thrown around require/setApiKey.
