### ISSUE TITLE
Unable to debug error

### ISSUE THREAD

**Issue by heymartinadams** [sendgrid/sendgrid-nodejs#695]
#### Issue Summary

SendGrid sends me a nondescript error message `SendGridError: Response error` at `/node_modules/sendgrid/lib/sendgrid.js:104:23`

Unfortunately, absent a more specific error message, I can’t seem to debug this issue.

```javascript
  const html = '<div>some html</div>'
  let helper = require('sendgrid').mail
  const fromEmail = new helper.Email(email, company)
  const subject = 'A subject line'
  const toEmail = new helper.Email(email, name)
  const content = new helper.Content('text/html', html)
  let mail = new helper.Mail(fromEmail, subject, toEmail, content)
  mail.setTemplateId('__TEMPLATE_ID__')
  
  let sg = require('sendgrid')(process.env.SENDGRID_API_KEY)
  let request = sg.emptyRequest({
    method: "POST",
    path: "/v3/mail/send",
    body: mail.toJSON()
  })
  
  sg.API(request)
      .then(res => console.log(res))
      .catch(err => console.log(err))
```

node: `v8.7.0`
sendgrid: `^5.2.3`

**Comment by thinkingserious** [comment]
Hello @heymartinadams,

You should be able to capture the error in the response body. But, I suggest you update to the [newest SDK](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail) which is a radical improvement.

With Best Regards,

Elmer
