### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ORESoftware** [sendgrid/sendgrid-nodejs#698]
npm install sendgrid

?

is it in the docs? should be one of the first things in README?

**Comment by ORESoftware** [comment]
a link to this in the readme might help?
https://www.npmjs.com/package/@sendgrid/client

I guess the client sdk is the most frequently used

**Comment by thinkingserious** [comment]
Hello @ORESoftware,

Please see [this section](https://github.com/sendgrid/sendgrid-nodejs#introduction---please-read-first) to be routed to the appropriate repo.

Thanks!

With Best Regards,

Elmer
