### ISSUE TITLE
how to send embedded image in nodejs using sendgrid

### ISSUE THREAD

**Issue by Muthuprasanth** [sendgrid/sendgrid-nodejs#701]
I want to send the company logo as embedded image in the mail content. I use the following code to send embedded image. 
attachments: 
        [{
          filename: "logo.png",     
          path: "/images",     
          cid:  "myimagecid",
         disposition:"inline",
        }],
I use the cid in img src tag as
src='cid:myimagecid'

But I get the following error.
**TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:222:9)
    at new Buffer (buffer.js:170:17)**
 I used various options but the issue is not resolved.
Please help me to resolve it.

**Comment by thinkingserious** [comment]
Hello @Muthuprasanth,

It looks like you are missing the content. Please see [this example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#attachments).

Thanks!

With Best Regards,

Elmer

**Comment by Muthuprasanth** [comment]
Thanks for you reply.
I updated the code.
I want to send an **email with embedded image** from node js using sendgrid. I use the following code

var base64Img = require('base64-img');
const sgMail = require('@sendgrid/mail');
var base64str = base64_encode("logo.png");

function base64_encode(file) {
  var bitmap = fs.readFileSync(file);
  return new Buffer(bitmap).toString("base64");
}
sendMail(["example1@gmail.com"],base64str);
function sendMail(emails,data)
{
sendgrid.send({
      to: emails[0],
      from: 'example2@gmail.com',
      subject: 'Test Mail',
      attachments: [
       {
        filename: "logo.png",
        type : "image/png",
        content: data,
        content_id: "myimagecid",
        disposition : "inline"
       }
     ],
       html: I gave the src attribute of img tag as src='content_id:myimagecid' alt='no image',

  }, function (err) {
    if (err) {
      response.json({ message: 'Selected but Mail not sended and Error is'+err });
      console.log("Mail error",err);

    } else {
      console.log("Success Mail sended ");
      response.json({ message: 'Selected and Mail sended' });
    }
  });

}
Here I used **disposition : "inline"** but still the image send as an attachment. In the img tag area of email I got "no image" Can you help me please?

**Comment by thinkingserious** [comment]
Hello @Muthuprasanth,

Can you try: `<img src="cid:myimagecid"/>`?

Thanks!

With Best Regards,

Elmer

**Comment by yeahsmaggy** [comment]
This was super helpful to help me understand although on my remote server I needed to use path to resovle the file

```
        const file = fs.readFileSync(path.resolve(__dirname, "./build/" + req.body.badge_image));
        const imageDate =  Buffer.from(file).toString("base64");
```

**Comment by gnaneshdev** [comment]
Hi,

I'm facing exactly same issue faced by @Muthuprasanth. Though disposition is inline, image is being appeared as attachment instead of getting embedded in html body.  I'm using sendgrid service 'attachments' to send emails (https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html).
Could someone help on this issue.

Thanks in Advance!

Regards,
Gnanesh

**Comment by ssankabathula** [comment]
i am similar issue, in the email i dont get the image, any help is appreciated

 			//Send Email
                    function base64_encode(file) {
                        var bitmap = fs.readFileSync(file);
                        return new Buffer(bitmap).toString('base64');
                    }

                    let data_base64 = base64_encode(imageFile);

                    const msg = {
                        to: emailList,
                        from: '',
                        subject: '',
                        html:'<strong>Some Text</strong><img src="cid:Logo" alt="image" />',
                        files: [
                            {
                                filename: image,
                                type: 'image/png',
                                cid:'Logo',
                                content: data_base64,
                                disposition: 'inline'
                            },
                        ],
                    };

                    sgMail.send(msg, function (err, json) {
                        if (err) {
                            return console.error(err);
                        } 
                    });

**Comment by childish-sambino** [comment]
@ssankabathula Just tested locally and not seeing any issues. In you example, change `cid` to `content_id` and `files` to `attachments`:
```
attachments: [
    {
        filename: 'image',
        type: 'image/png',
        content_id: 'Logo',
        content: data_base64,
        disposition: 'inline'
    },
],
```

**Comment by ssankabathula** [comment]
@childish-sambino its worked. Thanks.

**Comment by Abokorhassan** [comment]
@thinkingserious, guess, I'm having the same issue @Muthuprasanth was having 2 years ago...
`


          const msg = {

                to: "abokorhassan@gmail.com",
                from: process.env.EMAIL_FROM,
                subject: 'Login: Password',
                html: '<strong>Some Text</strong><img src="content_id:logo" alt="image" />',

                attachments: [{
                    filename: 'logo2',
                    type: 'image/png',
                    content_id: 'logo',
                    content: fs.readFileSync('./src/img/logo2.png', { encoding: 'base64' }),
                    disposition: 'inline',
                }],

            };
            send_email(msg);`

The image is not apearing as a html, instead it appears as an attachment

**Comment by childish-sambino** [comment]
@Abokorhassan Change the `img src` to `cid`: `<img src="cid:logo" alt="image" />`

**Comment by efah** [comment]
Can base64 render image properly in Gmail? I've tried attachment with cid and `<img src="data:image/png;base64,SomeBase64Code" />`, none of them work in Gmail. Html source code has base64, but doesn't show in email.
