### ISSUE TITLE
Add Dynamic Template Support

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#703]
#### Issue Summary

On 7/24/2018, our team publicly launched dynamic content for transactional templates. It is now available for all customers sending over v3 of our Mail Send API. Iterate over lists, handle conditionals and more, thanks to native support for a subset of Handlebars syntax!

More information can be found in our [blog post announcement](https://sendgrid.com/blog/how-to-use-sendgrids-dynamic-templates-for-your-transactional-emails/).

You can currently use this feature by manually creating the request body as [shown here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/USAGE.md#v3-mail-send). 

Now, we need to create helper code ([this is complete](https://github.com/sendgrid/sendgrid-nodejs/pull/691#issuecomment-407490342)) and examples for this SDK.

#### Acceptance Criteria

* [[COMPLETE](https://github.com/sendgrid/sendgrid-nodejs/pull/691#issuecomment-407490342)] [Implement a helper similar to what we have for the legacy templates](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#transactional-templates)
* Update the [USE_CASES.md](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#transactional-templates) example to demonstrate the new *Dynamic Templates* using the helper and re-name the current example to *Legacy*

#### Documentation
- [How to Send an Email With Dynamic Transactional Templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html)
- [Using Handlebars](https://sendgrid.com/docs/User_Guide/Transactional_Templates/Using_handlebars.html)
- [Interactive API Docs](https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send)

**Comment by jharris-code** [comment]
Please update your documentation- I just spent an hour trying to figure out why substitutions were not working with the v3 API.

**Comment by thinkingserious** [comment]
My apologies for the poor experience @jharris-code.

I've added your vote to this issue to help it gain priority. I think it will be updated soon because we sone have PR #711.

**Comment by catamphetamine** [comment]
It is very silly that the absense of documentation blocks releasing the actual code.

**Comment by thinkingserious** [comment]
Hi @catamphetamine,

The code was released in [v6.3.1](https://github.com/sendgrid/sendgrid-nodejs/releases). I hope that helps, thanks!

With Best Regards,

Elmer

**Comment by catamphetamine** [comment]
@thinkingserious Oh, cool, actually it didn't cross my mind to update the version of the library.
I'll try that out, thx.

**Comment by catamphetamine** [comment]
Note to users: when using templates pass `dynamic_template_data` instead of `substitutions`.

**Comment by Beethoven** [comment]
Now you have to change "substitutions:" to "dynamic_template_data:"

And the templates uses handlebars no more need to specify "substitutionWrappers"

**Comment by josh-yonomi** [comment]
[This](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#transactional-templates) example in your use cases still uses substitutions rather than dynamic_template_data. Plz update, it definitely took me a couple hours of playing with the SDK and searching before I found this thread. (Also your [api docs](https://sendgrid.com/docs/API_Reference/api_v3.html) don't mention anything about this, which didn't help either.

**Comment by thinkingserious** [comment]
My apologies @josh-yonomi,

I've updated the documentation based on your feedback. 

For our new templates, they use handlebars syntax. The legacy templates still work as before.

With Best Regards,

Elmer

**Comment by drav96** [comment]
I receive the email but the substitutions does not work. What can cause the problem?

    const msg = {
        to: email,
        from: sendGridMail,
        templateId: emailTemplate.confirmationEmail,
        dynamic_template_data: {
          firstName: firstName,
          lastName: lastName,
          link: link
        }
      };

**Comment by larafale** [comment]
fuck you sendgrid, your doc is shit af. I'm pissed

**Comment by thinkingserious** [comment]
@drav96,

Do you mind sharing what your template looks like?

With Best Regards,

Elmer

**Comment by larafale** [comment]
why do you strip special chars in substitutionWrappers ??
```
dynamic_template_data: {
      foo-bar: 'wtf',
      bar_baz: 'wtf',
      'baz.bro': 'wtf',
      foo: 'wtf'
    }
```
only `{{foo}}` return `wtf` string in emails.

**Comment by thinkingserious** [comment]
I'm not sure @larafale, but that certainly does not seem reasonable. Looking at the source code for this SDK, I don't see where those keys are getting modified. 

Do you mind creating a separate issue for this issue and include what your HTML template looks like? I'll mark the new issue as a bug and try to reproduce and fix if necessary.

**Comment by gianfelipe93** [comment]
@drav96 thanks mate, it's working now

**Comment by kael-shipman** [comment]
Adding what I hope will be some **definitive documentation** after wasting another hour of my time on this. (First, thanks to everyone who wasted hours of their time before me.)

1. If your template id starts with `d-`, then `substitutions` won't work, and you should use CAMEL-CASE `dynamicTemplateData` (see [here](https://github.com/sendgrid/sendgrid-nodejs/blob/0c83ae9a7151f466383df35a897a3426c5cdb06b/packages/helpers/classes/mail.js#L60), where they convert snake_case keys to camelCase anyway)
2. If your template starts with `d-`, then **`setSubstitutionWrappers` is silently ignored, and you must use `{{` and `}}` in your templates**

**Comment by kael-shipman** [comment]
Yes, it does work with snake case keys, but it appears as though the devs have committed internally to camel case (see the line I linked to in my report above). Thus, I would recommend all new code use camel case.

**Comment by thinkingserious** [comment]
Hello @kael-shipman,

Thanks for taking the time to help out, we greatly appreciate it!

Did you happen to see [this documentation](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#transactional-templates)? If not, would you mind describing your path of discovery that led to a wasted hour. I would love for that to never happen again and my apologies for the poor experience.

With Best Regards,

Elmer

**Comment by kael-shipman** [comment]
@thinkingserious , thanks for your understanding and willingness to improve the situation. And sorry for getting snippety up there. Had had a looooooooooooooong day ;).

Anyway, the problem is not so much that the correct(ish) documentation exists somewhere, it's that a lot of old documentation is still caught up in Google searches. I did a search for "sendgrid template fields" (just now) and the first non-ad result is [this](https://sendgrid.com/docs/API_Reference/SMTP_API/substitution_tags.html), which by all indications is the official documentation, but is clearly out of date. Not only that, but it also has two different substitution formats (`-firstName-` and `%firstName%`) and says only "what you use may depend on the SDK library you use", which seems really off, considering that all SDK libraries would presumably point to the same single temple (which only has one style of substitution tags).

In my experience with sendgrid, while I greatly appreciate what has been built, this documentation confusion is actually the rule, not the exception. I know it's probably barreling forward as much as the rest of the software world is, but it would be nice to take a month or so to just normalize all the documentation, put version numbers on it, etc., and maybe do something about the top Google hits.

Anyway, thanks again!

**Comment by kael-shipman** [comment]
Also, the documentation you linked still shows `dynamic_template_data` in snake case, and if that's correct, then I'm not sure why the code itself seems to be converting it to camelCase. As noted above, I recognize that snake case works, but given the code, it doesn't seem like the documentation should recommend using it.

**Comment by thinkingserious** [comment]
Hello @kael-shipman,

Thank you for taking the time to provide detailed feedback! 

With regards to the link you provided, that documentation is in reference to our SendGrid SMTP API, not the SendGrid v3 REST API which this SDK supports. That said, you should not be expected to know that. I'll bring this issue to the attention of our documentation team to see if there is a way to make it clear.

We just recently updated and [re-launched our open sourced documentation](https://sendgrid.com/blog/how-to-get-the-most-from-sendgrids-new-knowledge-center/). I hope you find it easier to navigate.

I will fix the README to use camelCase for consistency. Thanks for catching that and bringing it to our attention!

Thanks again and as a token of our appreciation for your detailed feedback, we would like to offer you [some swag](https://dx.sendgrid.com/swag). Enjoy!

With Best Regards,

Elmer

**Comment by kael-shipman** [comment]
Hey cool, thanks :D

**Comment by abohannon** [comment]
I'm able to get `dynamic_template_data` to work for general email variables, but what if we need to add dynamic data per recipient, as well? E.g. Order numbers, order quantity, etc. I don't see a use case for this in the docs, but maybe I'm overlooking it.

**Comment by Rolandisimo** [comment]
> Note to users: when using templates pass `dynamic_template_data` instead of `substitutions`.

@catamphetamine I've downvoted your comment because I've just spent too much time trying to figure out why everybody's code seems to be working with `dynamicTemplateData`, but in my case substitutions are simply removed.

Turns out that for me I had to do the following (the opposite of what people say):

```
// This seems to be the default, however, to avoid unexpected API changes,
// I'd rather set this manually
setSubstitutionWrappers("{{", "}}");

{
      subject: EMAIL_SUBJECT_ONBOARDING,
      templateId: "d-50df3f540e1d43eea57b6a7bde0f2c74",
      personalizations: [{
        to,
        // NOT WORKING WITH THIS ❌
        // dynamicTemplateData: {
        //   senderName: EMAIL_FROM_NAME,
        //   senderAddress: "an actual adress",
        // },

        // WORKS WITH THIS ✅
        substitutions: {
            senderName: EMAIL_FROM_NAME,
            senderAddress: "an actual adress",
        },
    }],
}
```

**Comment by Rolandisimo** [comment]
Ok, I need to investigate again. I'm stupefied because now neither `dynamicTemplateData` nor `substitutions` work for me.

**Comment by yeahsmaggy** [comment]
> **Finally,** I get `dynamic_template_data` to work consistently like so:
> 
> ```
> {
>     templateId: "d-templateId",
>     dynamic_template_data: { name: "elton yet again"}, // <-- either here
>     personalizations: [{
>         to,
>         dynamic_template_data: { name: "Elton again" }, // <-- or here
>     }],
> }
> ```

This was an important point for me. I was trying to set subject in transactional template different for to vs cc emails. It worked when I put the dynamic_template_data property inside the personalization array as per above.

**Comment by waelmas** [comment]
The solution that worked for me is placing the dynamic_template_data inside the personalization object in the exact way seen below:

```
    "personalizations": [
        {
              "dynamic_template_data": {
            "fullname": "full Name",
            "useremail": ":info@test.coml",
            "userphone": "56456",
            "usermsg": "tex fdsfgasdf t"
    },
            "to": [
                {
                    "email": "test1@test.com"
                }
            ],
            "cc": [
                {
                    "email": "test@test.com"
                }
            ]
        }
```
        
    ]
