### ISSUE TITLE
Moving from Legacy Templates to Primary

### ISSUE THREAD

**Issue by Scraso** [sendgrid/sendgrid-nodejs#705]
This is the first time when I'm using sendgrid service and it looks pretty easy however I faced with the problem when passing substitutions don't work on 'Primary' Transactional Templates. When I tried to create a Legacy one everything is working fine and data passing perfectly.

I'm using the following code

```
const SENDGRID_API_KEY = functions.config().sendgrid.key
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(SENDGRID_API_KEY);

exports.newOrderCreated = functions.firestore
    .document('orders/{itemId}')
    .onCreate((snap ) => {

        const order = snap.data();
        const db = admin.firestore()

        return db.collection('users').doc(order.userId)
            .get()
            .then(doc => {

                const user = doc.data()

                const msg = {
                    to: user.email,
                    from: 'sometestemail@gmail.com',
                    subject: 'Test subject',
                    // custom templates
                    templateId: 'd-fe7bd6772a97451ea2983805f0ede433',
                    substitutionWrappers: ['{{', '}}'],
                    substitutions: {
                        'name': 'Alexa',
                        'city': 'LA'
                    }
                };

                return sgMail.send(msg);
            })
            .then(() => console.log('email sent!'))
            .catch(err => console.log(err))

    });
```

My Templates look loke

`My name is {{name}} and I'm from {{city}} `

I tried everything but still receive the following email

`My name is and I'm from`

as I said above everything is working fine when I'm using the Legacy version. Please advice what might be wrong here and how to solve the issue.

Node.js

**Comment by thinkingserious** [comment]
Hello @Scraso,

Welcome to SendGrid!

When using the new templates, please use the key `dynamic_template_data` instead of `substitutions`. 

We have an open issue to update our SDK docs to avoid this confusion in the future. My apologies for the confusion.

With Best Regards,

Elmer

**Comment by Scraso** [comment]
Hello @thinkingserious ,

Thank you so much! It works perfectly now! Case can be closed now.

Regards,
Tigran Ambarcumyan
