### ISSUE TITLE
subject in dynamicTemplateData is not encoding correctly

### ISSUE THREAD

**Issue by januszhou** [sendgrid/sendgrid-nodejs#708]
#### Issue Summary
if subject contains `'`, it doesn't encode correctly. However, it works fine in email body, eg. `Some'd One` looks good in body content.

#### Steps to Reproduce

1. Set subject to `{{subject}}`
2. Set `dynamicTemplateData = {subject: "You've been"}`
3. Email subject become `You&apos;ve Been`

#### Technical details:

* sendgrid-nodejs Version: 6.3.1
* Node.js Version: v9.3.0

**Comment by thinkingserious** [comment]
Hi @januszhou,

Thanks for reporting this! I've added this to our backlog for further investigation.

With Best Regards,

Elmer

**Comment by geekyd** [comment]
@thinkingserious I had a look at this one & it seems like the sendgrid API does not support some special characters ' , ` in the subject. Check this.

![screen shot 2018-10-08 at 1 21 49 am](https://user-images.githubusercontent.com/12807846/46586202-934df680-ca98-11e8-9156-6207c810c2a8.png)

**Comment by nvthai** [comment]
@thinkingserious i faced same issue. Is there any update on this please?

**Comment by kylearoberts** [comment]
@januszhou @geekyd @nvthai 

We actually have a note about this in our [docs](https://sendgrid.com/docs/ui/sending-email/using-handlebars/#replacement-with-html). The encoding that happens is just part of handlebars and is talked about in [handlebars documentation](https://handlebarsjs.com/):

> Handlebars HTML-escapes values returned by a {{expression}}. If you don't want Handlebars to escape a value, use the "triple-stash", {{{.

So with all that said make sure you are using "triple-stash", {{{.

**Comment by nvthai** [comment]
@kylearoberts it works!
thank a lot !

**Comment by januszhou** [comment]
Going to close it since we have a fix now
