### ISSUE TITLE
Substitution isn't working

### ISSUE THREAD

**Issue by Doxify** [sendgrid/sendgrid-nodejs#709]
I'm currently using NodeJS to make the request and everything seems to be working fine except for the substitutions. When I test it out, I get the template I've created emailed to me, but sendgrid doesn't use my substitutions that I've specified in the code.

**Code responsible for sending email:**
```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

module.exports =  {
    sendMail(payload) {
        const msg = {
            substitutionWrappers: ["{{", "}}"],
            to: payload.customerEmail,
            from: 'REDACTED',
            templateId: 'REDACTED',
            substitutions: {
              customerName: payload.customerName,
              tourName: payload.tourName,
              departureDate: payload.departureDate,
              pickupLocation: payload.pickupLocation,
              pickupTime: payload.pickupTime
            },
        };
          
        sgMail.send(msg)
        .then(() => {
            console.log('Mail send successfully');
        })
        .catch((error) => {
            console.log('ERROR: ', error);
        })
    }
}
```

**Sendgrid template data:**
```
Dear {{customerName}},

Congratulations! Your reservation is booked.

Tour: {{tourName}}
Date of Departure: {{departureDate}}
Pick-up Location: {{pickupLocation}}
Pick-up Time: {{pickupTime}}

Thank you for your business.
```

**Picture of the email I recieve:**
![image](https://user-images.githubusercontent.com/9636316/43350786-3880e6ca-91bf-11e8-937a-7f68a7721869.png)

**Comment by jackmusick** [comment]
Same issue here. I've data preview seems to work in the designer with the same data but not when sending via the NodeJS module.

**Comment by Doxify** [comment]
I've fixed this issue by using a legacy template instead of a transactional template.

**Comment by jackmusick** [comment]
I actually fixed it for myself. Maybe I was looking at outdated documentation. Basically, the rest API has you use `dynamic_template_data` instead of `substitutions`. I tested it and it seems to work. My msg object now looks like:

```
const msg = {
            to: recipient@gmail.com,
            from: 'name@email.com',
            templateId: 'my-template-id',
            dynamic_template_data: {
                foo: 'bar',
            }
};
```

**Comment by Doxify** [comment]
Alright I'll try this out, thanks for the response!

**Comment by thinkingserious** [comment]
Thanks for helping out @jackmusick!

@Doxify @jackmusick,

Please follow [this issue](https://github.com/sendgrid/sendgrid-nodejs/issues/703) for progress on properly documenting the dynamic template functionality.

**Comment by sweetyams** [comment]
+1 Had the same issue and resolved it by using `dynamic_template_data` instead of `substitutions`

**Comment by LaptopTheOne** [comment]
Yes!!!!
dynamicTemplateData fixed the issue!

Many thanks!
