### ISSUE TITLE
event webhook strategies

### ISSUE THREAD

**Issue by jamesdixon** [sendgrid/sendgrid-nodejs#710]
#### Issue Summary
This isn't a library-specific question but more about the general approach of the community.

I'm curious how people are handling data that's coming in through the SendGrid Event Webhook?

In my case, I'm really only concerned with the latest event in the "natural sequence." Meaning I only need my users to see if the message, for example, has been opened. I'm not interested in storing every single event as I realize this can be a storage issue and for me, it's just extraneous data. When I store the events, I'm overwriting the existing event for the message if the record exists. Otherwise, I create a new record with that event.

The biggest issue I'm running into right now is the seemingly random stream of events that I get from the webhook. For example, I woke up this morning and refreshed the table where these events are logged and I'm still receiving events for messages that I sent almost a day ago. I'm also seeing cases where I receive an event, such as `open` and then I'll come back later and that message event is now `delivered`, which is out of order because a new batch came in with that event.

I am doing event de-deduplication as recommended in the docs but as I mentioned above, I'm seeing cases where I'll receive a `delivered` event after I've already received an `open` event. I realize I could check the database to see an event already exists for the message in question but I'm trying to avoid multiple round trips to the database.

Any suggestions would be helpful!

**Comment by thinkingserious** [comment]
Hello @jamesdixon,

How about storing a history for each event stream for a few days? Resolve the event stream, then delete the history.

Alternatively, when you receive an `open` event or some other KPI related final measure, auto-drop anything that would have normally happened prior, such as `delivered` in your example, assuming the only final result is what you care about tracking.

I think a good ol' fashioned white boarding session is probably in order ;)

You may also want to reach out to our support team to verify that the out of order event data behavior is expected.

With Best Regards,

Elmer

**Comment by jamesdixon** [comment]
@thinkingserious sorry for the delayed reply and thank you for the thoughtful answer! I ended up limiting the events that are sent back from the webhook, which is helping very much.
