### ISSUE TITLE
dynamic_template_data instead of substitutions

### ISSUE THREAD

**Issue by nicolastakashi** [sendgrid/sendgrid-nodejs#717]
#### Issue Summary

I'm using sendgrid-nodejs v3 to send some transactional e-mails, I read the documentation to learn how to send e-mails and make an override of variables in my SendGrid template.

After a lot of attempts to send an email with a peace of code like that:

```
import SendGrid from '@sendgrid/mail';

SendGrid.setApiKey(process.env.SENDGRID_API_KEY);
SendGrid.setSubstitutionWrappers('{{', '}}'); // Configure the substitution tag wrappers globally

const message = {
  to: 'recipient@example.org',
  from: 'sender@example.org',
  subject: 'Hello world',
  text: 'Hello plain world!',
  html: '<p>Hello HTML world!</p>',
  templateId: '13b8f94f-bcae-4ec6-b752-70d6cb59f932',
  substitutions: {
    name: 'Some One',
    city: 'Denver',
  },
};

SendGrid.send(message);
```
I did not have any success, so I make some research on [Stackoverflow] and I found a guy talking about use _dynamic_template_data_ instead of _substitutions_, so I tried and this works like a charm.

But I not found anything about that in SendGrid Documentation, somebody can tell us why the substitution, doesn't work?

#### Technical details:

* sendgrid-nodejs Version: 6.3.1
* Node.js Version: 8.11.3

[Stackoverflow]:<https://stackoverflow.com/questions/51650080/variable-substitution-in-sendgrid-templates-with-nodejs-does-not-work/51653566>

**Comment by thinkingserious** [comment]
Hi @nicolastakashi!

Please follow [this issue](https://github.com/sendgrid/sendgrid-nodejs/issues/703). Thanks!

With Best Regards,

Elmer
