### ISSUE TITLE
Substitutions not working with templateID

### ISSUE THREAD

**Issue by CustomDesignBuildStudios** [sendgrid/sendgrid-nodejs#718]
I've tried hundreds of different ways trying to get substitutions with templateID to work...
It only works when using text/html not templateId.

HTML/TEXT Version - Works
```
Code
sgMail.setApiKey(key)
...
let msg = {
            to: to,
            from: from,
            subject: title,
            html:"{{name}} how are you",
            text:"{{name}} how are you",
            substitutions:{
                name: 'Some One',
                price: 'Denver',
    }

return sgMail.send(msg).then(data=>{
```

templateId Version - Does not work
```
SendGrid Transaction Email
Hi {{name}} how are you...

Code
sgMail.setApiKey(key)
...
let msg = {
            to: to,
            from: from,
            subject: title,
            templateId: id,
            substitutions:{
                name: 'Some One',
                price: 'Denver',
    }

return sgMail.send(msg).then(data=>{
```

Also something I noticed all the docs show the template id in a certain format that matches the marketing templates not the transnational templates.

Marketing Templates IDs = #######-####-####-####-#########
Transational IDs = d-############################
(^not accurate amount of numbers/letters)

Using
@sendgrid/mail": "^6.3.1
Node v10.5.0

**Comment by CustomDesignBuildStudios** [comment]
Found similar issue #709  (for some reason github search didn't work)
Had to use 
"dynamic_template_data"
instead of 
"substitutions"

Please add this to the docs.

**Comment by thinkingserious** [comment]
Hello @CustomDesignBuildStudios,

Please follow [this issue](https://github.com/sendgrid/sendgrid-nodejs/issues/703) for progress, thanks!

With Best Regards,

Elmer

**Comment by JimLynchCodes** [comment]
I am not receiving emails at all when specifying templateId...
