### ISSUE TITLE
Unable to attach  and send .eml file

### ISSUE THREAD

**Issue by ichabondcrane** [sendgrid/sendgrid-nodejs#722]
Issue Summary

We are unable to attached .eml file to the email. The .eml file is attached as a text
![emailbody](https://user-images.githubusercontent.com/23738406/43836678-b3620fda-9b48-11e8-845f-a0a3b65b50f0.png)

For other attachments like .csv, xls, .doc etc, the email is attached without any issues.
![emailbody1](https://user-images.githubusercontent.com/23738406/43836900-65b4e8f6-9b49-11e8-8ad8-c91ecefe086e.png)

Steps to Reproduce

Here is the code we used in sending the email notification
[mailhandler.txt](https://github.com/sendgrid/sendgrid-nodejs/files/2270173/mailhandler.txt)

Technical details:
  "engines": {
    "node": "9.11.1",
    "npm": "5.6.0"
  },
 "@sendgrid/mail": "^6.3.1",

Thanks in advance and hope to hear from you soon.

**Comment by thinkingserious** [comment]
Hello @ichabondcrane,

Have you tried using `message/rfc822` as the mime [type](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/attachments.md)?

With Best Regards,

Elmer

**Comment by ichabondcrane** [comment]
Hi @thinkingserious 

fileObj.name contains the filename being attached.

Thanks,
Elizabeth

**Comment by thinkingserious** [comment]
Hi @ichabondcrane,

Does the filename end in .eml? Could you double check? Thanks!

**Comment by ichabondcrane** [comment]
Hi @thinkingserious 

I did a console.info to see the value of the filename, here is the screenshot, this indeed get the .eml filename.

![emlgithub](https://user-images.githubusercontent.com/23738406/44391955-a85fdc00-a563-11e8-8c98-c14ca283bb8c.png)

Thanks

**Comment by thinkingserious** [comment]
Hi @ichabondcrane,

Do you mind sending us the .eml file to dx@sendgrid.com so I can try and reproduce locally? Thanks!

With Best Regards,

Elmer

**Comment by ichabondcrane** [comment]
hi @thinkingserious 

I've sent the .eml in the email you specified above. Thanks

Thanks

**Comment by thinkingserious** [comment]
Note, see subject line: "DX@: sample EML file - ticket 722"

Thanks @ichabondcrane!

**Comment by ichabondcrane** [comment]
@thinkingserious - I managed to fix the issue by setting the content  into content: text/plain, and after that I was able to receive the mail with the .eml format. we can close this issue now. thanks again for all your help on this.

**Comment by thinkingserious** [comment]
Thanks for letting me know your solution!
