### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by rekhasinghal08** [sendgrid/sendgrid-nodejs#727]
Send grid Mail send response {"statusCode":500,"body":"{\"message\":\"self signed certificate in certificate chain\",\"name\":\"Error\",\"stack\":\"Error: self signed certificate in certificate chain\\n    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)\\n    at emitNone (events.js:86:13)\\n    at TLSSocket.emit (events.js:188:7)\\n    at TLSSocket._finishInit (_tls_wrap.js:610:8)\\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)\"}","headers":{}}

**Comment by thinkingserious** [comment]
Hello @rekhasinghal08,

This appears to be a non-library/SDK related issue. I believe you have an issue with your [certificate configuration](https://stackoverflow.com/a/45088585).

With Best Regards,

Elmer
