### ISSUE TITLE
Google Cloud: Invalid character in header content ["Authorization"]

### ISSUE THREAD

**Issue by DakshMiglani** [sendgrid/sendgrid-nodejs#732]
#### Issue Summary
I'm getting the following error: `Invalid character in header content ["Authorization"]` on google cloud, on my personal device it's not showing that error.

**Comment by thinkingserious** [comment]
Hello @DakshMiglani,

How did you solve your issue?

With Best Regards,

Elmer

**Comment by DakshMiglani** [comment]
Yea, so I was running my emailing service on kubernetes which was also supplying it the sendgrid key via secrets, But I didn't realise that it was also adding a '\n' character to it.

That's why later, when I checked the sendgrid api key, it looked like:
"SG_SOME-KEY-HERE\n".

So I stripped that newline character and boom it started working.

**Comment by thinkingserious** [comment]
Thanks @DakshMiglani! Hopefully your solution will help others experiencing the same issue.

Would you mind adding a PR to our TROUBLESHOOTING.md?

**Comment by DakshMiglani** [comment]
@thinkingserious sure.

**Comment by thinkingserious** [comment]
Thank you @DakshMiglani!

**Comment by Existenziell** [comment]
That saved my day... have been searching the error for hours! thanks!

**Comment by 0xDaksh** [comment]
@Existenziell glad this was helpful! such a pain to deal with such tiny issues!

**Comment by shadab14meb346** [comment]
> That saved my day... have been searching the error for hours! thanks!
> 
> For me: In Vercel Environment Variables - hit Enter - add a \n to SENDGRID_API_KEY... lol

I think this is the issue I am having but not able to understand what do you mean by hit enter. and add a \n.
Could you please give an example of the value which is supposed to be passed in vercel.
Currently, my value for `SENDGRID_API_KEY`  is something like in this pattern `SG.part1.part2-part3`
I am passing the value in vercel as this which is giving the error "SG.part1.part2-part3".
Could you please help how should I pass the value
The shown way to pass environment variable below in the pic is giving error.
![screenshot-newtab-2021 12 31-22_38_04](https://user-images.githubusercontent.com/31199288/147833582-74e79656-bb28-4dd9-a3bf-2d867d8d7449.png)
