### ISSUE TITLE
An issue with 'Access-Control-Allow-Origin' using SendGrid v3 API

### ISSUE THREAD

**Issue by jamiedejong** [sendgrid/sendgrid-nodejs#733]
Hello all,

I have created a simple HTML website with Node.js and Gulp that includes a submit form, and I catch the submit in a JavaScript file with the following code (using SendGrid v3 API):

```
		var settings = {
		  "async": true,
		  "crossDomain": true,
		  "url": "https://api.sendgrid.com/v3/mail/send",
		  "method": "POST",
		  "headers": {
			"authorization": "Bearer <<MyKey>>",
			"content-type": "application/json"
		  },
		  "processData": false,
		  "data": "{\"personalizations\":[{\"to\":[{\"email\":\"Test@Test.nl\",\"name\":\"Test\"}],\"subject\":\"Hello, World!\"}],\"from\":{\"email\":\"Test@Test.nl\",\"name\":\"Test\"},\"reply_to\":{\"email\":\"Test@Test.nl\",\"name\":\"Test\"}}"
		}

		$.ajax(settings).done(function (response) {
		  console.log(response);
		  console.log('Done!');
		});
```
But unfortunately when I try to submit the form I receive the following error in the console:

`Failed to load https://api.sendgrid.com/v3/mail/send: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://sendgrid.api-docs.io' that is not equal to the supplied origin. Origin 'http://MyWebsite' is therefore not allowed access.`.

I've tried many things, but still getting the same error.

**Comment by thinkingserious** [comment]
Hello @jamiedejong,

You have run into [this issue](https://sendgrid.com/docs/for-developers/sending-email/cors/).

My suggestion is to move the SendGrid piece to the backend.

With Best Regards,

Elmer
