### ISSUE TITLE
Send Grid C#

### ISSUE THREAD

**Issue by matheusdelre** [sendgrid/sendgrid-nodejs#734]
Good afternoon,

I'm trying to use sendgrid, but whenever I try to use a personalization I can not send, but when I remove the personalization I send it normally:

`

            var client = new SendGridClient(apiKey);

            var msg = new SendGridMessage()
            {
                From = new EmailAddress("noreply@easysistema.com", "Equipe Easy"),
                Subject = subject,
                TemplateId = "d-ce99b65e0bed498fa6f83b715d2c10d7",
                Personalizations = new List<Personalization>()
                {
                    new Personalization()
                    {
                        Substitutions = new Dictionary<string, string>()
                        {
                            {"%linkConfirmacao%", link}
                        }
                    }
                }
            };

            msg.AddTo(new EmailAddress(email));

            return client.SendEmailAsync(msg);
        }`

* C# ASP.NET MV5 CORE 2;0

**Comment by JamesTheHacker** [comment]
This repo is for the NodeJS version. The C# repo can be found here: https://github.com/sendgrid/sendgrid-csharp

**Comment by thinkingserious** [comment]
Hello @matheusdelre,

Please upgrade to v9.10.0 and utlize this [documentation](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional-templates).

Thanks!

Elmer
