### ISSUE TITLE
Payment failure gives response status of 202

### ISSUE THREAD

**Issue by mevillep** [sendgrid/sendgrid-nodejs#737]
Payment failure occurred in PROD version of my application.
The response that I receive from SendGrid is 202
`{ statusCode: 202,
          body: '',
            headers:
             { server: 'nginx',
               date: 'Mon, 10 Sep 2018 14:54:14 GMT',
               'content-type': 'text/plain; charset=utf-8',
               'content-length': '0',
               connection: 'close',
               'x-message-id': 'WM2NUgL7SwOPqnKYDKoJyg',
               'access-control-allow-origin': 'https://sendgrid.api-docs.io',
               'access-control-allow-methods': 'POST',
               'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
               'access-control-max-age': '600',
               'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' } }`

* Node.js Version: 7.10.0

**Comment by mevillep** [comment]
I have a credit card associated with the SendGrid account. Due to some unknown reasons, the auto payment failed. During this time, the requests that I made to SendGrid got me 202. 
Also, if a 202 status code means that "Your message is both valid, and queued to be delivered." I was hoping for the message to be delivered after the payment went through. Which by the way, it did with a different card, within a few hours.

**Comment by thinkingserious** [comment]
Hello @mevillep,

Please reach out to our [support team](https://support.sendgrid.com) for further assistance. 

Thanks!

With Best Regards,

Elmer
