### ISSUE TITLE
SendGrid SetTemplateData method not found C#

### ISSUE THREAD

**Issue by HindoliyaYogesh** [sendgrid/sendgrid-nodejs#738]
Hello,

I am trying to use Transactional Templates with SendGrid Mail Helper API.

I read the USE_CASE.md and found out the following code that helps me add data to be passed to template for substitutions :

```
var dynamicTemplateData = new ExampleTemplateData
{
    Subject = "Hi!",
    Name = "Example User",
    Location = new Location
    {
        City = "Birmingham",
        Country = "United Kingdom"
    }
};

msg.SetTemplateData(dynamicTemplateData);
```

My issue is I cannot see SetTemplateData method in the version of helper I have.
I am using SendGrid 9.9.0 and dll version is 9.8.0.0 and runtime version is v4.0.30319.
.NET Version 4.5.2

**Comment by thinkingserious** [comment]
Hello @HindoliyaYogesh,

Please upgrade to version 9.10.0. Thanks!

With Best Regards,

Elmer
