### ISSUE TITLE
Email is not getting verified before sending email.

### ISSUE THREAD

**Issue by AhmadRaza786** [sendgrid/sendgrid-nodejs#739]
# Email is not getting verified.
 ```
const msg = {
        to: 'vision.asasdddae@gmail.com',
        from: 'ahmed.raazaa@hotmail.com',
        subject: 'Sending with SendGrid is Fun',
        text: 'and easy to do anywhere, even with Node.js',
        html: '<strong>and easy to do anywhere, even with Node.js</strong>',
      };
      let result = await sgMail.send(msg);
      console.log(result);
```

In above code I am writing an invalid email in agains `to`. But sendGrid is still sending the same result as the valid email. every target email must be verified before sending email. it must be make sure that the target email exist or not.

**Comment by thinkingserious** [comment]
Hello @AhmadRaza786,

Are you requesting that we implement a service where we check the validity of the email before you send it?

With Best Regards,

Elmer

**Comment by AhmadRaza786** [comment]
Hello @thinkingserious , Exactly this is what I am asking for. Currently, SendGrid is not verifying that the target email is exist or not. It must take care of this verification. And I am ready to contribute in SendGrid for it.

**Comment by siqueira-ec** [comment]
I'm on It.

**Comment by eshanholtz** [comment]
Closing as this is a non-library issue.
