### ISSUE TITLE
Dynamic Template support is missing from the TypeScript definitions

### ISSUE THREAD

**Issue by SPARTAN563** [sendgrid/sendgrid-nodejs#740]
#### Issue Summary

A user [raised the issue](https://github.com/sendgrid/sendgrid-nodejs/commit/a01a2775954a07b6c436a9ab9a57269ca98f800e#commitcomment-30488495) that the new dynamic template functionality (and fields) are not represented in the TypeScript definitions for this project.

Specifically, it appears that the [use case](https://github.com/sendgrid/sendgrid-nodejs/commit/2fbcd05f14b7776d92f8e01e7b196644776332cc) described in the mail package is not possible right now using TypeScript.

#### Steps to Reproduce

1. Attempt to implement [this use case](https://github.com/sendgrid/sendgrid-nodejs/commit/2fbcd05f14b7776d92f8e01e7b196644776332cc) in TypeScript.

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: 0c83ae9a7151f466383df35a897a3426c5cdb06b)
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Hi @SPARTAN563,

I think this is a related PR: https://github.com/sendgrid/sendgrid-nodejs/pull/716

Thanks for opening this issue and getting the party started :)

With Best Regards,

Elmer

**Comment by duncanleung** [comment]
I’d like to try take this on!

**Comment by duncanleung** [comment]
@thinkingserious the `help wanted` tag should be removed from this issue?

Looks like PR #716 adds in the fix to `mail.d.ts` and is just waiting to be merged.

**Comment by thinkingserious** [comment]
Thanks for the heads up @duncanleung!
