### ISSUE TITLE
& character escaped to &amp; on dynamic template subjects

### ISSUE THREAD

**Issue by rafaelrpinto** [sendgrid/sendgrid-nodejs#741]
#### Issue Summary

When using dyamic templates and substitutions to set the e-mail subject, the character `&` is escaped to `&amp;` which makes the subject of the e-mail not show company / product names correctly. 

EX: The subject is of the message received is `Thanks for buying at C&amp;A` instead of the expected:  `Thanks for buying at C&A`.

#### Steps to Reproduce

1. Create a new dynamic template and set the subject to `{{subject}}`

2. Send the e-mail informing a subject containing the `&` character:

```javascript
const sgMail = require("@sendgrid/mail");

const templateId = "XXXXXXXX";
const apiKey =  "XXXXXXXXXX";

sgMail.setApiKey(apiKey);
const msg = {
  templateId,
  to: "some@email.com",
  from: "other@email.com",
  dynamic_template_data: {
    subject: "Escape & work"
  }
};
sgMail.send(msg);
```

3. Check your e-mail client for the message with subject `Escape &amp; work`

#### Technical details:

* sendgrid-nodejs Version: 6.3.1
* Node.js Version: 6.10.3

**Comment by kylearoberts** [comment]
Hello @rafaelrpinto 

Looks like what you need to do is use a triple bracket on your subject so that handlebars does not HTML encode the content. So instead of using `{{subject}}` use `{{{subject}}}`. We have an example of this in our docs [here](https://sendgrid.com/docs/ui/sending-email/using-handlebars/#replacement-with-html) and is talked about in the handlebars documentation [here](https://handlebarsjs.com/) under HTML Escaping.

**Comment by rafaelrpinto** [comment]
@kylearoberts 

Yep, that solves my problem.

Thanks for the quick response. 

Rafael

**Comment by maxirby** [comment]
> @kylearoberts
> 
> Yep, that solves my problem.
> 
> Thanks for the quick response.
> 
> Rafael

Please show how your msg looks like (code example) after you added {{{}}} ?

**Comment by rafaelrpinto** [comment]
@maxirby 

The code is the same, what changed is the subject definition on the template where I set to: `{{{subject}}}` instead of `{{subject}}`

**Comment by maxirby** [comment]
Thanks

**Comment by riceyrice** [comment]
It would be handy if the automatic plain text templates converted `{{ value }}` to {{{ value }}}` to avoid HTML entities appearing in plain text emails.

**Comment by mattstabeler** [comment]
> > @kylearoberts
> > Yep, that solves my problem.
> > Thanks for the quick response.
> > Rafael
> 
> Please show how your msg looks like (code example) after you added {{{}}} ?

It's the template itself that needs to be updates - using the UI like this: 

![image](https://user-images.githubusercontent.com/237220/148050414-80363ca9-6863-4d16-968f-75bfa3ca0dcc.png)

by adding the triple brackets in the settings/subject setting

**Comment by idanail** [comment]
Wrapping the variable with three brackets doesn't resolve the issue for the subject, just for the email body.

Test data:
```
{
    "first_name": "Mc&apos;Brian"
}
```

In the Email Body:
- Using `{{first_name}}` renders the encoded value `Mc&apos;Brian`.
- Using `{{{first_name}}}` renders the value correctly as `Mc'Brian`.

In the Subject Line:
- Both `{{first_name}}` and `{{{first_name}}}` render the value as `Mc&apos;Brian`.

I tried both `{{{first_name}}}`, and `{{{ first_name }}}`, the outcome is the same.

![image](https://github.com/sendgrid/sendgrid-nodejs/assets/82705378/884f10c3-8bff-4f7e-819d-90bb9f22f053)

**Comment by nick-carma** [comment]
> > > @kylearoberts
> > > Yep, that solves my problem.
> > > Thanks for the quick response.
> > > Rafael
> > 
> > 
> > Please show how your msg looks like (code example) after you added {{{}}} ?
> 
> It's the template itself that needs to be updated - e.g. by using the UI like this:
> 
> ![image](https://user-images.githubusercontent.com/237220/148050414-80363ca9-6863-4d16-968f-75bfa3ca0dcc.png)
> 
> by adding the triple brackets in the settings/subject setting

this should work, but whether I use double braces or triple braces in the subject, the value is html encoded
