### ISSUE TITLE
SendGrid.com destroys "dynamic" templates

### ISSUE THREAD

**Issue by catamphetamine** [sendgrid/sendgrid-nodejs#742]
I created a "dynamic" template and then saved it.
After that I navigated to it in edit mode and then refreshed the page.
It destroyed the template (erased all content and saved the changes).

It also happened the second time.

This is not about the `npm` package, it's about the website.
You can pass this issue to your QA.

**Comment by kylearoberts** [comment]
Hey @catamphetamine 

It is best that you bring these kinds of things to support so we can take a look at normal causes for this. I would create a ticket with support [here](https://support.sendgrid.com/). They may have additional questions and follow-ups for your issue. In your ticket I would provide the template you had an issue with so they can check our logs to try and get an idea of what happened.

**Comment by catamphetamine** [comment]
Ok.
