### ISSUE TITLE
Dynamic Content Template. Substitution do not show up. 

### ISSUE THREAD

**Issue by coredomain** [sendgrid/sendgrid-nodejs#745]
**Please help** 
I'm not using any library. I'm making a post requests directly to your API. The email shows up without the replacement.

This my html 
<br>
<p>Email Send By {{ **dynamicTemplateData.portalsender** }}</p>

My JSON Call dynamicTemplateData with camel case
https://api.sendgrid.com/v3/mail/send

{
  "personalizations": [
    {
      "to": [
        {
          "email": "asfsfsf@asdfasf.com",
          "name": "John Doe"
        }
      ],
      "dynamicTemplateData ": {
        "portalsender": "Test"
      }
    }
  ],
  "from": {
    "email": "teste@asdfasd.com",
    "name": "Sam Smith"
  },
  "reply_to": {
    "email": "sdfasdfasd@asdfasdfa.com",
    "name": "Sam Smith"
  },
  "template_id": "d-asfasdfsdfasdfasdfasdfasdf"
}

**Comment by kylearoberts** [comment]
Hey @coredomain

It is best to bring things like this to support so they can look at your account and the specific data around what you are doing. To solve issues like these we have to look at the template in your account and check the data you are passing. You can hit up the support team [here](https://support.sendgrid.com/).
