### ISSUE TITLE
Update integration tests to utilize StopLight.io's Prism version v2.X

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#755]
#### Issue Summary

We use a mock server for integration/contract testing that is driven by our OpenAPI specification and StopLight.io's Prism service. The service is spun up utilizing the prism.sh script in this repo.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* we automatically use the latest v2.X version of Prism locally, in Travis CI and in Docker
* tests pass locally, in Travis CI and using Docker
* update `CONTRIBUTING.md` documentation, if necessary

#### Notes & References

* [Prism GitHub Repo](https://github.com/stoplightio/prism)

**Comment by aslafy-z** [comment]
I had a try with `prism` v2 but i'm not able to run the mock server (haven't tried docker release). 
Openned an issue here: https://github.com/stoplightio/prism/issues/152

####  Here are my findings:
New installer url: `https://raw.githubusercontent.com/stoplightio/prism/2.x/install.sh`
New command to mock: `prism mock --spec https://raw.githubusercontent.com/sendgrid/sendgrid-oai/master/oai_stoplight.json`
Update tests globbing: 
- "&ast;&ast;/&ast;.spec.js" becomes $(find . -name '*.spec.js' ! -ipath '&ast;node_modules&ast;')
- "packages/client/&ast;&ast;/&ast;.spec.js" becomes $(find packages/client -name '*.spec.js' ! -ipath '&ast;node_modules&ast;')

Also, It seems that incorrect values are sent to api in `packages/client/src/client.spec.js` (Prism 0.6 was trowing bunch of errors about this)
eg: `/v3/access_settings/whitelist/{rule_id}` should be `/v3/access_settings/whitelist/MYRULE`, no ?
If needed, here the list of the in-url variables names grabbed in this `client.spec.js`:
rule_id alert_id api_key_id group_id email campaign_id client_type 
custom_field_id list_id recipient_id segment_id pool_name id_address 
batch_id request_id sender_id subuser_name token username template_id 
version_id batch_id hostname id ip link_id

**Comment by anand2131993** [comment]
I got Prism 2.0 working locally. I shall try to take this up if that's ok.

**Comment by anand2131993** [comment]
@thinkingserious Any inputs on this? If there's that I need to change in the PR, please let me know.

**Comment by childish-sambino** [comment]
Closing as prism integration has been moved to https://github.com/sendgrid/sendgrid-oai/
