### ISSUE TITLE
i have 500 error when i try to make a post send a email with express.js

### ISSUE THREAD

**Issue by seif1000** [sendgrid/sendgrid-nodejs#758]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by aroach** [comment]
Can you provide more details and repro steps?  Maybe a gist?

**Comment by leovazquezz1** [comment]
I have the same Issue, I just basically used the exaomple that is on sedn grid Here is my code.

Node version: 10.8.0
npm version: 6.4.1 
@sendgrid/mail version: ^6.3.1

function sendClientMessageToDispatcher(clientNumber, orderId, body) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);
  const msg = {
    to: 'to@gmail.com',
    from: 'from@gmail.com',
    subject: 'Client Message -- '+ clientNumber +' -- '+ orderId,
    text: '',
    html: body + ' <br> ------------ ',
  };
  sgMail.send(msg);
  console.log("Email send!!!");
};

And I get this error:

(node:17070) UnhandledPromiseRejectionWarning: Error: Bad Request
    at Request.http [as _callback] (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (node_modules/request/request.js:1163:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:17070) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17070) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by thinkingserious** [comment]
Hello @leovazquezz1, @seif1000,

Could you please try to obtain the error message [like so](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#success-failure-errors)? Thanks!

With Best Regards,

Elmer

**Comment by leovazquezz1** [comment]
We just rolled back to the first version and is all working now

**Comment by thinkingserious** [comment]
HI @leovazquezz1,

I'm not sure what you mean by rolled back to the first version? Do you mean that you are using a different version of the SDK? If so, which one?

@seif1000,

Were you able to figure out the issue?
