### ISSUE TITLE
Implement auto-deploy to package manager

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#761]
#### Issue Summary

When all tests on the master branch pass in Travis CI, we would like to auto-deploy the release to the package manager.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* when Travis CI passes all tests on the master branch we auto-deploy to the package manager
* the version is determined by the `CHANGELOG.md`

**Comment by thinkingserious** [comment]
@joostme,

I agree, `lerna publish` is probably the way to go, but I can't seem to find any examples on how to do this :(

Maybe there is some way to use lerna to figure out the right npm publish commands to use and in what order.

Maybe the move is use a script to generate the yml you provided and only update the relevant packages based on the particular update.

In any case, thanks for trying to take this one on!

With Best Regards,

Elmer

**Comment by aslafy-z** [comment]
`lerna publish` doc can be found here: https://github.com/lerna/lerna/tree/master/commands/publish#readme

**Comment by joostme** [comment]
The problem I see with `lerna publish` is that it authenticates the user using the `.npmrc` which should not be commited. Maybe the token can be stored encrypted in the Travis pipeline as environment variable and the publish is done using a custom script that uses `lerna changed` to get all packages that have changed.

**Comment by aslafy-z** [comment]
For reference: https://github.com/lerna/lerna/issues/1705

**Comment by childish-sambino** [comment]
Fixed by 37473ad95a20258196d7cf256ea391508872d65e
