### ISSUE TITLE
[inbound-mail-parser] mailparser@0.6.2 is deprecated

### ISSUE THREAD

**Issue by aslafy-z** [sendgrid/sendgrid-nodejs#762]
#### Issue Summary

mailparser@0.6.2 is deprecated and needs to be upgraded.

#### Steps to Reproduce

1. npm install

> npm WARN deprecated mailparser@0.6.2: Mailparser versions older than v2.3.0 are deprecated

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: f0449de)
* Node.js Version: 10.10.0
* NPM Version: 6.4.1

**Comment by AllUsernamesHaveBeenTaken** [comment]
I'll take this one.

**Comment by aslafy-z** [comment]
@AllUsernamesHaveBeenTaken already did... See #763

**Comment by AllUsernamesHaveBeenTaken** [comment]
> @AllUsernamesHaveBeenTaken already did... See #763

Oops, I must have looked over it.
