### ISSUE TITLE
Require conformance to style standards

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#766]
#### Issue Summary

In the `CONTRIBUTING.md` file there is a section on Style Guidelines & Naming Conventions. Please review and implement a check in Travis CI. If there are any style errors, either fix or create a rule to exclude the error.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* TravisCI checks that the code conforms to our Style Guidelines & Naming Conventions as defined in our `CONTRIBUTING.md` file
* tests pass locally, in Travis CI and using Docker

**Comment by wer12345** [comment]
I like to challenge myself with this issue if there is still no one working on it

**Comment by wer12345** [comment]
Oh.. Too bad
    Pada Minggu, 7 Oktober 2018 05.22.58 WIB, Tony Ho <notifications@github.com> menulis:  
 
 
@wer12345 I've already opened PR #767 to take care of this one.
