### ISSUE TITLE
Create a Dockerized event webhook consumer

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#786]
#### Issue Summary

SendGrid has an [Event Webhook](https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html) which posts events related to your email activity to a URL of your choice. We want to have an easily deployable solution that allows for customers to easiy get up and running processing (parse and save) their event webhooks.

#### Acceptance Criteria

* A folder which contains a Dockerized solution
* Example documentation on how to deploy locally and start processing events
* Example documentation on how to deploy on at least one cloud service and start processing events
* An example complete payload with a test to verify the data is parsed properly

**Comment by aroach** [comment]
Hey!  @thinkingserious  I'll take this one too.  What do you think about if I just modified the inbound parse example to also be able to accept the event webhooks on a different route?  For example, currently, I have a route `POST /parse_webhook`.  I can just add a second `POST /event_webhook` in the same app, and then explain the event object that is sent by SG.  We can then just rename the subfolder to something more general like `webhook-consumer`...

**Comment by thinkingserious** [comment]
Great idea! It's all yours :D
