### ISSUE TITLE
Create a Dockerized email inbound parse webhook consumer

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#787]
#### Issue Summary

SendGrid has an [Email Inbound Parse Webhook](https://sendgrid.com/docs/API_Reference/Parse_Webhook/inbound_email.html) which posts data from a specified incoming email address to a URL of your choice. We want to have an easily deployable solution that allows for customers to easiy get up and running processing (parse and complete some action) their inbound parse webhooks.

#### Acceptance Criteria

* A folder which contains a Dockerized solution
* Example documentation on how to deploy locally and start processing incoming emails
* Example documentation on how to deploy on at least one cloud service and start processing incoming emails
* An example complete payload with a test to verify the data is parsed properly

**Comment by aroach** [comment]
I'll take this one
