### ISSUE TITLE
Document the difference of using three brackets vs two brackets with a template and throw or log an error when used improperly

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#790]
#### Issue Summary

Our templates use the handlebars.js syntax as documented [here](https://sendgrid.com/docs/ui/sending-email/using-handlebars/). When including the characters ', " or & in a subject line replacement you need to use three brackets vs two ( {{{ content }}} vs {{ content }} ). 

#### Acceptance Criteria

* Documentation of this functionality in the use cases section (transactional templates) of this repo.
* A new test is added that demonstrates that if you use the characters ', " or & in a subject line replacement utilizing template id's prefixed with d-, the code will throw an error or log (to avoid a breaking change) the incident.

**Comment by reedsa** [comment]
I'll dig into this one.
