### ISSUE TITLE
Create first time contributor documentation

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#791]
#### Issue Summary

Our open sourced documentation has a great [first time contributor page](https://github.com/sendgrid/docs/blob/develop/first-timers.md) that we wish to duplicate here.

#### Acceptance Criteria

* We have a file in the root directory called first-timers.md or similar that helps a first time contributor make their first PR (please use our CONTRIBUTOR.md file for inspiration as well as [this page](https://github.com/sendgrid/docs/blob/develop/first-timers.md))
* We provide a link to tasks with the labels "difficulty: easy" and "status: help wanted" ([example query](https://github.com/sendgrid/sendgrid-python/issues?q=is%3Aopen+label%3A%22difficulty%3A+easy%22+label%3A%22status%3A+help+wanted%22)) to all the repos listed [here](https://dx.sendgrid.com/hacktoberfest), please scroll to the bottom.

**Comment by ely-alamillo** [comment]
I'll take this one @thinkingserious
