### ISSUE TITLE
Issue with 'crypto' module using React Native, Verifying Integration

### ISSUE THREAD

**Issue by noahsarktheapp** [sendgrid/sendgrid-nodejs#794]
#### Issue Summary

Looking for help in fixing my red screen. Created the environment variable and added the npm package, however when I add in the sample code just to test to make sure its working, I get this error:

Failed to load bundle(http://localhost:8081/index.bundle? platform=ios&dev=true&minify=false) with error:(Unable to resolve module 'crypto' from '[filepath of my app]/node_modules/request/lib/helpers.js': Module 'crypto' does not exist in the Haste module map.

I cleared watchman and node modules and reset the bundler cache. 

I saw online some people talking about using rn-nodeify to install shims and a --hack to workaround React Native not allowing crypto, but was hoping to find a safer approach that was a better production solution.

Let me know if I left out any useful information, Thanks for any help!

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Hello @noahsarktheapp 

Have you tried any of the solutions mentioned [here](https://stackoverflow.com/questions/36415157/twilio-react-native-unable-to-resolve-module-crypto)?

With Best Regards,

Elmer

**Comment by valevarela2612** [comment]
Hi! Could you finally solve this issue?
