### ISSUE TITLE
Auto-generate the CHANGELOG.md file upon release

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#796]
#### Issue Summary

For every release, we currently hand craft a CHANGELOG.md update, now we would like to automate this process. Please see the existing CHANGELOG.md for formatting structure.

#### Acceptance Criteria

* A script, which when run, creates a CHANGELOG.md update based on any merged PRs since the last release.

**Comment by HeroProtagonist** [comment]
I would like to give this a shot!

**Comment by mauricetmeyer** [comment]
@HeroProtagonist If you need any help, you can have a look at [my implementation](https://github.com/sendgrid/php-http-client/pull/117/commits/ecfaf051f6267075b97152f83afbd05dd219e9b4).

**Comment by arguiot** [comment]
I created a PR (#808)

**Comment by aslafy-z** [comment]
I'd recommend using a maintained project instead of our own implementation. Give a look to https://github.com/github-changelog-generator/github-changelog-generator

**Comment by harshil1712** [comment]
Is anyone still working on this? I would like to work on this

**Comment by thinkingserious** [comment]
Interesting @aslafy-z, I was not aware of those project. What do you think @arguiot?

**Comment by schalkneethling** [comment]
Anyone actively working on this? If not, I would like to take this up. @HeroProtagonist @arguiot @thinkingserious @harshil1712 @mauricetmeyer @aslafy-z

**Comment by thinkingserious** [comment]
I gave you Hacktoberfest points for your efforts @arguiot, thank you!

If someone would like to re-implement this using one of the supported project that @aslafy-z recommended, please post a message here and it's all yours. Thanks!

**Comment by schalkneethling** [comment]
@thinkingserious I will take a stab at this using semantic-release. If this works for you, let me know and I will get cracking.

**Comment by childish-sambino** [comment]
Closing as we're now using internal tooling for this.
