### ISSUE TITLE
Document new Git workflow in CHANGELOG.md

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#799]
#### Issue Summary

We want to update our git workflow to function more like [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow). We need to update the CONTRIBUTING.md file and PULL_REQUEST_TEMPLATE to direct contributors to fork/branch off the `development` branch and to merge their PRs with the `development` branch. Once this issue is complete, we will be creating the `development` branch and making that branch the default. This is part of a larger strategy to execute releases for this SDK on a predictable cadence.

#### Acceptance Criteria

* Update CONTRIBUTING.md documentation, explaining the process of forking and branching off the `development` branch and submitting PRs agains the `development` branch.
* Update PULL_REQUEST_TEMPLATE with the same addition to the CONTRIBUTING.md documentation.

**Comment by pandaa880** [comment]
I would like to take this one. May i ?

**Comment by tony-ho** [comment]
I can take this one.

@thinkingserious This repository contains both a PULL_REQUEST_TEMPLATE and PULL_REQUEST_TEMPLATE.md with exactly the same content. I propose removing the md version to reduce duplication and keeping PULL_REQUEST_TEMPLATE for consistency with the other repos.
