### ISSUE TITLE
Bad request for sending scheduled emails with send_at

### ISSUE THREAD

**Issue by oxiumio** [sendgrid/sendgrid-nodejs#805]
#### Issue Summary

Since today I am getting 400 for each scheduled email I am sending with send_at. It worked fine two days ago, source code did not change since then.

#### Steps to Reproduce

Here's the code on the node server (obviously I am using correct API key, not "MY_API" as below):

```
const options = {
                        url: 'https://api.sendgrid.com/v3/mail/batch',
                        headers: {Authorization: `Bearer SG.MY_API`}
                      };
                      request.post(options).then(resp => {
                        const batch_id = resp.split(':"')[1].split('"}')[0];
                        
const msg = {
                          to: req.body.email,
                          from: 'my@email.com',
                          subject: 'Initial email',
                          text: `Hello! This is initial email`,
                          html: `<p>Hello! This is initial email</p>`,
                        };
sgMail.send(msg).then(result => {}).catch(err => console.log(err));

const reminder = {
                                "to": req.body.email,
                                "from": 'reminders@email.com',
                                "subject": 'Reminder',
                                "text": `Hello! This is a friendly reminder`,
                                 "html": `<p>Hello! This is a friendly reminder</p>`,

                                // reminder is sent 1 hr before the appointment
                                "send_at": +((new Date(req.body.start).getTime() - 1000 * 3600)/1000).toFixed(0),
                                "batch_id": batch_id
                              };
sgMail.send(reminder).then(result => {}).catch(err => console.log(err));
```

if I console.log `batch_id`, it seems to be of the right format, and it checks out with GET https://api.sendgrid.com/v3/mail/batch/{batch_id}

the `send_at` value is 1539781200, which translates into Thursday, October 18, 2018 9:15:00 AM (EST), so seems to be a correct unix timestamp

To sum this up - the difference between `msg` and `reminder` is send_at and batch_id. `msg` sends out fine at all times. If I comment out `send_at` for `reminder` - it also sends out fine. With `send_at` it fails with 400. I checked API key permissions just in case - full access for both keys I have in this account.

Here's error message:
```
{ Error: Bad Request
    at ResponseError (node_modules/@sendgrid/helpers/classes/response-error.js:19:5)
    at Request.http [as _callback] (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 400,
  message: 'Bad Request',
  response: 
   { headers: 
      { server: 'nginx',
        date: 'Sat, 13 Oct 2018 21:06:32 GMT',
        'content-type': 'application/json',
        'content-length': '544',
        connection: 'close',
        'access-control-allow-origin': 'https://sendgrid.api-docs.io',
        'access-control-allow-methods': 'POST',
        'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
        'access-control-max-age': '600',
        'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' },
     body: { errors: [Object] } } }
```

#### Technical details:

"@sendgrid/mail": "^6.3.1"
node 10.11.0

Thank you for your help

**Comment by tgercek** [comment]
Hi there,

I've been unable to reproduce this error using a time that's 10 minutes into the future. I suspect your issue is that in testing you're scheduling an email outside the [72 hour window that SendGrid provides](https://sendgrid.com/docs/API_Reference/SMTP_API/scheduling_parameters.html) - seems SG don't want to be responsible for hosting our email content for too long.

Funnily enough I just made it outside that window using your UNIX timestamp as an example and received this:

`{ errors: 
   [ { message: 'Scheduling more than 72 hours in advance is forbidden.',
       field: 'send_at',
       help: 'http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.send_at' } ] }`

For future reference, you can reveal the error descriptions by drilling into the errors thrown by this API. The SendGrid level errors are located as follows: err > response > body.

Hope that helps!

**Comment by oxiumio** [comment]
@tgercek thank you so much for your answer. This does make sense now as if I schedule a reminder 15 minutes from now, it seems to be working fine. I was confused with this bit in documentation:

> A batch_id is valid for 10 days (864,000 seconds) after generation.

Since I'd need a batch_id for cancelling or pausing scheduled email, I thought that I can schedule a reminder anytime within the 10 day lifecycle. Probably I skipped the part about 72 hours. But again, thanks so much for helping me out!
