### ISSUE TITLE
Suddenly sendgrid module unable to find / Google Cloud Function

### ISSUE THREAD

**Issue by mldmld68** [sendgrid/sendgrid-nodejs#808]
#### Issue Summary

I'm writing a Cloud Function on GCP using SendGrid.
I'm using the embedded GCP editor to update my cloud function.
After a few versions, it's no more possible to use sendgrid. I get the error
 
**Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'sendgrid'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/index.js:8:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)_**

The .json is unchanged. And even using a former version of my code, it has the same issue.
### The package.json contains 
_{
  "name": "send email alerts",
  "version": "0.0.2",
   "engines": {
    "node": "0.10.x",
    "npm": "1.2.x"
   },
  "dependencies": {
    "dotenv": "^0.5.1",
    "nodemailer": "^1.3.0",
    "sendgrid": "^1.5.0",
    "@sendgrid/mail": "^6.0.0",
    "smtpapi": "^1.0.5"
  }
}_
### The index.js contains
const sendgrid = require('sendgrid');
const sendgridAlertBillingApiKey = 'xxxxxxxx'

exports.sendmail = (event, callback) => {
  const pubsubMessage = event.data;
  const name = pubsubMessage.data ? Buffer.from(pubsubMessage.data, 'base64').toString() : 'World';
  console.log(`Message received from Pub : ${name}!`);
  const sgMail = require('@sendgrid/mail');
  sgMail.setApiKey(sendgridAlertBillingApiKey);
  
   var msg = {};
   msg.to      = 'xxxxx@xxxx.com';
   msg.from    = 'noreply@xxxx.com';
   msg.subject = 'Billing Alert 2';
   msg.html    = `<strong><P>${name}</P><P>Automatic billing alert generated by Pub/Sub & CloudFunction on node.js</P></strong>`;
 
  sgMail.send(msg);
  console.log('Mail sent')
  callback();
};_
#### Steps to Reproduce
1. Create a new cloud function
2. Update it many times.
After a while , the error occurs.

I wonder if the sendgrid module are always online ?
#### Technical details:
* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 6

**Comment by thinkingserious** [comment]
Hello @mldmld68,

Could you please try removing this line `"sendgrid": "^1.5.0",`. Thanks!

With Best Regards,

Elmer
