### ISSUE TITLE
Can I change ip port when I mail send?

### ISSUE THREAD

**Issue by JongSikLim** [sendgrid/sendgrid-nodejs#811]
Issue Summary

In my client environment, can't using 443 port, So i want to change port. 

What should i do?

Technical details:
sendgrid-nodejs Version: latest version
Node.js Version: 8.11.4
Using electron.

**Comment by aroach** [comment]
Our servers are only listening on port 443.  So, if you can't do that, you would likely need to communicate to a write/use a "proxy" server on a custom port to it, and then the "proxy" would communicate via 443 to our servers.  You probably would want to do something like this anyway, so you don't put your API key in the wild.
