### ISSUE TITLE
Type Exception Handling for the Mail Helper

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-nodejs#816]
#### Issue Summary

The appropriate types necessary for a successful `mail/send` API call is documented [here](https://sendgrid.com/docs/API_Reference/api_v3.html). We want to throw a type exception when the wrong type is provided.

#### Acceptance Criteria

* All parameters for the `mail\send` endpoint are type checked and if they fail the type check and exception is thrown with instructions on how to fix

**Comment by jcfi** [comment]
@alexhoffman617 Some of them do already have validation, but it's not consistent across fields. For example, [the subject field is validated on creation](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/helpers/classes/mail.js#L141), but [the from field is not](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/helpers/classes/mail.js#L121).

**Comment by childish-sambino** [comment]
Changes have been merged: https://github.com/sendgrid/sendgrid-nodejs/commit/96f2c7aae6af22d2ec74afb391ba0a2d8892f49e
