### ISSUE TITLE
SendGrid and Netlify Lambda Functions ERROR

### ISSUE THREAD

**Issue by joshicraft** [sendgrid/sendgrid-nodejs#839]
#### Issue Summary

I'm experiencing some issues with the SendGrid Transactional Templates when using node.js and netlifys functions. I'm using the netlify-lambda to build the function file's on deploy.

When I use the raw template html in the function.js file for the msg.html property it works fine.

When I use the SendGrid v2 substitutions the email sends to my email but the handlebar properties e.g. {{name}} don't get placed in the email.

#### The error I'm receiving is

```
5:18:42 PM: TypeError: s is not a function
5:18:42 PM: {"errorMessage":"TypeError: s is not a function"}
```

#### function.js
```
const sgMail = require('@sendgrid/mail')

exports.handler = function (event, context, callback) {

  sgMail.setApiKey(process.env.SENDGRID_API_KEY)
  sgMail.setSubstitutionWrappers('{{', '}}')
  let body = JSON.parse(event.body)

  let msg = {
    to: process.env.CONTACT_MAIL_TO,
    from: process.env.CONTACT_MAIL_FROM,
    subject: 'Website Contact Form',
    text: 'Someone has filled out a form on your website, check out the message they left and get in touch with them :)',
    templateId: 'd-39c15b77271449548e2f13b66920f808',
    html: '<p>Hello HTML world!</p>',
    dynamic_template_data: {
      subject: 'Testing Templates',
      name: body.name,
      phone: body.phone,
      email: body.email,
      message: body.message,
      website: body.website
    }
  }

  sgMail.send(msg).then(() => {
    console.log(`Contact form sent from: ${process.env.CONTACT_MAIL_FROM}, to: ${process.env.CONTACT_MAIL_TO}, with name: ${body.name}`)
    callback()
  }).catch(e => {
    console.error(e.toString())
    callback(e.toString())
  })
}
```

#### Markup Structure
```
        <div><span>Name:&nbsp;</span>{{name}}</div>
        <div><span>Email:&nbsp;</span>{{email}}</div>
        <div><span>Phone:&nbsp;</span>{{phone}}</div>
        <h1><span>Message</span></h1>
        <div><span>Message:&nbsp;</span>{{message}}</div>
```

#### package.json

```
 "engines": {
    "node": ">= 8.0.0",
    "npm": ">= 3.0.0"
  }
  "dependencies": {
    "@sendgrid/mail": "^6.3.1"...
```

**Comment by thinkingserious** [comment]
Hello @joshicraft,

[Here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/transactional-templates.md) is an updated example on how to use our transactional templates within this library. Could you please adjust your code (e.g. this line `sgMail.setSubstitutionWrappers('{{', '}}')` is no longer needed) and let me know if that solves the issue.

With Best Regards,

Elmer

**Comment by joshicraft** [comment]
Thank's for the update, I got what I needed by using the API instead of the require('@sendgrid/mail') lib.  :)
