### ISSUE TITLE
setApiKey is not a function using imports

### ISSUE THREAD

**Issue by atellier** [sendgrid/sendgrid-nodejs#840]
#### Issue Summary

When I try to import the mail service, I have the following error: 

> mail_1.MailService.setApiKey is not a function

#### Example code

```
import {MailService} from '@sendgrid/mail';
MailService.setApiKey('myKey');
```

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* `"@sendgrid/mail":` "^6.3.1" in package.json
* ts-node v7.0.1, node v11.0.0, typescript v3.1.1

Any help or pointers would be great. Trying to use **require()** as documented gave me the error and **new MailService()** would not work either. Thanks!

**Comment by thinkingserious** [comment]
Hello @atellier,

Please feel free to re-open if you still need some help.

With Best Regards,

Elmer

**Comment by kalahari** [comment]
I replaced 
`import {MailService} from '@sendgrid/mail';`
with
`import MailService from '@sendgrid/mail';`
and everything worked as expected.

**Comment by kevinsimper** [comment]
The typescript types are not kept up to date and it uses module.exports so to use the types:
"@sendgrid/mail": "^6.4.0",

```
import MailService from "@sendgrid/mail/src/mail";
```

**Comment by prmichaelsen** [comment]
I've tried each of these and still having trouble. 
* node v10.24.1
* @sendgrid/mail ^7.4.5

**Comment by zuhaib446** [comment]
`import { setApiKey, send } from '@sendgrid/mail';
 await setApiKey(process.env.SEND_GRID_API_KEY);
      const mailOptions = {
        from: `"Delores Digital"${process.env.EMAIL_USER}`,
        to: to,
        subject: 'Welcome to Delores Digital',
        html: `<h1>Welcome to Delores Digital</h1>
             <p>${otp} is your otp for Login.Please Enter the OTP to proceed.</p>`,
      };
      await send(mailOptions);
`
I have the same issue but this code works for me
