### ISSUE TITLE
Subject not being set if using Dynamic templates

### ISSUE THREAD

**Issue by nyel-dev** [sendgrid/sendgrid-nodejs#843]
I was trying to add subject for my email with dynamic templates but it is not working. Is this a known bug already? Can you suggest any workarounds for this issue?

template code:
```
<html>
<head>
  <title></title>
</head>
<body>
  <p> Hello <span>{{test_name}}!</span></p>
</body>
</html>
```

send mail function:
```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(settings.sendgrid.api_key);
sgMail.setSubstitutionWrappers('{{', '}}');

const msg = {
    to: 'test@email.com',
    from: settings.sendgrid.from,
    subject: 'Test Subject',
    templateId: settings.sendgrid.template_id,
    dynamic_template_data: {
	test_name: 'Testing Name'
    },
};

sgMail.send(msg);
```

**Comment by 10kc-zack** [comment]
Same as #834

**Comment by nyel-dev** [comment]
@10kc-zack I see. It is a known issue then. 

By the way, what workaround did you do to fix it?

**Comment by 10kc-zack** [comment]
@nyel-dev Setting the template's subject on SendGrid website works. The problem is that it seems that SendGrid's API does not let you supply a template when you trigger a dynamic template.

**Comment by thinkingserious** [comment]
Hello @nyel-dev,

I believe in the transactional template you would set the subject to be {{ subject }}, then in your code you set `data.subject` to be `"[TEST] My Email Subject"`.

Does that work for you?

With Best Regards,

Elmer

**Comment by jlouie** [comment]
Hi @thinkingserious, hoping you may have additional insight.

I am transitioning from a legacy template to the transactional template and I am experiencing this same issue now (sendgrid-nodejs v6.3.1, Node: v8.11.4) even after replacing the transactional template subject field with `{{subject}}`.  I have not explicitly set the substitution wrappers via `setSubstitutionWrappers()` and have just fallen back on the default handlebars set (although I did try setting those as well while testing).

I've confirmed I'm passing a `subject` property (no quotes or special characters) as `msg.subject` in my first test case, `msg.dynamic_template_data.subject` in my second test case and with both set for my third test case and the resultant emails received still do not have the subject replaced as I would expect.  The email subject shows "(no subject)".

Testing the template itself on the sendgrid site in Preview mode and setting the Test Data, does replace the text as expected though.

Any help would be appreciated.  Thanks!

**Comment by jlouie** [comment]
> Hello @jlouie,
> 
> Here is a [complete example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/transactional-templates.md). I hope that helps!
> 
> With Best Regards,
> 
> Elmer

@thinkingserious: Unfortunately, it doesn't.  I'm still experiencing a missing Subject line in the email sent/received, just like @nicholasess.

**Comment by thinkingserious** [comment]
Hello @jlouie,

Does your subject area look something like this in the UI?

![screen shot 2019-01-24 at 1 30 06 pm](https://user-images.githubusercontent.com/146695/51709821-486ed500-1fdc-11e9-9f88-ef72d3b52787.png)

With Best Regards,

Elmer

**Comment by nyel-dev** [comment]
By the way I was able to solve this problem by using the Set Subject on the Sendgrid template interface.

**Comment by nicholasess** [comment]
I suggest that the settings change to the menu like code,  test data.
![image](https://user-images.githubusercontent.com/3238901/51791627-2cf6fc00-218d-11e9-9d83-0e6f689e7e12.png)

The place where is the settings, is hidden :/

**Comment by thinkingserious** [comment]
Thanks for the feedback @nicholasess! I will pass it on to the design team.

**Comment by pavelpashkovsky** [comment]
We still have this issue

**Comment by marek-survicate** [comment]
@thinkingserious

Why is this issue closed? It is not fixed.

**Comment by pavelpashkovsky** [comment]
I know it might looks weird, but guys make sure you don't have opened windows or tabs with same screen. Sendgrid ui has autosave which can rewrite all data which you saved before.

**Comment by alyak46141414** [comment]
use in subjects {{subject}}

and send as variable like other variables , 

this way it work .

**Comment by kelyvin** [comment]
Damn I was stuck on this issue for so long because I thought I was following the docs and thought I did something wrong. Especially since I'm migrating from legacy templates, I thought the API would stay the same. 

Are there any plans to update the documentation to `v3/mail/send` to properly reflect this change?

**Comment by s3tjan** [comment]
The only way I was able to solve this issue was with _triple-stash_:

`{{{ subject }}}`

According to this article https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/transactional-templates.md

**Comment by russell07** [comment]
Can confirm using triple instead of double curly braces in the subject field works

**Comment by niklas-b** [comment]
Whenever I save the triple curlys or any other code in the subject line, the code reverts back automatically after a few minutes to the standard <%subject%>. 

Is anyone else having the same issue?

**Comment by harveyramer** [comment]
> Is anyone else having the same issue?

I have seen something like this when I had two windows open. SendGrid auto-saves, so if you have two windows open, they will cancel each other out.

**Comment by strongSoda** [comment]
The way it worked for me:

use in subject filed in SendGrid UI: `{{{subject}}}`

send `"subject": "test"` in `message.dynamic_template_data`

**Suggestion**: You guys should really work on your docs. I mean really they are so scattered and bits and pieces are outdated.

**Comment by tcukanoot** [comment]
Triple brackets is still working, I'm just checking to see if that is still the official solution.

Thanks!

![image](https://user-images.githubusercontent.com/37633617/97900011-b55de580-1cff-11eb-8fcc-d8cab64157c6.png)

**Comment by childish-sambino** [comment]
@tcukanoot Yes.

**Comment by andreieuganox** [comment]
Please do re-open issue! The documents still are not correct suggesting `subject` to be set on the top level of the request. However, it must be included in `dynamic_template_data` and subject in template must be set as `{{subject}}` or any other dynamic key. This is open from 2018 and no any changes in documentation introduced since!

**Comment by psdh** [comment]
I get a 400 request error from the server when I'm trying to use substitutions or dynamic_template_data

Please fix your docs. dynamic_template_date shouldn't be valid based on the https://github.com/sendgrid/sendgrid-python/blob/main/use_cases/kitchen_sink.md and the v3 documentation
Yet people are reporting that it works for them

what's going on? 👍

**Comment by RIGUPTA2** [comment]
> The way it worked for me:
> 
> use in subject field in SendGrid UI: `{{{subject}}}`
> 
> send `"subject": "test"` in `message.dynamic_template_data`
> 
> **Suggestion**: You guys should really work on your docs. I mean really they are so scattered and bits and pieces are outdated.

How to do it in PHP. Please share the code!

**Comment by UlyssesInvictus** [comment]
Are the docs currently just incorrect in suggesting that subject be sent as a top level parameter then?

**Comment by sshah98** [comment]
> The way it worked for me:
> 
> use in subject field in SendGrid UI: `{{{subject}}}`
> 
> send `"subject": "test"` in `message.dynamic_template_data`
> 
> **Suggestion**: You guys should really work on your docs. I mean really they are so scattered and bits and pieces are outdated.

This worked for me!

**Comment by andretti1977** [comment]
When i used triple bracket i was still missing the fact that **subject** property must be placed under dynamic_template_data and not at higher level as wrongly stated in docs

**Comment by ChitrangWhiteblink** [comment]
Is there any way to put variable in mail subject ?

**Comment by heymartinadams** [comment]
SendGrid’s greatest weakness is its scattered documentation. It’s awful.

> **Suggestion**: You guys should really work on your docs. I mean really they are so scattered and bits and pieces are outdated.

**Comment by cocuba** [comment]
> > The way it worked for me:
> > use in subject field in SendGrid UI: `{{{subject}}}`
> > send `"subject": "test"` in `message.dynamic_template_data`
> > **Suggestion**: You guys should really work on your docs. I mean really they are so scattered and bits and pieces are outdated.
> 
> This worked for me! Your doc should look something like:
> 
> ```
> const msg = {
>     to: toEmail,
>     from: "email",
>     templateId: "tempateId",
>     dynamic_template_data: {
>       subject: "subjectHere",
>     },
>   };
> 
> sendGridEmail
>     .send(msg)
>     .then(() => console.log("email sent"))
>     .catch((error) => console.error(error.toString()))
> ```

this works with 
{{{subject}}} in template in sengrid web

**Comment by speix** [comment]
November 2021, still not working according to the documents

**Comment by yanghuanqun-bst** [comment]
I notice the subject is always use dynamic template setting from official 
`message = Mail(
    from_email=FROM_EMAIL,
    to_emails=TO_EMAILS,
    subject='a test subject'
)
`
The param "subject" in above code is not working

**Comment by breakline87** [comment]
For me when using {{subject}} on the template page in the subject field, then setting:

mail.getPersonalization().get(0).addDynamicTemplateData("subject", "MyCoolSubject");

Worked

**Comment by yanghuanqun-bst** [comment]
Thanks!  I have solved the problem

**Comment by pike-msonda** [comment]
@breakline87 solution solved the problem for me.

`{
      from: "admin@test.com",
      template_id: "d-xxx",
      personalizations: [
        {
          to: [{email: "test@test.com"}],
          dynamic_template_data: {
           username: "test",
            subject: message.subject,
          },
        },
      ],
    };`
