### ISSUE TITLE
dynamicTemplateData should support object and array, not only strings

### ISSUE THREAD

**Issue by becuz** [sendgrid/sendgrid-nodejs#856]
#### Issue Summary

MailData type support only string values, while Handlebars support JSON.
In the Transactional Templates it's possible to have "Hello, {{obj.field}}!".
I tried myself using Test Data in Transactional Templates Preview. Also it is stated in the official documentation at https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/ and https://sendgrid.com/docs/ui/sending-email/using-handlebars/

In MailData instead, the field personalizations.dynamicTemplateData has type { [key: string]: string; };
As values we are limited to string, making it practically impossible to code conditionals or multi language templates. It also force to update the code whenever we want to add a field in the template, while we could simply pass the entire object.

* sendgrid-nodejs Version: 6.3.1

**Comment by thinkingserious** [comment]
Thanks for bringing this to our attention @becuz! Great catch!

I have added this to our backlog and exposed the issue to our community with appropriate tags.

**Comment by childish-sambino** [comment]
Fixed by #939
