### ISSUE TITLE
Types are not exported

### ISSUE THREAD

**Issue by ryanvolum** [sendgrid/sendgrid-nodejs#857]
#### Issue Summary

It's great that this library is typed, as it allows intellisense to help developers understand the shape of your API! Unfortunately for TypeScript developers who want to use your library, those types don't seem to be exported. Notably, having access to the `MailService` and `MailData` types would make it easier for TS developers to describe the shape of their applications. 

My specific scenario is that I want to create my SendGrid client and pass it into other app components that will use it (think dependency injection). Those components _shouldn't_ be spinning up their own client, as they _shouldn't_ have to be aware of my environment variables (in this case the sendgrid api key). If I'm going to pass a SendGrid client around, the components that receive it should be able to type their expected parameters. Hardcore TypeScript devs turn a flag on that requires _everything_ to be typed. 

Let me know if you need help with this! I'm more than happy to contribute a PR. 

#### Steps to Reproduce

1. Create a function or class that takes a SendGrid `MailService` or `MailData`
2. Try to type that parameter

#### Technical details:

* sendgrid-nodejs Version: 6.3.1
* Node.js Version: v10.13.0

**Comment by thinkingserious** [comment]
Hello @ryanvolum,

We would love to have a PR! Thanks for offering to do that 😀 

With Best Regards,

Elmer

**Comment by scsper** [comment]
@ryanvolum is this something you're still working on?

**Comment by jdforsythe** [comment]
I was just looking at this and it appears to be fixed on `@sendgrid/mail` v7.1.1

```ts
import * as mailService from '@sendgrid/mail';

mailService.setApiKey(process.env.SG_API_KEY);

async function sendMessage(data) {
  const message: mailService.MailDataRequired = {}; // this is the type

  return mailService.send(message);
}
```

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-nodejs/pull/1102

**Comment by jdforsythe** [comment]
I take that back. TSlint wasn't complaining but it doesn't compile with tsc.

Here are the attempts I made and the results:

```ts
import * as mail from '@sendgrid/mail';

async function sendMessage(data) {
  mail.setApiKey();
  const message: mail.MailDataRequired = {};
  return mail.send(message);
}
```

```txt
error: TS2503: Cannot find namespace 'mail'.

mail.MailDataRequired
~~~~
```

```ts
import { MailService, MailDataRequired } from '@sendgrid/mail';

async function sendMessage(data) {
  MailService.setApiKey();
  const message:MailDataRequired = {};
  return MailService.send(message);
}
```

```txt
Module "......./@sendgrid/mail" has no exported member "MailService"

import { MailService, MailDataRequired } from '@sendgrid/mail';
         ~~~~~~~~~~~

Module "......./@sendgrid/mail" has no exported member "MailDataRequired"

import { MailService, MailDataRequired } from '@sendgrid/mail';
                     ~~~~~~~~~~~~~~~
```

Also, tslint does complain about that one above because MailService is a type and doesn't have methods on it.

```ts
import { send, setApiKey, MailDataRequired } from '@sendgrid/mail';

async function sendMessage(data) {
  setApiKey();
  const message: MailDataRequired = {};
  return send(message);
}
```

```txt
Module "......./@sendgrid/mail" has no exported member "MailDataRequired"

import { MailService, MailDataRequired } from '@sendgrid/mail';
                     ~~~~~~~~~~~~~~~
```

```ts
import mail, { MailDataRequired } from '@sendgrid/mail';

async function sendMessage(data) {
  mail.setApiKey();
  const message: MailDataRequired = {};
  return mail.send(message);
}
```

```txt
Module "......./@sendgrid/mail" has no exported member "MailDataRequired"

import { MailService, MailDataRequired } from '@sendgrid/mail';
                     ~~~~~~~~~~~~~~~
```

I also tried combinations of `import mail = require('@sendgrid/mail')` from reading [the docs](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) but to no avail.

Is there a working example using the commit pushed in #1102 [commit](https://github.com/sendgrid/sendgrid-nodejs/pull/1102/commits/eadee1173ae1fa9d61b0b8271211ea75dc5d295c#diff-0ab4f6d710cac1c2f8b58f99841c835fR42-R47)>

I think it would be more properly exported like:

```ts
declare const mail: MailService;

export {mail, MailService, MailDataRequired};
```

**Comment by childish-sambino** [comment]
Something like this works for me:

```
import { MailDataRequired, MailService } from "@sendgrid/mail";

async function sendMessage(message: MailDataRequired) {
    mailer = new MailService();
    mailer.setApiKey("SG.123");
    return mailer.send(message);
}
```

The `mail` export was to provide some weird backward-compatibility support for the singleton `MailServer` in vanilla JS (without getting type warnings if you've set up tsconfig). It should just be ignored in TS.

**Comment by jdforsythe** [comment]
@childish-sambino with TypeScript 3.4.5 and @sendgrid/mail 7.1.1 that code gives me these errors:

```txt
Module "......./@sendgrid/mail" has no exported member "MailService"

import { MailService, MailDataRequired } from '@sendgrid/mail';
         ~~~~~~~~~~~

Module "......./@sendgrid/mail" has no exported member "MailDataRequired"

import { MailService, MailDataRequired } from '@sendgrid/mail';
```

**Comment by childish-sambino** [comment]
Yup, looks like `3.7.2` is the oldest version where it works.
