### ISSUE TITLE
How to set up webhook for dynamic template emails

### ISSUE THREAD

**Issue by guptaluv99** [sendgrid/sendgrid-nodejs#861]
#### Issue Summary

We use sendgrid to email our customers and we store events against all the emails sent to get an insight of how our marketing and promotional emails are doing. But when we started using some of dynamic template emails we are unable to store events against them. Please let us know any api ref doc link or some useful resource which can help in setting up a webhook for events on dynamic template emails.
Thanks!

#### Technical details:

* sendgrid-nodejs Version: master
* Node.js Version: 6.x

**Comment by aroach** [comment]
Hi @guptaluv99 -- This doesn't sound right to me, I'd recommend reaching out to our Support team (support.sendgrid.com) to double-check this behavior.
