### ISSUE TITLE
Not able to get the template list

### ISSUE THREAD

**Issue by jem890** [sendgrid/sendgrid-nodejs#863]
![image](https://user-images.githubusercontent.com/4973274/50404801-978ed380-07ac-11e9-9713-fb72454bc8ab.png)
Hi, when I try to get the template list, the api returns only the legacy templates, not the regular transactional templates.

Could you please help?
Thanks

**Comment by thinkingserious** [comment]
Hello @jem890,

Please use `/v3/templates?generations=legacy,dynamic` for the `url` value if you want to get all templates. If you just want the newer templates, please use `/v3/templates?generations=dynamic`. 

Thanks!

With Best Regards,

Elmer

**Comment by jem890** [comment]
Many thanks, it works as expected. Great support.
