### ISSUE TITLE
Operator incompatible errors when using client with /messages endpoint

### ISSUE THREAD

**Issue by Dygerati** [sendgrid/sendgrid-nodejs#865]
#### Issue Summary

I'm trying to use the _@sendgrid/client_ package to query the `/messages/` endpoint for version 3, and return only activity that has occurred since a certain date/time. Here is my code:
```
const client = require('@sendgrid/client');

client.setApiKey('SG.KEY_HERE');

const messages = qs => client.request({ qs, method: 'GET', url: '/v3/messages' });

(async () => {
   try {
      const [ response, body ] = await messages({
         limit: 20,
         query: 'last_event_time="2018-12-27T23:26:33Z"'
      });

      console.log(`${body.messages.length} results`);
   } catch (e) {
      console.log(e.response.body.errors);
   }
})();

```
This will produce the error `operator > is incompatible with DATETIME, NUMBER`.

I've tried encoding the query property string, as seems to be indicated by the documentation, but that just results in another earlier error: `syntax error: unexpected IDENTIFIER`

I've also tried many variations on the query string - `'last_event_time="2018-12-27T23:26:33Z"'` including without quotes, different dates formats, different operators, etc. Still the same error, but pertaining to the other operator (ex: >).

#### Technical details:

* sendgrid-nodejs Version: master 6.3.0
* Node.js Version: 10.12

**Comment by thinkingserious** [comment]
Hello @Dygerati,

Your code looks correct to me. I've added this to our backlog for further investigation.

In the mean time, you might try experimenting [here](https://sendgrid.com/docs/API_Reference/api_v3.html).

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @Dygerati,

It looks like you may need to specify a [range of dates](https://sendgrid.com/docs/for-developers/sending-email/getting-started-email-activity-api/#filter-by-date-range), could you please try that?

With Best Regards,

Elmer

**Comment by Dygerati** [comment]
Thanks @thinkingserious, I was able to get that to work. Much appreciated. 

Also, wanted to mention that there seems to be an extra `%` in the example directly before the start date.
