### ISSUE TITLE
SendGrid sends e-mails only when connected to specific networks

### ISSUE THREAD

**Issue by KamilSobieraj** [sendgrid/sendgrid-nodejs#869]
Need help with SendGrid. I've created a form that is sending e-mail with an order to a one specific e-mail address. But it works only when I'm connetcted to the internet on my hotspot or to my office network. When I'm connected to any different network with the internet connection nothing happens. I supposed the problem might be in my account settings, but SendGrid Support Member checked it and said it's allright. 
I want that every user, connected to any network in the world could send e-mail through that form. Any idea what's the problem?

Here's a code responsible for creating and sending e-mail request:

```
const express = require("express");
const cors = require("cors");
const sgMail = require("@sendgrid/mail");

require("dotenv").config();
const API_KEY = process.env.REACT_APP_SG_MAIL_API_KEY;
sgMail.setApiKey(API_KEY);

const app = express();

app.use(cors());

app.get("/", (req, res) => {
  res.send("Hello");
});

app.get("/send-email", (req, res) => {
  const { recipient, sender, topic, html, senderName } = req.query;
  let subject = topic + senderName;
  const msg = {
    to: recipient,
    from: sender,
    subject: subject,
    html: html
  };

  sgMail.send(msg).then();
});

app.listen(4005, () => {
  console.log("Server 4005 is listening");
});
```

#### Technical details:

*  @sendgrid/mail: ^6.3.1,
* Node.js Version: v10.4.1

**Comment by thinkingserious** [comment]
Hello @KamilSobieraj,

[Perhaps Postman](https://learning.getpostman.com/docs/postman/sending_api_requests/troubleshooting_api_requests/) can help you troubleshoot your connectivity issues.

With Best Regards,

Elmer
