### ISSUE TITLE
Update documentation to reflect use of promises.

### ISSUE THREAD

**Issue by Berkmann18** [sendgrid/sendgrid-nodejs#870]
It's not an issue per se but more of a README/documentation suggestion.
That concerns the example(s) on the [README](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/README.md)/[USE_CASES](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md).

The basic example is this:
```js
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'test@example.com',
  from: 'test@example.com',
  subject: 'Sending with SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
};
sgMail.send(msg);
```
But reading this makes me think it's a synchronous code which is fine but I didn't realise it was returning a `Promise` until running it live on Node v11.

I'm aware of the [callback version](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#handling-successfailureerrors):
```js
sgMail
  .send(msg, (error, result) => {
    if (error) {
      //Do something with the error
    }
    else {
      //Celebrate
    }
  });
```
And that there's  `then`able use cases [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#kitchen-sink---an-example-with-all-settings-used) and [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#implement-the-hello-email-appjs-file) that uses:
```js
//...
sgMail
  .send(msg)
  .then(() => console.log('Mail sent successfully'))
  .catch(error => console.error(error.toString()));
```
But if someone runs an async code without rejection handling (so not using either `try { await ... } catch (err) { ... }` in ES8 or `Promise.catch(...)` in ES6) it can be noisy and possibly leave room for bugs and errors if someone were to use the package without a proper error handling mechanism.

So for example having this:
- ES6
```js
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'test@example.com',
  from: 'test@example.com',
  subject: 'Sending with SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
};
sgMail
  .send(msg)
  .then(() => {}, console.error); //or .then(() => {}).catch(console.error)
```
- ES8
```js
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'test@example.com',
  from: 'test@example.com',
  subject: 'Sending with SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
};

(async () => {
  try {
    await sgMail.send(msg);
  } catch (err) {
    console.error(err.toString());
  }
})();
```

#### Technical details:

* `@sendgrid/mail@6.3.1`
* Node.js Version: 11.1.0

**Comment by thinkingserious** [comment]
Great idea @Berkmann18! Thanks for taking the time to make this suggestion. 

I have labeled it appropriately to get this change integrated into our docs.

**Comment by Berkmann18** [comment]
@thinkingserious You're welcome.

**Comment by Sammy-White** [comment]
Thanks man this really helped me to fix an issue with my code. 

Thanks a lot.

**Comment by Berkmann18** [comment]
@Sammy-White No problem, I'm glad I helped.

**Comment by ogrotten** [comment]
So I was digging around to see if this was promise-able or chainable. Nothing says it is, or even hints to it . . . and then I tripped across this issue.

It's quite a missed boat.

**Comment by Berkmann18** [comment]
@ogrotten Yup, see #877.
