### ISSUE TITLE
Protecting Endpoints in the Subscription Widget Package

### ISSUE THREAD

**Issue by adamsoffer** [sendgrid/sendgrid-nodejs#873]
In the subscription widget package, I was wondering, is there anything stopping someone from posting to the `/signup` endpoint and bypassing a user's confirmation link in the email?

**Comment by Berkmann18** [comment]
You could add a middleware on the route which would check if said user is allowed (say if the credentials/token are/is valid) then you call `next()` in that route which would lead to where `/signup` is pointing towards.

**Comment by adamsoffer** [comment]
Thanks. Is there a token that gets included in the sendgrid webhook or is it possible to include one?

**Comment by adamsoffer** [comment]
Basically, I want the webhook to be allowed to post to the `/signup` endpoint, but no one else.

**Comment by Berkmann18** [comment]
I'm not that familiar with the codebase but I think you _should be able_ to do so.
> Thanks. Is there a token that gets included in the sendgrid webhook or is it possible to include one?
There's your login token which you need to specify to the `sendgrid` package you're using so you could, in theory, get your webhook to use that.

I haven't tried that myself but I think that's at least one way to go about it (feel free to prove me wrong).

I'm not that familiar with the codebase but I think you _should be able_ to do so.
> Thanks. Is there a token that gets included in the sendgrid webhook or is it possible to include one?
There's your login token which you need to specify to the `sendgrid` package you're using so you could, in theory, get your webhook to use that.

I haven't tried that myself but I think that's at least one way to go about it (feel free to prove me wrong).

**Comment by adamsoffer** [comment]
@thinkingserious The way the double opt-in works is when you click the confirmation link in an email, it triggers a sendgrid webhook that makes a post request to the `/signup` endpoint provided in the package. If an access token exists in the webhook post request, I could check if and only proceed only if it's present. Otherwise, I'm not sure the solution described by @Berkmann18 works.

**Comment by adamsoffer** [comment]
BTW I'm referring to the Event webhook. The package utilizes the "click" event described [here](https://sendgrid.com/docs/for-developers/tracking-events/event/).

**Comment by adamsoffer** [comment]
Another potential solution: whitelist the sendgrid IP?

If sendgrid has a known/static IP I could whitelist it and only sign up a user if the webhook originated from this whitelisted IP.

**Comment by thinkingserious** [comment]
Hello @adamsoffer,

[Here are examples](https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html) of what fields the event webhook is expected to return. Perhaps some combination of these could be use to help verify that only our webhook is accepted by your `/signup` endpoint. I'm not sure if you can reliably count on the SendGrid IP to be static. 

Another thought, you could also randomize the `/signup` endpoint to be something like `/signupid=XXXXX` where the XXXXX is only revealed in your opt-in email.

**Comment by adamsoffer** [comment]
Thanks @thinkingserious. Randomizing the `/signup` endpoint is an interesting thought. Although,  anyone can then use that `XXXXX` value to post to the endpoint right? Unless I'm misunderstanding.

**Comment by adamsoffer** [comment]
@thinkingserious Perhaps I could add a query parameter with an access token to the sendgrid webhook and check for it in the `/signup` request handler.

**Comment by adamsoffer** [comment]
Seems like that's best practice. At least[ that's how github](https://developer.github.com/webhooks/securing/) and many others go about securing webhooks. 

So adding `?token=my_token` to the HTTP post url in sendgrid and exporting an environment var that stores this token `export token=my_token`.

I think it might be worth submitting a PR to the package with this change to prevent others who plan on using this package being exposed. Thoughts?

**Comment by adamsoffer** [comment]
@Berkmann18 gotcha. So sendgrid puts all query parameters on the post URL into the body?

**Comment by adamsoffer** [comment]
@Berkmann18 Gotcha. At this point I just need to determine what's the more secure approach. 

Option 1:
Explicitly adding a query parameter to the webhook like so:
![image](https://user-images.githubusercontent.com/555740/51407216-38ad4780-1b29-11e9-8620-c11c1bab2a86.png)

Option 2:
Passing the token as a `custom_arg` to the confirmation email body. (My only concern with this approach is I'm not sure if it would then be exposed to the user).

Or maybe there's a third option I don't know about.

**Comment by Berkmann18** [comment]
@adamsoffer If you want to pass it in the URL it can also be a route param like http://somesite.com/signup/:token which would parse `http://somesite/signup/yourtoken`.
For option 2, you could pass it as a `hidden` field (`<input type="hidden">`).

**Comment by adamsoffer** [comment]
@Berkmann18 passing it as a hidden field to the signup form would expose it to the user which it can then use to bypass the opt-in. I'm thinking option 1 is the way to go.

**Comment by Berkmann18** [comment]
Fair point.

**Comment by thinkingserious** [comment]
Hi @adamsoffer,

If you want to submit a PR documenting your final security solution here that would be great.

@Berkmann18,

Thanks again for your continued support!

**Comment by adamsoffer** [comment]
Will do. Thanks guys!

**Comment by Berkmann18** [comment]
@thinkingserious @adamsoffer You're welcome.
