### ISSUE TITLE
Confused between `substitutions` and `dynamicTemplateData`

### ISSUE THREAD

**Issue by herkulano** [sendgrid/sendgrid-nodejs#874]
#### Issue Summary

I'm confused between `substitutions` and `dynamicTemplateData`.

I only get the `substitutions` or `dynamicTemplateData` to work if I send both! If I take out either of them it doesn't replace the handlebars values in the template.

```js
sgMail
        .send({
          from: { email: 'test@test.com', name: 'Test' },
          personalizations: [
            {
              to: { email: member.email },
              substitutions: {
                memberName: member.name
              },
              dynamicTemplateData: {
                memberName: member.name
              }
            }
          ],
          templateId: '111'
        })
        .then(() => console.log('Mail sent successfully'))
        .catch(error => console.error(error.toString()))
```

#### Technical details:

* sendgrid-nodejs Version: 6.3.1
* Node.js Version: 10.15.0

**Comment by thinkingserious** [comment]
Hello @herkulano,

You would use `dynamicTemplateData` along with our [transactional templates](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/transactional-templates.md). `substitutions` are used with our [legacy templates](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/transactional-legacy-templates.md).

I hope that helps!

With Best Regards,

Elmer

**Comment by danielzen** [comment]
Can someone please update the docs at

https://sendgrid.com/docs/for-developers/sending-email/personalizations 

to mention `dynamic_template_data` where `substitutions` are mentioned? I think this could save a lot of people a lot of time.

Thanks!

**Comment by thinkingserious** [comment]
Hello @herkulano,

Is your issue now resolved?

@danielzen,

Thanks for pointing out that documentation link! (cc @ksigler7 @Whatthefoxsays)

With Best Regards,

Elmer

**Comment by herkulano** [comment]
Not really, as I mentioned for some reason it only works if I add both values if I take either one it doesn't work.

I've since moved away from sendgrid so I won't be able to follow up on this. 

Thank you for your support.

**Comment by thinkingserious** [comment]
Thanks for the response @herkulano,

If you choose to come back, I'm happy to further assist.

**Comment by formster-biz** [comment]
@thinkingserious 

and here... https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send

**Comment by iudelsmann** [comment]
Still facing this issue in version 6.3.1. Workaround is to add a empty object as the `substitutions` value.

**Comment by thinkingserious** [comment]
Hello @iudelsmann,

Have you tried using [this example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/transactional-templates.md)?

With Best Regards,

Elmer

**Comment by oopyrj** [comment]
Experiencing same behavior in 6.3.1 as @iudelsmann.

**Comment by skapur1424** [comment]
I'm sorry guys but this really is frustrating. I got it to work now using dynamicTemplateData but why not update the documentation. Otherwise, people like me just waste our time thinking we have done something wrong. Not to mention some endpoints just don't work with the new API (like adding contacts). I chose SendGrid because it's supposed to be developer friendly but it seems like there are so many issues with things you have changed over the years. I also got completely conflicting opinions on ASM vs subscription tracking from multiple support people. I am almost wishing I had gone with MailChimp or something else at this point given the inconsistencies and just plain wrong documentation.

**Comment by skapur1424** [comment]
Here is the wrong documentation that needs an update to save some other person some time in the future. Both these use 'substitutions' which doesn't work:
https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/customization.md
https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/kitchen-sink.md

**Comment by zhyhun-ivan** [comment]
Any updates for documentation? It's still to complicated to find out usage of dynamicTemplateData without docs.

**Comment by childish-sambino** [comment]
I've updated the docs listed by replacing the legacy template parameters with dynamic ones. For examples on using legacy templates, see [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/transactional-legacy-templates.md).

**Comment by chdharm** [comment]
Same error: Substitution is not working.

`{
            from: 'dharmpal@slt.com',
            subject: 'test subject',
            text: 'Text',
            html: html,
            personalizations: [
                {
                    'to': [
                        {
                            'email': 'dharmpal@slt.com',
                            'name': 'John'
                        }
                    ],
                    'subject': 'Example 01',
                    'substitutions': {
                        '-name-': 'John'
                    }
                },
                {
                    'to': [
                        {
                            'email': 'sachin@slt.com',
                            'name': 'Jane'
                        }
                    ],
                    'subject': 'Example 02',
                    'substitutions': {
                        '-name-': 'Jane'
                    }
                }
            ]
        }`


Email is being send but the html substitution variable is not replaces by the value provided.

**Comment by childish-sambino** [comment]
@chdharm Please open a new issue with details about what you're attempting to do. Closed issues are not closely followed.
