### ISSUE TITLE
#with block not working

### ISSUE THREAD

**Issue by aneesshameed** [sendgrid/sendgrid-nodejs#879]
{{#with name}}
  {{first}}, {{second}}
{{/with}}

using #with block in handlebar syntax is not working, it shows positive result while testing in email editor but while making api calls #with block fails.

**Comment by aneesshameed** [comment]
Bellow are the screenshots, #with works in email editor
![TEST DATA](https://user-images.githubusercontent.com/12719773/51878232-fee40880-2394-11e9-9aa6-4ae622b7c593.png)

![HTML Template](https://user-images.githubusercontent.com/12719773/51878289-22a74e80-2395-11e9-8a54-104b8642fa63.png)

TEST DATA Used
{
  "name":{
    "first": "Anees",
    "last": "Hameed"
  },
  "orders": [
    {
      "orderid": 1,
      "item": "apple",
      "price": {
        "currency": "$",
        "amount": 30
      }
    },
    {
      "orderid": 5,
      "item": "mango",
      "price": {
        "currency": "$",
        "amount": 50
      }
    }
  ]
}

I was getting confused. Since it was working in email editor and not working via api. Also documentation doesn't says anything on #with. Please all the list of marksup that are supported and not supported on to documentation. 😊

**Comment by aneesshameed** [comment]
Bellow are the screenshots, #with works in email editor
TEST DATA
![TEST DATA](https://user-images.githubusercontent.com/12719773/51878864-3b186880-2397-11e9-9f39-1fba1b4b1448.png)

HTML Template
![HTML Template](https://user-images.githubusercontent.com/12719773/51878877-49ff1b00-2397-11e9-9d88-a6506bf80f22.png)

TEST DATA Used
{
"name":{
"first": "Anees",
"last": "Hameed"
},
"orders": [
{
"orderid": 1,
"item": "apple",
"price": {
"currency": "$",
"amount": 30
}
},
{
"orderid": 5,
"item": "mango",
"price": {
"currency": "$",
"amount": 50
}
}
]
}

I was getting confused. Since it was working in email editor and not working via api. Also documentation doesn't says anything on #with. Please all the list of marksup that are supported and not supported on to documentation. 😊

**Comment by thinkingserious** [comment]
@aneesshameed,

My apologies, I have found that the #with block is not supported. The UI editor we use is likely using handlebars proper, while our API implementation is a subset. This is why it is not documented.

I have passed along feedback to the team to add support on your behalf. Thank you!

With Best Regards,

Elmer
