### ISSUE TITLE
Not an object provided for data at mergeData

### ISSUE THREAD

**Issue by brandonwk** [sendgrid/sendgrid-nodejs#882]
#### Issue Summary

When following the example provided the following error is provided: 

Error: Not an object provided for data at mergeData (/node_modules/@sendgrid/helpers/helpers/merge-data.js:13:11)

#### Steps to Reproduce

example provided:

const data = [
    { email: 'Testing@email.com',
        first_name: 'teddy',
        last_name: 'ted',
        userType: 'Workshop' }
];
request.body = data;
request.method = 'POST';
request.url = '/v3/contactdb/recipients';
client.request(request)
    .then(([response, body]) => {
        console.log(response.statusCode);
        console.log(response.body);
    })

#### Technical details:

* sendgrid-nodejs Version: 6.3.0
* Node.js Version: 6.7.0

**Comment by thinkingserious** [comment]
Hello @brandonwk,

I think:

```javascript
const data = [
{ email: '[Testing@email.com](mailto:Testing@email.com)',
first_name: 'teddy',
last_name: 'ted',
userType: 'Workshop' }
];
```

should be:

```javascript
const data = { email: '[Testing@email.com](mailto:Testing@email.com)',
first_name: 'teddy',
last_name: 'ted',
userType: 'Workshop' };
```

With Best Regards,

Elmer

**Comment by chapter247-yash** [comment]
Please help me, Even I am facing the same issue.

                        const data = {
                            email:'yash.chapter247@gmail.com',
                            first_name:'Yash'
                        }
                        console.log('data')
                        console.log(data)
                        console.log(typeof data)
                                request.body = data;
                                request.method = 'POST';
                                request.url = '/v3/contactdb/custom_fields';
                                console.log(request)
                                console.log('request')
                                client.request(request)
                                .then(([response, body]) => {
                                  console.log(response.statusCode);
                                  console.log(response.body);
                                  console.log("EMAILWORKING");
                                })

Thanks in advance.

**Comment by chapter247-yash** [comment]
> #### Issue Summary
> When following the example provided the following error is provided:
> 
> Error: Not an object provided for data at mergeData (/node_modules/@sendgrid/helpers/helpers/merge-data.js:13:11)
> 
> #### Steps to Reproduce
> example provided:
> 
> const data = [
> { email: '[Testing@email.com](mailto:Testing@email.com)',
> first_name: 'teddy',
> last_name: 'ted',
> userType: 'Workshop' }
> ];
> request.body = data;
> request.method = 'POST';
> request.url = '/v3/contactdb/recipients';
> client.request(request)
> .then(([response, body]) => {
> console.log(response.statusCode);
> console.log(response.body);
> })
> 
> #### Technical details:
> * sendgrid-nodejs Version: 6.3.0
> * Node.js Version: 6.7.0

Hello Sir,
Did you issue got resolve or find a solution yourself?? Please help. I'm also facing the same issue.

**Comment by thinkingserious** [comment]
Hello @chapter247-yash,

[For the endpoint `/v3/contactdb/custom_fields`](https://sendgrid.api-docs.io/v3.0/contacts-api-custom-fields/create-a-custom-field), you need to specify a `name` and `type` rather than an `email` and `first_name`. 

With Best Regards,

Elmer
