### ISSUE TITLE
String literals not supported ?

### ISSUE THREAD

**Issue by KerimHelal** [sendgrid/sendgrid-nodejs#883]
#### Issue Summary

I just switched to transactional templates and now i see my substitution which is in string literals format is not working anymore (it shows nothing on the email), how to overcome this problem?

#### Steps to Reproduce
{{{content}}} ---> this is the tag on sendgrid template
```
sendEmail({
    templateId: Meteor.settings.template1,
    emails: [user.emails[0].address],
    category: "category 1",
    substitutions: {
      content: `Hello ${getUserFirstName(user.name)},
      <br /><br />
      Lorem Ipsum is simply dummy text of the printing and typesetting,
      <br /><br />
      Lorem Ipsum is simply dummy text of the printing and typesetting`,
      subject: 'Email Subject',
      preheader: '',
    }
```

#### Technical details:

* sendgrid/mail 6.2.1

**Comment by thinkingserious** [comment]
Hello @KerimHelal,

I believe in the SendGrid template you would need: ``{{content}}``. 

Thanks!

With Best Regards,

Elmer
