### ISSUE TITLE
SendGrid shows email without Subject

### ISSUE THREAD

**Issue by tahayazdani** [sendgrid/sendgrid-nodejs#884]
SendGrid shows email without Subject

Hi Everyone,
Here is my issue with SendGrid and seems like it's a bug:
I sent an email with subject(it's not possible send an email without subject), and after that I had a API call for that MessageID and realized that SendGrid showed me blank subject.
Like I said for sure I passed the subject and it's most likely happens with the email got failed, However I had some experience even email even revived and then sendGrid API updated after a day

**Comment by thinkingserious** [comment]
Hello @tahayazdani,

I have a couple of follow up questions:

1. Can you share your code?
2. Are you using dynamic templates.
3. When you say that "SendGrid showed me blank subject", do you mean in your email client?
4. How did you detect that the email failed?

Thanks!

With Best Regards,

Elmer

**Comment by tahayazdani** [comment]
Hey @thinkingserious 
Please see my notes blow 👍 

* Can you share your code?

` var config = JsonConvert.DeserializeObject<Configuration>(Helper.GetFileContent("Config.json"));
            var apiKey = Helper.GetApiKey();
            var client = new SendGridClient(apiKey);
            var msg = new SendGridMessage()
            {
                From = new EmailAddress(config.From, config.FromFullName),
                Subject = subject,
                HtmlContent = body.ToString(),
            };
            msg.CustomArgs = new Dictionary<string, string>()
            {
                {"custom_template_id", custom_template_id}
            };
            msg.AddTo(new EmailAddress(to, !string.IsNullOrEmpty(fullName) ? fullName : to));
            var emailResponse = await client.SendEmailAsync(msg);

            return emailResponse;`

* Are you using dynamic templates.
No , I just have my template(HTML body) , I don't use SendGrid Template 

* When you say that "SendGrid showed me blank subject", do you mean in your email client?
I mean In my sendGrid dashboard UI , it shows me blank subject , it's seems like it's not just subject , sometimes it shows me blank to_address as well .


* How did you detect that the email failed?
I just putted wrong email and checked the dashboard , it shows "not-delivered" status which is fine , but the subject is blank .

Again it's not just happening for subject prop and it's not happening just for failed emails , I had a same example that happened for "delivered" as well , but the funny thing is the email does have subject , but when you call it through API or dashbaord it doesn't show the subject.

Cheers
Taha

**Comment by thinkingserious** [comment]
Hello @tahayazdani,

This is C# code and this is the Node.js repo, do you mind posting this issue at our [C# SDK repo](https://github.com/sendgrid/sendgrid-csharp)?

With Best Regards,

Elmer
