### ISSUE TITLE
Transnational Template getting replace by "-" after sending mail  

### ISSUE THREAD

**Issue by adesai201** [sendgrid/sendgrid-nodejs#885]
I create a transactional template and then trigger a mail from my JAVA code. On the first time when I trigger mail, everything works fine and mail received with proper template and data.
But at the same time, my template HTML is replaced with "-" automatically.
I don't why but I'm not able to understand the workaround for this.

Here is my sample code :

public void sendSurveyResponseNotification(String studyId,String surveyId,String surveyEndTime, String participantId, String surveyName,
			List<NotificationMailResponse> surveyResponse,List<SurveyEmailRecipient> emailList) {
		
		try {
			String emailSubject = "Survey Response Notification";
			String templateId = "-Template ID-";
			Gson gson = new Gson();
			DynamicTemplatePersonalization personalization = new DynamicTemplatePersonalization();
			 
			for(SurveyEmailRecipient emailRecipient : emailList) {
				Email toMail = new Email();
				toMail.setEmail(emailRecipient.getEmail());
				personalization.addTo(toMail);
			}
			personalization.addDynamicTemplateData("subject", emailSubject);
			personalization.addDynamicTemplateData("surveyEndTime", surveyEndTime);
			personalization.addDynamicTemplateData("participantId", participantId);
			personalization.addDynamicTemplateData("surveyName", surveyName);
			personalization.addDynamicTemplateData("surveyResponse", surveyResponse);
			sendmail(templateId, personalization, emailSubject, null);
		}catch(Exception e) {
			
		}
	}

private void sendmail(String templateId, Personalization personalization, String subject, Attachments attachments)
			throws IOException {
		SendGrid sg = new SendGrid(sendGridApiKey);
		Request request = new Request();
		request.setMethod(Method.POST);
		request.addHeader("Content-Type", "application/json");
		request.setEndpoint("mail/send");
		Mail mail = new Mail();
		mail.setTemplateId(templateId);
		mail.setSubject(subject);
		if (attachments != null){
			mail.addAttachments(attachments);
		}
		Email from = new Email();
		from.setEmail(fromMail);
		mail.setFrom(from);
		mail.addPersonalization(personalization);
		request.setBody(mail.build());
		sg.api(request);
	}

Please help me to out this glitch.

**Comment by thinkingserious** [comment]
Hello @adesai201,

This is the repo for our Node.js library, could you please move this issue to our [Java library](https://github.com/sendgrid/sendgrid-java)? Thanks!

With Best Regards,

Elmer
