### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by brycelund** [sendgrid/sendgrid-nodejs#891]
#### Issue Summary

I've been using the @sendgrid/mail library fine until this evening I started getting the error _Client network socket disconnected before secure TLS connection was established_. Not sure how to go about troubleshooting this. Any ideas?

#### Technical details:

* sendgrid/mail Version: 6.3.1
* Node.js Version: v10.11.0

**Comment by aroach** [comment]
@brycelund you might try to connect with our support team https://support.sendgrid.com.  But, it sounds like maybe a firewall or proxy issue?  Did something change upstream in your environment?

**Comment by adamreisnz** [comment]
I have also started to get this error periodically since a couple of weeks ago.

**Comment by adamreisnz** [comment]
Seems to be almost a daily occurrence now

**Comment by thinkingserious** [comment]
Thanks for reporting this @brycelund and @adamreisnz,

I've checked with our support team and they would like for you to [submit a ticket](https://support.sendgrid.com) please. Thank you!

**Comment by adamreisnz** [comment]
Thanks will do

**Comment by rturk** [comment]
I'm also seeing this, we think might be realated with AWS load balancer

**Comment by adamreisnz** [comment]
So far no luck through support for us. They've asked for more details regarding the outbound request, which we can't provide at this stage until we put some more logging in place.

I'm thinking the only thing we recently would have changed, is enabled for all API traffic to go through Cloudflare.

**Comment by thinkingserious** [comment]
Any update on this one @adamreisnz?

**Comment by adamreisnz** [comment]
Not yet, I've had to travel abroad unexpectedly and have not been able to put more logging in place yet.

**Comment by RhianneMoll** [comment]
I suspect it's the same TLS snafu I've been struggling with. AFAICT, Node 10.x uses TLS2.3 by default, which means TLS1 and 1.1 have been deprecated. All things being equal, if the remote server admins have downgraded their TLS requirement, you have to add "secureProtocol: 'TLSv1_method'" to the http request options, or some other value that aligns with what they've done on the server side.

(I stumbled across this post while googling for the same error message, my use case however is connecting to an ancient AFIS system with TLS1.1 security for its SOAP server)

I hope this helps!!!

**Comment by yugasun** [comment]
Does somebody solve this problem?

**Comment by adamreisnz** [comment]
I didn't manage to solve it, but put more logging in place to help the Sendgrid team analyse it if it happens again. However, until now it hasn't re-occurred, so hoping it was a temporary disruption or routing issue.

**Comment by yugasun** [comment]
@aanandjha I wrote a simple [demo](https://github.com/yugasun/node-mutual-ssl-auth) for TLS，this error never comes out.

Node Version: `v10.16.0`

**Comment by Dudeful** [comment]
I'm getting the same error as of today December 27.

**Here's my AWS CloudWatch log:**

```
2020-12-27T22:48:50.073Z	309306e9-0f6a-4105-bcec-0b12580e98e0	ERROR	Uncaught Exception 	{
    "errorType": "Error",
    "errorMessage": "Client network socket disconnected before secure TLS connection was established",
    "code": "ECONNRESET",
    "path": null,
    "host": "api.sendgrid.com",
    "port": 443,
    "stack": [
        "Error: Client network socket disconnected before secure TLS connection was established",
        "    at connResetException (internal/errors.js:609:14)",
        "    at TLSSocket.onConnectEnd (_tls_wrap.js:1547:19)",
        "    at Object.onceWrapper (events.js:420:28)",
        "    at TLSSocket.emit (events.js:326:22)",
        "    at TLSSocket.EventEmitter.emit (domain.js:483:12)",
        "    at endReadableNT (_stream_readable.js:1223:12)",
        "    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
    ]
}
```

I'm using Express to process the request through AWS Lambda. Locally it runs great, but when deployed I get this.

Any thoughts anyone?

**Comment by ethoman** [comment]
I figured out a solution to this. The issue is that Lambda is closing / returning before the request is finalized, so you get that error. To avoid the error, wrap your code in a promise and wait for it to finish like so:

```
await new Promise((resolve, reject) => {
   request(options, function(error, response, body) {
      if (error) {
        reject(error);
        throw new Error(error);
      }
      console.log(body);
      resolve("done");
    });
  });
```

**Comment by ericelliott** [comment]
I had the same issue. [This fixed it for me](https://github.com/sendgrid/sendgrid-nodejs/issues/891#issuecomment-819766766).

**Comment by pandiyanganeshan** [comment]
The mentioned error, I am getting while starting react native project(bundling) ... Any opinions?
