### ISSUE TITLE
Mail with List-Unsubscribe-Post header does not get whitelisted in DKIM headers

### ISSUE THREAD

**Issue by julianlam** [sendgrid/sendgrid-nodejs#893]
#### Issue Summary

I am attempting to integrate one-click unsubscribe to my emails. I have `List-Id` and `List-Unsubscribe` headers set up, and recently added `List-Unsubscribe-Post`, following [RFC8058](https://www.ietf.org/rfc/rfc8058.txt). Unfortunately, Gmail will not show the "Unsubscribe" button.

#4 of the spec specifies:

> 4.  Additional Requirements
> 
>    The message needs at least one valid authentication identifier.  In
>    this version of the specification, the only supported identifier type
>    is DKIM [RFC6376].  Hence, senders MUST apply at least one valid DKIM
>    signature to the message.
> 
>    **The List-Unsubscribe and List-Unsubscribe-Post headers MUST be
>    covered by the signature and included in the "h=" tag of a valid
>    DKIM-Signature header field.**
> 
>    If the message does not have the required DKIM signature, the mail
>    receiver SHOULD NOT offer a one-click unsubscribe for that message.

(Emphasis mine)

Here are the headers as reported by Gmail:
```
List-Id: <digest.2.my.site>
List-Unsubscribe: <https://my.site/email/unsubscribe/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW1wbGF0ZSI6ImRpZ2VzdCIsInVpZCI6MiwiaWF0IjoxNTUwNzAwMTY3LCJleHAiOjE1NTMyOTIxNjd9.gExTDZ4qbbSqClIazz2Cc38tXQY2E-A-LzcvrsFG1rs>
List-Unsubscribe-Post: List-Unsubscribe=One-Click
```

However, here is the DKIM signature, note the missing `List-Unsubscribe-Post` header, although `list-unsubscribe` is present.

`DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=nodebb.org; h=content-transfer-encoding:content-type:from:mime-version:list-id: list-unsubscribe:subject:to; s=s1; bh=ecVCRuV9D20XWPvAhAezXrbVGtbF+HhsiPKNYErwQHw=; `

I have an authenticated domain with SendGrid, and use Automated Security. I believe the missing header in the `DKIM-Signature` field may be the reason why Gmail refuses to show the Unsubscribe button.

#### Technical details:

* sendgrid-nodejs Version: v6.3.1
* Node.js Version: v10.15.1

**Comment by thinkingserious** [comment]
Hello @julianlam,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by fannigurt** [comment]
Any news about this issue? I'm Python SDK user, experienced the same issue - List-Unsubscribe-Post header does not get whitelisted in DKIM headers.
How could I add it via API?

**Comment by julianlam** [comment]
@fannigurt Despite the suggestion from @thinkingserious, the SendGrid team seemingly does not consider this high priority. I have opened a support ticket, and they've essentially passed the buck over to Gmail, and suggested I send `mailto:` instead of `http:` in list-unsubscribe.

So basically, there's not much support for list-unsubscribe-post...?

The ticket: https://support.sendgrid.com/hc/en-us/requests/1941763?flash_digest=73772eec7f0a813f891b294090fb70bea78b85f9

**Comment by fannigurt** [comment]
@julianlam we can make the full message by ourselves and sign it with custom DKIM, but wait, why we need Sendgrid? 😁
Ok, seems like we need to build a new bike: make `mailto:` format and then using `Imbound Parse` hook the unsubscribe message from user client, parse it and make unsubscription in database. Looks strange 🤔

**Comment by VolneiMonteiroRibeiro** [comment]
@julianlam you try?
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=nodebb.org; h=content-transfer-encoding:content-type:from:mime-version:list-id: list-unsubscribe:list-unsubscribe-post:subject:to; s=s1; bh=ecVCRuV9D20XWPvAhAezXrbVGtbF+HhsiPKNYErwQHw=;
