### ISSUE TITLE
ETIMEDOUT 169.45.89.179:443 at TCPConnectWrap.afterConnect 

### ISSUE THREAD

**Issue by leogoesger** [sendgrid/sendgrid-nodejs#896]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

I have been getting time out errors on occasion on my production server. I cannot reproduce the same issue all the time.

> { Error: connect ETIMEDOUT 169.45.89.179:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'connect',
> address: '169.45.89.179', port: 443 } [bugsnag] Reported an unhandled rejection… Error: Error: connect ETIMEDOUT 169.45.89.179:443 at SendGrid.send.then.catch.e (/home/leoqiu/foodnome-api/build/src/utils/emailHelpers.js:143:11)
> 

#### Steps to Reproduce

Here is the code I am using on the node server. It works as usual during development and staging. The ufw rules are the same.

```
export const sendVerifyMail = (to: string, token: string) =>
  SendGrid.send({
    to,
    from: { email: '..' },
    subject: 'Verify you..',
    dynamic_template_data: {
      header: 'Verify your account',
      text:
        'Please use the button below to continue the process.',
      c2a_link: `${serverAddress}/api/user-account/verify?token=${token}`,
      c2a_button: 'Verify'
    },
    template_id: 'd-0f6411434fbc4896bf389e3945affd5d'
  } as any)
    .then(d => d)
    .catch(e => {
      console.log(e);
      throw new Error(e);
    });
```

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 10

**Comment by ad34** [comment]
how did you solved this?

**Comment by menocomp** [comment]
I have the same issue in production and it happens from time to time.
