### ISSUE TITLE
deepmerge needs to be updated to latest version to prevent webpack bug

### ISSUE THREAD

**Issue by celicoo** [sendgrid/sendgrid-nodejs#899]
#### Issue Summary

The current `deepmerge` version doesn't work with Webpack:

```
TypeError: merge is not a function
    at Personalization.deepMergeDynamicTemplateData (/opt/sulvo/cloudflare-app/handlers/.webpack/service/webpack:/node_modules/@sendgrid/helpers/classes/personalization.js:289:1)
...
```

This is a known [issue](https://github.com/TehShrike/deepmerge/issues/137).

#### Steps to Reproduce

1. Setup Webpack
2. Send a transactional email injecting dynamic template data, e.g:

```javascript
import sgMail from '@sendgrid/mail'

sgMail.setApiKey(process.env.SENDGRID_API_KEY)

sgMail
  .send({
    to: 'me@sendgrid.com',
    from: 'no-reply@sendgrid.com',
    templateId: '...',
    dynamicTemplateData: {
      name: '',
    },
  }).catch(console.error)
```

#### Technical details:

* sendgrid-nodejs version: 6.3.1
* Node.js version: 10.15.1

**Comment by thinkingserious** [comment]
Thanks for bringing this to our attention @celicoo! I've added this to the backlog.

**Comment by celicoo** [comment]
@thinkingserious my pleasure, happy to help.

**Comment by celicoo** [comment]
@thinkingserious any update on this?

**Comment by richardcase** [comment]
Is this going to be included in a release soon?

**Comment by adamf** [comment]
Hi, this is blocking sendgrid adoption for us. Any ETA on release?

**Comment by robertsmikej** [comment]
Blocking adoption for us too, please let us know what the status is. Thanks!

**Comment by phu-bc** [comment]
I am getting this issue too :(

**Comment by terryds** [comment]
If currently you're using Webpack, just add this to your webpack config file (I know this is dirty, but it works!).
```
  resolve: {
      alias: {
        deepmerge$: 'deepmerge/dist/umd.js',
      }
  }
```

**Comment by pzhine** [comment]
Note that updating to 6.5.1, which includes #935, didn't work. I had to implement the workaround by @terryds, which worked!

**Comment by tkdan235** [comment]
Also ran into this issue...  giving @terryds's dirty solution a try... come on sendgrid!
