### ISSUE TITLE
Requirement conflict with unsubscribe substitution in a campaign

### ISSUE THREAD

**Issue by wizardlyhel** [sendgrid/sendgrid-nodejs#901]
#### Issue Summary

The requirement of `[[unsubscribe]]` and `<%asm_preferences_raw_url%>` is in conflict of each other.

#### Steps to Reproduce
I tried a couple things.

**Goal:** In a campaign email, I would like to use a custom unsubscribe link with `<%asm_preferences_raw_url%>`

In a `PATCH` campaign api call, I was able to set
```js
    data = {
        ...,
        html_content: '..[[unsubscribe]]..'
        plain_content: '..[[unsubscribe]]..'
        custom_unsubscribe_url: '<%asm_preferences_raw_url%>'
    }
```

**Result:** The `[[unsubscribe]]` tag is replace but `<%asm_preferences_raw_url%>` is not.

This is the raw email content from sending a test.
<img width="664" alt="screen shot 2019-03-06 at 10 12 27 pm" src="https://user-images.githubusercontent.com/2319002/53935981-29dd0e80-405d-11e9-801a-44fa9c18e85e.png">
<img width="667" alt="screen shot 2019-03-06 at 10 12 48 pm" src="https://user-images.githubusercontent.com/2319002/53935983-2c3f6880-405d-11e9-8a23-136b099cf786.png">

The reason I was doing above is because
* `[[unsubscribe]]` is a requirement in the `html_content` and `plain_content`
* Just having `<%asm_preferences_raw_url%>` in `html_content` and `plain_content` gives me campaign unsubscribe requirement error
* I don't want to use an unsubscribe group because if a recipient is on List A and List B, I can only assign one unsubscribe group to a campaign that is directed to multiple list

According to all the documents that I went through, it seems that I should be able to achieve something like this but that is not the case.

**Document Reference**
* https://sendgrid.com/docs/ui/sending-email/recipient-subscription-preferences/
* https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/campaigns.html#-Campaigns
* http://d2w67tjf43xwdp.cloudfront.net/release_notes.html#-Unsubscribe-Tag-Support-for-Transactional-Templates

#### Technical details:

* sendgrid-nodejs Version: release 6.3.1
* Node.js Version: 6.11.5

**Comment by thinkingserious** [comment]
Hello @wizardlyhel,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by wizardlyhel** [comment]
It doesn't help when the help document just takes you in circles and no way to actually contact a support even as a paying customer but thanks for the reply anyways.
