### ISSUE TITLE
How to get messageId from header

### ISSUE THREAD

**Issue by wooyah** [sendgrid/sendgrid-nodejs#904]
We’re using inbound parse to handle messages inside SendGrid. Now we want to work with replying to messages, for which we need to extract the Message-ID from the email.

How do we extract the Message-ID from an email that goes via the inbound parsing? As I do not see it in the request headers.

**Comment by thinkingserious** [comment]
Hello @wooyah,

The Message-ID should be in the headers. Could you please provide a bit more detail so I can try and reproduce?

1. Could you provide a code sample?
2. Are you using [this SDK](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/inbound-mail-parser)?

With Best Regards,

Elmer

**Comment by jerryongit** [comment]
@wooyah 

I found it better to use the following...
  var MailParser = require("mailparser").MailParser;
  var mailparser = new MailParser();
  mailparser.on("end", function(mail_object){
      log(util.inspect(mail_object));     
  });
  mailparser.write(req.body.email);
  mailparser.end();

This requires checking the Inbound Parse setting 'POST the raw, full MIME message'.
You'll find the mail_object has what you need.

**Comment by thinkingserious** [comment]
Thanks for helping out @jerryongit!

I've just edited your comment for readability.

**Comment by wooyah** [comment]
Thanks @jerryongit ,
Your code was really helpful.
I set to use busboy to catch required data from Headers, and now have no problem to get. :)
