### ISSUE TITLE
To field only accepts plain email

### ISSUE THREAD

**Issue by agostonbonomi** [sendgrid/sendgrid-nodejs#905]
#### Issue Summary

When using '@sendgrid/mail' to send any email, the 'to' field only accepts plain email addresses, not name/email format (example: {name:'John Doe', email:'john@doe.com'} ).

#### Steps to Reproduce

```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: { email:'test@example.com', name: 'John Doe' },
  from: 'test@example.com',
  subject: 'Sending with SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};
sgMail.send(msg);
```

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Hello @agostonbonomi,

[Here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/mail/USE_CASES.md#flexible-email-address-fields) are the supported methods of formatting email.

Please let me know if that helps.

Thanks!

With Best Regards,

Elmer

**Comment by agostonbonomi** [comment]
hey @thinkingserious , thanks for this. i missed this in the docs, works fine :)

**Comment by thinkingserious** [comment]
Thank for the follow up @agostonbonomi!
