### ISSUE TITLE
Request Release

### ISSUE THREAD

**Issue by SpainTrain** [sendgrid/sendgrid-nodejs#911]
It appears there are new type defs that have not yet been released - https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/helpers/classes/mail.d.ts

**Comment by thinkingserious** [comment]
Hello @SpainTrain,

We have a release coming within the next few weeks. If you would like to be notified upon release, please [subscribe here](https://dx.sendgrid.com/newsletter/nodejs).

Thank you!

With Best Regards,

Elmer

**Comment by SpainTrain** [comment]
Thanks go the quick turnaround and mailing list link :+1:
