### ISSUE TITLE
Dynamic data does not working with arrays

### ISSUE THREAD

**Issue by AlanFerreiraDias** [sendgrid/sendgrid-nodejs#912]
#### Issue Summary

Using the exact same template as described here: https://github.com/sendgrid/email-templates/tree/master/dynamic-templates/receipt
and the same data as well, does not produce the expected table.

The email is being sent correctly, but the data for the items is being sent empty (trying through the API or with the template builder)

#### Steps to Reproduce

1. Copy code from template and data from here https://github.com/sendgrid/email-templates/tree/master/dynamic-templates/receipt
2. Try it on the template builder
3. Does not show the items

**Comment by thinkingserious** [comment]
Hello @AlanFerreiraDias,

Could you please try the example [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/transactional-templates.md)?

Thanks!

With Best Regards,

Elmer

**Comment by kevduncan** [comment]
@thinkingserious I am experiencing this same issue when using node8, if I run in node6 everything works as expected.

**Comment by kevduncan** [comment]
I solved this issue by upgrading my @sengrid/mail package to the most recent version (6.3.1). I had been experiencing this same issue running a prior version (6.2.1) on a node8 engine. Version 6.2.1 previously worked with node6, but upgrading the engine to node8 without upgrading the package caused the issue.

**Comment by thinkingserious** [comment]
Hello @kevduncan! 

Thanks for helping out :)

**Comment by AlanFerreiraDias** [comment]
@thinkingserious : sorry, I don't see this example that you sent dealing with arrays. Is it the right one?

@kevduncan : unfortunately, on my case, I'm already using @sendgrid/mail 6.3.1 and node8 :/

**Comment by thinkingserious** [comment]
Hello @AlanFerreiraDias,

Can you please share the Ruby code you are using to interact with the template?

Thanks!

With Best Regards,

Elmer
