### ISSUE TITLE
How to send reply mail

### ISSUE THREAD

**Issue by wooyah** [sendgrid/sendgrid-nodejs#914]
Hi, I'm using Inbound-parse webhook. 

When user send reply to specific domain, webhook catches that request, and I can get some infos from headers.

Here are data from headers

```
subject: Re: where is parking?
to: to_mail address
from: from_mail address
messageID: CAFM7W=U=T8nJAW=rwDA1u844h1f_u45mPCi0YvrVa9z0KqieFw@mail.gmail.com
inReplyTo: lWs8clL7ROi0sI23-UdJ-w@ismtpd0008p1maa1.sendgrid.net
references: [ 'lWs8clL7ROi0sI23-UdJ-w@ismtpd0008p1maa1.sendgrid.net' ]
```

With these data, I'd like to send a reply mail for master mail which has 'where is parking?' as a subject.
I created mail instance for a reply with `Re: where is parking?` for subject and sent, but just got 'where is parking?' for subject, and didn't get thread from master mail - just only reply content included.

Here is my code snippet.

```
const sendgridMailHelper = require('sendgrid').mail;
const mail = new sendgridMailHelper.Mail(
        fromEmailInfo,
        `Re: where is parking?`,
        toEmailInfo,
        content
    );

mail.addHeader(new sendgridMailHelper.Header('References', `lWs8clL7ROi0sI23-UdJ-w@ismtpd0008p1maa1.sendgrid.net`))
mail.addHeader(new sendgridMailHelper.Header('In-Reply-To', `lWs8clL7ROi0sI23-UdJ-w@ismtpd0008p1maa1.sendgrid.net`))
```

Have I missed something or set the wrong configuration?

I've checked this issue https://github.com/sendgrid/sendgrid-nodejs/issues/690#issuecomment-393336215 but was not helping me.

Thanks.

**Comment by thinkingserious** [comment]
Hello @wooyah,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by SKempin** [comment]
@wooyah Did you ever find a solution to this? I wish my replies to include the original email content quoted in the body.
