### ISSUE TITLE
@sendgrid/mail not working with Node 9.4.0

### ISSUE THREAD

**Issue by samuelfreiberg** [sendgrid/sendgrid-nodejs#915]
#### Issue Summary

Simple error, but I'm not too familiar with npm so I'm having a hard time. I have a React/Redux ES6 application. I'm getting Node errors when I run my application after I do the following:
1. I installed sendgrid/mail using "npm install --save @sendgrid/mail".
2. "import {MailService} from '@sendgrid/mail'" at the top of the file I wanted to use.
3. npm run dev creates some of the following errors. I read on the git page that this support Node versions 6, 7, or 8. Is there anyway I can get it working for Node 9?
![1](https://user-images.githubusercontent.com/32719011/55832747-104f3c80-5acb-11e9-8df3-648b38193b1d.png)

![1](https://user-images.githubusercontent.com/32719011/55832763-1cd39500-5acb-11e9-97ea-3f6fecd36749.png)
![1](https://user-images.githubusercontent.com/32719011/55832793-2c52de00-5acb-11e9-85a1-ec2289039fe8.png)

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by aroach** [comment]
It looks like you attempting to import sendgrid in your client-side React app.  If so, you really shouldn't do that because you will eventually expose your API Keys to the world.  It's better to implement an API for your React app to hit on your backend, which will then interact with SendGrid.

**Comment by samuelfreiberg** [comment]
> It looks like you attempting to import sendgrid in your client-side React app.  If so, you really shouldn't do that because you will eventually expose your API Keys to the world.  It's better to implement an API for your React app to hit on your backend, which will then interact with SendGrid.

The API key is stored and declared in the backend side of my application. Long story short, once the user presses a button here I was planning on writing something up like...

"import {MailService} from '@sendgrid/mail'"

// In another function in my REACT component
const msg = {
  to: 'test@example.com',
  from: 'test@example.com',
  subject: 'Sending with SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};
sgMail.send(msg);
