### ISSUE TITLE
Critical security vulnerability in sshpk

### ISSUE THREAD

**Issue by lukewlms** [sendgrid/sendgrid-nodejs#917]
#### Issue Summary

The sshpk dependency has a high-severity vulnerability and should be updated as soon as possible.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/19214773/55893671-21618180-5b8f-11e9-92d0-fa68dfe838e0.png">

#### Steps to Reproduce

1. Install @sendgrid/mail latest
2. yarn audit / npm audit

#### Technical details:

* sendgrid-nodejs Version: latest.    "@sendgrid/mail": "^6.3.1",
* Node.js Version: 11 (all versions affected)

**Comment by Hardik500** [comment]
This issue has already been fixed so why not close it.

**Comment by thinkingserious** [comment]
Thanks for the heads up @Hardik500!
