### ISSUE TITLE
Different Attachments to Multiple Recipients 

### ISSUE THREAD

**Issue by sreekanth6495** [sendgrid/sendgrid-nodejs#919]
Issue Summary
Related to issue #352 

I need to send multiple emails with different personalizations and different attachments.

Is this functionality added in the last two years ??

I need to send a single email to multiple recipients but different personalizations and a different attachment file for each recipient.

Thanks

Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

**Comment by thinkingserious** [comment]
Helklo @sreekanth6495,

No, this feature is not available as described. You will need a separate API call for each email.

With Best Regards,

Elmer

**Comment by sreekanth6495** [comment]
Thank you

**Comment by sreekanth6495** [comment]
thank you
