### ISSUE TITLE
I can not send emails with Sendgrid/mail

### ISSUE THREAD

**Issue by The-Caesar** [sendgrid/sendgrid-nodejs#922]
Dear,

I can not send emails :(

I get this response:

{ Error: Bad Request
    at Request.http [as _callback] (...\module\storemonitoring-fa\node_modules\@sendgrid\client\src\classes\client.js:124:25)
    at Request.self.callback (...\module\storemonitoring-fa\node_modules\@sendgrid\client\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (....\module\storemonitoring-fa\node_modules\@sendgrid\client\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (....\module\storemonitoring-fa\node_modules\@sendgrid\client\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  code: 400,
  message: 'Bad Request',
  response: 
   { headers: 
      { server: 'nginx',
        date: 'Thu, 02 May 2019 07:29:09 GMT',
        'content-type': 'application/json',
        'content-length': '204',
        connection: 'close',
        'access-control-allow-origin': 'https://sendgrid.api-docs.io',
        'access-control-allow-methods': 'POST',
        'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
        'access-control-max-age': '600',
        'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' },
     body: { errors: [Array] } } }

sendgrid-nodejs Version: "@sendgrid/mail": "^6.3.1"
Node.js Version: 8.13.0

**Comment by aroach** [comment]
Can you post your code that is throwing this?  Also, if you can inspect `body: { errors: [Array] }` you might have some more clues.  Since it's a 400, it's on the client side, and likely how you're building up the request to the servers.

**Comment by The-Caesar** [comment]
here what i do to send mail i declare:
1- const sgMail = require('@sendgrid/mail');
then i configure my mail with APIKey
2- sgMail.setApiKey(config.sendGridAPIKey);
then i fill my emailsData  with Emails that i want to send depending on my treatment:
3- let emailsData = [];
then i send my emails:
4- sgMail.send(emailsData)

PS: it was to work but not anymore

**Comment by thinkingserious** [comment]
Hello @The-Caesar,

It looks like `emailsData` is of the wrong type. Please see [this example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/single-email-single-recipient.md).

With Best Regards,

Elmer

**Comment by The-Caesar** [comment]
emailsData  is a array of emails wich is filled with hmtl template depends on my treatement as i said before so when i want to send an email i just push my email to  "emailsData" and send them all by
calling "sgMail.send(emailsData)" so in other word i'm sending many email in just one call !!

>

**Comment by aroach** [comment]
Comparing with the example code shared by Elmer, emailsData in your example
should be a JavaScript Object and not an array.  The to property of the JS
Object can be an array.

let emailsData = { to: [], ... }

Please give that a try and let us know!

**Comment by izznogooood** [comment]
I can verify this:

```javascript
const sgMail = require('@sendgrid/mail');

const sendGridAPIKey = someMagic();
sgMail.setApiKey(sendGridAPIKey);

const sendWelcomeEmail = async (email, name) => {
    try {
        await sgMail.send({
            to: email,
            from: 'fancy@email.not',
            subject: 'Welcome to my site',
            text: `Welcome to the app, ${name}.`,
            html: ''
        });
    } catch (e) {
        console.log(e);
    }
};
```
Output:

```
{ ResponseError: Bad Request
    at Request.http [as _callback] (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at Request.emit (events.js:193:13)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:281:20)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
  code: 400,
  message: 'Bad Request',
  response:
   { headers:
      { server: 'nginx',
        date: 'Wed, 08 May 2019 19:38:58 GMT',
        'content-type': 'application/json',
        'content-length': '219',
        connection: 'close',
        'access-control-allow-origin': 'https://sendgrid.api-docs.io',
        'access-control-allow-methods': 'POST',
        'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
        'access-control-max-age': '600',
        'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' },
     body: { errors: [Array] } } } // <-- Dont know how to parse this.
```

**Comment by Full-Stack-Zach** [comment]
@izznogooood, I tried this same block of code in my application. Not getting any errors but the emails are not sending at all.

**Comment by izznogooood** [comment]
yup, something's up...

I use it for testing so not as bad for me. But happy to help.

**Comment by Full-Stack-Zach** [comment]
I've been working on this for a while now and can't get SendGrid to consistently send emails any way I try in NodeJs. Currently looking at other service providers because I need email functionality to start working soon. Let me know if you figure out how to get it working. I'd love to stick with this if it works.

**Comment by aroach** [comment]
The code block provided never calls the `sendWelcomeEmail()` function, and so it never executes.

But, after fixing that, this code worked (note that I removed the empty `html` property:

Tested using node v8.12.0.

```
const sgMail = require('@sendgrid/mail');

const sendGridAPIKey = 'SG.xxx.yyy';
sgMail.setApiKey(sendGridAPIKey);

const email = 'me@gmail.com';
const name = 'Ashley Roach';

const sendWelcomeEmail = async (email, name) => {
    try {
        await sgMail.send({
            to: email,
            from: 'fancy@email.not',
            subject: 'Welcome to my site',
            text: `Welcome to the app, ${name}.`,
        });
    } catch (e) {
        console.log(e);
    }
};

sendWelcomeEmail(email, name);
```

**Comment by thinkingserious** [comment]
Hello everyone, 

@izznogooood,

Please see [this documentation](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/success-failure-errors.md) on how to capture the error message.

@The-Caesar,

Could you either provide a full code sample or the value of the `msg` you pass to `.send`?

@Full-Stack-Zach,

Could you please provide some code that I can use to try and reproduce your issue?

FWIW, here is what works for me using `@sendgrid/mail@6.4.0`:

```javascript
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'ethomas@twilio.com',
  from: 'dx@sendgrid.com',
  subject: 'Hello world',
  text: 'Hello plain world!'
};

sgMail
  .send(msg)
  .then(() => {
    //Celebrate
    console.log('Email Sent!');
  })
  .catch(error => {

    //Log friendly error
    console.error(error.toString());

    //Extract error msg
    const {message, code, response} = error;

    //Extract response msg
    const {headers, body} = response;
  });
```

I hope this is helpful.

With Best Regards,

Elmer

**Comment by izznogooood** [comment]
@thinkingserious 
```javascript
console.log(e.response.body);

// message
{ errors:
   [ { message:
        'The content value must be a string at least one character in length.',
       field: 'content.1.value',
       help:
        'http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.content.value' } ] }
```

So in my case it was as simple as adding a space in my html string (or remove it)... But I dont belive I've done that before. But thank you.

@Full-Stack-Zach 
I assumed you'd call the function, that was my bad. Sorry about that.

**Comment by The-Caesar** [comment]
here an object from the array emailsData:
{  
   from:'no-reply-stores-monitoring@xxxxx.xxx',
   to:'emails',
   subject:'[Stores-monitoring] Norges_Gruppen - STORE_M14',
   html:'   <HTML>\n<HEAD>\n</HEAD>\n<BODY> \n\t<div style="left:0   ; position:   absolute; top:25   px; width:100   %;">\n\t\t<p> &nbsp;</p>\n\t\t<table width="100%" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="background-color:   #ffffff">\n\t\t\t<tbody>\n\t\t\t\t<tr>\n\t\t\t\t\t<td align="center" style="text-align:   left">\n\t\t\t\t\t\t<table width="600" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" \n\t\t\t\t\t\tstyle="background-color:   #ffffff; color:   #333333; font-family:   \'Georgia\'; \n\t\t\t\t\t\tfont-size:12   px; width:600   px; padding-bottom:0   px; border-top:0   px none transparent; \n\t\t\t\t\t\tborder-right:0   px none transparent; border-bottom:0   px none transparent; border-left:0   px none transparent; padding-top:0   px; margin:0   auto;">\n\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t\t<table width="600" cellspacing="0" cellpadding="0" border="0" id="topMessageWrapperMainTable">\n\t\t\t\t\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t\t\t<td width="100%" style="color:   #333333; font-family:   \'Georgia\'; font-size:12   px;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t<table width="100%" cellspacing="0" cellpadding="0" border="0">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width="400" valign="top" style="border:0   px none transparent; color:   #333333; font-family:   \'Georgia\'; font-size:12   px;" class="responsiveColumn">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width="100%" cellspacing="0" cellpadding="0" border="0">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td
valign="top" style="padding-top:0   px; padding-right:0   px; padding-bottom:0   px; padding-left:0   px; color:   #333333; font-family:   \'Georgia\'; font-size:12   px;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style="border-color:   #c2d9e7; display:   block;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width="100%" cellspacing="0" cellpadding="0" border="0" style="word-wrap:   break-word; table-layout:   fixed;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td bgcolor="#FFFFFF" style="background-color:   #FFFFFF; padding-top:3   px; padding-right:3   px; padding-bottom:3   px; padding-left:3   px; border-top:0   px none transparent; border-right:0   px none transparent; border-bottom:0   px none transparent; border-left:0   px none transparent; color:   #333333; font-family:   \'Georgia\'; font-size:12   px;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style="margin-bottom:0   ; margin-left:0   ; margin-right:0   ; margin-top:0   ; padding:0   ;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width="300" valign="top" style="border:0   px none transparent; color:   #333333; font-family:   \'Georgia\'; font-size:12   px;" class="responsiveColumn">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width="100%" cellspacing="0" cellpadding="0" border="0">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td valign="top" style="padding-top:0   px; color:   #333333; font-family:   \'Georgia\'; font-size:12   px;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style="border-color:   #c2d9e7; display:   block;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width="100%" cellspacing="0" cellpadding="0" style="word-wrap:   break-word; table-layout:   fixed;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style="padding-top:3   px; padding-right:3   px; padding-bottom:3   px; padding-left:3   px; border-top:0   px none transparent; border-right:0   px none transparent; border-bottom:0   px none transparent; border-left:0   px none transparent; color:   #333333; font-family:   \'Georgia\'; font-size:12   px;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style="margin-bottom:0   ; margin-left:0   ; margin-right:0   ; margin-top:0   ; padding:0   ; float:   right;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td width="100%" valign="top" bgcolor="transparent" style="border:0   px none transparent; background-color:   transparent; color:   #333333; font-family:   \'Georgia\'; font-size:12   px;">\n\t\t\t\t\t\t\t\t\t\t\t<table width="100%" cellspacing="0" cellpadding="0" border="0">\n\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td valign="top" style="padding-top:15   px; color:   #333333; font-family:   \'Georgia\'; font-size:12   px;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style="display:   block; border-color:   #c2d9e7;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width="100%" cellspacing="0" cellpadding="0" style="word-wrap:   break-word; table-layout:   fixed;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td bgcolor="transparent" style="background-color:   transparent; padding-top:12   px; padding-right:0   px; padding-bottom:0   px; padding-left:0   px; border-top:0   px none transparent; border-right:0   px none transparent; border-bottom:0   px none transparent; border-left:0   px none transparent; color:   #333333; font-family:   \'Georgia\'; font-size:12   px;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style="text-align:   justify; margin-bottom:0   ; margin-left:0   ; margin-right:0   ; margin-top:0   ; padding:0   ;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span style="font-size:26   px;"><span style="font-family:times new roman,
   times,
   serif;">Hello,
   </span></span></p>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style="text-align:   justify; margin-bottom:0   ; margin-left:0   ; margin-right:0   ; margin-top:0   ; padding:0   ;">&nbsp;</p>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style="text-align:   justify; margin-bottom:0   ; margin-left:0   ; margin-right:0   ; margin-top:0   ; padding:0   ;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span style="font-family:arial,
   helvetica,
   sans-serif;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tMatchings events with batch matchings number exceeds (<strong>$datas.errorRate %</strong>)\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style="border-color:   #c2d9e7; margin-left:20   ;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width="100%" cellspacing="0" cellpadding="0" border="0" style="word-wrap:   break-word; table-layout:   fixed; color:   #333333; font-family:arial,
   helvetica,
   sans-serif;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td bgcolor="transparent" style="background-color:   transparent; padding-top:12   px; padding-right:0   px; padding-bottom:0   px; padding-left:0   px; border-top:0   px none transparent; border-right:0   px none transparent; border-bottom:0   px none transparent; border-left:0   px none transparent; color:   #333333; font-family:   \'Georgia\'; font-size:12   px;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style="text-align:   justify; margin-bottom:0   ; margin-left:0   ; margin-right:0   ; margin-top:0   ; padding:0   ;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span style="font-family:arial,
   helvetica,
   sans-serif;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&bull;&nbsp;Number of matching events\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td bgcolor="transparent" style="background-color:   transparent; padding-top:12   px; padding-right:0   px; padding-bottom:0   px; padding-left:0   px; border-top:0   px none transparent; border-right:0   px none transparent; border-bottom:0   px none transparent; border-left:0   px none transparent; color:   #333333; font-family:   \'Georgia\'; font-size:12   px;">\t\t\t                                          \t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style="text-align:   justify; margin-bottom:0   ; margin-left:0   ; margin-right:0   ; margin-top:0   ; padding:0   ;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span style="font-family:arial,
   helvetica,
   sans-serif;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$datas.eventsCount\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>&nbsp; </div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style="text-align:   justify;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span style="font-family:arial,
   helvetica,
   sans-serif;">Best regards,
   </span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div> \n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style="padding-bottom:10   px; padding-top:5   px;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<strong><span style="font-family:arial,
   helvetica,
   sans-serif;">Store-monitoring Team</span></strong>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span style="">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span style="font-family:arial,
   helvetica,
   sans-serif; font-size:34   px; font-weight:   bold;">ses </span><span style="font-family:arial,
   helvetica,
   sans-serif;font-size:34   px; font-weight:   lighter;">imagotag</span> \n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>&nbsp; </div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div> \n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style="text-align:   justify;">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>&nbsp; </div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div> \n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>&nbsp; </div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span style="font-family:arial,
   helvetica,
   sans-serif;"><i>This email is automatically generated from Stores-monitoring platform on $date </i></span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span style="font-family:arial,
   helvetica,
   sans-serif;"><i>Please don\'t reply. If you have questions or comments,
   you can contact the <a href="mailto:cloud.support@xxx.xxx">Cloud Support</a> </i></span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t</tr>   \t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t</tbody>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t</tbody>\n\t\t\t\t</table>\n\t\t\t</div>      \t\n\t\t</BODY>\n\t</HTML>'

> }

>

**Comment by thinkingserious** [comment]
Hello @The-Caesar,

One think I noticed is that you don't have a `text` value. Can you try adding a `text` value? Also, what is the value of the `emails` variable?

Thanks!

With Best Regards,

Elmer

**Comment by andrewlew1s** [comment]
I got this response when entering an invalid email.

**Comment by MeisterJustice** [comment]
> I got this response when entering an invalid email.

Thanks so much man. I spent hours on this error until this.

**Comment by himanshuhx** [comment]
Hello Everyone i was using wordpress to buid my portfolio which i hosted on github the contact form part is working on localhost in my system and i am getting the mail bur when i pushed the code to github it is not working and i am not getting the mail.i am using sendGrid for this .Can anyone help? Thank you

**Comment by childish-sambino** [comment]
@himanshuhx Please open a new issue.
