### ISSUE TITLE
getaddrinfo EAI_AGAIN api.sendgrid.com:443

### ISSUE THREAD

**Issue by MatteoGioioso** [sendgrid/sendgrid-nodejs#927]
#### Issue Summary

Just trying to send an email with cloud functions
```
const functions = require('firebase-functions')
const express = require('express')
const cors = require('cors')
const mailService = require('@sendgrid/mail')
const bodyParser = require('body-parser')

//Constants
const SENDGRID_API_KEY = 'Myapikey'

//Set up
const app = express()

app.use(bodyParser.json())
app.use(cors({ origin: true }))
app.post('/send', async (req, res) => {
  mailService.setApiKey(SENDGRID_API_KEY)

  const { name, email, message } = req.body

  const emailContent = {
    to: 'email@email.com',
    from: 'email@email.com'',
    subject: `subject`,
    text: `some message`,
  }

  try{
    const response = await mailService.send(emailContent)

    res.json({message: 'message sent'})

  } catch(error){
    const { message, code, response } = error

    res.json({message, response})
  }
})

exports.api = functions.https.onRequest(app)
```

#### Technical details:

* sendgrid-nodejs: 6.3.1
* Node.js Version: 11.15.0

**Comment by aroach** [comment]
Looks like a DNS issue. I read elsewhere (stackoverflow) that you need to be on a paid plan to make external Requests on firebase functions. Does it work locally on your laptop?

**Comment by MatteoGioioso** [comment]
@aroach 

> Does it work locally on your laptop?

No, is not working locally. 
Paid plan? From Sendgrid or Firebase?
Thanks

**Comment by MatteoGioioso** [comment]
@aroach turns out it was true: https://firebase.google.com/support
And after upgrade my plan I could send the message.

Thanks

**Comment by kadnan0900** [comment]
This is a fire-base issue. If you are using Free(Spark Plan) account you can only use Google services if you are using external services you have to pay for that. 
https://firebase.google.com/pricing/
Upgrade your plan(Flame Plan or Blaze Plan) you can send emails.

**Comment by saravanan10393** [comment]
@kadnan0900 i upgraded to blaze plan but still getting  getaddrinfo ENOTFOUND api.github.com api.github.com:443 error.

**Comment by patbrennan** [comment]
Also getting the error. Interestingly, it worked once, then didn't work again. On the Blaze plan in firebase, verified I'm using correct API keys, the API key creds are correct. Testing locally with firebase emulator/UI, getting this error. 

Using:
`    
"@sendgrid/mail": "^7.1.1",
"firebase-admin": "^8.12.1",
"firebase-functions": "^3.6.2"
`

**Comment by AkshataBadiger** [comment]
> Looks like a DNS issue. I read elsewhere (stackoverflow) that you need to be on a paid plan to make external Requests on firebase functions. Does it work locally on your laptop?

Its working locally. But not on deployment

**Comment by dschnare** [comment]
> Also getting the error. Interestingly, it worked once, then didn't work again. On the Blaze plan in firebase, verified I'm using correct API keys, the API key creds are correct. Testing locally with firebase emulator/UI, getting this error.
> 
> Using:
> ` "@sendgrid/mail": "^7.1.1", "firebase-admin": "^8.12.1", "firebase-functions": "^3.6.2"`

Any luck? We're experiencing this issue ourselves on the Blaze plan.

**Comment by yusufhajjar** [comment]
@AkshataBadiger  , i have same issue did you solve it

**Comment by yusufhajjar** [comment]
any one !!???
