### ISSUE TITLE
TypeError: SGmail.setApikey is not a function

### ISSUE THREAD

**Issue by emilfrancis2027** [sendgrid/sendgrid-nodejs#936]
Ive been trying to add a registration successfull email feature to my node js user login project.Please help. 
i used the following code:
var SGmail = require('@sendgrid/mail')
SGmail.setApikey("SG.XXXX");
const msg = {
     to: 'emil.francis2027@gmail.com',
     from: 'emil.francis2021@gmail.com',
     subject: 'Sending with Twilio SendGrid is Fun',
     text: 'and easy to do anywhere, even with Node.js',
     html: '<strong>and easy to do anywhere, even with Node.js</strong>',
   };
  sgMail.send(msg);

**Comment by thinkingserious** [comment]
Hello @emilfrancis2027,

Can you please verify what version of this SDK you are using? 

If you hare on the latest version, then [this example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/single-email-single-recipient.md#send-a-single-email-to-a-single-recipient) should work for you.

Thanks!

With Best Regards,

Elmer

**Comment by emilfrancis2027** [comment]
I actually made a pretty stupid mistake .the K in setApiKey should be in uppercase ,i mistyped that.

**Comment by emilfrancis2027** [comment]
Thanks a lot for replying Elmer
I actually made a pretty stupid mistake .the K in setApiKey should be in
uppercase ,i mistyped that.

**Comment by thinkingserious** [comment]
Thanks for following up!
