### ISSUE TITLE
The Previously sent msg is being sent on the next send

### ISSUE THREAD

**Issue by nspeet** [sendgrid/sendgrid-nodejs#937]
#### Issue Summary
Using:
const sgMail = require('@sendgrid/mail');
....
  const msg = {
     to: emailList,
     from: FROM_EMAIL_ADDRESS,
     subject: subjectText,
     template_id: templateID, 
     dynamic_template_data: {name: name, url: url}
  };
  console.log("Email msg1: " ,  msg);
  try {  
    sgMail.send(msg).then((sent) => {
      console.log("Email msg2: " ,  msg);
      console.log("Email Sent: " ,  sent);
    });
  }catch (err) {
    console.log("send error: ", err);
  }

#### Steps to Reproduce

When running this code on AWS lambda:

msg1 does not match msg2? Why? msg2 is the PREVIOUSLY SENT msg (in .then after the send).

#### Technical details:

* sendgrid-nodejs Version: master "@sendgrid/mail": "^6.3.1"
* Node.js Version: 8.10

**Comment by thinkingserious** [comment]
Hello @nspeet,

I suspect that there is a logic error in your code that is not related to this SDK, but to make sure, please answer a few follow up questions:

How does this code get executed? 
Is this the only code in your lambda function? Does the code only get executed once?

Thank you!

With Best Regards,

Elmer
