### ISSUE TITLE
Add Sender names

### ISSUE THREAD

**Issue by ukor** [sendgrid/sendgrid-nodejs#938]
#### Issue Summary

This is not a bug, rather a how to question.
How can one include a name with the `to` attribute?

**Comment by thinkingserious** [comment]
Hello @ukor,

I believe [this](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/flexible-address-fields.md) is the documentation you need.

With Best Regards,

Elmer

**Comment by ukor** [comment]
Thank you @thinkingserious That's exactly what I needed.

**Comment by thinkingserious** [comment]
Awesome, thanks for following up!

**Comment by isaumya** [comment]
Thank you so much @thinkingserious I have been looking for this for so long in Google and got knows why that readme file is nowhere to be found in Google. Please add this readme file link in USE_CASE.md and in the NPM readme file. This is super helpful. Thanks again.
