### ISSUE TITLE
Attachment filename encoding is wrong in Outlook

### ISSUE THREAD

**Issue by accenture-bharadwaj** [sendgrid/sendgrid-nodejs#941]
#### Issue Summary

When using the Sendgrid NodeJS, sending an attachment with filename that includes German characters (ä/ü) results in incorrect encoding in outlook. Gmail encodes it perfectly.

![image](https://user-images.githubusercontent.com/48679006/59095497-51c06480-8921-11e9-9c32-0c6bc4e96540.png)

#### Steps to Reproduce

Sending an attachment with a filename that includes German character (ä/ü)

import * as MailService from '@sendgrid/mail'
...
const attachments = fileAttachments.map(file => ({
    content: file.data.toString('base64'),
    filename: file.filename,
    type: mime.lookup(file.filename) as string,
    disposition: 'attachment'
  }));
...
const email = {
    to,
    cc: cc !== to ? cc : undefined,
    bcc: bcc !== to && cc !== bcc ? bcc : undefined,
    from: {name, email: from},
    subject,
    html,
    **attachments**
  }

  return MailService.send(email).then(() => undefined)

Same issue has been raised under c-sharp as well https://github.com/sendgrid/sendgrid-csharp/issues/667

#### Technical details:
* "@sendgrid/mail": "6.2.1",
* Node.js v10.15.0
* NPM v6.4.1

**Comment by thinkingserious** [comment]
Also, related to: https://github.com/sendgrid/sendgrid-csharp/issues/667

**Comment by thinkingserious** [comment]
Hello @accenture-bharadwaj,

I'm thinking that if this only happens on certain clients, it may be something out of our control. That said, I've added this to our backlog for further investigation. Thank you for taking the time to report it.

With Best Regards,

Elmer

**Comment by accenture-bharadwaj** [comment]
Thank you so much @thinkingserious. But if you can provide any workaround on this would be appreciated.

**Comment by thinkingserious** [comment]
Hello @accenture-bharadwaj,

As of now, I don't know of any work around. If I discover one, I will post it here. Thanks!

**Comment by KimDal-hyeong** [comment]
I solved with this code.
```js
const filename = `=?UTF-8?B?${btoa(unescape(encodeURIComponent(filename)))}?=`;
```

**Comment by accenture-bharadwaj** [comment]
> I solved with this code.
> 
> ```js
> const filename = `=?UTF-8?B?${btoa(unescape(encodeURIComponent(filename)))}?=`;
> ```

Thank you so much for your reply @KimDal-hyeong. it worked 👍
