### ISSUE TITLE
Transactional template not working

### ISSUE THREAD

**Issue by milottit** [sendgrid/sendgrid-nodejs#944]
When I use this code to send a transactional template , I get a success response but nothing is really sent. Nothing is received in the inbox and nothing in the activity section of SendGrid.

```
Sendgrid.setApiKey(SENDGRID_API_KEY);

const email =
{
    to: 'xxxxxx@gmail.com',
    from: SENDGRID_SENDER,
    subject: 'Test',
    template_id: 'd-128e110d98e040c6b81f4694d04e0572',
    dynamic_template_data: {
        subject: 'Coucou :)',
        club_name: 'VTR School',
    },
};

Sendgrid.send(email)
    .then(m => {
        console.log('Mail sent');
    })
    .catch(error => {

        //Log friendly error
        console.error(error.toString());

        //Extract error msg
        const { message, code, response } = error;

        //Extract response msg
        const { headers, body } = response;
    });
```

However, all is fine when I use

text: 'and easy to do anywhere, even with Node.js',
or
html: '<strong>and easy to do anywhere, even with Node.js</strong>',

Do you have any idea for which reason?

Thanks

versions:
    "@sendgrid/mail": "^6.4.0",
     Node.js Version: v11.10.0

**Comment by thinkingserious** [comment]
Hello @milottit,

Could you please verify what version of this library you are using? npm sendgrid --version

Thanks!

Elmer

**Comment by flexchar** [comment]
@thinkingserious Hey, I have exactly the same error. SendGrid responds with `statusCode: 202`. The OP actually posted a an answer to your question. Not to be rude but it makes me believe that you have not read it. 

I am on the same SG version but using node v10.16.3 (npm v6.9.0).

**Comment by wispyco** [comment]
I am able to send a message with a template but If I use the dynamic data part, which is needed I get the following response `s is not a function`

**Comment by wispyco** [comment]
So I ended up finding a resource somewhere else and this format worked for me 

```
const msg = {
        from: email,
        template_id: 'd-49792420493820492(notreal)',
        personalizations: [{
            to: { email: SENDGRID_TO_EMAIL, },
            dynamic_template_data: {
                subject: payload.subject,
                name:payload.name,
                data:payload.data,
                message:payload.message,
                package:payload.package,
            },
        }],
        
    };
```
