### ISSUE TITLE
npm v6.4.0

### ISSUE THREAD

**Issue by AndyMori** [sendgrid/sendgrid-nodejs#945]
I'm trying to use the @sendgrid/mail setTimeout. I see it in the github repo but when i pull it into my own repo that function doesn't show in the node modules. It says its version 6.4.0.
I don't think npm package @sendgrid/mail v6.4.0 matches to the github repo version 6.4.0 but some older version.
Please explain.

**Comment by childish-sambino** [comment]
Not sure how the change didn't make it into the release, but the release tag matches what's in npmjs: https://github.com/sendgrid/sendgrid-nodejs/tree/v6.4.0

It will be included in the next release, which is happening more frequently than previously.
