### ISSUE TITLE
How to POST to client API?

### ISSUE THREAD

**Issue by KaitaniLabs** [sendgrid/sendgrid-nodejs#949]
https://github.com/sendgrid/sendgrid-nodejs/blob/68b7c45234558207c0a5263a6a45513810cb3afe/packages/client/src/classes/client.js#L98

I've been trying to POST to the API endpoint 'v3/templates/' for a while now and constantly get 400 BAD REQUEST.

I'm confused about how to include the body data because according to the code referenced, mergeData won't include any keys that aren't already listed in defaultRequest object.

I'm trying the following:
````
    sgClient.request({
        method : "POST",
        url : "v3/templates",
        body : {
            name : "Test Template",
            generation : "dynamic"
        }
    }).then(([response, body]) => {
    console.log(response.statusCode);
    console.log(response.body);
  });
````
the body key/val isn't merged. What am I doing wrong?

Thanks in advance.

**Comment by childish-sambino** [comment]
Here's the `mergeData` implementation: https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/helpers/helpers/merge-data.js

It loops through the keys in `data` (not `base`) and merges them into the final result.

Recommend logging the response body on error to see what errors are being returned back:
```
...
}).catch(function (error) {
    console.error(error.response.body);
});
...
```

**Comment by KaitaniLabs** [comment]
Thanks for the help.
