### ISSUE TITLE
unable to create an node.jd environment variable for sendgrid on windows

### ISSUE THREAD

**Issue by IshayMaya** [sendgrid/sendgrid-nodejs#951]
There are 3 steps at the Sendrig Docs to set the enviorment variable :

1. echo "export SENDGRID_API_KEY='YOUR_KEY'" > sendgrid.env

2. echo "sendgrid.env" >> .gitignore

3. source ./sendgrid.env

1-2 are working fine , but when i tried the 3rd step i got this message : 'source' is not recognized as an internal or external command, operable program or batch file.

I understand that the 'source' command belongs to linux , so my question is what is the equivalent for this step in windows ? for some reason i found no mentions for this in the documentaion

**Comment by childish-sambino** [comment]
You can just use `set SENDGRID_API_KEY='YOUR_KEY'` on Windows.

**Comment by shaheryarshaikh1011** [comment]
how to do this on windows?

**Comment by childish-sambino** [comment]
@shaheryarshaikh1011 

> You can just use `set SENDGRID_API_KEY='YOUR_KEY'` on Windows.
