### ISSUE TITLE
Can't resolve 'fs' in '@sendgrid\helpers\classes'

### ISSUE THREAD

**Issue by JakenHerman** [sendgrid/sendgrid-nodejs#952]
#### Issue Summary

Fresh install trying to use @sendgrid/mail - getting this error. 

#### Steps to Reproduce

1. npm install --save @sendgrid/mail
2. Run project

#### Technical details:

* sendgrid-nodejs Version: 0.1.0-2
* Node.js Version: 10.15.1

**Comment by nephlin7** [comment]
Same Here 😕
![image](https://user-images.githubusercontent.com/22168189/61473018-d0f28080-a942-11e9-8ed6-64922c2732c2.png)

**Comment by madison-soucie** [comment]
I am experiencing the same error. Has anyone found a solution or a workaround in the short term?
<img width="1161" alt="Screen Shot 2019-07-23 at 11 32 08 AM" src="https://user-images.githubusercontent.com/19200284/61733716-a2f3ae80-ad3d-11e9-86e8-609edd7ef5ad.png">

Seems like [Issue #955](https://github.com/sendgrid/sendgrid-nodejs/issues/955) is related.

**Comment by nephlin7** [comment]
I found this Lil workaround, set in webpack config:
```
 node: {
      net: 'empty',      
      fs: 'empty',
      tls: 'empty'
}
```

**Comment by anniesu1** [comment]
@nephlin7 thanks for the workaround! 
what should be done if my project does not have a webpack config? can this go in the tsconfig?

**Comment by tyshcr** [comment]
Anyone have an answer in case I don't have a webpack config?

**Comment by tyshcr** [comment]
Anyone have an answer in case I don't have a webpack config?

**Comment by MihaiWill** [comment]
me2

**Comment by tyshcr** [comment]
I figured out ... you have to use SendGrid in your backend, not in your frontend. Install this library in your backend service, make the call from your frontend to initiate the backend. the 'fs' library will not work on the frontend.

**Comment by childish-sambino** [comment]
Those are backend dependencies. It's you're using webpack for a backend service, you'll need to add this to your webpack config: `target: 'node'`
