### ISSUE TITLE
Sendgrid escaping apostrophe to &apos

### ISSUE THREAD

**Issue by galenweber** [sendgrid/sendgrid-nodejs#954]
#### Issue Summary

We are using `@sendgrid/mail` to send a transactional template with data passed via `dynamic_template_data` and rendered using Handlebars.

However, our users on older email clients have reported that **apostrophe characters are being rendered as `&apos;`**. So they will see text like:

> Hi, I hope you\&apos;re doing well!

From a CX perspective, that's not ideal. 

What I think is happening is that Sendgrid and Handlebars are escaping the apostrophe character to `&apos;`. [Shouldn't it be escaped to `&#39;`?](https://stackoverflow.com/questions/609166/asp-and-apos-does-not-work)

If we use triple brackets in our templates `{{{ myMessage }}}` instead of double brackets it works as expected (because that prevents Sendgrid from escaping the text). However, [Sendgrid documentation](https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/) makes it seem like we only need to do this if we have the ', " or & characters **in the subject line**.

Can Sendgrid change how apostrophe characters are being escaped? If not, is there any danger to simply using triple brackets (`{{{ message }}}`) for all text we insert?

NOTE: it does look like Sendgrid [warns against those characters in dynamic template data](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/helpers/constants/index.js), but there's nothing in the docs to explain why that would be. 

#### Steps to Reproduce

1. Create a transactional email template that includes handlebars templating to insert a value ( ie. `{{ message }}`)
2. Use `@sendgrid/mail` to send that transactional template, passing the following for the `dynamic_template_data` property: `{ "message": "Hope you're doing well" }`
3. Inspect the HTML of the email that is sent. The apostrophe character will have been replaced with `&apos;`. That does not render well on older email clients.

I consider this a bug because Sendgrid is rendering `&apos;` instead of the officially supported 
`&#39;`. 

#### Technical details:

"@sendgrid/mail": "^6.3.1"
* Node.js Version: 8.14.x

**Comment by childish-sambino** [comment]
The guidance for using triple brackets with special characters applies to both the subject and body.

As to why apostrophes are encoded differently than expected, best to reach out to [support](https://support.sendgrid.com/).

**Comment by tunminster** [comment]
why is this closed? i don't see the solution here. I've come to this same issue.

**Comment by childish-sambino** [comment]
> The guidance for using triple brackets with special characters applies to both the subject and body.
> 
> As to why apostrophes are encoded differently than expected, best to reach out to [support](https://support.sendgrid.com/).

**Comment by connor4312** [comment]
> The guidance for using triple brackets with special characters applies to both the subject and body.

This allows HTML injection, though.

I'm kind of confused as to what to do here. If I use two braces in the message body, apostrophes are badly escaped

![](https://memes.peet.io/img/20-10-d47c377b-a87b-478a-a50d-ebdad8ecfc40.png)

If I use three braces, they don't get escaped but I can then inject, for example `<b>hi</b>`

![](https://memes.peet.io/img/20-10-97291048-4238-4e09-b1f9-78960fba7c7f.png)

From what I can tell either I'm stuck with bad escape, or no escaping, neither of which puts me in a good place.

**Comment by childish-sambino** [comment]
@connor4312 Understood and thanks for highlighting the issue. But since this is not something that can/should be directly addressed by this library, best to reach out to [support](https://support.sendgrid.com/).
