### ISSUE TITLE
Any example of best practice for sending large amount of emails?

### ISSUE THREAD

**Issue by zachweinberg** [sendgrid/sendgrid-nodejs#956]
What is the best practice while using the @sendgrid/mail library to send 1000 emails when the body of the message is unique for all emails?

**Comment by childish-sambino** [comment]
Is the body unique or something that can be templated?

Here's a comment about this in general: https://github.com/sendgrid/sendgrid-csharp/issues/660#issuecomment-360553420

**Comment by IanKemp** [comment]
Why is there no method that simply takes an array of `SendGridMessage` objects and batch sends them? The only way to achieve that functionality is by manually constructing a request to the SendGrid API, which entirely defeats the purpose of having a wrapper library.

**Comment by childish-sambino** [comment]
@IanKemp Does this example help?

https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/multiple-emails-multiple-recipients.md
