### ISSUE TITLE
Inline styles are trimed off

### ISSUE THREAD

**Issue by praveenkumart** [sendgrid/sendgrid-nodejs#958]
#### Issue Summary

I am using sendgrid 6.3.1 , i am able to send emails , css and inline styles are getting trimmed , design is not reflecting in email .
Problem happening only in Zoho .

#### Technical details:

* sendgrid-nodejs Version: 6.3.1

**Comment by childish-sambino** [comment]
Could you provide sample code that illustrates the issue you're seeing?

**Comment by praveenkumart** [comment]
Issue resolved , I have applied to .toUppercase() to body string , 
thats was the issue.
