### ISSUE TITLE
Sending email with text and html fields

### ISSUE THREAD

**Issue by fcastrocs** [sendgrid/sendgrid-nodejs#962]
#### Issue Summary

Sending email with the following template only sends html, not text

```
module.exports.sendVerification = (url, username, email) =>{
    msg = {
        to: email,
        from: 'email@domain.com',
        subject: 'subject...',
        text: `Hello ${username}, please confirm your account.`,
        html: `<div><a href="${url}"><strong>Verify Account</strong></a></div>`,
    };
    sgMail.send(msg);
}
```

#### Technical details:

npm sendgrid --version
6.5.0
 
node --version
v11.7.0

**Comment by childish-sambino** [comment]
The plain text content should be a plain version of the HTML content. It should not appear in conjunction with the HTML content.
