### ISSUE TITLE
Adding recipients to a list

### ISSUE THREAD

**Issue by olaven** [sendgrid/sendgrid-nodejs#964]
#### Issue Summary
I want to add recipients to lists via the [marketing API](https://sendgrid.api-docs.io/v3.0/lists/update-list), however, I am not able to find this ability. 

This seems like a feature that really should be available. 
Am I missing something, or is this not possible? 

Thank you for your time. 
Olav

**Comment by JClackett** [comment]
Also unable to find anything on this

**Comment by hypetechnologies2019** [comment]
https://sendgrid.com/docs/API_Reference/api_v3.html

Please refer this

**Comment by olaven** [comment]
Sorry for not updating this issue earlier. 
As it turns out, out you have to use the `https://api.sendgrid.com/v3/marketing/contacts`-endpoint. 
You can then pass `list_ids` in the body 😄 

I did not find this very clear in the documentation though, and I spent many hours searching for this..

**Comment by hypetechnologies2019** [comment]
> Sorry for not updating this issue earlier.
> As it turns out, out you have to use the `https://api.sendgrid.com/v3/marketing/contacts`-endpoint.
> You can then pass `list_ids` in the body 😄
> 
> I did not find this very clear in the documentation though, and I spent many hours searching for this..

Hi, what did u pass in the request body, i get invalid json, even if its valid.. what did u pass in `list_ids` ?

**Comment by olaven** [comment]
`list_ids` is a list of the ID-strings of the lists :) 
i.e.: `["SOME_ID", "OTHER_ID"]`. 

However , you cannot access these IDs from the GUI. You have to make [this call](https://sendgrid.api-docs.io/v3.0/lists/get-all-lists) first :-)

**Comment by hypetechnologies2019** [comment]
I need to insert a new mailid to contacts list.

Request Body
 {
    "list_ids": [ 
        "062ab507-279c-4ac7-8423-da88cae77ed7"
    ],
    "contacts": [
        {
            "address_line_1": "abc",
            "address_line_2": "def",
            "alternate_emails": [
                "myidxxx@gmail.com"
            ],          
            "email": "hypetechnologies2019@gmail.com",
            "first_name": "aa",     
            "custom_fields": {}
        }
    ]
}


I get this error :
{
  "errors": [
    {
      "field": "",
      "message": "invalid JSON"
    }
  ]
}

Can u tel me wer i am going wrong. thanks
