### ISSUE TITLE
Could not able to send javascript as attachment

### ISSUE THREAD

**Issue by Achyuth-India** [sendgrid/sendgrid-nodejs#971]
Hello,

I am trying to send an email with javascript file as an attachment. I could successfully able to send the mail but the file is not sent as javascript. Instead I receive it as plain text file.

Please find the payload I use for filename and type:

`filename: 'somejsfile',
type: 'application/javascript',`

And if I try to specify file name as `somejsfile.js`. I am not even receiving the email.

I also tried with type `text/javascript`, but still facing the same issue.

**Note:** If I use the same payload with type `application/pdf` it is working perfectly and I receive pdf file in mail.

* sendgrid-nodejs Version: 6.4.0
* Node.js Version: 10.15.0

Any help will be highly appreciated.
Thanks in Advance

**Comment by childish-sambino** [comment]
I'm seeing the same issue. Adding a `.js` extension to the file name and it never gets received and no errors are reported. Checking internally if this is a known limitation. Note that when I send the file without the extension it is received fine.

**Comment by childish-sambino** [comment]
Pull requests to add this feature are welcome and will be reviewed based on priority, but Twilio SendGrid is not actively building new functionality for the library.

**Comment by childish-sambino** [comment]
Nothing on the SendGrid side is blocking the attachment. But, this could be the reason why the email is getting bounced: https://www.pcworld.com/article/3162038/gmail-will-block-javascript-attachments-a-common-source-of-malware.html
