### ISSUE TITLE
Sending emails using personalizations with invalid email

### ISSUE THREAD

**Issue by himanshuphirke** [sendgrid/sendgrid-nodejs#974]
I am using /v3/mail/send to send email using Transactional templates.

The personalization some times contains invalid email (since they are coming from 3rd party)

Questions:
1. Is there a way I can send email to rest of the valid and skip invalid. Right now complete batch fails
2. What kind of email validation does SendGrid do? Is it just a something@domain.somerthing?
3. Is there a way I can run validations with SendGrid before sending so I can skip those emails?

**Comment by himanshuphirke** [comment]
When I contacted SendGrid they pointed me to there paid server which validates email (and does lot of other things). They were not ready to provide what is the criteria they have for valid email.
Instead I added a regex to validate emails on my side before I add to personalization.

Regex (as per RFC2822 standards):
`/[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/i`

**Comment by charlie-s** [comment]
I'm using [isemail](https://www.npmjs.com/package/isemail) on a number of projects now, and used it here as well. After going through lots of regex and other validation libs, I settled on this one. It validates the kinds of emails we want to accept on ecommerce, email subscriptions, stuff like that. It has a few options such as "blacklist tlds" that lets me exclude common issues like `.xom`. Working with SendGrid for the past 3 days, sending emails to about 20k unique addresses. We'll see how it continues to do.

**Comment by himanshuphirke** [comment]
@charlie-s ok sure.
