### ISSUE TITLE
Unable to Instantiate a new MailService class

### ISSUE THREAD

**Issue by krazibit** [sendgrid/sendgrid-nodejs#977]
#### Issue Summary

Unable to instantiate the MailService class as it thought to be a property by TS

#### Steps to Reproduce
```typescript 
import {MailService} from '@sendgrid/mail'
const ms = new MailService()
```
Error :  Cannot use 'new' with an expression whose type lacks a call or construct signature.

#### Technical details:

* sendgrid-nodejs Version: 6.4.0
* Node.js Version: 10.15.3

**Comment by childish-sambino** [comment]
Fixed by #921
