### ISSUE TITLE
@sendgrid/mail doesnt support cc.

### ISSUE THREAD

**Issue by NithyakalaRajendran** [sendgrid/sendgrid-nodejs#980]
@sendgrid/mail doesnt support cc.

In below code, cc is not supported and showing following error "UnhandledPromiseRejectionWarning: Error: Bad Request".

                        const msg = {
                        from: 'nithyakr@in.ibm.com',
                        to: ['nithyakr@in.ibm.com',distContactEmail],                        
                        cc: 'nithyakr@in.ibm.com',
                       subject: 'Reminder: ' +doc.User_Programs+ ' Nomination'
                        html: message + nominationLink , 
                        };
                        sgMail.send(msg);

**Comment by childish-sambino** [comment]
Recommend catching the rejection for more details why it was a bad request:
```
sgMail.send(msg).catch(function (error) {
     console.error(error.response.body);
 });
```
