### ISSUE TITLE
Sending template emails via API

### ISSUE THREAD

**Issue by ramosjeremy** [sendgrid/sendgrid-nodejs#981]
I am able to send regular emails via the API without trouble. However, I need to send an email with a template. I am able to send a test email from my SendGrid console, but when I try to send via the API the email never arrives at the destination.

The POST returns a 202 Accepted as if everything is ok.

Here is the template.
<!DOCTYPE html>
    <html>
    <head>
      <title></title>
    </head>
    <body>
      Hello {{ first_name }}
    </body>
    </html>

Here is the POST body.
```
{
   "personalizations":[
      {
         "to":[
            {
               "email":"ramos.jeremy+sgtest@gmail.com",
               "name":"Jeremy Ramos"
            }
         ],
            "dynamic_template_data":{  
            "first_name":"Test Name"
         },
         "subject":"Test Template Email"
      }
   ],
   "from":{
      "email":"jeremy@phiquest.com",
      "name":"support staff"
   },
   "reply_to":{
      "email":"jeremy@phiquest.com",
      "name":"Jeremy Ramos"
   },
   "template_id": "d-539f599eeef64433968c2d524311cbdb"
}
```

**Comment by perezpaya** [comment]
Having the same issue

**Comment by ramosjeremy** [comment]
> Having the same issue

Perezpaya - I figured out the issue. I was pointing to the wrong account. Double check your APIKey and make sure the template ID you are using exists in the same account.

**Comment by flexchar** [comment]
Same error. It is very big shame that SendGrid doesn't allocate resources to fixing these issues. Especially from paying clients point of view.

**Comment by wispyco** [comment]
I get a similar issue but I get the following error `s is not a function`

**Comment by Anav0** [comment]
Issue is still here. Any ideas?

**Comment by flexchar** [comment]
To be perfectly honest, for me it turned out to be an API key issue. The code base I was working with was using other API key that is legit but does not belong to our account, thus it never appeared in the logs.

However, Twilio/SendGrid should definitely improve API responses and tell what exactly is wrong.

**Comment by childish-sambino** [comment]
@wispyco The error you're seeing was fixed by https://github.com/sendgrid/sendgrid-nodejs/pull/1039
