### ISSUE TITLE
How can I get the html of a sent email

### ISSUE THREAD

**Issue by dvora-worthy** [sendgrid/sendgrid-nodejs#987]
Hi @thinkingserious ,

I want to get the html of an email, after the email was sent.
I'm sending the email with template_id...
Can I get it somehow?

* sendgrid-nodejs Version: "@sendgrid/mail": "^6.4.0"
* Node.js Version: 10.0.0

**Comment by childish-sambino** [comment]
I'm not aware of an API to get this information. You could use a bcc address and process the email content there.
