### ISSUE TITLE
Unable to send attachment as zip in Nodejs

### ISSUE THREAD

**Issue by sphopale** [sendgrid/sendgrid-nodejs#993]
#### Issue Summary

Unable to send mail with zip as attachment.

#### Steps to Reproduce

1. Create a zip file with a single csv file in it.
2. generate base64 encode of the zip file and provide as content value, type: application/zip

I see that the generated base64 content of the zip file isn't correct and attaches an empty zip file attachment .
```
return new MailMessage("sphurti XXX","Testing attachment","TestMail",[{
        content: await fs.readFileSync(test.zip).toString('base64'),
        filename: "test.zip",
        type: 'application/zip',
        disposition: 'attachment',
    }])
```

**Comment by childish-sambino** [comment]
Are you able to send other attachments? Is the path to the zip file correct? Is the content value included in the payload correct?

**Comment by kushal4** [comment]
no for zip only its causing issue here

**Comment by kushal4** [comment]
path of the zip file is correct

**Comment by kushal4** [comment]
how to verify content value  ?

**Comment by kushal4** [comment]
When am sending invidual file then the file content and payload is conserved but when i zip it and send it as attachement then the file is getting corrupted

**Comment by childish-sambino** [comment]
@kushal4 Recommend reaching out to [support](https://support.sendgrid.com/hc/en-us) as I've been unable to recreate the issue.

**Comment by thinkingserious** [comment]
Hello @sphopale,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by Madhu-1234** [comment]
Was this resolved? I am also facing the same issue

**Comment by childish-sambino** [comment]
@Madhu-1234 

> Recommend reaching out to [support](https://support.sendgrid.com/hc/en-us) as I've been unable to recreate the issue.
