### ISSUE TITLE
Handling error code

### ISSUE THREAD

**Issue by Gilles33** [sendgrid/sendgrid-nodejs#997]
#### Issue Summary

When I'm using the send method, the error code is undefined. I get the error message only.

#### Steps to Reproduce

```
function sendEmail(receiver, template, data = {}) {
    
    const msg = {
       //to: receiver,            I remove this line in order to trigger an error
       from: "user@mail.com,
       templateId: templates[template],
       dynamic_template_data: data, 
       mail_settings : {sandbox_mode:  {enable: true}}
    };
    
    sgMail.send(msg)
    .then(() => {
        logger.log.info(`mail to ${receiver} is sent`);
    }).catch(error => {
        const {message, code, response} = error;
        logger.log.error(`${error.code} :${error.message}`);
    });

 }

 exports.sendEmail = sendEmail;

```
When I call this method on some controller, that's what I get :

`10:05:07 error:  undefined :Provide at least one of to, cc or bcc`

The error object only contains the message part, code and response are undefined. I'm getting the same issue when I'm not in sandbox mode.

Am I missing out something ?

#### Technical details:

* @sendgrid/mail: ^6.4.0,
* Node.js Version: 8.10.0

**Comment by wispyco** [comment]
I got that error, when my environment variables were not being passed properly. I was using Gatsby JS, so different, but I got that response, so I tried hard coding the env variables and realized I needed a require for env variables in gatsby. So I would try hard coding your api key just to test.

**Comment by childish-sambino** [comment]
In this case it's an error thrown by the client so no API call is made so there is no status code. Here's where the error is thrown: https://github.com/sendgrid/sendgrid-nodejs/blob/47b6a5cd583cc10544ac19434419bdda5272b107/packages/helpers/classes/mail.js#L281
