### ISSUE TITLE
The provided authorization grant is invalid, expired, or revoked sendgrid error on sending email using node.js

### ISSUE THREAD

**Issue by fahadsubzwari924** [sendgrid/sendgrid-nodejs#998]
#### Issue Summary

I have `node.js` server in which in of the api i am sending email to user using sendgrid so i am getting this error

`The provided authorization grant is invalid, expired, or revoked sendgrid`

Here is my code 

        `const sgMail = require('@sendgrid/mail');
         sgMail.setApiKey(config.app["sendgridEmailApiKey"])
         let emailProps = {
                        to: obj.email,
                        from: "referling@gmail.com",
                        subject: `Email Verification`,
                        html: `<p>Your verification code is : ${verification_code}</p>
                    <p>Please verify your email <a href="http://referral-sow.s3-website.us-east-2.amazonaws.com/verify"> Here</a> </p>`
                    }
                    if (user) {
                        sgMail.send(emailProps, (err, result) => {
                            if (err) {
                                resolve({ success: false, message: "Error in email sending", data: err })
                            } else {
                                resolve({ success: true, message: "User added & mail sent", data: user })
                            }
                        })
                    }`

I just mentioned necessary code to show my basic code to send email. Please see above code and lidentify the mistake?
i am getting this error in response
`The provided authorization grant is invalid, expired, or revoked sendgrid`

**Note : I have already create sendgrid api key and placed in my config file.**

**Comment by childish-sambino** [comment]
Recommend logging the API key to verify it is proper. Should start with `SG.`
```
console.log(config.app["sendgridEmailApiKey"]);
```
