### ISSUE TITLE
Substitutions not appearing in emails

### ISSUE THREAD

**Issue by ohabash** [sendgrid/sendgrid-nodejs#999]
Substitutions not working in this setup 

## In express App
```
const msg = {
        to: data.email,
        from: 'hello@joma.com',
        subject: 'New Follower',
        templateId: 'd-92486bd616c64b6e***53ddad1232e',
        substitutionWrappers: ['{{', '}}'],
        substitutions: {
            name: "Test Name"
        }
    };
    sgMail.send(msg);
```

## SendGrid Test Data works fine with the following 
```{"name":"test name"}```

## Trying 
When i run the above function my email is sent but it does not consider the `substitutions` which work well with test data. Can you see what i am missing?

**Comment by lionbee** [comment]
Had the same problem. Got it working using personalizations. So in your example it would be:

```
const msg = {
        from: 'hello@joma.com',
        subject: 'New Follower',
        personalizations: [{
            to: {
                email: data.email,
            },
            dynamic_template_data: {
                name: "Test Name"
            } ,
        }],
        templateId: 'd-92486bd616c64b6e***53ddad1232e',
    };
    sgMail.send(msg);
```

**Comment by ohabash** [comment]
@lionbee that works thank you... Do you know how to set the subject dynamically... is it related to this object structure?

on the admin in the template's subject field i have {{subject}}

**Comment by lionbee** [comment]
@ohabash Apologies for the late reply, but yes. That should work for subject as well
